Repository kubernetes/kops, pull requests merged in 2018-11, with the labels that each got.

#6039 Fix s3 encryption role
  pkg/model/iam/iam_builder.go
  pkg/model/iam/tests/iam_builder_master_legacy.json
  pkg/model/iam/tests/iam_builder_master_strict.json
  pkg/model/iam/tests/iam_builder_master_strict_ecr.json
  pkg/model/iam/tests/iam_builder_node_legacy.json
  pkg/model/iam/tests/iam_builder_node_strict.json
  pkg/model/iam/tests/iam_builder_node_strict_ecr.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6032 Fix indentation for monitoring-standalone addon
  addons/monitoring-standalone/addon.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6023 Correct the table format in upgrade_from_kubeup.md
  docs/upgrade_from_kubeup.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#6043 Update Weave Net to version 2.5.0
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6041 Change "if" -> "if and only if" to make more clear
  channels/pkg/channels/addons_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6030 Spotinst: Attempt to find a Security Group even without a VPC ID
  upup/pkg/fi/cloudup/awstasks/securitygroup.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6013 fix some typos
  README.md
  node-authorizer/pkg/utils/logger.go
  pkg/client/simple/api/clientset.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6022 Fix blog link
  docs/node_resource_handling.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6010 Bump kopeio-networking to latest version
  upup/models/cloudup/resources/addons/networking.kope.io/k8s-1.6.yaml
  upup/models/cloudup/resources/addons/networking.kope.io/pre-k8s-1.6.yaml
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6025 Spotinst: Do not log unmatched groups as warning messages
  pkg/resources/spotinst/resources.go
Labels: approved, cncf-cla: yes, lgtm

#5875 #5700: Add command line flag for disabling Subnet ELB tags
  cmd/kops/create_cluster.go
  docs/cli/kops_create_cluster.md
  docs/run_in_existing_vpc.md
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/model/network.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6053 Remove unnecessary code
  cmd/kops/create_cluster.go
  cmd/kops/create_cluster_test.go
  cmd/kops/replace.go
  cmd/kops/root.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5917 coredns should not be running on master by default
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6035 Document etcd volume options + fail fast if ratio is too high
  docs/cluster_spec.md
  pkg/model/master_volumes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6015 Spotinst: Skip the creation of LoadBalancerAttachment tasks if Spotinst is enabled
  pkg/model/awsmodel/BUILD.bazel
  pkg/model/awsmodel/api_loadbalancer.go
  pkg/model/bastion.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6077 Update Calico to v3.3.1
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6078 delete some code
  channels/pkg/channels/channel_version.go
  cmd/kops/create.go
  dns-controller/pkg/dns/dnscache.go
  kube-discovery/cmd/kube-discovery/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5929 Adding describe launch config to autoscaler permissions
  addons/cluster-autoscaler/cluster-autoscaler.sh
Labels: approved, area/aws, cncf-cla: yes, lgtm, size/XS

#6086 Remove trailing comma from from k8s-1.7-v3.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5873 Updating image and docs for metrics-server add-on
  addons/metrics-server/README.md
  addons/metrics-server/v1.8.x.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5824 Updates to roadmap for 1.11 and 1.12 and new upcoming features section (WIP)
  ROADMAP.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#5905 Update amazon-vpc-routed-eni to v1.2.1
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.8.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/L

#6056 Request AWS ASGs in batches
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6087 Typo fix: Deploy -> Deploying
  docs/api-server/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6084 Use a single command in Linux install instructions
  docs/install.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6089 autoscaler setup: Use set -x to stop execution if errors are encountered
  addons/cluster-autoscaler/cluster-autoscaler.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6092 Typo fix "api server" -> "API server"
  dns-controller/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5644 increase docker-healthcheck respose timeout
  upup/models/nodeup/docker/_systemd/_debian_family/files/opt/kubernetes/helpers/docker-healthcheck
Labels: approved, cncf-cla: yes, lgtm, size/S

#6094 Bump version of amazon-vpc-cni in bootstrapchannelbuilder
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6095 Fix typo in CRD: singuar
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.8.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6082 add SSL certificate ARN to Terraform output
  upup/pkg/fi/cloudup/awstasks/load_balancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5586 Add flag to disable Basic Auth.
  docs/cluster_spec.md
  nodeup/pkg/model/kube_apiserver.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
Labels: approved, area/security, cncf-cla: yes, lgtm, size/S

#6096 Update machine types
  hack/machine_types/machine_types.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5502 Implemented Nvidia DevicePlugin GPU Support on AWS
  hooks/nvidia-device-plugin/Makefile
  hooks/nvidia-device-plugin/README.md
  hooks/nvidia-device-plugin/image/Dockerfile
  hooks/nvidia-device-plugin/image/files/01-aws-nvidia-driver.sh
  hooks/nvidia-device-plugin/image/files/02-nvidia-docker.sh
  hooks/nvidia-device-plugin/image/files/nvidia-device-plugin.service
  hooks/nvidia-device-plugin/image/files/nvidia-device-plugin.sh
  hooks/nvidia-device-plugin/image/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#5939 Setting the manifest directory when it is required by kubelet
  nodeup/pkg/model/kubelet.go
  nodeup/pkg/model/kubelet_test.go
  nodeup/pkg/model/tests/kubelet/featuregates/cluster.yaml
  nodeup/pkg/model/tests/kubelet/featuregates/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6101 Update CoreDNS version to 1.2.6
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6108 Fix typos: dnsmaq -> dnsmasq, mutiple -> multiple
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/resources/aws/securitygroup.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6100 Document how to create a custom addon
  docs/addons.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/M

#5902 [monitoring-standalone] Add kubernetes 1.7 version
  addons/monitoring-standalone/addon.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4762 Cni ipvlan vpc k8s support
  cmd/kops/create_cluster.go
  nodeup/pkg/model/context.go
  nodeup/pkg/model/network.go
  pkg/apis/kops/cluster.go
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/validation/legacy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/components/context.go
  pkg/model/components/kubecontrollermanager.go
  pkg/model/components/networking.go
  pkg/model/iam/iam_builder.go
  upup/models/nodeup/resources/_lyft_vpc_cni/files/etc/cni/net.d/10-cni-ipvlan-vpc-k8s.conflist.template
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/networking.go
  upup/pkg/fi/cloudup/tagbuilder.go
  upup/pkg/fi/nodeup/BUILD.bazel
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6105 Node Authorizer Recovery Middleware
  node-authorizer/pkg/server/middleware.go
  node-authorizer/pkg/server/server.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6111 Fix log warning info
  upup/pkg/kutil/import_cluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6059 Set a `dateformat` on logrotate configs on CoreOS
  nodeup/pkg/model/logrotate.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6114 Mention about possible state store vendors in error message
  cmd/kops/util/factory.go
  docs/philosophy.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6112 Create separate certificate for etcd peer authentication
  nodeup/pkg/model/protokube.go
  pkg/model/pki.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/M

#6058 Set MaxPods when using Amazon VPC CNI Plugin
  Makefile
  hack/machine_types/BUILD.bazel
  hack/machine_types/machine_types.go
  hack/machine_types/vpc_ip_resource_limit.go
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/kubelet.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#6118 machine-type generator: Warn if instance type not in ENI map
  hack/machine_types/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6122 Include name of unhealthy component in validation error
  pkg/validation/validate_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6123 Bump alpha channel kubernetes versions
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/S

#6124 Add missing locking to awsmock LaunchConfigurations
  cloudmock/aws/mockautoscaling/launchconfigurations.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6117 Add a1 and c5n instance types
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6121 Simplify makefile for update-machine-types
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6125 Update docs, removing brew --devel
  docs/development/homebrew.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#6127 machine-types: remove duplicate dedup
  hack/machine_types/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6128 Update amazon cni to 1.3.0
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6132 Automated cherry pick of #6128: Update amazon cni to 1.3.0
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6130 Enable HPA tolerance configuration
  docs/cluster_spec.md
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6136 Update addons dashboard version
  docs/addons.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS
