Repository kubernetes/kops, pull requests merged in 2018-08, with the labels that each got.

#5566 Remove GetAsgForInstance IAM permission
  pkg/model/iam/iam_builder.go
  pkg/model/iam/tests/iam_builder_master_legacy.json
  pkg/model/iam/tests/iam_builder_master_strict.json
  pkg/model/iam/tests/iam_builder_master_strict_ecr.json
  tests/integration/update_cluster/additional_cidr/cloudformation.json
  tests/integration/update_cluster/additional_user-data/cloudformation.json
  tests/integration/update_cluster/externallb/cloudformation.json
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#5579 Don't set kube-proxy cluster-cidr with aws-vpc-cni
  pkg/model/components/kubeproxy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5590 Move CloudProviderID consts into a block
  pkg/apis/kops/channel.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5589 Fix cpu unit measurement
  docs/cluster_spec.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5599 Node Authorizer Prometheus Metrics
  upup/models/cloudup/resources/addons/node-authorizer.addons.k8s.io/k8s-1.10.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5597 Add AWS IAM permission to check for volume resize
  pkg/model/iam/iam_builder.go
  pkg/model/iam/tests/iam_builder_master_strict.json
  pkg/model/iam/tests/iam_builder_master_strict_ecr.json
Labels: approved, cherrypick-candidate, cncf-cla: yes, lgtm, size/S

#5577 Add amazon.com image owner alias and Amazon Linux 2 documentation
  docs/images.md
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, cherrypick-candidate, cncf-cla: yes, lgtm, size/M

#5600 make dep-ensure checks that mercurial is installed
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5596 Ability to configure `--node-cidr-mask-size` into `kube-controller-manager`
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5604 fix typo
  docs/networking.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5603 Update install.md
  docs/install.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5601 Don't assume that we only have one subnet per AZ
  pkg/model/network.go
  tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
  tests/integration/update_cluster/complex/kubernetes.tf
  tests/integration/update_cluster/existing_iam/kubernetes.tf
  tests/integration/update_cluster/externallb/kubernetes.tf
  tests/integration/update_cluster/ha/kubernetes.tf
  tests/integration/update_cluster/lifecycle_phases/network-kubernetes.tf
  tests/integration/update_cluster/minimal-141/kubernetes.tf
  tests/integration/update_cluster/minimal/kubernetes.tf
  tests/integration/update_cluster/private-shared-subnet/kubernetes.tf
  tests/integration/update_cluster/privatecalico/kubernetes.tf
  tests/integration/update_cluster/privatecanal/kubernetes.tf
  tests/integration/update_cluster/privatedns1/kubernetes.tf
  tests/integration/update_cluster/privatedns2/kubernetes.tf
  tests/integration/update_cluster/privateflannel/kubernetes.tf
  tests/integration/update_cluster/privatekopeio/kubernetes.tf
  tests/integration/update_cluster/privateweave/kubernetes.tf
  tests/integration/update_cluster/shared_subnet/kubernetes.tf
  tests/integration/update_cluster/shared_vpc/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/subnet.go
Labels: approved, blocks-next, cherrypick-candidate, cncf-cla: yes, lgtm, size/L

#5602 Fix additional security groups changes on api lb
  upup/pkg/fi/cloudup/awstasks/load_balancer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5611 Cherry pick of #5529 onto release-1.10
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5595 Enable weave network encryption for k8s 1.6
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
Labels: approved, area/networking, cherrypick-candidate, cncf-cla: yes, lgtm, size/S

#5613 Cherry pick of #5566 onto release-1.10
  pkg/model/iam/iam_builder.go
  pkg/model/iam/tests/iam_builder_master_legacy.json
  pkg/model/iam/tests/iam_builder_master_strict.json
  pkg/model/iam/tests/iam_builder_master_strict_ecr.json
  tests/integration/update_cluster/additional_cidr/cloudformation.json
  tests/integration/update_cluster/additional_user-data/cloudformation.json
  tests/integration/update_cluster/externallb/cloudformation.json
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#5610 Create ExperimentalClusterDNS feature flag
  pkg/apis/kops/validation/legacy.go
  pkg/featureflag/featureflag.go
  pkg/model/components/kubelet.go
Labels: approved, cherrypick-candidate, cncf-cla: yes, lgtm, size/M

#5616 Cherry pick of #5508 onto release-1.10
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/L

#5617 Cherry pick of #5597 onto release-1.10
  pkg/model/iam/iam_builder.go
  pkg/model/iam/tests/iam_builder_master_strict.json
  pkg/model/iam/tests/iam_builder_master_strict_ecr.json
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/S

#5621 Validate that require-kubeconfig is not passed after 1.10
  pkg/apis/kops/validation/legacy.go
Labels: approved, blocks-next, cherrypick-candidate, cncf-cla: yes, lgtm, size/S

#5615 Cherry pick of #5595 onto release-1.10
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/S

#5619 Cherry pick of #5511 onto release-1.10
  pkg/resources/aws/aws.go
  pkg/resources/dumpmodel.go
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/M

#5622 Docs for policy to do cross account state store in s3
  docs/state.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5614 Cherry pick of #5577 onto release-1.10
  docs/images.md
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/M

#5625 DigitalOcean: don't try to set SSE
  util/pkg/vfs/s3fs.go
Labels: approved, blocks-next, cherrypick-candidate, cncf-cla: yes, lgtm, size/S

#5628 Cherry pick of #5610 onto release-1.10
  pkg/apis/kops/validation/legacy.go
  pkg/featureflag/featureflag.go
  pkg/model/components/kubelet.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/M

#5629 Cherry pick of #5621 onto release-1.10
  pkg/apis/kops/validation/legacy.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/S

#5623 Remove _kubernetes_master tag
  nodeup/pkg/model/context.go
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_master-us-west-2a.masters.k8s-iam.us-west-2.td.priv_user_data
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  upup/pkg/fi/cloudup/tagbuilder.go
  upup/pkg/fi/nodeup/command.go
Labels: P2, approved, cncf-cla: yes, lgtm, size/M

#5630 Cherry pick of #5625 onto release-1.10
  util/pkg/vfs/s3fs.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/S

#5631 Cherry pick of #5618 onto release-1.10
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/XS

#5608 Update CoreDNS deployment
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5636 Add `DEBUGGABLE` option to Makefile to compile debuggable bins
  Makefile
  docs/development/building.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#5639 Add changelog to release notes for 1.10
  docs/releases/1.10-NOTES.md
Labels: approved, cncf-cla: yes, size/L

#5638 Update README.md
  addons/kube-ingress-aws-controller/README.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5643 Fix build: prevent verify-misspelling failing on releases
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5484 Update readme compatability matrix for 1.10
  README.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#5651 Upgrade DigitalOcean CCM to v0.1.7
  upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5649 add kube-proxy hostname override
  pkg/model/components/kubeproxy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5637 Create getting started with OpenStack doc
  docs/tutorial/openstack.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#5648 Update route53api.go
  dnsprovider/pkg/dnsprovider/providers/aws/route53/stubs/route53api.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5654 AWS VPC Daemonset Correctly Tolerate Node Taints
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5580 Added // restore // guide to single-to-multi-master.md
  docs/single-to-multi-master.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#5657 Update alpha channel with images for foreshadow
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/S

#5660 Basic validation for imagetype for NVME enabled instances
  pkg/apis/kops/validation/BUILD.bazel
  pkg/apis/kops/validation/aws.go
  pkg/apis/kops/validation/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5593 Apply cloud labels into ELB
  tests/integration/update_cluster/complex/kubernetes.tf
  upup/pkg/fi/cloudup/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5665 Cherry-pick release 1.10.0 commit
  Makefile
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
  version.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5663 Promote kubernetes versions from alpha -> stable
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5666 Push latest k8s versions to alpha channel
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/S

#5656 Cherry pick of #5651 to release-1.10
  upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5674 Added myself to SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5669 Fixes go vet complain in package upup/pkg/fi/cloudup/awstasks
  upup/pkg/fi/cloudup/awstasks/iamrole.go
  upup/pkg/fi/cloudup/awstasks/iamrolepolicy.go
  upup/pkg/fi/cloudup/awstasks/load_balancer.go
  upup/pkg/fi/cloudup/awstasks/natgateway.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5681 Update machine_types.go to support T3 family
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5693 Change vendored weave mesh to use hash keys by default
  Gopkg.lock
  Makefile
  vendor/github.com/weaveworks/mesh/BUILD.bazel
  vendor/github.com/weaveworks/mesh/peer_name_hash.go
  vendor/github.com/weaveworks/mesh/peer_name_mac.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5692 Add etcd volumeSize docs
  docs/cluster_spec.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#5698 Fix a typo: ectd->etcd
  docs/manifests_and_customizing_via_api.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5711 updated image versions and deployment instructions for the nginx-ingress addon
  addons/ingress-nginx/README.md
  addons/ingress-nginx/v1.6.0-gce.yaml
  addons/ingress-nginx/v1.6.0.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5727 Update CoreDNS version and manifest
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5716 Make chrisz100 a reviewer for kops
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5731 OpenStack: enable cluster state deletion
  hack/.packages
  pkg/resources/openstack/BUILD.bazel
  pkg/resources/openstack/resources.go
  pkg/resources/ops/BUILD.bazel
  pkg/resources/ops/collector.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5732 OpenStack: vendor schedulerhints
  Gopkg.lock
  upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel
  upup/pkg/fi/cloudup/openstacktasks/instance.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/schedulerhints/BUILD.bazel
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/schedulerhints/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/schedulerhints/requests.go
Labels: approved, cncf-cla: yes, lgtm, size/L
