Repository kubernetes/kops, pull requests merged in 2018-05, with the labels that each got.

#5084 Typo fix in vsphere-development-status.md: secrete->secret
  docs/vsphere-development-status.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5081 Note that `kops rolling-update` is required after tf apply
  docs/terraform.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5091 Typo fix: wil->will
  docs/apireference/build/documents/_generated_accessspec_v1alpha2_kops_definition.md
  docs/apireference/build/index.html
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha2/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5094 Add SubnetType tags to run_in_existing_vpc docs
  docs/run_in_existing_vpc.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5099 Typo fix: acutally->actually/overide->override/to to->to
  cmd/kops/create_cluster.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/lifecycle.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5067 Typo fix detaults->defaults
  docs/apireference/build/index.html
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha2/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5125 Typo fix: healthly->healthy
  cmd/kops/validate.go
  docs/cli/kops_validate.md
  docs/cli/kops_validate_cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4958 Remove custom Statement IDs from IAM Policy Statements
  pkg/model/iam/iam_builder.go
  pkg/model/iam/iam_builder_test.go
  pkg/model/iam/tests/iam_builder_bastion.json
  pkg/model/iam/tests/iam_builder_master_legacy.json
  pkg/model/iam/tests/iam_builder_master_strict.json
  pkg/model/iam/tests/iam_builder_master_strict_ecr.json
  pkg/model/iam/tests/iam_builder_node_legacy.json
  pkg/model/iam/tests/iam_builder_node_strict.json
  pkg/model/iam/tests/iam_builder_node_strict_ecr.json
  tests/integration/update_cluster/additional_user-data/cloudformation.json
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#5113 Adds new kops logo
  README.md
  docs/img/logo-notext.ai
  docs/img/logo-notext.eps
  docs/img/logo-notext.jpg
  docs/img/logo-notext.pdf
  docs/img/logo-notext.png
  docs/img/logo-notext.psd
  docs/img/logo-notext.svg
  docs/img/logo.ai
  docs/img/logo.eps
  docs/img/logo.jpg
  docs/img/logo.pdf
  docs/img/logo.png
  docs/img/logo.psd
  docs/img/logo.svg
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XXL

#5100 Update rules go to support go 1.10.2 and 1.9.6
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5112 Typo fix in returned message: formated->formatted
  cmd/kops/toolbox_template.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5096 Fix for validating kubeconfig's hosts
  pkg/validation/validate_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5088 Added tls certificate and private key path flags to kubelet config
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5104 kublet: expose --experimental-allowed-unsafe-sysctls
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5057 Update docker image versions
  WORKSPACE
  images/utils-builder/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4041 CoreDNS in Kops as an addon
  docs/cluster_spec.md
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/validation/legacy.go
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4991 Implement network task for AlibabaCloud
  Gopkg.lock
  Makefile
  cmd/kops/BUILD.bazel
  cmd/kops/create_cluster.go
  hack/.packages
  pkg/apis/kops/channel.go
  pkg/model/alimodel/BUILD.bazel
  pkg/model/alimodel/context.go
  pkg/model/alimodel/convenience.go
  pkg/model/alimodel/network.go
  upup/pkg/fi/cloud.go
  upup/pkg/fi/cloudup/BUILD.bazel
  upup/pkg/fi/cloudup/alitasks/BUILD.bazel
  upup/pkg/fi/cloudup/alitasks/vpc.go
  upup/pkg/fi/cloudup/alitasks/vpc_fitask.go
  upup/pkg/fi/cloudup/alitasks/vswitch.go
  upup/pkg/fi/cloudup/alitasks/vswitch_fitask.go
  upup/pkg/fi/cloudup/aliup/BUILD.bazel
  upup/pkg/fi/cloudup/aliup/ali_apitarget.go
  upup/pkg/fi/cloudup/aliup/ali_cloud.go
  upup/pkg/fi/cloudup/aliup/ali_utils.go
  upup/pkg/fi/cloudup/aliup/ali_utils_test.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/defaults.go
  upup/pkg/fi/cloudup/utils.go
  upup/pkg/fi/values.go
  vendor/github.com/denverdino/aliyungo/ecs/BUILD.bazel
  vendor/github.com/denverdino/aliyungo/ecs/client.go
  vendor/github.com/denverdino/aliyungo/ecs/disks.go
  vendor/github.com/denverdino/aliyungo/ecs/eni.go
  vendor/github.com/denverdino/aliyungo/ecs/forward_entry.go
  vendor/github.com/denverdino/aliyungo/ecs/images.go
  vendor/github.com/denverdino/aliyungo/ecs/instance_types.go
  vendor/github.com/denverdino/aliyungo/ecs/instances.go
  vendor/github.com/denverdino/aliyungo/ecs/monitoring.go
  vendor/github.com/denverdino/aliyungo/ecs/nat_gateway.go
  vendor/github.com/denverdino/aliyungo/ecs/networks.go
  vendor/github.com/denverdino/aliyungo/ecs/regions.go
  vendor/github.com/denverdino/aliyungo/ecs/route_tables.go
  vendor/github.com/denverdino/aliyungo/ecs/router_interface.go
  vendor/github.com/denverdino/aliyungo/ecs/security_groups.go
  vendor/github.com/denverdino/aliyungo/ecs/snapshots.go
  vendor/github.com/denverdino/aliyungo/ecs/snat_entry.go
  vendor/github.com/denverdino/aliyungo/ecs/ssh_key_pair.go
  vendor/github.com/denverdino/aliyungo/ecs/tags.go
  vendor/github.com/denverdino/aliyungo/ecs/vpcs.go
  vendor/github.com/denverdino/aliyungo/ecs/vrouters.go
  vendor/github.com/denverdino/aliyungo/ecs/vswitches.go
  vendor/github.com/denverdino/aliyungo/ecs/zones.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#5122 Allow rolling-update to filter on roles
  cmd/kops/rollingupdatecluster.go
  docs/cli/kops_rolling-update_cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#5117 Remove stub tests
  upup/pkg/fi/cloudup/awsup/BUILD.bazel
  upup/pkg/fi/cloudup/awsup/aws_topology_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5138 Don't tag shared instances at all
  pkg/model/network.go
  upup/pkg/fi/cloudup/awstasks/instance.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4994 fix:please N/A should be " Not Applicable"
  docs/advisories/cve_2017_14491.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5142 Re-enable validation of DNS ServerIP
  pkg/apis/kops/validation/legacy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4990 digitalocean: don't set --cloud-provider=external on control plane starting v1.10
  pkg/apis/kops/validation/legacy.go
  pkg/model/components/apiserver.go
  pkg/model/components/kubecontrollermanager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5152 [instance_groups.md] typo: recieve->receive
  docs/instance_groups.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5148 Update office hours time to account for DST
  README.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5143 set default GracePeriodSeconds to -1 when draining nodes
  pkg/instancegroups/instancegroups.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5158 implement disk task for ALICloud and fix typos
  upup/pkg/fi/cloudup/alitasks/BUILD.bazel
  upup/pkg/fi/cloudup/alitasks/disk.go
  upup/pkg/fi/cloudup/alitasks/disk_fitask.go
  upup/pkg/fi/cloudup/aliup/BUILD.bazel
  upup/pkg/fi/cloudup/aliup/ali_cloud.go
  upup/pkg/fi/cloudup/aliup/ali_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5123 Unify create-create overrides and set-cluster fields
  cmd/kops/create_cluster.go
  pkg/commands/set_cluster.go
  pkg/commands/set_cluster_test.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/M

#5186 Typo fix in the returned message: runnning->running
  upup/pkg/fi/nodeup/nodetasks/package.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5189 added i3.metal AWS instance type
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5181 Documentation - cloudProvider required in kubelet spec with Amazon VPC backend
  docs/cluster_spec.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#5182 1.8 release notes correctly note `replace --force`
  docs/releases/1.8-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5196 CA Key File Permissions
  nodeup/pkg/model/kube_controller_manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5184 implement SSHKey task for ALICloud
  upup/pkg/fi/cloudup/alitasks/BUILD.bazel
  upup/pkg/fi/cloudup/alitasks/sshkey.go
  upup/pkg/fi/cloudup/alitasks/sshkey_fitask.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5198 Documentation - updated example for dashboard installation to 1.8.3
  docs/addons.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5203 Update CoreDNS manifest
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5210 Create initial docs for etcd-manager
  docs/etcd/manager.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#5126 Support (optional) etcd-manager
  hack/.packages
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/manifests.go
  nodeup/pkg/model/protokube.go
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/apis/nodeup/config.go
  pkg/client/simple/vfsclientset/clientset.go
  pkg/kubemanifest/BUILD.bazel
  pkg/kubemanifest/volumes.go
  pkg/model/components/etcd.go
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/options.go
  pkg/urls/BUILD.bazel
  pkg/urls/join.go
  protokube/cmd/protokube/main.go
  protokube/pkg/protokube/kube_boot.go
  upup/pkg/fi/cloudup/BUILD.bazel
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/populate_cluster_spec.go
  upup/pkg/fi/nodeup/command.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/XL

#5136 Create override for etcd-manager image
  pkg/commands/set_cluster.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/XS

#5150 Add stdin support for create -f and replace -f
  cmd/kops/create.go
  cmd/kops/replace.go
  docs/cli/kops_create.md
  docs/cli/kops_replace.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#5173 Update AWS AMI for kubernetes >=1.9.0 <1.10.0
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5167 Kuberenets 1.11 has deprecated ExternalID this replaces it with Provi…
  pkg/cloudinstances/BUILD.bazel
  pkg/cloudinstances/cloud_instance_group.go
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
  upup/pkg/fi/cloudup/gce/instancegroups.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5217 Update alpha channel with latest k8s versions
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/S

#5222 Update alpha channel with latest images
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/S

#5218 Recommend kops 1.9.1 in alpha channel
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5140 Create addon for prometheus-operator
  .gitignore
  addons/prometheus-operator/README.md
  addons/prometheus-operator/addon.yaml
  addons/prometheus-operator/sync-repo.sh
  addons/prometheus-operator/v0.19.0.yaml
  docs/addons.md
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#5220 Fixing name of cert file
  addons/cluster-autoscaler/README.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5216 Promote alpha channel to stable
  channels/stable
  tests/integration/create_cluster/complex/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha/expected-v1alpha1.yaml
  tests/integration/create_cluster/ha/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha1.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
  tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5221 Add --enable-admission-plugins API server flag for k8s 1.10
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/components/apiserver.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5232 Fix typo: "to user" -> "to use"
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/openapi/openapi_generated.go
Labels: approved, cncf-cla: yes, lgtm, size/S
