Repository kubernetes/kops, pull requests merged in 2018-09, with the labels that each got.

#4797 lifecycle tests: check no legacy tags on shared resources
  cmd/kops/lifecycle_integration_test.go
  tests/integration/update_cluster/shared_subnet/in-v1alpha2.yaml
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/XS

#5503 Fix suspendprocess
  pkg/model/awsmodel/autoscalinggroup.go
  pkg/model/bootstrapscript.go
  pkg/model/tests/data/bootstrapscript_0.txt
  pkg/model/tests/data/bootstrapscript_1.txt
  pkg/model/tests/data/bootstrapscript_2.txt
  pkg/model/tests/data/bootstrapscript_3.txt
  pkg/model/tests/data/bootstrapscript_4.txt
  pkg/model/tests/data/bootstrapscript_5.txt
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5686 Fixes go vet complains
  dns-controller/cmd/dns-controller/main.go
  dns-controller/pkg/dns/dnscontroller.go
  pkg/acls/s3/storage.go
  pkg/apis/kops/validation/validation_test.go
  pkg/kubemanifest/visitor.go
  pkg/resources/aws/aws.go
  upup/pkg/fi/cloudup/alitasks/disk.go
  upup/pkg/fi/cloudup/alitasks/launchconfiguration.go
  upup/pkg/fi/cloudup/alitasks/loadbalancer.go
  upup/pkg/fi/cloudup/alitasks/scalinggroup.go
  upup/pkg/fi/cloudup/aliup/ali_cloud.go
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
  upup/pkg/fi/files_owner.go
  upup/pkg/fi/fitasks/keypair.go
  upup/pkg/fi/nodeup/nodetasks/file.go
  upup/pkg/fi/users.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5740 correct 8 spell errors
  docs/instance_groups.md
  docs/networking.md
  docs/node_authorization.md
  docs/releases.md
  docs/single-to-multi-master.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5739 correct spell errors in 'docs/cluster_spec.md'
  docs/cluster_spec.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5726 Use appropriate log level for KOPS_STATE_S3_ACL debug message
  util/pkg/vfs/s3fs.go
Labels: approved, area/usability, cncf-cla: yes, lgtm, size/XS

#5746 Update k8s-ec2-srcdst to v0.2.2
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5752 Add elasticloadbalancing:DeregisterTargets permission to master policy
  pkg/model/iam/iam_builder.go
  pkg/model/iam/tests/iam_builder_master_strict.json
  pkg/model/iam/tests/iam_builder_master_strict_ecr.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5769 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#5745 Explicitly install conntrack
  images/utils-builder/Dockerfile
  images/utils-builder/README.md
  images/utils-builder/extract.sh
  nodeup/pkg/model/kubelet.go
  nodeup/pkg/model/packages.go
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5784 Don't unset AWS_PROFILE in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5787 machine-type generator: go vet fixes
  Makefile
  hack/machine_types/machine_types.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#5737 typo fixes in stable for ci verify jobs
  docs/releases/1.10-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5642 Fix interactive rolling update silently ignored
  pkg/instancegroups/instancegroups.go
Labels: approved, area/rolling-update, cncf-cla: yes, lgtm, size/S

#5641 Update iaminstanceprofile.go
  cloudmock/aws/mockiam/iaminstanceprofile.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5796 Recognize ubuntu images in sshUser dumping
  pkg/resources/aws/aws.go
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5793 Added documentation for Api server LB Certificate
  docs/cluster_spec.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5785 Move verify-spelling to script, install from vendor
  Gopkg.lock
  Gopkg.toml
  Makefile
  hack/verify-spelling.sh
  vendor/github.com/client9/misspell/.gitignore
  vendor/github.com/client9/misspell/.travis.yml
  vendor/github.com/client9/misspell/BUILD.bazel
  vendor/github.com/client9/misspell/Dockerfile
  vendor/github.com/client9/misspell/Gopkg.lock
  vendor/github.com/client9/misspell/Gopkg.toml
  vendor/github.com/client9/misspell/LICENSE
  vendor/github.com/client9/misspell/Makefile
  vendor/github.com/client9/misspell/README.md
  vendor/github.com/client9/misspell/RELEASE-HOWTO.md
  vendor/github.com/client9/misspell/ascii.go
  vendor/github.com/client9/misspell/case.go
  vendor/github.com/client9/misspell/cmd/misspell/BUILD.bazel
  vendor/github.com/client9/misspell/cmd/misspell/main.go
  vendor/github.com/client9/misspell/goreleaser.yml
  vendor/github.com/client9/misspell/install-misspell.sh
  vendor/github.com/client9/misspell/legal.go
  vendor/github.com/client9/misspell/mime.go
  vendor/github.com/client9/misspell/notwords.go
  vendor/github.com/client9/misspell/replace.go
  vendor/github.com/client9/misspell/stringreplacer.go
  vendor/github.com/client9/misspell/stringreplacer_test.gox
  vendor/github.com/client9/misspell/url.go
  vendor/github.com/client9/misspell/words.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#5801 Protect against panic when networking is not set
  pkg/apis/kops/validation/legacy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5804 Cni toleration for tainted nodes
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5799 Fix bazel cross platform
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5199 Addon update heapster
  addons/monitoring-standalone/addon.yaml
  addons/monitoring-standalone/v1.11.0.yaml
  docs/addons.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#5290 Amazon VPC CNI: Kubernetes 1.8+ Manifests
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5813 Add rdrgmnzs as a reviewer to owners file.
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5635 Support for deletion of aws resources albs nlbs during delete
  Gopkg.lock
  cloudmock/aws/mockelbv2/BUILD.bazel
  cloudmock/aws/mockelbv2/api.go
  hack/.packages
  pkg/resources/aws/BUILD.bazel
  pkg/resources/aws/aws.go
  pkg/testutils/BUILD.bazel
  pkg/testutils/integrationtestharness.go
  upup/pkg/fi/cloudup/awsup/BUILD.bazel
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
  upup/pkg/fi/cloudup/awsup/aws_utils.go
  upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/debug.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/decode.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/encode.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/error.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/eventstreamapi/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/eventstreamapi/api.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/eventstreamapi/error.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/header.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/header_value.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/message.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/payload.go
  vendor/github.com/aws/aws-sdk-go/service/elbv2/elbv2iface/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/service/elbv2/elbv2iface/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#5795 Avoid using which, CoreOS doesn't always have it
  pkg/model/resources/nodeup.go
  pkg/model/tests/data/bootstrapscript_0.txt
  pkg/model/tests/data/bootstrapscript_1.txt
  pkg/model/tests/data/bootstrapscript_2.txt
  pkg/model/tests/data/bootstrapscript_3.txt
  pkg/model/tests/data/bootstrapscript_4.txt
  pkg/model/tests/data/bootstrapscript_5.txt
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5815 Start release notes for 1.11
  docs/releases/1.11-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5085 Generate live project documentation using mkdocs and gh-pages
  .gitignore
  Makefile
  docs/.pages
  docs/README.md
  docs/extra.css
  docs/index.md
  docs/releases/legacy-changes.md
  hack/publish-docs.sh
  mkdocs.yml
  requirements-docs.txt
Labels: cncf-cla: yes, lifecycle/stale, size/L

#5811 Fix a typo in usage of server.go
  node-authorizer/cmd/node-authorizer/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5547 Add test for etcd-manager output
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/docker_test.go
  nodeup/pkg/model/kubelet_test.go
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/model_test.go
  pkg/model/components/etcdmanager/tests/minimal/cluster.yaml
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  pkg/testutils/BUILD.bazel
  pkg/testutils/modelharness.go
  upup/pkg/fi/resources.go
Labels: approved, cncf-cla: yes, size/XL

#5794 Delete nodes from k8s api during rolling-update
  pkg/instancegroups/BUILD.bazel
  pkg/instancegroups/instancegroups.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5817 Update golang version to 1.10.3, for k8s 1.11
  Makefile
  WORKSPACE
  images/dns-controller-builder/Dockerfile
  images/protokube-builder/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#5828 Field names are case-sensitive again
  docs/releases/1.11-NOTES.md
  pkg/model/resources/nodeup.go
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/in-v1alpha2.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5822 Run dep to add missing new aws dependencies for elbv2
  Gopkg.lock
  vendor/github.com/aws/aws-sdk-go/aws/client/client.go
  vendor/github.com/aws/aws-sdk-go/aws/client/logger.go
  vendor/github.com/aws/aws-sdk-go/aws/client/metadata/client_info.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/csm/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/aws/csm/doc.go
  vendor/github.com/aws/aws-sdk-go/aws/csm/enable.go
  vendor/github.com/aws/aws-sdk-go/aws/csm/metric.go
  vendor/github.com/aws/aws-sdk-go/aws/csm/metric_chan.go
  vendor/github.com/aws/aws-sdk-go/aws/csm/reporter.go
  vendor/github.com/aws/aws-sdk-go/aws/defaults/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/logger.go
  vendor/github.com/aws/aws-sdk-go/aws/request/handlers.go
  vendor/github.com/aws/aws-sdk-go/aws/request/request.go
  vendor/github.com/aws/aws-sdk-go/aws/request/request_1_7.go
  vendor/github.com/aws/aws-sdk-go/aws/request/request_1_8.go
  vendor/github.com/aws/aws-sdk-go/aws/request/retryer.go
  vendor/github.com/aws/aws-sdk-go/aws/session/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/aws/session/doc.go
  vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go
  vendor/github.com/aws/aws-sdk-go/aws/session/session.go
  vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/internal/sdkuri/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/internal/sdkuri/path.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/build.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/xml_to_struct.go
  vendor/github.com/aws/aws-sdk-go/service/autoscaling/service.go
  vendor/github.com/aws/aws-sdk-go/service/cloudformation/service.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/service.go
  vendor/github.com/aws/aws-sdk-go/service/ecr/service.go
  vendor/github.com/aws/aws-sdk-go/service/elb/service.go
  vendor/github.com/aws/aws-sdk-go/service/elbv2/service.go
  vendor/github.com/aws/aws-sdk-go/service/iam/api.go
  vendor/github.com/aws/aws-sdk-go/service/iam/iamiface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/iam/service.go
  vendor/github.com/aws/aws-sdk-go/service/kms/service.go
  vendor/github.com/aws/aws-sdk-go/service/pricing/service.go
  vendor/github.com/aws/aws-sdk-go/service/route53/service.go
  vendor/github.com/aws/aws-sdk-go/service/s3/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/service/s3/api.go
  vendor/github.com/aws/aws-sdk-go/service/s3/service.go
  vendor/github.com/aws/aws-sdk-go/service/sts/service.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#5783 Tweak machine_types generator to match our existing values
  hack/machine_types/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5814 Fixes spurious LoadBalancer change when using ACM Certificate
  upup/pkg/fi/cloudup/awstasks/load_balancer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5834 Revert "Apply cloud labels into ELB"
  tests/integration/update_cluster/complex/kubernetes.tf
  upup/pkg/fi/cloudup/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5838 Fix markdown typo
  docs/addons.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5841 Node Authorizer Fixes
  node-authorizer/cmd/node-authorizer/BUILD.bazel
  node-authorizer/cmd/node-authorizer/server.go
  node-authorizer/pkg/utils/misc.go
  pkg/model/components/node-authorizer/options.go
  upup/models/cloudup/resources/addons/node-authorizer.addons.k8s.io/k8s-1.10.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5842 Update HPA docs
  docs/horizontal_pod_autoscaling.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5843 Add clarity to AWS IAM Authenticator documentation
  docs/authentication.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#5844 ECU fixes and add f1.4xlarge
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/M
