Repository kubernetes/kops, pull requests merged in 2018-04, with the labels that each got.

#4848 Fix toolbox dump bug: store subnet in resource
  pkg/resources/aws/aws.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4805 Add VPC to kops toolbox dump
  pkg/resources/aws/vpc.go
  pkg/resources/dumpmodel.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4850 Typo fix in err messages
  upup/pkg/fi/cloudup/gcetasks/address.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4612 Export kubernetes client metrics from dns-controller.
  Gopkg.lock
  dns-controller/cmd/dns-controller/BUILD.bazel
  dns-controller/cmd/dns-controller/main.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/BUILD.bazel
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_7.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/k8s.io/kubernetes/BUILD.bazel
  vendor/k8s.io/kubernetes/pkg/client/metrics/prometheus/BUILD.bazel
  vendor/k8s.io/kubernetes/pkg/client/metrics/prometheus/prometheus.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4852 AWS: etcd volume provisioned IOPS support
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/master_volumes.go
  upup/pkg/fi/cloudup/awstasks/ebsvolume.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4698 digitalocean: external cloud controller addon
  upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/template_functions.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4843 Docs/update kube ingress aws controller security group walkthrough
  addons/kube-ingress-aws-controller/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4697 digitalocean: nodeup & protokube support
  nodeup/pkg/bootstrap/install.go
  nodeup/pkg/model/protokube.go
  pkg/client/simple/vfsclientset/clientset.go
  pkg/model/bootstrapscript.go
  pkg/model/resources/nodeup.go
  pkg/model/tests/data/bootstrapscript_0.txt
  pkg/model/tests/data/bootstrapscript_1.txt
  pkg/model/tests/data/bootstrapscript_2.txt
  pkg/model/tests/data/bootstrapscript_3.txt
  pkg/model/tests/data/bootstrapscript_4.txt
  pkg/model/tests/data/bootstrapscript_5.txt
  pkg/resources/digitalocean/cloud.go
  pkg/resources/digitalocean/dns/dns.go
  protokube/cmd/protokube/main.go
  protokube/pkg/protokube/BUILD.bazel
  protokube/pkg/protokube/do_volume.go
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4858 Add DigitalOcean VFS
  util/pkg/vfs/context.go
  util/pkg/vfs/s3fs.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4830 implement network task for OpenStack platform
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel
  upup/pkg/fi/cloudup/openstacktasks/network.go
  upup/pkg/fi/cloudup/openstacktasks/network_fitask.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/BUILD.bazel
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/urls.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4581 Add metrics-server addon
  addons/metrics-server/README.md
  addons/metrics-server/v1.7.x.yaml
  addons/metrics-server/v1.8.x.yaml
  docs/horizontal_pod_autoscaling.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#4859 Validation around IOPS fields
  pkg/apis/kops/validation/cluster.go
  pkg/apis/kops/validation/instancegroup.go
  pkg/model/awsmodel/autoscalinggroup.go
  pkg/model/master_volumes.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4860 add output support to terraform & cloudformation for iops volume
  upup/pkg/fi/cloudup/awstasks/ebsvolume.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4842 add network builder
  hack/.packages
  pkg/model/openstackmodel/BUILD.bazel
  pkg/model/openstackmodel/context.go
  pkg/model/openstackmodel/convenience.go
  pkg/model/openstackmodel/network.go
  upup/pkg/fi/cloudup/BUILD.bazel
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/openstack/cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4864 update basic-requirements.md
  docs/examples/basic-requirements.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4870 Typo fix in err message
  upup/pkg/fi/cloudup/gce/mock_gce_cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4865 two spell mistake
  docs/examples/coreos-kops-tests-multimaster.md
  docs/examples/kops-test-route53-subdomain.md
  docs/examples/kops-tests-private-net-bastion-host.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4871 Release 1.9.0-beta.1
  Makefile
  tools/get_workspace_status.sh
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4861 spell depedencies --> dependencies
  docs/apireference/build/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4719 Implement vfs with AlibabaCloud OSS
  Gopkg.lock
  util/pkg/vfs/BUILD.bazel
  util/pkg/vfs/context.go
  util/pkg/vfs/osscontext.go
  util/pkg/vfs/ossfs.go
  util/pkg/vfs/vfs.go
  vendor/github.com/denverdino/aliyungo/LICENSE.txt
  vendor/github.com/denverdino/aliyungo/common/BUILD.bazel
  vendor/github.com/denverdino/aliyungo/common/client.go
  vendor/github.com/denverdino/aliyungo/common/endpoint.go
  vendor/github.com/denverdino/aliyungo/common/endpoints.xml
  vendor/github.com/denverdino/aliyungo/common/regions.go
  vendor/github.com/denverdino/aliyungo/common/request.go
  vendor/github.com/denverdino/aliyungo/common/types.go
  vendor/github.com/denverdino/aliyungo/common/version.go
  vendor/github.com/denverdino/aliyungo/oss/BUILD.bazel
  vendor/github.com/denverdino/aliyungo/oss/authenticate_callback.go
  vendor/github.com/denverdino/aliyungo/oss/client.go
  vendor/github.com/denverdino/aliyungo/oss/export.go
  vendor/github.com/denverdino/aliyungo/oss/multi.go
  vendor/github.com/denverdino/aliyungo/oss/regions.go
  vendor/github.com/denverdino/aliyungo/oss/signature.go
  vendor/github.com/denverdino/aliyungo/util/BUILD.bazel
  vendor/github.com/denverdino/aliyungo/util/attempt.go
  vendor/github.com/denverdino/aliyungo/util/encoding.go
  vendor/github.com/denverdino/aliyungo/util/iso6801.go
  vendor/github.com/denverdino/aliyungo/util/signature.go
  vendor/github.com/denverdino/aliyungo/util/util.go
  vendor/k8s.io/kubernetes/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4874 Adding Mike and myself as reviewers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4876 Fix some info errors
  upup/pkg/fi/cloudup/subnets.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4872 Typo fix in info message
  upup/pkg/fi/nodeup/nodetasks/service.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4878 Fixes port collision between dns-controller metrics and gossip.
  upup/pkg/fi/cloudup/template_functions.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4888 removed sed from command to get AMI images
  docs/examples/coreos-kops-tests-multimaster.md
  docs/images.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4887 spell correct
  docs/etcd_backup.md
  docs/instance_groups.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4886 correct spell in the code and the relative doc
  cmd/kops/create_cluster.go
  cmd/kops/create_ig.go
  cmd/kops/validate_cluster.go
  docs/cli/kops_create_cluster.md
  docs/cli/kops_create_instancegroup.md
  docs/cli/kops_validate_cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4892 Don't enable dns-controller prometheus metrics by default
  dns-controller/cmd/dns-controller/main.go
  upup/pkg/fi/cloudup/template_functions.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4891 Document the ports we use, to avoid conflicts
  docs/development/ports.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4885 update download_config.md
  docs/download_config.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4884 fix spell mistakes in cluster_spec.md
  docs/cluster_spec.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4883 update two file
  docs/arguments.md
  docs/aws-china.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4881 digitalocean: support multiple droplets
  pkg/model/domodel/droplets.go
  upup/pkg/fi/cloudup/dotasks/droplet.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4880 digitalocean: add kubelet hostname override
  pkg/model/components/kubelet.go
  upup/pkg/fi/nodeup/command.go
  util/pkg/vfs/context.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4879 typo fix
  pkg/validation/validate_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4898 fix go vet error from util/pkg/vfs/ossfs.go
  util/pkg/vfs/ossfs.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4894 coreos/containeros: restart kops-configuration service after docker drop-in is loaded
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4905 update vsphere-development-status.md
  docs/vsphere-development-status.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4902 three spell mistakes
  docs/manifests_and_customizing_via_api.md
  docs/node_resource_handling.md
  docs/philosophy.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#4907 Release 1.9.0-beta.2
  Makefile
  tools/get_workspace_status.sh
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4911 Updating API Machinery
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/XS

#4915 protokube: also check for device symlinks
  protokube/pkg/protokube/kube_boot.go
  protokube/pkg/protokube/volume_mounter.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4916 digitalocean: list/delete resources
  pkg/resources/digitalocean/BUILD.bazel
  pkg/resources/digitalocean/dns/BUILD.bazel
  pkg/resources/digitalocean/dns/dns.go
  pkg/resources/digitalocean/dns/dns_test.go
  pkg/resources/digitalocean/do.go
  pkg/resources/digitalocean/resources.go
  pkg/resources/ops/collector.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4933 Update channels to 1.9.0-beta.2
  channels/alpha
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4932 Fix typo in api_updates
  docs/development/api_updates.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#4930 Typo fix an->and
  nodeup/pkg/model/protokube.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4939 Fix spelling
  docs/bastion.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4936 Fix grammar mistake
  upup/pkg/fi/cloudup/urls.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4934 Update the reccomended Ubuntu Image
  docs/images.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4929 Typo fix dont'->don't
  docs/examples/basic-requirements.md
  docs/examples/kops-test-route53-subdomain.md
  docs/examples/kops-tests-private-net-bastion-host.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4948 Update rules go and use more recent debian snapshot
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4943 fix typo
  cmd/kops/delete_confirm_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4947 digitalocean: external cloud controller manager avoid circular dependencies
  upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4945 implement subnet task for OpenStack platform
  pkg/model/openstackmodel/context.go
  pkg/model/openstackmodel/network.go
  upup/pkg/fi/cloudup/defaults.go
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel
  upup/pkg/fi/cloudup/openstacktasks/subnet.go
  upup/pkg/fi/cloudup/openstacktasks/subnet_fitask.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/BUILD.bazel
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/urls.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4944 Add warning about google cloud repository versions
  docs/cluster_spec.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4935 fix version of kube-router at v0.1.0
  upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.6.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4928 Configurable log level for calico
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/S

#4924 Feature/4920 add authorization mode flag
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4919 Add configurable dnsmasq params to KubeDNS
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/model/components/kubedns.go
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/pre-k8s-1.6.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#4851 Update kube-dns to 1.14.9
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4952 Avoid collisions in IAM ids
  pkg/model/iam/iam_builder.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/M

#4909 Disable locksmithd on CoreOS if UpdatePolicy set
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/update_service.go
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3498 Pod Security Policies
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  upup/models/cloudup/resources/addons/podsecuritypolicy.addons.k8s.io/k8s-1.9.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4957 Fix etcd Keypair change showing on every kops update when TLS enabled
  upup/pkg/fi/fitasks/keypair.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4959 Only do etcd backups on main
  nodeup/pkg/model/protokube.go
  protokube/pkg/protokube/etcd_cluster.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/S

#4954 Bump Weave Net to 2.3.0
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4960 Ignore shared-ownership tags on volumes
  protokube/pkg/protokube/aws_volume.go
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4962 Release 1.9.0
  Makefile
  tools/get_workspace_status.sh
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4965 Update alpha channel with latest k8s releases
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/S

#4964 1.9.0 release notes
  docs/releases/1.9-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#4976 digitalocean tutorial
  README.md
  docs/tutorial/digitalocean.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#4966 Update roadmap
  ROADMAP.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#5005 digitalocean: use new droplet sizes providing the same resources at cheaper prices
  upup/pkg/fi/cloudup/populate_instancegroup_spec.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4982 Set AWS_REGION into bootstrapscript
  pkg/bundle/builder.go
  pkg/model/awsmodel/autoscalinggroup.go
  pkg/model/bootstrapscript.go
  pkg/model/bootstrapscript_test.go
  pkg/model/domodel/droplets.go
  pkg/model/gcemodel/autoscalinggroup.go
  pkg/model/resources/nodeup.go
  pkg/model/tests/data/bootstrapscript_0.txt
  pkg/model/tests/data/bootstrapscript_1.txt
  pkg/model/tests/data/bootstrapscript_2.txt
  pkg/model/tests/data/bootstrapscript_3.txt
  pkg/model/tests/data/bootstrapscript_4.txt
  pkg/model/tests/data/bootstrapscript_5.txt
  pkg/model/vspheremodel/autoscalinggroup.go
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  upup/pkg/fi/cloudup/vspheretasks/attachiso.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5006 digitalocean: only delete A DNS records
  pkg/resources/digitalocean/resources.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4983 AWS: validate region against aws-sdk
  upup/pkg/fi/cloudup/awsup/BUILD.bazel
  upup/pkg/fi/cloudup/awsup/aws_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5028 Treat Amazon Linux 2 as CentOS 7
  nodeup/pkg/distros/identify.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5022 Add missing google cloud zones
  upup/pkg/fi/cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5036 gazelle: use separate gazelle
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#5041 Bump recommended version for kops 1.9.0
  channels/alpha
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5014 fix IAM role for current versions of the kube-ingress-aws-controller
  addons/kube-ingress-aws-controller/README.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5042 Add docker 17.09.0 version for Debian 9
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5016 Fixes environment variable export.
  docs/networking.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#4993 fix :"rbac" should be "RBAC"
  docs/addons.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5026 upgrade kube-dns to 1.14.10, fixes #4986
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5053 makefile: fix bazel-push
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5058 Typo fix aditional->additional
  docs/apireference/build/index.html
  docs/instance_groups.md
  pkg/apis/kops/cluster.go
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  pkg/model/resources/nodeup.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5050 Add Replace and delete for SSH Secret YAML
  cmd/kops/create.go
  cmd/kops/delete.go
  cmd/kops/replace.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4963 Update readme for 1.9
  README-ES.md
  README.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#5073 Typo fix in 1.9-NOTES.md: compatability->compatibility
  docs/releases/1.9-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5079 Typo fix: Kuberenetes->Kubernetes
  docs/manifests_and_customizing_via_api.md
  docs/node_resource_handling.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5080 Typo fix: seet->set
  upup/pkg/fi/cloudup/awstasks/tags.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
