Repository kubernetes/kops, pull requests merged in 2018-10, with the labels that each got.

#5849 Fix minor typo.
  pkg/instancegroups/instancegroups.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5719 copy path on kops-server-build
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5741 cluster-autoscaler.yaml for 1.10
  addons/cluster-autoscaler/README.md
  addons/cluster-autoscaler/v1.10.0.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5855 Controller Manager Flag
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5744 Allow using existing/shared Security Groups
  cmd/kops/integration_test.go
  docs/security_groups.md
  pkg/apis/kops/cluster.go
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/BUILD.bazel
  pkg/model/awsmodel/api_loadbalancer.go
  pkg/model/awsmodel/autoscalinggroup.go
  pkg/model/external_access.go
  pkg/model/firewall.go
  pkg/model/firewall_test.go
  tests/integration/update_cluster/existing_sg/id_rsa.pub
  tests/integration/update_cluster/existing_sg/in-v1alpha2.yaml
  tests/integration/update_cluster/existing_sg/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/securitygroup.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#5820 etcd: introduce field to specify whether we are using etcd-manager or legacy mode
  cmd/kops/create_cluster_integration_test.go
  docs/etcd/manager.md
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/validation/cluster.go
  pkg/apis/kops/validation/legacy.go
  pkg/apis/kops/validation/validation.go
  pkg/commands/set_cluster.go
  pkg/model/components/etcd.go
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/options.go
  pkg/model/components/etcdmanager/tests/minimal/cluster.yaml
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  tests/integration/create_cluster/minimal/expected-v1alpha1.yaml
  tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal/options.yaml
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/populate_cluster_spec.go
  upup/pkg/fi/cloudup/validation_test.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/L

#5865 Remove last vestiges of _vendor directory
  Makefile
  _vendor/bitbucket.org/ww/goautoneg/Makefile
  _vendor/bitbucket.org/ww/goautoneg/README.txt
  _vendor/bitbucket.org/ww/goautoneg/autoneg.go
  _vendor/bitbucket.org/ww/goautoneg/autoneg_test.go
  hack/dep.py
  hack/verify-spelling.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#5857 Stop cloudformation output switching to literal quotes
  cmd/kops/integration_test.go
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5861 doc: Trivial spelling change
  docs/examples/kops-tests-private-net-bastion-host.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5867 Node mode controllers
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/components/kubecontrollermanager.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5868 Node Authorizer Fixes
  node-authorizer/cmd/node-authorizer/client.go
  node-authorizer/cmd/node-authorizer/server.go
  node-authorizer/pkg/client/client.go
  node-authorizer/pkg/server/admission.go
  node-authorizer/pkg/server/server.go
  pkg/model/components/node-authorizer/options.go
  upup/models/cloudup/resources/addons/node-authorizer.addons.k8s.io/k8s-1.10.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5853 Fix broken url in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5860 doc: fix minor typo in the terraform doc
  docs/terraform.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5858 Mirror secrets using API
  upup/pkg/fi/secrets/vfs_secretstore.go
  upup/pkg/fi/vfs_castore.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5859 Fix mis-typing in documentation
  docs/download_config.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5869 Generate much smaller keys in integration tests
  pkg/pki/privatekey.go
  pkg/testutils/BUILD.bazel
  pkg/testutils/integrationtestharness.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5872 Fix a few typos.
  cmd/kops/create.go
  cmd/kops/create_secret.go
  cmd/kops/create_secret_dockerconfig.go
  cmd/kops/create_secret_sshpublickey.go
  cmd/kops/rollingupdatecluster.go
  docs/cli/kops_create.md
  docs/cli/kops_create_secret.md
  docs/cli/kops_create_secret_dockerconfig.md
  docs/cli/kops_create_secret_sshpublickey.md
  docs/cli/kops_rolling-update.md
  docs/cli/kops_rolling-update_cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5878 Fix mis-typings in documentation.
  docs/instance_groups.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5812 Add no_masq_local to weave network options.
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5894 propagate error when initializing digitalocean provider
  upup/pkg/fi/cloudup/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5425 Fixed duplicate info
  docs/cli/kops_create_cluster.md
Labels: area/documentation, cncf-cla: yes, size/XS

#5832 add support for max-mutating-requests-inflight parameter
  docs/cluster_spec.md
  nodeup/pkg/model/kube_apiserver_test.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5887 Fix mis-typings in docs
  docs/manifests_and_customizing_via_api.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5882 Fix some typos
  addons/prometheus-operator/v0.19.0.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5885 Fix typos issues
  docs/apireference/build/scroll.js
  pkg/apis/kops/cluster.go
  pkg/apis/kops/instancegroup.go
  pkg/systemd/unit_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5886 Fix typos issues in upup files
  protokube/pkg/protokube/kube_boot.go
  upup/pkg/fi/assettasks/copyfile.go
  upup/pkg/fi/cloudup/gcetasks/storagebucketacl.go
  upup/pkg/fi/cloudup/gcetasks/storagebucketiam.go
  upup/pkg/fi/cloudup/gcetasks/storageobjectacl.go
  upup/pkg/fi/cloudup/networking.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5888 Fix mis-typings in docs
  docs/cluster_spec.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5889 Fix broken link to etcd 2 documentation
  docs/etcd_backup.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5896 Update create-cluster arg help
  cmd/kops/create_cluster.go
  cmd/kops/create_secret_sshpublickey.go
  docs/cli/kops_create_cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5898 Removed misleading comment about metav1
  channels/pkg/api/channel.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5890 add targetRamMb to kubeAPIServer spec
  docs/cluster_spec.md
  nodeup/pkg/model/kube_apiserver_test.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5854 Fix mis-typing in CLI command documentations
  cmd/kops/validate.go
  docs/cli/kops_validate.md
  docs/cli/kops_validate_cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5897 alpha-channel: Use stretch by default for k8s 1.11 on AWS
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4949 Fix cloudmock to pass govet
  Makefile
  cloudmock/aws/mockautoscaling/unimplemented.go
  cloudmock/aws/mockec2/address.go
  cloudmock/aws/mockec2/dhcpoptions.go
  cloudmock/aws/mockec2/images.go
  cloudmock/aws/mockec2/instances.go
  cloudmock/aws/mockec2/internetgateways.go
  cloudmock/aws/mockec2/keypairs.go
  cloudmock/aws/mockec2/natgateway.go
  cloudmock/aws/mockec2/routetable.go
  cloudmock/aws/mockec2/securitygroups.go
  cloudmock/aws/mockec2/subnets.go
  cloudmock/aws/mockec2/tags.go
  cloudmock/aws/mockec2/unimplemented.go
  cloudmock/aws/mockec2/volumes.go
  cloudmock/aws/mockec2/vpcs.go
  cloudmock/aws/mockiam/iaminstanceprofile.go
  cloudmock/aws/mockiam/iamrole.go
  cloudmock/aws/mockiam/iamrolepolicy.go
  cloudmock/aws/mockiam/unimplemented.go
  cloudmock/aws/mockroute53/records.go
  cloudmock/aws/mockroute53/unimplemented.go
  cloudmock/aws/mockroute53/zones.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#5845 Update Weave Net to version 2.4.1
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5883 fix typo: remove duplicate words
  docs/development/homebrew.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5884 Add default S3 encryption example
  docs/aws.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5903 Update weave bootstrapchannelbuilder version
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5909 fix some typos
  docs/apireference/build/README.md
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha2/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5906 Google Cloud Storage md5 decoding fix
  util/pkg/vfs/gsfs.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5911 If don't use formatted output,fix logging calls
  pkg/featureflag/featureflag_test.go
  pkg/instancegroups/instancegroups.go
  pkg/instancegroups/rollingupdate.go
  pkg/kubeconfig/kubecfg_builder.go
  pkg/kubemanifest/manifest.go
  pkg/resources/aws/routetable.go
  pkg/resources/aws/vpc.go
  pkg/resources/digitalocean/cloud.go
  pkg/resources/digitalocean/dns/dns.go
  pkg/resources/ops/delete.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5913 Promote kubernetes versions from alpha to stable
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/S

#5914 alpha channel: update with latest kubernetes versions
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/S

#5893 Recognize shasum format for hashes
  pkg/assets/builder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5920 Optimize kops get cluster with a cluster name
  cmd/kops/get.go
  cmd/kops/get_cluster.go
  cmd/kops/get_instancegroups.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5923 Service Address Check
  pkg/apis/kops/validation/legacy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5921 s3: lazy-evaluate encryption policy
  util/pkg/vfs/s3context.go
  util/pkg/vfs/s3fs.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5918 Fixed node-authorizer systemd Unit paths
  nodeup/pkg/model/node_authorizer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5924 fix some typos
  docs/apireference/build/documents/_generated_instancegroup_v1alpha2_kops_concept.md
  docs/apireference/build/index.html
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  pkg/openapi/openapi_generated.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5925 Disable RBAC Addon's in Node Mode
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5931 added possible state store vendors to documentation
  docs/state.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#5943 Fix documents issue
  docs/manifests_and_customizing_via_api.md
  docs/node_resource_handling.md
  docs/terraform.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5927 Canal v3
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.9.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#5942 fix small typos in security.md
  docs/security.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5944 Fix typos in files
  cmd/kops/get_instancegroups.go
  dnsprovider/pkg/dnsprovider/providers/aws/route53/interface.go
  pkg/model/pki.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5948 Ensure we parse k8s versions through 1.16
  pkg/k8sversion/version_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5935 IPVS Options
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/validation/legacy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5947 Promote AMIs from alpha -> stable
  channels/stable
  tests/integration/create_cluster/complex/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha/expected-v1alpha1.yaml
  tests/integration/create_cluster/ha/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha1.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal/expected-v1alpha1.yaml
  tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
  tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5949 Mark release 1.11.0-alpha.1
  Makefile
  docs/releases/1.11-NOTES.md
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
  version.go
Labels: approved, cncf-cla: yes, size/M

#5953 add EnableNodeAuthorization in the list of experimental features
  docs/experimental.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5957 Fix broken url in documentation
  docs/networking.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5963 Delete duplicate 'be'.
  docs/node_resource_handling.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5951 Fix grammatical error in the warning message
  cmd/nodeup/main.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/XS

#5966 Add suggested alias for bazelrc import location
  .bazelrc
  tools/bazel.rc
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5972 Fix the typos
  addons/prometheus-operator/v0.19.0.yaml
  cmd/kops/validate_cluster.go
  docs/advisories/cve_2017_14491.md
  docs/development/testing.md
  docs/high_availability.md
  docs/networking.md
  nodeup/pkg/model/kubelet.go
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#5974 Switch CI to bazel
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#5970 Fix nsenter mounter in protokube
  protokube/pkg/protokube/volume_mounter.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5969 Use hostPID: true with etcd-manager
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5979 terraform: Fix resource formatting for IPv6 CIDRs
  cmd/kops/integration_test.go
  tests/integration/update_cluster/externallb/kubernetes.tf
  tests/integration/update_cluster/restrict_access/id_rsa.pub
  tests/integration/update_cluster/restrict_access/in-v1alpha2.yaml
  tests/integration/update_cluster/restrict_access/kubernetes.tf
  upup/pkg/fi/cloudup/terraform/target.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#5928 Correct Spelling of "kubernetesVersion"
  docs/upgrade.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#5946 More CNI toleration for tainted nodes.
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.8.yaml.template
  upup/models/cloudup/resources/addons/networking.kope.io/k8s-1.6.yaml
  upup/models/cloudup/resources/addons/networking.romana/k8s-1.7.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6001 fix typo in comments
  pkg/apis/kops/cluster.go
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/instancegroup.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6006 Clarify license statement for nvidia-bootstrap hook
  hooks/nvidia-bootstrap/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5996 fixed MIN_NODES missing closing bracket
  addons/cluster-autoscaler/v1.10.0.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6002 fix typo in log
  upup/pkg/fi/cloudup/alitasks/disk.go
  upup/pkg/fi/cloudup/alitasks/launchconfiguration.go
  upup/pkg/fi/cloudup/alitasks/loadbalancer.go
  upup/pkg/fi/cloudup/alitasks/scalinggroup.go
  upup/pkg/fi/cloudup/alitasks/securitygroup.go
  upup/pkg/fi/cloudup/awstasks/vpccidrblock.go
  upup/pkg/fi/secrets/clientset_secretstore.go
  upup/pkg/fi/secrets/vfs_secretstore.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5950 Mount etc-hosts in calico-kube-controller
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7.yaml.template
Labels: approved, area/networking, cncf-cla: yes, lgtm, size/XS

#5985 Bump CoreDNS version to 1.2.4 and update manifest
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5987 cilium: Fix Prometheus serve addr flag
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5993 Add stdin input for secrets
  cmd/kops/create.go
  cmd/kops/create_secret_dockerconfig.go
  cmd/kops/create_secret_encryptionconfig.go
  cmd/kops/create_secret_weave_encryptionconfig.go
  cmd/kops/delete.go
  cmd/kops/root.go
  docs/apireference/openapi-spec/swagger.json
  docs/cli/kops_create_secret_dockerconfig.md
  docs/cli/kops_create_secret_encryptionconfig.md
  docs/cli/kops_create_secret_weavepassword.md
  docs/cli/kops_delete.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#6004 Separate subnet utils into a standalone package
  hack/.packages
  pkg/apis/kops/validation/BUILD.bazel
  pkg/apis/kops/validation/helpers.go
  pkg/apis/kops/validation/helpers_test.go
  pkg/apis/kops/validation/legacy.go
  pkg/util/subnet/BUILD.bazel
  pkg/util/subnet/subnet.go
  pkg/util/subnet/subnet_test.go
  upup/pkg/fi/cloudup/BUILD.bazel
  upup/pkg/fi/cloudup/subnets.go
  upup/pkg/fi/cloudup/subnets_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5997 Update v0.19.0.yaml
  addons/prometheus-operator/v0.19.0.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6019 Prune some license files that dep added
  Makefile
  vendor/github.com/docker/docker/contrib/selinux-fedora-24/docker-engine-selinux/LICENSE
  vendor/github.com/docker/docker/contrib/selinux-oraclelinux-7/docker-engine-selinux/LICENSE
  vendor/github.com/docker/docker/contrib/syntax/vim/LICENSE
Labels: approved, cncf-cla: yes, lgtm, size/XL
