Repository kubernetes/kops, pull requests merged in 2018-02, with the labels that each got.

#4411 Bump alpha channel to new image
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/S

#4413 Update Weave Net to version 2.2.0
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#4421 Bump weave version to 2.2.0
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4406 upup: Make RenderTerraform handle an error from AddOutputVariableArray
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4422 Cherrypicks for 1.8.1
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/model/components/kubelet.go
  upup/models/cloudup/resources/addons/networking.kope.io/k8s-1.6.yaml
  upup/models/cloudup/resources/addons/networking.kope.io/pre-k8s-1.6.yaml
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.8.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/pre-k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.romana/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4423 Add notes for 1.8.1 release
  docs/development/release.md
  docs/releases/1.8.1.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#4409 master node requires DescribeRegions when using a bucket from another…
  pkg/model/iam/iam_builder.go
  pkg/model/iam/tests/iam_builder_master_strict.json
  pkg/model/iam/tests/iam_builder_master_strict_ecr.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4371 Pick up etcd version changes for a rolling update on master nodes
  cmd/kops/integration_test.go
  hack/.packages
  nodeup/pkg/model/convenience.go
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_controller_manager.go
  nodeup/pkg/model/kube_proxy.go
  nodeup/pkg/model/kube_scheduler.go
  pkg/model/bootstrapscript.go
  pkg/model/bootstrapscript_test.go
  pkg/model/tests/data/bootstrapscript_0.txt
  pkg/model/tests/data/bootstrapscript_1.txt
  pkg/model/tests/data/bootstrapscript_2.txt
  protokube/pkg/protokube/etcd_manifest.go
  protokube/tests/integration/build_etcd_manifest/main/etcd_env_vars.yaml
  protokube/tests/integration/build_etcd_manifest/main/non_tls.yaml
  protokube/tests/integration/build_etcd_manifest/main/tls.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  util/pkg/exec/exec.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4427 API audit doc changes
  docs/cluster_spec.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4426 fix a typo in tool_template.go
  cmd/kops/toolbox_template.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4432 Updating Makefile to the correct versions for the 1.8.1 release
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4431 Update BUILD files to account for some recent changes
  nodeup/pkg/model/BUILD.bazel
  pkg/instancegroups/BUILD.bazel
  protokube/pkg/protokube/BUILD.bazel
  util/pkg/exec/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/S

#4433 Update upgrade.md
  docs/upgrade.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, retest-not-required-docs-only, size/XS

#4182 Update Cluster Autoscaler image and Reduce the Delta between autoscaler docs
  addons/cluster-autoscaler/README.md
  addons/cluster-autoscaler/addon.yml
  addons/cluster-autoscaler/v1.8.0.yaml
Labels: approved, area/addon-manager, cncf-cla: yes, lgtm, size/L

#4436 Fix wrong backticks markdown.
  docs/commands.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4169 Add live-restore flag to docker config
  pkg/apis/kops/dockerconfig.go
  pkg/apis/kops/v1alpha1/dockerconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/dockerconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4438 Fixing problems in dev build script example
  hack/dev-build.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#4395 Add max-requests-inflight parameter
  docs/apireference/build/index.html
  docs/apireference/build/manifest.json
  docs/apireference/build/navData.js
  docs/cluster_spec.md
  nodeup/pkg/model/kube_apiserver_test.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/openapi/openapi_generated.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4437 Updates for x1 instance family
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4440 Fix instange groups docs
  cmd/kops/create_ig.go
  cmd/kops/delete_instancegroup.go
  docs/cli/kops_create_instancegroup.md
  docs/cli/kops_delete_instancegroup.md
  docs/instance_groups.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4240 Kubernetes Calico TLS
  cmd/kops/integration_test.go
  cmd/kops/update_cluster.go
  nodeup/pkg/model/calico.go
  nodeup/pkg/model/context.go
  nodeup/pkg/model/protokube.go
  pkg/assets/builder.go
  pkg/model/iam.go
  pkg/model/iam/iam_builder.go
  pkg/model/pki.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/template_functions.go
  upup/pkg/fi/nodeup/command.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/L

#4384 Add to aws-china.md to prevent Etag not match the HASH of file.
  docs/aws-china.md
  upup/pkg/fi/cloudup/networking.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4456 add storageclasses permissions for cluster-autoscaler:v1.1.0
  addons/cluster-autoscaler/v1.8.0.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4459 Fixing ExistsAndWarnIfChanges so that it will allow a user to pass
  upup/pkg/fi/context.go
  upup/pkg/fi/executor.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4457 updating bazel BUILD file
  nodeup/pkg/model/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4445 Lifecycle overrides
  cmd/kops/update_cluster.go
  docs/cli/kops_update_cluster.md
  upup/pkg/fi/assettasks/copydockerimage_fitask.go
  upup/pkg/fi/assettasks/copyfile_fitask.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup_fitask.go
  upup/pkg/fi/cloudup/awstasks/dhcpoptions_fitask.go
  upup/pkg/fi/cloudup/awstasks/dnsname_fitask.go
  upup/pkg/fi/cloudup/awstasks/dnszone_fitask.go
  upup/pkg/fi/cloudup/awstasks/ebsvolume_fitask.go
  upup/pkg/fi/cloudup/awstasks/elasticip_fitask.go
  upup/pkg/fi/cloudup/awstasks/iaminstanceprofile_fitask.go
  upup/pkg/fi/cloudup/awstasks/iaminstanceprofilerole_fitask.go
  upup/pkg/fi/cloudup/awstasks/iamrole_fitask.go
  upup/pkg/fi/cloudup/awstasks/iamrolepolicy_fitask.go
  upup/pkg/fi/cloudup/awstasks/internetgateway_fitask.go
  upup/pkg/fi/cloudup/awstasks/launchconfiguration_fitask.go
  upup/pkg/fi/cloudup/awstasks/loadbalancer_fitask.go
  upup/pkg/fi/cloudup/awstasks/loadbalancerattachment_fitask.go
  upup/pkg/fi/cloudup/awstasks/natgateway_fitask.go
  upup/pkg/fi/cloudup/awstasks/route_fitask.go
  upup/pkg/fi/cloudup/awstasks/routetable_fitask.go
  upup/pkg/fi/cloudup/awstasks/routetableassociation_fitask.go
  upup/pkg/fi/cloudup/awstasks/securitygroup_fitask.go
  upup/pkg/fi/cloudup/awstasks/securitygrouprule_fitask.go
  upup/pkg/fi/cloudup/awstasks/sshkey_fitask.go
  upup/pkg/fi/cloudup/awstasks/subnet_fitask.go
  upup/pkg/fi/cloudup/awstasks/vpc_fitask.go
  upup/pkg/fi/cloudup/awstasks/vpcdhcpoptionsassociation_fitask.go
  upup/pkg/fi/cloudup/dotasks/droplet_fitask.go
  upup/pkg/fi/cloudup/dotasks/volume_fitask.go
  upup/pkg/fi/cloudup/gcetasks/address_fitask.go
  upup/pkg/fi/cloudup/gcetasks/disk_fitask.go
  upup/pkg/fi/cloudup/gcetasks/firewallrule_fitask.go
  upup/pkg/fi/cloudup/gcetasks/forwardingrule_fitask.go
  upup/pkg/fi/cloudup/gcetasks/instance_fitask.go
  upup/pkg/fi/cloudup/gcetasks/instancegroupmanager_fitask.go
  upup/pkg/fi/cloudup/gcetasks/instancetemplate_fitask.go
  upup/pkg/fi/cloudup/gcetasks/network_fitask.go
  upup/pkg/fi/cloudup/gcetasks/storagebucketacl_fitask.go
  upup/pkg/fi/cloudup/gcetasks/storagebucketiam_fitask.go
  upup/pkg/fi/cloudup/gcetasks/storageobjectacl_fitask.go
  upup/pkg/fi/cloudup/gcetasks/subnet_fitask.go
  upup/pkg/fi/cloudup/gcetasks/targetpool_fitask.go
  upup/pkg/fi/cloudup/loader.go
  upup/pkg/fi/cloudup/openstacktasks/securitygroup_fitask.go
  upup/pkg/fi/cloudup/openstacktasks/securitygrouprule.go
  upup/pkg/fi/cloudup/openstacktasks/volume_fitask.go
  upup/pkg/fi/fitasks/keypair_fitask.go
  upup/pkg/fi/fitasks/managedfile_fitask.go
  upup/pkg/fi/fitasks/mirrorkeystore_fitask.go
  upup/pkg/fi/fitasks/mirrorsecrets_fitask.go
  upup/pkg/fi/fitasks/secret_fitask.go
  upup/pkg/fi/lifecycle.go
  upup/pkg/fi/task.go
  upup/tools/generators/fitask/generator.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4467 Updating variables to use Camel Case
  cmd/kops/completion.go
  cmd/kops/create.go
  cmd/kops/create_cluster.go
  cmd/kops/create_ig.go
  cmd/kops/create_secret.go
  cmd/kops/create_secret_dockerconfig.go
  cmd/kops/create_secret_encryptionconfig.go
  cmd/kops/create_secret_sshpublickey.go
  cmd/kops/delete.go
  cmd/kops/delete_cluster.go
  cmd/kops/delete_instancegroup.go
  cmd/kops/delete_secret.go
  cmd/kops/describe.go
  cmd/kops/describe_secrets.go
  cmd/kops/edit.go
  cmd/kops/edit_cluster.go
  cmd/kops/edit_instancegroup.go
  cmd/kops/export.go
  cmd/kops/export_kubecfg.go
  cmd/kops/get.go
  cmd/kops/get_cluster.go
  cmd/kops/get_instancegroups.go
  cmd/kops/get_secrets.go
  cmd/kops/import.go
  cmd/kops/import_cluster.go
  cmd/kops/rollingupdate.go
  cmd/kops/rollingupdatecluster.go
  cmd/kops/root.go
  cmd/kops/toolbox.go
  cmd/kops/toolbox_bundle.go
  cmd/kops/toolbox_convert_imported.go
  cmd/kops/toolbox_dump.go
  cmd/kops/update.go
  cmd/kops/update_cluster.go
  cmd/kops/upgrade.go
  cmd/kops/upgrade_cluster.go
  cmd/kops/validate.go
  cmd/kops/validate_cluster.go
  cmd/kops/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4468 Updating missed BUILD files for gazelle
  upup/pkg/fi/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4469 Support updating autoscaling metrics
  pkg/model/awsmodel/autoscalinggroup.go
  tests/integration/update_cluster/additional_user-data/cloudformation.json
  tests/integration/update_cluster/complex/kubernetes.tf
  tests/integration/update_cluster/ha/kubernetes.tf
  tests/integration/update_cluster/lifecycle_phases/cluster-kubernetes.tf
  tests/integration/update_cluster/minimal-141/kubernetes.tf
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json
  tests/integration/update_cluster/minimal/kubernetes.tf
  tests/integration/update_cluster/privatecalico/kubernetes.tf
  tests/integration/update_cluster/privatecanal/kubernetes.tf
  tests/integration/update_cluster/privatedns1/kubernetes.tf
  tests/integration/update_cluster/privatedns2/kubernetes.tf
  tests/integration/update_cluster/privateflannel/kubernetes.tf
  tests/integration/update_cluster/privatekopeio/kubernetes.tf
  tests/integration/update_cluster/privateweave/kubernetes.tf
  tests/integration/update_cluster/shared_subnet/kubernetes.tf
  tests/integration/update_cluster/shared_vpc/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4137 Convert registry to k8s.gcr.io
  WORKSPACE
  addons/cluster-autoscaler/README.md
  addons/ingress-nginx/README.md
  addons/ingress-nginx/v1.4.0.yaml
  addons/ingress-nginx/v1.6.0-gce.yaml
  addons/ingress-nginx/v1.6.0.yaml
  addons/kube-state-metrics/v1.0.1.yaml
  addons/kube-state-metrics/v1.1.0-rc.0.yaml
  addons/kube-state-metrics/v1.1.0.yaml
  addons/kubernetes-dashboard/v1.1.0.yaml
  addons/kubernetes-dashboard/v1.4.0.yaml
  addons/kubernetes-dashboard/v1.5.0.yaml
  addons/kubernetes-dashboard/v1.6.0.yaml
  addons/kubernetes-dashboard/v1.6.1.yaml
  addons/kubernetes-dashboard/v1.6.3.yaml
  addons/kubernetes-dashboard/v1.7.0.yaml
  addons/kubernetes-dashboard/v1.7.1.yaml
  addons/kubernetes-dashboard/v1.8.0.yaml
  addons/kubernetes-dashboard/v1.8.1.yaml
  addons/logging-elasticsearch/v1.5.0.yaml
  addons/logging-elasticsearch/v1.6.0.yaml
  addons/monitoring-standalone/v1.1.0.yaml
  addons/monitoring-standalone/v1.2.0.yaml
  addons/monitoring-standalone/v1.3.0.yaml
  addons/monitoring-standalone/v1.6.0.yaml
  addons/monitoring-standalone/v1.7.0.yaml
  docs/advisories/cve_2017_14491.md
  images/dns-controller-builder/Dockerfile
  images/dns-controller/Dockerfile
  images/kops-server/Dockerfile
  images/protokube-builder/Dockerfile
  images/protokube/Dockerfile
  images/utils-builder/Dockerfile
  nodeup/pkg/model/protokube.go
  pkg/assets/builder.go
  pkg/model/components/context.go
  pkg/model/components/etcd.go
  pkg/model/components/kubelet.go
  pkg/openapi/openapi_generated.go
  pkg/validation/validate_cluster_test.go
  protokube/cmd/protokube/main.go
  protokube/tests/integration/build_etcd_manifest/main/etcd_env_vars.yaml
  protokube/tests/integration/build_etcd_manifest/main/non_tls.yaml
  protokube/tests/integration/build_etcd_manifest/main/tls.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  upup/models/cloudup/resources/addons/core.addons.k8s.io/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/pre-k8s-1.6.yaml.template
  upup/pkg/fi/assettasks/docker_api.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4475 Updating kops version when using bazel
  Makefile
  tools/get_workspace_status.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4473 Update apimachinery & ensure we always run goimports
  Makefile
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/client/clientset_generated/clientset/scheme/register.go
  pkg/client/clientset_generated/internalclientset/scheme/register.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4478 Update kube-dns to 1.14.8
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/S

#4479 kube-dns: turn off negcache
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/XS

#4465 Initial support for standalone etcd-manager backups
  nodeup/pkg/model/protokube.go
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/components/etcd.go
  pkg/model/iam/BUILD.bazel
  pkg/model/iam/iam_builder.go
  protokube/cmd/protokube/main.go
  protokube/pkg/etcd/cluster_spec.go
  protokube/pkg/protokube/etcd_cluster.go
  protokube/pkg/protokube/etcd_manifest.go
  protokube/pkg/protokube/kube_boot.go
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/L

#3592 Require kops 1.7.1 (with the CVE fix), recommend kops 1.8.1
  channels/alpha
  pkg/apis/kops/channel.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/S

#3561 Build docker images through bazel
  images/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/M

#4485 Update ingress versions and fix to quay registry
  addons/ingress-nginx/v1.6.0-gce.yaml
  addons/ingress-nginx/v1.6.0.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4481 Update AWS Logo In Docs
  docs/img/k8s-aws.png
Labels: approved, area/documentation, cncf-cla: yes, lgtm, retest-not-required-docs-only, size/XS

#4500 Change FeatureGates to omitempty under KubeProxyConfig
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4502 Fix -ldflags incompatibility in go1.10
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#4489 Adding additional tags and shared to various AWS components
  pkg/model/network.go
  tests/integration/update_cluster/additional_user-data/cloudformation.json
  tests/integration/update_cluster/complex/kubernetes.tf
  tests/integration/update_cluster/ha/kubernetes.tf
  tests/integration/update_cluster/lifecycle_phases/network-kubernetes.tf
  tests/integration/update_cluster/minimal-141/kubernetes.tf
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json
  tests/integration/update_cluster/minimal/kubernetes.tf
  tests/integration/update_cluster/privatecalico/kubernetes.tf
  tests/integration/update_cluster/privatecanal/kubernetes.tf
  tests/integration/update_cluster/privatedns1/kubernetes.tf
  tests/integration/update_cluster/privatedns2/kubernetes.tf
  tests/integration/update_cluster/privateflannel/kubernetes.tf
  tests/integration/update_cluster/privatekopeio/kubernetes.tf
  tests/integration/update_cluster/privateweave/kubernetes.tf
  tests/integration/update_cluster/shared_vpc/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/dhcp_options.go
  upup/pkg/fi/cloudup/awstasks/internetgateway.go
  upup/pkg/fi/cloudup/awstasks/routetable.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4477 Bazel docker, cross builds and uploading to s3
  .gitignore
  Makefile
  WORKSPACE
  images/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/L

#4510 Build protokube tar in bazel
  Makefile
  images/BUILD.bazel
  tools/get_workspace_status.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#4512 Add cidr-allocator-type flag to kcm and ccm
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4515 Bazel follow up
  docs/development/bazel.md
  images/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/S

#4505 DockerConfig Order
  pkg/apis/kops/dockerconfig.go
  pkg/apis/kops/v1alpha1/dockerconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/dockerconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4381 Experimental kops set cluster command
  cmd/kops/BUILD.bazel
  cmd/kops/edit_cluster.go
  cmd/kops/export_kubecfg.go
  cmd/kops/replace.go
  cmd/kops/root.go
  cmd/kops/set.go
  cmd/kops/set_cluster.go
  cmd/kops/update_cluster.go
  cmd/kops/upgrade_cluster.go
  docs/cli/kops.md
  docs/cli/kops_set.md
  docs/cli/kops_set_cluster.md
  hack/.packages
  pkg/commands/BUILD.bazel
  pkg/commands/helpers_readwrite.go
  pkg/commands/set_cluster.go
  pkg/commands/set_cluster_test.go
  pkg/commands/status_discovery.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4497 docker: Adds hosts configuration option
  pkg/apis/kops/dockerconfig.go
  pkg/apis/kops/v1alpha1/dockerconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/dockerconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4522 Fixing verify bazel
  hack/update-bazel.sh
  hack/verify-bazel.sh
  pkg/commands/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4520 Fix snake case
  cmd/kops/set.go
  cmd/kops/set_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4493 VFS: WriteFile takes an io.ReadSeeker
  cmd/kops/toolbox_bundle.go
  pkg/apis/kops/registry/statestore.go
  pkg/client/simple/vfsclientset/commonvfs.go
  pkg/model/components/image_test.go
  upup/models/vfs.go
  upup/pkg/fi/assettasks/copyfile.go
  upup/pkg/fi/fitasks/managedfile.go
  upup/pkg/fi/secrets/clientset_secretstore.go
  upup/pkg/fi/secrets/vfs_secretstore.go
  upup/pkg/fi/vfs_castore.go
  util/pkg/vfs/fs.go
  util/pkg/vfs/gsfs.go
  util/pkg/vfs/k8sfs.go
  util/pkg/vfs/memfs.go
  util/pkg/vfs/s3fs.go
  util/pkg/vfs/sshfs.go
  util/pkg/vfs/swiftfs.go
  util/pkg/vfs/vfs.go
  util/pkg/vfs/vfssync.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/L

#4530 Update rules go
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4525 Add node monitor flags
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4519 Clarify few things in Running an existing VPC
  docs/run_in_existing_vpc.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#4443 Set the default docker for kubernetes 1.9 to 17.03.2
  pkg/model/components/docker.go
Labels: blocks-next, cncf-cla: yes, size/XS

#4302 Add option for using existing EIP's
  docs/cluster_spec.md
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/model/network.go
  pkg/resources/aws.go
  upup/pkg/fi/cloudup/awstasks/elastic_ip.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4010 Etcd TLS Peer & CLient Auth
  nodeup/pkg/model/context.go
  nodeup/pkg/model/protokube.go
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/model/pki.go
  protokube/cmd/protokube/main.go
  protokube/pkg/protokube/etcd_cluster.go
  protokube/pkg/protokube/etcd_manifest.go
  protokube/pkg/protokube/kube_boot.go
  upup/pkg/fi/fitasks/keypair.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4535 Fix suspicious space in struct tag value
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4452 Add support for bastion aws user-data
  cmd/kops/integration_test.go
  pkg/apis/kops/instancegroup.go
  pkg/model/bootstrapscript.go
  pkg/model/resources/nodeup.go
  tests/integration/update_cluster/bastionadditional_user-data/data/aws_launch_configuration_bastion.bastionuserdata.example.com_user_data
  tests/integration/update_cluster/bastionadditional_user-data/id_rsa.pub
  tests/integration/update_cluster/bastionadditional_user-data/in-v1alpha2.yaml
  tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4528 Moving from one IG w multiple AZs to one IG per AZ
  docs/instance_groups.md
Labels: approved, cncf-cla: yes, lgtm, retest-not-required-docs-only, size/S

#4538 Make addon specification into an object
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  tests/integration/conversion/minimal/v1alpha0.yaml
  tests/integration/conversion/minimal/v1alpha1.yaml
  tests/integration/conversion/minimal/v1alpha2.yaml
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/cluster.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/cluster.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4539 Fixing integration tests
  tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
Labels: approved, cncf-cla: yes, lgtm, size/S

#4354 Increase key size in GeneratePrivateKey() to 3072
  pkg/pki/privatekey.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/S

#4476 Kube-proxy API to accept cpu: limit, memory: request and limit
  nodeup/pkg/model/kube_proxy.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/model/bootstrapscript_test.go
  pkg/model/tests/data/bootstrapscript_0.txt
  pkg/model/tests/data/bootstrapscript_1.txt
  pkg/model/tests/data/bootstrapscript_2.txt
  pkg/model/tests/data/bootstrapscript_3.txt
  pkg/model/tests/data/bootstrapscript_4.txt
  pkg/model/tests/data/bootstrapscript_5.txt
Labels: approved, cncf-cla: yes, lgtm, size/M

#4529 Expose Felix metrics
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/M
