Repository kubernetes/kops, pull requests merged in 2018-06, with the labels that each got.

#5208 Bump Cilium version to released
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5237 Typo fix: are be->are
  nodeup/pkg/model/context.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5230 Add proper autoloading for kops autocomplete
  cmd/kops/completion.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5235 Fix typo: adddresses -> addresses
  protokube/cmd/protokube/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5234 Replace deprecated flags: address -> insecure-bind-address
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/model/components/apiserver.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5231 Add AuthenticationTokenWebhook flag
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5197 Setup heptio authenticator
  docs/authentication.md
  nodeup/pkg/model/kube_apiserver.go
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/pki.go
  upup/models/cloudup/resources/addons/authentication.hept.io/k8s-1.10.yaml
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5241 File Permissions Private Key
  nodeup/pkg/model/kube_apiserver.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5244 Correct PSP RoleBinding with namespace for kube-system
  upup/models/cloudup/resources/addons/podsecuritypolicy.addons.k8s.io/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/podsecuritypolicy.addons.k8s.io/k8s-1.9.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5095 Upgrade to flannel v0.10.0 and explicitly specify amd64 arch
  upup/models/cloudup/resources/addons/networking.flannel/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.flannel/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5248 Admission Controller Fix
  nodeup/pkg/model/kube_apiserver.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5249 Use HomeDir from client-go to get home directory
  cmd/kops/BUILD.bazel
  cmd/kops/toolbox_bundle.go
  upup/pkg/fi/utils/BUILD.bazel
  upup/pkg/fi/utils/sanitize.go
  util/pkg/vfs/BUILD.bazel
  util/pkg/vfs/swiftfs.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5056 Add public ssh keys for GCE
  cmd/kops/integration_test.go
  pkg/model/gcemodel/autoscalinggroup.go
  tests/integration/update_cluster/ha_gce/kubernetes.tf
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4524 Release windows build in alpha
  .shipbot.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5259 docker: Set TasksMax to infinity
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5261 Update aws-sdk-go to v1.13.60
  Gopkg.lock
  Gopkg.toml
  cloudmock/aws/mockec2/api.go
  cloudmock/aws/mockiam/api.go
  vendor/github.com/aws/aws-sdk-go/aws/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/aws/client/client.go
  vendor/github.com/aws/aws-sdk-go/aws/client/default_retryer.go
  vendor/github.com/aws/aws-sdk-go/aws/config.go
  vendor/github.com/aws/aws-sdk-go/aws/corehandlers/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go
  vendor/github.com/aws/aws-sdk-go/aws/corehandlers/user_agent.go
  vendor/github.com/aws/aws-sdk-go/aws/defaults/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/service.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/decode.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/endpoints.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/v3model.go
  vendor/github.com/aws/aws-sdk-go/aws/request/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/aws/request/offset_reader.go
  vendor/github.com/aws/aws-sdk-go/aws/request/request.go
  vendor/github.com/aws/aws-sdk-go/aws/request/request_pagination.go
  vendor/github.com/aws/aws-sdk-go/aws/session/session.go
  vendor/github.com/aws/aws-sdk-go/aws/signer/v4/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go
  vendor/github.com/aws/aws-sdk-go/aws/types.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/internal/sdkio/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/internal/sdkio/io_go1.6.go
  vendor/github.com/aws/aws-sdk-go/internal/sdkio/io_go1.7.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/ec2query/build.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/query/build.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/rest/build.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/rest/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/service/autoscaling/api.go
  vendor/github.com/aws/aws-sdk-go/service/autoscaling/doc.go
  vendor/github.com/aws/aws-sdk-go/service/autoscaling/errors.go
  vendor/github.com/aws/aws-sdk-go/service/cloudformation/api.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/ec2iface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/ecr/api.go
  vendor/github.com/aws/aws-sdk-go/service/ecr/doc.go
  vendor/github.com/aws/aws-sdk-go/service/ecr/errors.go
  vendor/github.com/aws/aws-sdk-go/service/elb/api.go
  vendor/github.com/aws/aws-sdk-go/service/elbv2/api.go
  vendor/github.com/aws/aws-sdk-go/service/elbv2/errors.go
  vendor/github.com/aws/aws-sdk-go/service/iam/api.go
  vendor/github.com/aws/aws-sdk-go/service/iam/iamiface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/kms/api.go
  vendor/github.com/aws/aws-sdk-go/service/kms/errors.go
  vendor/github.com/aws/aws-sdk-go/service/route53/api.go
  vendor/github.com/aws/aws-sdk-go/service/s3/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/service/s3/api.go
  vendor/github.com/aws/aws-sdk-go/service/s3/body_hash.go
  vendor/github.com/aws/aws-sdk-go/service/s3/content_md5.go
  vendor/github.com/aws/aws-sdk-go/service/s3/customizations.go
  vendor/github.com/aws/aws-sdk-go/service/s3/statusok_error.go
  vendor/github.com/aws/aws-sdk-go/service/sts/api.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#5262 Put verify-apimachinery into ci makefile target
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5255 Perf fix for makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5257 Use STABLE_ prefixes for bazel workspace vars
  cmd/kops/BUILD.bazel
  images/BUILD.bazel
  tools/get_workspace_status.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5263 bazel: add notes that tasks do not work
  hack/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5264 Clean up variable naming in integration test
  cmd/kops/integration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5265 Allow integration tests to update expected TF output
  cmd/kops/integration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5272 Validate FileAssets
  pkg/apis/kops/validation/instancegroup.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5271 Validate InstanceGroup Hooks
  pkg/apis/kops/validation/instancegroup.go
  pkg/apis/kops/validation/validation.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5274 Update bazel gazelle
  Gopkg.lock
  Gopkg.toml
  WORKSPACE
  vendor/github.com/bazelbuild/bazel-gazelle/cmd/gazelle/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/cmd/gazelle/fix-update.go
  vendor/github.com/bazelbuild/bazel-gazelle/internal/generator/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/internal/generator/construct.go
  vendor/github.com/bazelbuild/bazel-gazelle/internal/generator/doc.go
  vendor/github.com/bazelbuild/bazel-gazelle/internal/generator/generator.go
  vendor/github.com/bazelbuild/bazel-gazelle/internal/generator/sort_labels.go
  vendor/github.com/bazelbuild/bazel-gazelle/internal/merger/fix.go
  vendor/github.com/bazelbuild/bazel-gazelle/internal/merger/merger.go
  vendor/github.com/bazelbuild/bazel-gazelle/internal/repos/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/internal/repos/repo.go
  vendor/github.com/bazelbuild/bazel-gazelle/internal/resolve/resolve.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/L

#5267 Fix go version hack to be more generic.
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5268 CoreDNS pull image from gcr.io
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5275 Clarify the usage of the --state flag.
  cmd/kops/root.go
  docs/cli/kops.md
  docs/cli/kops_completion.md
  docs/cli/kops_create.md
  docs/cli/kops_create_cluster.md
  docs/cli/kops_create_instancegroup.md
  docs/cli/kops_create_secret.md
  docs/cli/kops_create_secret_dockerconfig.md
  docs/cli/kops_create_secret_encryptionconfig.md
  docs/cli/kops_create_secret_keypair.md
  docs/cli/kops_create_secret_keypair_ca.md
  docs/cli/kops_create_secret_sshpublickey.md
  docs/cli/kops_delete.md
  docs/cli/kops_delete_cluster.md
  docs/cli/kops_delete_instancegroup.md
  docs/cli/kops_delete_secret.md
  docs/cli/kops_describe.md
  docs/cli/kops_describe_secrets.md
  docs/cli/kops_edit.md
  docs/cli/kops_edit_cluster.md
  docs/cli/kops_edit_instancegroup.md
  docs/cli/kops_export.md
  docs/cli/kops_export_kubecfg.md
  docs/cli/kops_get.md
  docs/cli/kops_get_clusters.md
  docs/cli/kops_get_instancegroups.md
  docs/cli/kops_get_secrets.md
  docs/cli/kops_import.md
  docs/cli/kops_import_cluster.md
  docs/cli/kops_replace.md
  docs/cli/kops_rolling-update.md
  docs/cli/kops_rolling-update_cluster.md
  docs/cli/kops_set.md
  docs/cli/kops_set_cluster.md
  docs/cli/kops_toolbox.md
  docs/cli/kops_toolbox_bundle.md
  docs/cli/kops_toolbox_convert-imported.md
  docs/cli/kops_toolbox_dump.md
  docs/cli/kops_toolbox_template.md
  docs/cli/kops_update.md
  docs/cli/kops_update_cluster.md
  docs/cli/kops_upgrade.md
  docs/cli/kops_upgrade_cluster.md
  docs/cli/kops_validate.md
  docs/cli/kops_validate_cluster.md
  docs/cli/kops_version.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#5270 Implement AdditionalCIDR configuration.
  cmd/kops/integration_test.go
  pkg/model/network.go
  tests/integration/update_cluster/additional_cidr/cloudformation.json
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_cidr/id_rsa.pub
  tests/integration/update_cluster/additional_cidr/in-v1alpha2.yaml
  upup/pkg/fi/cloudup/awstasks/BUILD.bazel
  upup/pkg/fi/cloudup/awstasks/vpc.go
  upup/pkg/fi/cloudup/awstasks/vpccidrblock.go
  upup/pkg/fi/cloudup/awstasks/vpccidrblock_fitask.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#5276 Update heptio authenticator to 0.3.0
  upup/models/cloudup/resources/addons/authentication.hept.io/k8s-1.10.yaml
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5137 Update elasticsearch logging to 5.6.4
  addons/logging-elasticsearch/addon.yaml
  addons/logging-elasticsearch/v1.7.0.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5278 Fix: Update heptio authenticator to 0.3.0 #5276
  upup/models/cloudup/resources/addons/authentication.hept.io/k8s-1.10.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5279 Create a SECURITY_CONTACTS file. #5205
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#5277 Verify Spelling
  Makefile
  cmd/kops/integration_test.go
  docs/apireference/build/README.md
  docs/examples/coreos-kops-tests-multimaster.md
  docs/examples/kops-test-route53-subdomain.md
  docs/examples/kops-tests-private-net-bastion-host.md
  docs/releases/1.6.2.md
  docs/releases/1.7-NOTES.md
  docs/releases/1.8-NOTES.md
  docs/releases/1.9-NOTES.md
  nodeup/pkg/model/context.go
  nodeup/pkg/model/protokube.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/model/components/apiserver.go
  pkg/openapi/openapi_generated.go
  protokube/README.md
  upup/pkg/fi/nodeup/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#5282 Fix some typos
  cmd/kops/integration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5284 Update kops_edit_instancegroup.go and kops_edit_instancegroup.md
  cmd/kops/edit_instancegroup.go
  docs/cli/kops_edit_instancegroup.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5285 Override hostname with 'aws' only if hostname override is not specified.
  pkg/model/components/kubeproxy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5286 Enable override bind address for kube-proxy.
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5287 Add support for M5D instance family on AWS
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5258 Support overlay2 in docker
  docs/cli/kops_create_cluster.md
  docs/cli/kops_update_cluster.md
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/docker_test.go
  pkg/model/components/docker.go
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  upup/models/config/components/docker/_e2e_storage_test_environment/e2e.options
  upup/models/config/components/docker/_networking_cni/cni.options
  upup/models/config/components/docker/_networking_kubenet/kubenet.options
  upup/models/config/components/docker/docker.options
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/populate_cluster_spec.go
  upup/pkg/fi/cloudup/spec_builder.go
  upup/pkg/fi/cloudup/tagbuilder.go
  upup/pkg/fi/cloudup/tagbuilder_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5294 Destinctive names for ClusterRoleBindings in prometheus-operator addon
  addons/prometheus-operator/v0.19.0.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5297 Revert "digitalocean: don't set --cloud-provider=external on control plane starting v1.10"
  pkg/apis/kops/validation/legacy.go
  pkg/model/components/apiserver.go
  pkg/model/components/kubecontrollermanager.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/XS

#4985 Fix typo
  docs/apireference/build/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5139 Fix issue where we assumed that private zone were in order
  cmd/kops/lifecycle_integration_test.go
  pkg/model/network.go
  pkg/testutils/integrationtestharness.go
  tests/integration/update_cluster/private-shared-subnet/in-v1alpha2.yaml
  tests/integration/update_cluster/privatekopeio/in-v1alpha2.yaml
  tests/integration/update_cluster/privatekopeio/kubernetes.tf
Labels: approved, cncf-cla: yes, lgtm, size/L

#4171 Add support for external IAM Instance Profiles
  cmd/kops/integration_test.go
  docs/iam_roles.md
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/validation/BUILD.bazel
  pkg/apis/kops/validation/instancegroup.go
  pkg/apis/kops/validation/instancegroup_test.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/awsmodel/autoscalinggroup.go
  pkg/model/iam.go
  pkg/model/names.go
  tests/integration/update_cluster/existing_iam/id_rsa.pub
  tests/integration/update_cluster/existing_iam/in-v1alpha2.yaml
  tests/integration/update_cluster/existing_iam/kubernetes.tf
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/data/aws_key_pair_kubernetes.k8s-iam.us-west-2.td.priv-ad4e821eea9c965ed12a95b3bde99ed3_public_key
  tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_master-us-west-2a.masters.k8s-iam.us-west-2.td.priv_user_data
  tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_nodes.k8s-iam.us-west-2.td.priv_user_data
  tests/integration/update_cluster/existing_iam_cloudformation/id_rsa.pub
  tests/integration/update_cluster/existing_iam_cloudformation/in-v1alpha2.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/iaminstanceprofile.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/XXL

#5194 Feature/s3 bucket encryption - Implements PR #4235
  docs/aws.md
  util/pkg/vfs/s3context.go
  util/pkg/vfs/s3fs.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4724 Customize KubeDNS
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/validation/legacy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/components/kubedns.go
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/template_functions.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5207 implement LoadBalancer task for ALICloud
  Gopkg.lock
  pkg/model/alimodel/BUILD.bazel
  pkg/model/alimodel/api_loadbalancer.go
  pkg/model/alimodel/context.go
  upup/pkg/fi/cloudup/alitasks/BUILD.bazel
  upup/pkg/fi/cloudup/alitasks/loadbalancer.go
  upup/pkg/fi/cloudup/alitasks/loadbalancer_fitask.go
  upup/pkg/fi/cloudup/alitasks/loadbalancerlistener.go
  upup/pkg/fi/cloudup/alitasks/loadbalancerlistener_fitask.go
  upup/pkg/fi/cloudup/alitasks/loadbalancerwhitelist.go
  upup/pkg/fi/cloudup/alitasks/loadbalancerwhitelist_fitask.go
  upup/pkg/fi/cloudup/aliup/BUILD.bazel
  upup/pkg/fi/cloudup/aliup/ali_cloud.go
  vendor/github.com/denverdino/aliyungo/slb/BUILD.bazel
  vendor/github.com/denverdino/aliyungo/slb/certificates.go
  vendor/github.com/denverdino/aliyungo/slb/client.go
  vendor/github.com/denverdino/aliyungo/slb/listeners.go
  vendor/github.com/denverdino/aliyungo/slb/loadbalancers.go
  vendor/github.com/denverdino/aliyungo/slb/regions.go
  vendor/github.com/denverdino/aliyungo/slb/rules.go
  vendor/github.com/denverdino/aliyungo/slb/servers.go
  vendor/github.com/denverdino/aliyungo/slb/tags.go
  vendor/github.com/denverdino/aliyungo/slb/vserver_group.go
Labels: approved, area/networking, cncf-cla: yes, lgtm, size/XXL

#5250 Admission Controller Validation
  pkg/apis/kops/validation/legacy.go
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/S

#5119 Amazon VPC CNI: Upgrade to v1.0 and Allow Custom Images
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5254 ListKeypairs: don't print 'keyset.yaml' as the key id
  upup/pkg/fi/vfs_castore.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5301 Fix alitasks loadbalancer typo causing test failures
  upup/pkg/fi/cloudup/alitasks/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5146 fix broken link to example policy file in the cluster_spec docs
  docs/cluster_spec.md
Labels: approved, area/documentation, cncf-cla: yes, size/XS

#5030 Export outputs to aid with VPC peering in Terraform
  tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
  tests/integration/update_cluster/complex/kubernetes.tf
  tests/integration/update_cluster/ha/kubernetes.tf
  tests/integration/update_cluster/lifecycle_phases/network-kubernetes.tf
  tests/integration/update_cluster/minimal-141/kubernetes.tf
  tests/integration/update_cluster/minimal/kubernetes.tf
  tests/integration/update_cluster/private-shared-subnet/kubernetes.tf
  tests/integration/update_cluster/privatecalico/kubernetes.tf
  tests/integration/update_cluster/privatecanal/kubernetes.tf
  tests/integration/update_cluster/privatedns1/kubernetes.tf
  tests/integration/update_cluster/privatedns2/kubernetes.tf
  tests/integration/update_cluster/privateflannel/kubernetes.tf
  tests/integration/update_cluster/privatekopeio/kubernetes.tf
  tests/integration/update_cluster/privateweave/kubernetes.tf
  tests/integration/update_cluster/shared_subnet/kubernetes.tf
  tests/integration/update_cluster/shared_vpc/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/routetable.go
  upup/pkg/fi/cloudup/awstasks/subnet.go
  upup/pkg/fi/cloudup/awstasks/vpc.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4977 implement router interface task for OpenStack platform
  pkg/model/openstackmodel/context.go
  pkg/model/openstackmodel/network.go
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel
  upup/pkg/fi/cloudup/openstacktasks/routerinterface.go
  upup/pkg/fi/cloudup/openstacktasks/routerinterface_fitask.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/BUILD.bazel
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/urls.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#5303 Update expected TF output for latest master
  tests/integration/update_cluster/existing_iam/kubernetes.tf
  tests/integration/update_cluster/privatekopeio/kubernetes.tf
Labels: approved, lgtm, size/M

#5110 implement keypair task for OpenStack platform
  Gopkg.lock
  pkg/model/openstackmodel/BUILD.bazel
  pkg/model/openstackmodel/sshkey.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel
  upup/pkg/fi/cloudup/openstacktasks/sshkey.go
  upup/pkg/fi/cloudup/openstacktasks/sshkey_fitask.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs/BUILD.bazel
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/BUILD.bazel
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/images/BUILD.bazel
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/images/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/images/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/images/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/images/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/BUILD.bazel
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/util.go
Labels: approved, cncf-cla: yes, size/XXL

#5304 Fixup bazel
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4737 Add feature with s3 state store from configfile
  cmd/kops/root.go
  cmd/kops/util/factory.go
  docs/aws.md
  docs/cli/kops.md
  docs/cli/kops_completion.md
  docs/cli/kops_create.md
  docs/cli/kops_create_cluster.md
  docs/cli/kops_create_instancegroup.md
  docs/cli/kops_create_secret.md
  docs/cli/kops_create_secret_dockerconfig.md
  docs/cli/kops_create_secret_encryptionconfig.md
  docs/cli/kops_create_secret_keypair.md
  docs/cli/kops_create_secret_keypair_ca.md
  docs/cli/kops_create_secret_sshpublickey.md
  docs/cli/kops_delete.md
  docs/cli/kops_delete_cluster.md
  docs/cli/kops_delete_instancegroup.md
  docs/cli/kops_delete_secret.md
  docs/cli/kops_describe.md
  docs/cli/kops_describe_secrets.md
  docs/cli/kops_edit.md
  docs/cli/kops_edit_cluster.md
  docs/cli/kops_edit_instancegroup.md
  docs/cli/kops_export.md
  docs/cli/kops_export_kubecfg.md
  docs/cli/kops_get.md
  docs/cli/kops_get_clusters.md
  docs/cli/kops_get_instancegroups.md
  docs/cli/kops_get_secrets.md
  docs/cli/kops_import.md
  docs/cli/kops_import_cluster.md
  docs/cli/kops_replace.md
  docs/cli/kops_rolling-update.md
  docs/cli/kops_rolling-update_cluster.md
  docs/cli/kops_set.md
  docs/cli/kops_set_cluster.md
  docs/cli/kops_toolbox.md
  docs/cli/kops_toolbox_bundle.md
  docs/cli/kops_toolbox_convert-imported.md
  docs/cli/kops_toolbox_dump.md
  docs/cli/kops_toolbox_template.md
  docs/cli/kops_update.md
  docs/cli/kops_update_cluster.md
  docs/cli/kops_upgrade.md
  docs/cli/kops_upgrade_cluster.md
  docs/cli/kops_validate.md
  docs/cli/kops_validate_cluster.md
  docs/cli/kops_version.md
  docs/state.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#5306 Fix typo: HONE -> HOME
  docs/state.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5309 Node Bootstrap Fix Ups
  nodeup/pkg/model/context.go
  nodeup/pkg/model/kubelet.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5313 Fix Admission Controller Validation
  pkg/apis/kops/validation/legacy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5312 Added comment for 404 on healthcheck for non-standard vpc-cidr
  addons/kube-ingress-aws-controller/README.md
  addons/kube-ingress-aws-controller/v1.0.0.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5315 Correct deployment yaml of CoreDNS
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5307 Avoid changing IAM policy for users
  pkg/model/iam/iam_builder.go
  pkg/model/iam/tests/iam_builder_node_strict.json
  pkg/model/iam/tests/iam_builder_node_strict_ecr.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#5311 File Path Fixes
  nodeup/pkg/model/context.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5322 Communicate before long waits
  pkg/instancegroups/instancegroups.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5325 kops set cluster: honor --name flag
  cmd/kops/set_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5323 Don't always print state store path
  cmd/kops/util/factory.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5334 protokube: only specify etcd flags when managing etcd
  nodeup/pkg/model/context.go
  nodeup/pkg/model/protokube.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5324 Use less viper discovery
  cmd/kops/root.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5330 GCE: Set network tier, to avoid spurious changes
  upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5333 Set log-verbosity for etcd-manager
  pkg/model/components/etcdmanager/model.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5320 More configuration options for cilium
  pkg/apis/kops/cluster.go
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
  upup/pkg/fi/cloudup/BUILD.bazel
  upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/cluster.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#5332 gossip: create zone in protokube
  protokube/cmd/protokube/main.go
  protokube/pkg/gossip/dns/dns.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5328 implement SecurityGroup task for ALICloud
  upup/pkg/fi/cloudup/alitasks/BUILD.bazel
  upup/pkg/fi/cloudup/alitasks/securitygroup.go
  upup/pkg/fi/cloudup/alitasks/securitygroup_fitask.go
  upup/pkg/fi/cloudup/alitasks/securitygrouprule.go
  upup/pkg/fi/cloudup/alitasks/securitygrouprule_fitask.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#5331 Add missing nodes/stats resource to the system:metrics-server Cluster…
  addons/metrics-server/v1.8.x.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5256 Don't autoload SSH key on GCE
  cmd/kops/create_cluster.go
  docs/cli/kops_create_cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#5344 Typo fix
  pkg/apis/kops/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5350 Code Clean
  nodeup/pkg/model/calico.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5343 add firewallModel for ALIcloud
  pkg/model/alimodel/BUILD.bazel
  pkg/model/alimodel/context.go
  pkg/model/alimodel/external_access.go
  pkg/model/alimodel/firewall.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5351 Removing Duplication
  nodeup/pkg/model/convenience.go
  nodeup/pkg/model/kube_apiserver.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5354 Git Ignore - Merge Conflict Files
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5335 etcd-manager: GCE support
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/model.go
  pkg/model/gcemodel/BUILD.bazel
  pkg/model/gcemodel/autoscalinggroup.go
  pkg/model/gcemodel/storageacl.go
  pkg/model/iam/iam_builder.go
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5245 AWS: Delete old LaunchConfigurations
  cloudmock/aws/mockautoscaling/launchconfigurations.go
  cmd/kops/integration_test.go
  cmd/kops/lifecycle_integration_test.go
  cmd/kops/update_cluster.go
  cmd/nodeup/main.go
  docs/releases/1.10-NOTES.md
  nodeup/pkg/bootstrap/install.go
  pkg/featureflag/featureflag.go
  tests/keypair_test.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/awstasks/BUILD.bazel
  upup/pkg/fi/cloudup/awstasks/elastic_ip_test.go
  upup/pkg/fi/cloudup/awstasks/internetgateway_test.go
  upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
  upup/pkg/fi/cloudup/awstasks/launchconfiguration_test.go
  upup/pkg/fi/cloudup/awstasks/securitygroup_test.go
  upup/pkg/fi/cloudup/awstasks/subnet_test.go
  upup/pkg/fi/cloudup/awstasks/vpc_test.go
  upup/pkg/fi/context.go
  upup/pkg/fi/executor.go
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5362 GCE: Handle storage flag on COS more carefully
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5359 Revert COS in stable/alpha channel
  channels/alpha
  channels/stable
  tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5353 Fix containerRegistry for Kubernetes < 1.10
  pkg/assets/builder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5356 add RAM model for ALIcloud
  pkg/model/alimodel/BUILD.bazel
  pkg/model/alimodel/context.go
  pkg/model/alimodel/ram.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5240 Add etcd TLS support for Cilium
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/etcd_tls.go
  pkg/model/iam/iam_builder.go
  pkg/model/pki.go
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5352 Nodeup clean
  nodeup/pkg/model/directories.go
  nodeup/pkg/model/file_assets.go
  nodeup/pkg/model/firewall.go
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_controller_manager.go
  nodeup/pkg/model/kube_proxy.go
  nodeup/pkg/model/kube_router.go
  nodeup/pkg/model/kube_scheduler.go
  nodeup/pkg/model/kubectl.go
  nodeup/pkg/model/logrotate.go
  nodeup/pkg/model/network.go
  nodeup/pkg/model/packages.go
  nodeup/pkg/model/protokube.go
  nodeup/pkg/model/secrets.go
  nodeup/pkg/model/sysctls.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5364 add ScalingGroup model for AliCloud
  pkg/model/alimodel/BUILD.bazel
  pkg/model/alimodel/context.go
  pkg/model/alimodel/scalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5348 Typo fix in documentation.md
  docs/development/documentation.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5367 Mark 1.10.0-alpha.1
  Makefile
  tools/get_workspace_status.sh
  version.go
Labels: approved, cncf-cla: yes, size/S

#5369 Add 1.10-alpha.1 to stable & alpha channels
  channels/alpha
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/S

#5366 Go versions: don't block on 1.8
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#5357 Docker Userspace Remapping Options
  pkg/apis/kops/dockerconfig.go
  pkg/apis/kops/v1alpha1/dockerconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/dockerconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5376 Switch bucket encryption policy warning to debug
  util/pkg/vfs/s3context.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5386 Update rolling update ig roles flag to be case insensitive
  cmd/kops/rollingupdatecluster.go
  docs/cli/kops_rolling-update_cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5374 add Volume model for aliCloud
  pkg/model/BUILD.bazel
  pkg/model/master_volumes.go
  upup/pkg/fi/cloudup/aliup/ali_cloud.go
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/M
