Repository kubernetes/kops, pull requests merged in 2018-12, with the labels that each got.

#6129 Spotinst: Bump controller image
  upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.8.0.yaml.template
  upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.9.0.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6139 Add cni to usage network option for kops create cluster
  cmd/kops/create_cluster.go
  docs/cli/kops_create_cluster.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6144 Workspace updates for bazel / fix tests
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#6146 Promote alpha channels to stable
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6152 Add GCE europe-north1-{a,b,c}
  upup/pkg/fi/cloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6147 Add self to security contacts
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6159 Automated cherry pick of #6156: Fix Calico upgrade job to use the correct version
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6156 Fix Calico upgrade job to use the correct version
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6143 Automated cherry pick of #6129: feat: bump controller version to 1.0.18
  upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.8.0.yaml.template
  upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.9.0.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6175 Fix for when node and master use the same SG.
  pkg/model/awsmodel/autoscalinggroup.go
  pkg/model/firewall.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6171 Add experimental and metrics flags for docker
  pkg/apis/kops/dockerconfig.go
  pkg/apis/kops/v1alpha1/dockerconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/dockerconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6176 Automated cherry pick of #6175: Fix for when node and master use the same SG.
  pkg/model/awsmodel/autoscalinggroup.go
  pkg/model/firewall.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6177 Add y flag for upgrade command for consistency
  cmd/kops/upgrade_cluster.go
  docs/cli/kops_upgrade_cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6170 Add-ons spec example is missing "manifest".
  docs/addons.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6179 ExperimentalAllowedUnsafeSysctls has moved to AllowedUnsafeSysctls in k8s 1.11
  nodeup/pkg/model/kubelet.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6185 Let a user specify the validation timeout when rotating a cluster.
  cmd/kops/rollingupdatecluster.go
  docs/cli/kops_rolling-update_cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6193 fix(docs): fix the compatibility matrics on hpa.md
  docs/horizontal_pod_autoscaling.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6196 bump prometheus-operator version and deploy file
  addons/prometheus-operator/README.md
  addons/prometheus-operator/addon.yaml
  addons/prometheus-operator/sync-repo.sh
  addons/prometheus-operator/v0.26.0.yaml
  docs/addons.md
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#6195 update heapster version and mark it retired
  addons/monitoring-standalone/README.md
  addons/monitoring-standalone/v1.11.0.yaml
  docs/addons.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#6202 Add Docker 18.06.1 for CentOS and RHEL 7
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6208 Print --name with `kops update cluster`
  cmd/kops/create_cluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6211 Add --post-drain-delay to rolling-update cluster command
  cmd/kops/rollingupdatecluster.go
  docs/cli/kops_rolling-update_cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6224 Adding kubernetes-dashboard v1.10.1 deployment to kops addons
  addons/kubernetes-dashboard/addon.yaml
  addons/kubernetes-dashboard/v1.10.1.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6231 Consider pending pods to be a validation failure
  cmd/kops/validate_cluster.go
  pkg/validation/validate_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6238 Document how to update an existing vendored dependency
  docs/development/vendoring.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#6239 Bump channels and bump alpha to latest
  channels/alpha
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6090 Automagically use curl instead of wget if that's what's available
  addons/cluster-autoscaler/cluster-autoscaler.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6243 cloudmock: replace unimplemented methods with interface embedding
  cloudmock/aws/mockautoscaling/BUILD.bazel
  cloudmock/aws/mockautoscaling/api.go
  cloudmock/aws/mockautoscaling/unimplemented.go
  cloudmock/aws/mockec2/BUILD.bazel
  cloudmock/aws/mockec2/unimplemented.go
  cloudmock/aws/mockiam/BUILD.bazel
  cloudmock/aws/mockiam/unimplemented.go
  cloudmock/aws/mockroute53/BUILD.bazel
  cloudmock/aws/mockroute53/api.go
  cloudmock/aws/mockroute53/unimplemented.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#6235 bazel: cleanup gobindata generation
  upup/models/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6245 Update apimachinery for k8s 1.12
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6249 Cherry pick of #6117 onto release-1.11
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6180 Don't panic when an etcd cluster is added
  pkg/apis/kops/validation/cluster.go
Labels: approved, cherry-pick, cncf-cla: yes, lgtm, size/XS

#6220 Automated cherry pick of #6144: Workspace updates for bazel
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#6252 Cherry pick of #6179 onto release-1.11
  nodeup/pkg/model/kubelet.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6251 Cherry pick of #6152 onto release-1.11
  upup/pkg/fi/cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6254 Automated cherry pick of #6253: Add p3dn.24xlarge
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6259 Rationalize deserialiation code
  cmd/kops/create.go
  cmd/kops/create_ig.go
  cmd/kops/delete.go
  cmd/kops/edit_cluster.go
  cmd/kops/edit_instancegroup.go
  cmd/kops/replace.go
  pkg/client/simple/vfsclientset/commonvfs.go
  pkg/kopscodecs/codecs.go
  pkg/testutils/modelharness.go
  tests/integration/conversion/BUILD.bazel
  tests/integration/conversion/integration_test.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
  upup/pkg/fi/vfs_castore.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6260 Always log when a retry loop fails
  util/pkg/vfs/context.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6258 Update compatibility for v1.11.0
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#6276 AWS SDK v1.16.11
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6269 release process: add the relnotes command
  docs/development/release.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6272 Fix missed error check in hasPlaceHolderIP
  pkg/validation/validate_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6233 Create dev-upload tasks, for a faster upload during dev builds
  Makefile
  docs/development/adding_a_feature.md
  docs/development/release.md
  docs/development/testing.md
  hack/dev-build.sh
  hack/upload
Labels: approved, cncf-cla: yes, lgtm, size/M

#6271 Update recommended kubernetes version
  channels/alpha
  channels/stable
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/XS
