Repository kubernetes/kops, pull requests merged in 2019-12, with the labels that each got.

#8028 Alicloud: fix comparison failures for SecurityGroupRule and SSHKey
  upup/pkg/fi/cloudup/alitasks/BUILD.bazel
  upup/pkg/fi/cloudup/alitasks/securitygrouprule.go
  upup/pkg/fi/cloudup/alitasks/sshkey.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8026 Alicloud: add Encrypted field in Disk Find func
  upup/pkg/fi/cloudup/alitasks/disk.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8010 Add joshbranham to OWNERs as reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7406 Add CapacityOptimized to list of supported spot allocation strategies
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8027 Alicloud: fix comparison failures for VPC and NATGateway
  pkg/model/alimodel/network.go
  upup/pkg/fi/cloudup/alitasks/natgateway.go
  upup/pkg/fi/cloudup/alitasks/vpc.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7600 Allow users to set kube controller manager's concurrent sync flags.
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7925 Pass the cloud object to validator from caller
  cmd/kops/rollingupdatecluster.go
  cmd/kops/validate_cluster.go
  pkg/validation/BUILD.bazel
  pkg/validation/validate_cluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8025 Alicloud: allow use RAM role for OSS client
  util/pkg/vfs/BUILD.bazel
  util/pkg/vfs/osscontext.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8038 Fix Handling of LaunchTemplate Versions for MixedInstancePolicy
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8036 Additional leader election options
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8033 Fix truncation of admission control plugins list
  nodeup/pkg/model/kube_apiserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#8024 Add more verifications to Travis
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8042 Alicloud: fix comparison failures for LaunchConfiguration and LoadBalancerWhiteList
  upup/pkg/fi/cloudup/alitasks/launchconfiguration.go
  upup/pkg/fi/cloudup/alitasks/loadbalancerwhitelist.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8002 [Issue-7956] - [Digital Ocean] Minor fix to have proper indexing for digital ocean regions
  cmd/kops/create_cluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7865 EBS Root Volume Termination
  k8s/crds/kops.k8s.io_instancegroups.yaml
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/awsmodel/autoscalinggroup.go
  tests/integration/update_cluster/complex/cloudformation.json
  tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
  tests/integration/update_cluster/complex/in-v1alpha2.yaml
  tests/integration/update_cluster/complex/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#7917 Canal v3.10 manifest for k8s v1.15+
  cmd/kops/rollingupdatecluster.go
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/instancegroups/rollingupdate.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#8048 Cherry pick of #8038 onto release-1.15
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8045 Fix misleading message in "make ci" when imports formatted incorrectly
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#8039 Increase validation test coverage
  pkg/validation/BUILD.bazel
  pkg/validation/validate_cluster_test.go
  vendor/github.com/stretchr/testify/require/BUILD.bazel
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#8053 Update integration test to cover CloudFormation output of NAT gateways
  cmd/kops/integration_test.go
  tests/integration/update_cluster/privatecalico/cloudformation.json
  tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#8051 Fix CloudFormation template tags for NatGateway
  tests/integration/update_cluster/privatecalico/cloudformation.json
  upup/pkg/fi/cloudup/awstasks/natgateway.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8044 Alicloud: fix comparison failures for VSwitch and VSwitchSNAT
  upup/pkg/fi/cloudup/alitasks/vswitch.go
  upup/pkg/fi/cloudup/alitasks/vswitchSNAT.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8043 Alicloud: fix comparison failures for RAMRole and RAMPolicy
  upup/pkg/fi/cloudup/alitasks/rampolicy.go
  upup/pkg/fi/cloudup/alitasks/ramrole.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8022 Bump cilium version to 1.6.4
  pkg/apis/kops/networking.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8054 Add verify-generate to Travis and 'make ci'
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8062 Fix mounting Calico "flexvol-driver-host" in CoreOS
  cmd/kops/update_cluster.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7545 Complete support for Flatcar
  nodeup/pkg/distros/distribution.go
  nodeup/pkg/model/kube_controller_manager.go
  nodeup/pkg/model/kubelet.go
  nodeup/pkg/model/miscutils.go
  nodeup/pkg/model/ntp.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8068 Cherry pick of #8062 to release-1.17
  cmd/kops/update_cluster.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#8072 put kubernetes 1.17.0 to channels
  channels/alpha
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/S

#7792 remove unused functions and simplify return str
  pkg/model/components/kubecontrollermanager_test.go
  pkg/resources/gce/BUILD.bazel
  pkg/resources/gce/gce.go
  protokube/pkg/gossip/memberlist/state.go
  protokube/pkg/gossip/mesh/peer.go
  protokube/pkg/gossip/mesh/state.go
  upup/pkg/fi/assettasks/docker_api.go
  upup/pkg/fi/clientset_castore.go
  upup/pkg/fi/cloudup/openstack/utils.go
  upup/pkg/fi/vfs_castore.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8066 Cherry pick of #8062 to release-1.15
  cmd/kops/update_cluster.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8074 Validate cluster after updating bastions
  cmd/kops/rollingupdatecluster.go
  pkg/instancegroups/instancegroups.go
  pkg/instancegroups/rollingupdate.go
  pkg/instancegroups/rollingupdate_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#8076 Add support for NFT with Calico and Canal
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8075 Docs: Fix some broken development links
  docs/development/rolling_update.md
  docs/welcome/contributing.md
  docs/welcome/office_hours.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8084 Cherry-pick #8074 to release-1.17
  cmd/kops/rollingupdatecluster.go
  pkg/instancegroups/BUILD.bazel
  pkg/instancegroups/instancegroups.go
  pkg/instancegroups/rollingupdate.go
  pkg/instancegroups/rollingupdate_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8071 Automated cherry pick of #8022: Bump cilium version to 1.6.4
  pkg/apis/kops/networking.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8092 Docs: More List fixes
  docs/advisories/spectre-meltdown-kernel-update.md
  docs/boot-sequence.md
  docs/calico-v3.md
  docs/development/testing.md
  docs/development/vendoring.md
  docs/etcd/roadmap.md
  docs/examples/kops-test-route53-subdomain.md
  docs/examples/kops-tests-private-net-bastion-host.md
  docs/getting_started/arguments.md
  docs/getting_started/digitalocean.md
  docs/getting_started/openstack.md
  docs/iam_roles.md
  docs/labels.md
  docs/operations/addons.md
  docs/operations/cluster_upgrades_and_migrations.md
  docs/philosophy.md
  docs/releases.md
  docs/releases/1.6.1.md
  docs/rotate-secrets.md
  docs/run_in_existing_vpc.md
  docs/single-to-multi-master.md
  docs/upgrade_from_kops_1.6_to_1.7_calico_cidr_migration.md
  docs/vsphere-development-status.md
  docs/welcome/contributing.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#8086 Automated cherry pick of #7545: Complete support for Flatcar
  nodeup/pkg/distros/distribution.go
  nodeup/pkg/model/kube_controller_manager.go
  nodeup/pkg/model/kubelet.go
  nodeup/pkg/model/miscutils.go
  nodeup/pkg/model/ntp.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8085 Automated cherry pick of #7545: Complete support for Flatcar
  nodeup/pkg/distros/distribution.go
  nodeup/pkg/model/kube_controller_manager.go
  nodeup/pkg/model/kubelet.go
  nodeup/pkg/model/miscutils.go
  nodeup/pkg/model/ntp.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8094 Update documentation of go version requirement
  docs/development/building.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8095 add missing rbac rules
  upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.13.yaml.template
  upup/pkg/fi/cloudup/tests/manifests/k8s-1.13.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#8096 Cherry pick #8095
  upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.13.yaml.template
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#8088 test validateCluster twice to make sure it does not flap
  cmd/kops/rollingupdatecluster.go
  pkg/instancegroups/instancegroups.go
  pkg/instancegroups/rollingupdate.go
  pkg/instancegroups/rollingupdate_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#8046 update metrics server image
  addons/metrics-server/README.md
  addons/metrics-server/v1.8.x.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8102 docs(advanced): fix broken links on doc
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8105 Add test for flapping cluster validation and improve its logging
  pkg/instancegroups/instancegroups.go
  pkg/instancegroups/rollingupdate_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8103 some resources upgraded to google provider 3.0
  tests/integration/update_cluster/ha_gce/kubernetes.tf
  upup/pkg/fi/cloudup/gcetasks/instancegroupmanager.go
  upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8035 fix-pkg-staticcheck and remove the repeat code
  pkg/model/alimodel/convenience.go
  pkg/model/convenience.go
  pkg/model/dns.go
  pkg/model/openstackmodel/context.go
  pkg/model/openstackmodel/convenience.go
  pkg/model/openstackmodel/servergroup.go
  pkg/nodeidentity/openstack/identify.go
  pkg/pki/sshkey.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8109 Automated cherry pick of #8088: validate cluster twice #8105: Add unit test for flapping validation
  cmd/kops/rollingupdatecluster.go
  pkg/instancegroups/instancegroups.go
  pkg/instancegroups/rollingupdate.go
  pkg/instancegroups/rollingupdate_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8111 dev: hack/update-expected.sh should generate missing file
  pkg/testutils/modelharness.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8107 dev: ignore kops-controller in hack/update-expected.sh
  hack/update-expected.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8108 Terraform GCE output: setting google provider to at least 3.0.0
  tests/integration/update_cluster/ha_gce/kubernetes.tf
  upup/pkg/fi/cloudup/terraform/target.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8112 Add test for protokube builder
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/protokube_test.go
  nodeup/pkg/model/tests/protokube/docker/cluster.yaml
  nodeup/pkg/model/tests/protokube/docker/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8093 Automated cherry pick of #7545: Complete support for Flatcar
  nodeup/pkg/distros/distribution.go
  nodeup/pkg/model/kube_controller_manager.go
  nodeup/pkg/model/kubelet.go
  nodeup/pkg/model/miscutils.go
  nodeup/pkg/model/ntp.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8067 Cherry pick of #8062 to release-1.16
  cmd/kops/update_cluster.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8007 Automated cherry pick of #8004: fix(openstack): fix additional security groups on instance groups
  upup/pkg/fi/cloudup/openstacktasks/port.go
  upup/pkg/fi/cloudup/openstacktasks/port_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8123 channels: bump k8s versions after dec. patch releases
  channels/alpha
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/S

#8125 Fix doc(advanced) broken links
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8127 a little change
  cmd/nodeup/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8052 fix 404 urls
  docs/development/api_updates.md
  docs/examples/coreos-kops-tests-multimaster.md
  docs/operations/cluster_upgrades_and_migrations.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8120 pkg/model pkg/diff pkg/client/:simplify code and remove unused code
  hack/.staticcheck_failures
  pkg/client/simple/api/clientset.go
  pkg/diff/diff_test.go
  pkg/model/firewall_test.go
  pkg/model/gcemodel/convenience.go
  pkg/model/network.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8122 Cleans up the create cluster CLI prompts
  cmd/kops/create_cluster.go
  docs/cli/kops_create_cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#8110 Add kubeconfig flag to validate cluster command
  cmd/kops/validate_cluster.go
  docs/cli/kops_validate_cluster.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8128 Add inf1 isntances
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8133 Automated cherry pick of #7406: Add CapacityOptimized to list of supported spot allocation
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8121 util/pkg/ upup/tools/ : simplify code and remove unused code
  hack/.staticcheck_failures
  util/pkg/tables/format.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8141 Automated cherry pick of #8128: Add inf1 isntances
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8140 Automated cherry pick of #8128: Add inf1 isntances
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8134 Automated cherry pick of #7406: Add CapacityOptimized to list of supported spot allocation
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8116 Bump COS version in alpha channel for k8s >= 1.16
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8115 Openstack: Fix cluster floating ips
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/cloud_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#8147 Automated cherry pick of #8115 Openstack: Fix cluster floating ips
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/cloud_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#8139 tests: increase timeout in rolling update tests
  pkg/instancegroups/rollingupdate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8148 Automated cherry pick of #8115 Openstack: Fix cluster floating ips
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/cloud_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#8020 Automatically install dependencies with local packages
  nodeup/pkg/model/docker.go
  upup/pkg/fi/nodeup/nodetasks/package.go
  upup/pkg/fi/nodeup/tags/tags.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#8160 Fix periodic e2e test for Ubuntu 16.04
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8161 Latest bazel launcher seems to require a newline at end of .bazelversion
  .bazelversion
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8080 Spotinst: Upgrade the Spotinst controller to version 1.0.50
  upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8132 kops-change-main
  cmd/nodeup/main.go
  pkg/apis/kops/model/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8155 nodeup/pkg/model - fix static check
  hack/.staticcheck_failures
  k8s/crds/kops.k8s.io_clusters.yaml
  nodeup/pkg/model/convenience.go
  nodeup/pkg/model/file_assets.go
  nodeup/pkg/model/kubelet.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8118 upup/pkg/fi/ upup/pkg/kutil : simplify code and remove code
  hack/.staticcheck_failures
  upup/pkg/fi/cloudup/alitasks/securitygrouprule.go
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
  upup/pkg/fi/cloudup/gcetasks/storagebucketiam.go
  upup/pkg/fi/cloudup/gcetasks/subnet.go
  upup/pkg/fi/cloudup/openstacktasks/lblistener.go
  upup/pkg/fi/nodeup/loader.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8173 Update kubernetes versions used in integration tests
  tests/integration/create_cluster/complex/expected-v1alpha2.yaml
  tests/integration/create_cluster/complex/options.yaml
  tests/integration/create_cluster/ha/expected-v1alpha1.yaml
  tests/integration/create_cluster/ha/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha/options.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha1.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_encrypt/options.yaml
  tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_gce/options.yaml
  tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zones/options.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha1.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/ingwspecified/options.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha1.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/ngwspecified/options.yaml
  tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
  tests/integration/create_cluster/overrides/options.yaml
  tests/integration/create_cluster/private/expected-v1alpha1.yaml
  tests/integration/create_cluster/private/expected-v1alpha2.yaml
  tests/integration/create_cluster/private/options.yaml
  tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/private_shared_subnets/options.yaml
  tests/integration/create_cluster/shared_subnets/expected-v1alpha1.yaml
  tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets/options.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha1.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/options.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8169 Run dns-controller and kops-controller as non-root user
  cmd/kops-controller/BUILD.bazel
  dns-controller/cmd/dns-controller/BUILD.bazel
  images/dns-controller/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8182 Fix verify-staticcheck prow job
  Makefile
  hack/.staticcheck_failures
  hack/verify-staticcheck.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8165 protokube/pkg - fix static check
  hack/.staticcheck_failures
  protokube/pkg/gossip/dns/hosts/hosts.go
  protokube/pkg/gossip/mesh/gossip.go
  protokube/pkg/gossip/mesh/mesh.pb.go
  protokube/pkg/protokube/etcd_cluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8018 Automated cherry pick of #7961: Initial work
  cmd/kops-controller/BUILD.bazel
  cmd/kops-controller/main.go
  hack/.packages
  pkg/model/domodel/droplets.go
  pkg/nodeidentity/do/BUILD.bazel
  pkg/nodeidentity/do/identify.go
  upup/pkg/fi/cloudup/do/cloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8180 Refactor: Add Region() method to fi.Cloud
  pkg/resources/digitalocean/cloud.go
  pkg/resources/digitalocean/resources.go
  upup/pkg/fi/cloud.go
  upup/pkg/fi/cloudup/aliup/ali_cloud.go
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
  upup/pkg/fi/cloudup/baremetal/cloud.go
  upup/pkg/fi/cloudup/dotasks/volume.go
  upup/pkg/fi/cloudup/dotasks/volume_test.go
  upup/pkg/fi/cloudup/gce/gce_cloud.go
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/vsphere/vsphere_cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8189 Remove make command from verify-staticcheck.sh
  hack/verify-staticcheck.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8157 GCE: Fix Permission for the Storage Bucket
  upup/pkg/fi/cloudup/gcetasks/storagebucketacl.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8186 pkg/instancegroups - fix static check
  hack/.staticcheck_failures
  pkg/instancegroups/instancegroups.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8188 pkg/resources/aws:simplify code and remove code
  hack/.staticcheck_failures
  pkg/resources/aws/aws.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8190 Update links printed by Kops to use new docs site
  cmd/kops/update_cluster.go
  cmd/kops/util/factory.go
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8149 dnsprovider/pkg/dnsprovider - fix static check
  dnsprovider/pkg/dnsprovider/providers/aws/route53/route53_test.go
  dnsprovider/pkg/dnsprovider/providers/coredns/coredns_test.go
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/clouddns_test.go
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/clouddns.go
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/BUILD.bazel
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/clouddns.go
  hack/.staticcheck_failures
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8146 Automated cherry pick of #8115 origin release 1.17
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/cloud_test.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#8191 fix staticcheck failures in pkg/resources
  hack/.staticcheck_failures
  pkg/resources/ali/ali.go
  pkg/sshcredentials/BUILD.bazel
  pkg/sshcredentials/fingerprint.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8195 Add corresponding unit test to the function in subnet.go.
  pkg/util/subnet/subnet_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8197 Update gcr.io images
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#8192 pkg/resources-fix staticcheck
  hack/.staticcheck_failures
  pkg/resources/digitalocean/cloud.go
  pkg/resources/digitalocean/dns/dns.go
  pkg/resources/digitalocean/resources.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7898 Update Weave Net to version 2.6.0
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#7770 Guard External cloud controller manager with its feature flag
  cmd/kops/create.go
  cmd/kops/create_cluster.go
  cmd/kops/replace.go
  pkg/model/components/BUILD.bazel
  pkg/model/components/apiserver.go
  pkg/model/components/kubecontrollermanager.go
  pkg/model/components/kubelet.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8159 Always consider spot instance node readiness in cluster validation
  pkg/validation/BUILD.bazel
  pkg/validation/validate_cluster.go
  pkg/validation/validate_cluster_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/L

#8164 Update support for RHEL 8
  nodeup/pkg/distros/distribution.go
  nodeup/pkg/model/firewall.go
  nodeup/pkg/model/miscutils.go
  nodeup/pkg/model/ntp.go
  upup/models/nodeup/ntp/_aws/_rhel_family/packages/chrony
  upup/models/nodeup/ntp/_aws/_rhel_family/services/chronyd
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8203 Fix upup/tools/generators/pkg/codegen staticcheck failures
  hack/.staticcheck_failures
  upup/tools/generators/pkg/codegen/parse.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8170 containerd: Use containerd 1.2.4 with Docker 18.09.3
  nodeup/pkg/model/containerd.go
  nodeup/pkg/model/docker.go
  pkg/model/components/containerd.go
  pkg/model/components/containerd_test.go
  pkg/model/components/docker.go
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/containerd-cloudformation/in-v1alpha2.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8171 util/pkg/vfs/:staticcheck
  util/pkg/vfs/context.go
  util/pkg/vfs/gsfs.go
  util/pkg/vfs/sshfs.go
  util/pkg/vfs/vfssync.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8172 containerd: Add --container-runtime cli flag
  cmd/kops/create_cluster.go
  docs/cli/kops_create_cluster.md
  tests/integration/create_cluster/complex/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha/expected-v1alpha1.yaml
  tests/integration/create_cluster/ha/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha1.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha1.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal/expected-v1alpha1.yaml
  tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha1.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
  tests/integration/create_cluster/private/expected-v1alpha1.yaml
  tests/integration/create_cluster/private/expected-v1alpha2.yaml
  tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets/expected-v1alpha1.yaml
  tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha1.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_vpc/expected-v1alpha1.yaml
  tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8176 Add deprecation warning for older k8s versions
  permalinks/upgrade_k8s.md
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8179 Add all flag to export cluster command
  cmd/kops/export_kubecfg.go
  docs/cli/kops_export_kubecfg.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8194 Alicloud: refine Alicloud RAM role policy
  pkg/model/alimodel/BUILD.bazel
  pkg/model/alimodel/policy_builder.go
  pkg/model/alimodel/ram.go
  upup/pkg/fi/cloudup/alitasks/rampolicy.go
  upup/pkg/fi/cloudup/alitasks/ramrole.go
  util/pkg/vfs/ossfs.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#8202 Fix cmd/kops staticcheck failures
  cmd/kops/delete_cluster.go
  cmd/kops/export.go
  cmd/kops/export_kubecfg.go
  cmd/kops/integration_test.go
  cmd/kops/pkix.go
  cmd/kops/root.go
  cmd/kops/toolbox_bundle.go
  hack/.staticcheck_failures
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8150 Automated cherry pick of #7492: fix(addons/coredns.addons.k8s.io) Workaround to stop
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8047 Cherry pick of #8038 onto release-1.14
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8143 /hack: improve shell script in hack
  hack/go_install_from_commit.sh
  hack/pre-commit.sh
  hack/update-bazel.sh
  hack/update-expected.sh
  hack/verify-apimachinery.sh
  hack/verify-generate.sh
  hack/verify-gomod
  hack/verify-spelling.sh
  hack/verify-staticcheck.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#8049 Cherry pick of #8038 onto release-1.16
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8059 Automated cherry pick of #8022: Bump cilium version to 1.6.4
  pkg/apis/kops/networking.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8060 Automated cherry pick of #8022: Bump cilium version to 1.6.4
  pkg/apis/kops/networking.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8131 dns-controller: allow it to run on CNI networking mode and remove dependency on kube-proxy
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#8041 replace TrimRight with TrimSuffix
  pkg/assets/builder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8211 Fix typo in export kubeconfig
  cmd/kops/export_kubecfg.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8210 Fix typo in KubeProxy model
  nodeup/pkg/model/kube_proxy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8209 Fix link printed in k8s version deprecation message
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7832 cilium: don't try to mount sys/fs/bpf if already mounted
  nodeup/pkg/model/network.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8079 Set shared field for volume resource on delete
  pkg/resources/aws/aws.go
  pkg/resources/aws/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8144 clean up buildDiffLines
  pkg/diff/diff.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8218 Fix cloudmock/aws/mockelbv2 staticcheck failures
  cloudmock/aws/mockelbv2/api.go
  hack/.staticcheck_failures
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8222 Fix node-authorizer/pkg/authorizers/aws staticcheck failure
  hack/.staticcheck_failures
  node-authorizer/pkg/authorizers/aws/verifier.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8223 Fix pkg/resources/openstack staticcheck failure
  hack/.staticcheck_failures
  pkg/resources/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8232 Add code simplifications for staticheck
  cmd/kops/toolbox_template.go
  dns-controller/pkg/watchers/ingress.go
  dns-controller/pkg/watchers/service.go
  hack/verify-staticcheck.sh
  upup/pkg/fi/cloudup/alitasks/vpc.go
  upup/pkg/fi/cloudup/openstacktasks/volume.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8215 Automated cherry pick of #7832: cilium: don't try to mount sys/fs/bpf if already mounted
  nodeup/pkg/model/network.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8219 util/pkg/slice: Add slice test
  util/pkg/slice/BUILD.bazel
  util/pkg/slice/slice_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8229 pkg/apis/ pkg/commands/ pkg/model/ staticcheck
  pkg/apis/kops/registry/helpers.go
  pkg/apis/kops/validation/instancegroup.go
  pkg/apis/kops/validation/validation.go
  pkg/commands/status_discovery.go
  pkg/model/components/kubecontrollermanager.go
  pkg/model/iam.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8233 dnsprovider staticcheck
  dnsprovider/pkg/dnsprovider/plugins.go
  dnsprovider/pkg/dnsprovider/providers/aws/route53/stubs/route53api.go
  dnsprovider/pkg/dnsprovider/providers/coredns/coredns.go
  dnsprovider/pkg/dnsprovider/providers/coredns/rrchangeset.go
  dnsprovider/pkg/dnsprovider/providers/coredns/rrsets.go
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/changes_create_call.go
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/managed_zone_create_call.go
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/managed_zones_delete_call.go
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/managed_zones_list_call.go
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/rrsets_service.go
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/rrchangeset.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8231 upup/pkg/fi/cloudup/apply_cluster staticcheck
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8225 staticcheck:remove duplicate import packages
  pkg/apis/kops/channel.go
  pkg/client/simple/vfsclientset/commonvfs.go
  pkg/client/simple/vfsclientset/instancegroup.go
  pkg/cloudinstances/cloud_instance_group.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8230 cmd/kops/ staticcheck and remove one mom
  cmd/kops/replace.go
  cmd/kops/root.go
  cmd/kops/toolbox_bundle.go
  cmd/kops/toolbox_convert_imported.go
  cmd/kops/toolbox_dump.go
  cmd/kops/update_cluster.go
  cmd/kops/util/factory.go
  cmd/kops/validate_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8234 nodeup/pkg/ pkg/ staticcheck: Fix ST1005
  nodeup/pkg/model/context.go
  nodeup/pkg/model/file_assets.go
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_proxy.go
  nodeup/pkg/model/volumes.go
  pkg/model/components/context.go
  pkg/nodeidentity/do/identify.go
  pkg/resources/aws/aws.go
  pkg/testutils/modelharness.go
  pkg/util/subnet/subnet.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8236 upup/pkg/fi/cloudup/ staticcheck: Fix ST1005
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
  upup/pkg/fi/cloudup/awsup/aws_utils.go
  upup/pkg/fi/cloudup/defaults.go
  upup/pkg/fi/cloudup/dns.go
  upup/pkg/fi/cloudup/gce/gce_cloud.go
  upup/pkg/fi/cloudup/gce/labels.go
  upup/pkg/fi/cloudup/gcetasks/address.go
  upup/pkg/fi/cloudup/gcetasks/disk.go
  upup/pkg/fi/cloudup/gcetasks/forwardingrule.go
  upup/pkg/fi/cloudup/gcetasks/instance.go
  upup/pkg/fi/cloudup/loader.go
  upup/pkg/fi/cloudup/openstack/availability_zone.go
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/floatingip.go
  upup/pkg/fi/cloudup/openstack/instance.go
  upup/pkg/fi/cloudup/openstack/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/L
