Repository kubernetes/kops, pull requests merged in 2019-06, with the labels that each got.

#7045 Openstack delete dynamic floating ip in delete cluster
  pkg/resources/openstack/BUILD.bazel
  pkg/resources/openstack/lb.go
  pkg/resources/openstack/network.go
  pkg/resources/openstack/openstack.go
  pkg/resources/openstack/ports.go
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/L

#7092 Updated docs for openstack cloud provider.
  docs/tutorial/openstack.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7067 Change versions to fix memory.limit_in_bytes: device or resource busy
  addons/prometheus-operator/v0.29.0.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#7090 K8s 1.12.8 to stable 1.12.9 to alpha
  channels/alpha
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7088 Fix link to Calico route reflectors documentation + typo
  docs/networking.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7094 Mark ENI 0 as delete_on_termination for LaunchTemplates
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation_test.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
Labels: approved, cherry-pick, cncf-cla: yes, lgtm, size/S

#7099 Cherry pick of #7094 onto release-1.12
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation_test.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7100 Cherry pick of #7094 onto release-1.13
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation_test.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7101 Cherry pick of #7094 onto release-1.14
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation_test.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7106 Release 1.13 backport 7045
  pkg/resources/openstack/BUILD.bazel
  pkg/resources/openstack/lb.go
  pkg/resources/openstack/network.go
  pkg/resources/openstack/openstack.go
  pkg/resources/openstack/ports.go
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/L

#7107 Release 1 14 backport 7050
  pkg/resources/openstack/BUILD.bazel
  pkg/resources/openstack/lb.go
  pkg/resources/openstack/network.go
  pkg/resources/openstack/openstack.go
  pkg/resources/openstack/ports.go
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/L

#7071 Add Debian 10 (buster) support
  nodeup/pkg/distros/distribution.go
  nodeup/pkg/distros/identify.go
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/kubectl.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7050 Openstack support for rolling-update status
  pkg/client/simple/vfsclientset/BUILD.bazel
  pkg/client/simple/vfsclientset/cluster.go
  pkg/client/simple/vfsclientset/instancegroup.go
  pkg/model/openstackmodel/servergroup.go
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/instance.go
  upup/pkg/fi/cloudup/openstack/server_group.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/M

#7108 release 1.14 backport 7050
  pkg/client/simple/vfsclientset/BUILD.bazel
  pkg/client/simple/vfsclientset/cluster.go
  pkg/client/simple/vfsclientset/instancegroup.go
  pkg/model/openstackmodel/servergroup.go
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/instance.go
  upup/pkg/fi/cloudup/openstack/server_group.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/M

#7122 Upgrade AWS VPC CNI provider to 1.5.0
  docs/networking.md
  pkg/apis/kops/networking.go
  pkg/model/iam/iam_builder.go
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7123 Documentation Cleanup
  README.md
  docs/arguments.md
  docs/releases.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#7077 Adding affinity and PDB to dns.
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6984 bumped k8s 1.11 versions to 1.11.10 in stable channel
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7079 Cherry-pick #7070 to release-1.14
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/components/apiserver.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7078 Cherry-pick #7070 to release-1.13
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/components/apiserver.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7105 Release 1.13 backport 7050
  pkg/client/simple/vfsclientset/BUILD.bazel
  pkg/client/simple/vfsclientset/cluster.go
  pkg/client/simple/vfsclientset/instancegroup.go
  pkg/model/openstackmodel/servergroup.go
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/instance.go
  upup/pkg/fi/cloudup/openstack/server_group.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/M

#7115 Cherry pick debian buster support for release-1.14
  nodeup/pkg/distros/distribution.go
  nodeup/pkg/distros/identify.go
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/kubectl.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7114 Cherry pick debian buster support for release-1.13
  nodeup/pkg/distros/distribution.go
  nodeup/pkg/distros/identify.go
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/kubectl.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7116 Cherry pick of #7080 onto release-1.13
  node-authorizer/pkg/server/metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7117 Cherry pick of #7080 onto release-1.14
  node-authorizer/pkg/server/metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7127 Automated cherry pick of #7122: Upgrade AWS VPC CNI provider to 1.5.0
  docs/networking.md
  pkg/apis/kops/networking.go
  pkg/model/iam/iam_builder.go
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7126 Automated cherry pick of #7122: Upgrade AWS VPC CNI provider to 1.5.0
  docs/networking.md
  pkg/apis/kops/networking.go
  pkg/model/iam/iam_builder.go
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7066 Add support for SpotPrice and Mixed Instance ASGs
  cmd/kops/integration_test.go
  pkg/model/awsmodel/autoscalinggroup.go
  tests/integration/update_cluster/mixed_instances/cloudformation.json
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/id_rsa.pub
  tests/integration/update_cluster/mixed_instances/in-v1alpha2.yaml
  tests/integration/update_cluster/mixed_instances/kubernetes.tf
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/id_rsa.pub
  tests/integration/update_cluster/mixed_instances_spot/in-v1alpha2.yaml
  tests/integration/update_cluster/mixed_instances_spot/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#7109 support apiserver admission-control-config-file flag
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7131 Automated cherry pick of #7066: Add support for SpotPrice and Mixed Instance ASGs
  cmd/kops/integration_test.go
  pkg/model/awsmodel/autoscalinggroup.go
  tests/integration/update_cluster/mixed_instances/cloudformation.json
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/id_rsa.pub
  tests/integration/update_cluster/mixed_instances/in-v1alpha2.yaml
  tests/integration/update_cluster/mixed_instances/kubernetes.tf
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/id_rsa.pub
  tests/integration/update_cluster/mixed_instances_spot/in-v1alpha2.yaml
  tests/integration/update_cluster/mixed_instances_spot/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#7132 Automated cherry pick of #7066: Add support for SpotPrice and Mixed Instance ASGs
  cmd/kops/integration_test.go
  pkg/model/awsmodel/autoscalinggroup.go
  tests/integration/update_cluster/mixed_instances/cloudformation.json
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/id_rsa.pub
  tests/integration/update_cluster/mixed_instances/in-v1alpha2.yaml
  tests/integration/update_cluster/mixed_instances/kubernetes.tf
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/id_rsa.pub
  tests/integration/update_cluster/mixed_instances_spot/in-v1alpha2.yaml
  tests/integration/update_cluster/mixed_instances_spot/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#7144 updated link to kubernetes bot commands
  README.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7150 typo fix: fix kops-server-push -> make kops-server-push
  docs/api-server/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7154 Add rdrgmnzs to the approvers list in OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7084 Flatcar support
  docs/images.md
  nodeup/pkg/distros/distribution.go
  nodeup/pkg/distros/identify.go
  nodeup/pkg/model/context.go
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/etcd.go
  nodeup/pkg/model/kubelet.go
  nodeup/pkg/model/logrotate.go
  nodeup/pkg/model/update_service.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7141 Don't precreate etcd DNS records if we're using etcd-manager
  upup/pkg/fi/cloudup/dns.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7164 Update Docs for Calico Backend for kops 1.12
  docs/networking.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7169 Update Canal to v3.7.3
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7139 Improve docs on labels
  docs/labels.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7153 Allow user to set the --kube-api-qps and --kube-api-burst flags on KubeControllerManager
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/flagbuilder/buildflags_test.go
  upup/pkg/fi/cloudup/openstack/server_group.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7103 Egress proxy for etcd manager
  hack/.packages
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/convenience.go
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_controller_manager.go
  nodeup/pkg/model/kube_scheduler.go
  nodeup/pkg/model/protokube.go
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/model.go
  util/pkg/proxy/BUILD.bazel
  util/pkg/proxy/proxy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7124 [Unit Tests] Added unit test for kube proxy builder
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/kube_proxy_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7166 add c5.12xlarge, c5.24xlarge, c5.metal, i3en.metal
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7003 Simplify `go test` command
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7162 Fix the link to the Prow commands.
  README-ES.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7160 add masterPublicName support in kops set cluster
  pkg/commands/set_cluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6803 Update aws-iam-authenticator image to 0.4.0
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6985 Added some changes to openstack.md file
  docs/tutorial/openstack.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7174 Relnotes for 1.12.2
  docs/releases/1.12-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7176 Add updated 1.12 image to the alpha channel
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7177 Instance protection
  docs/instance_groups.md
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/awsmodel/autoscalinggroup.go
  tests/integration/update_cluster/mixed_instances/in-v1alpha2.yaml
  tests/integration/update_cluster/mixed_instances/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7179 Automated cherry pick of #7177: Instance protection
  docs/instance_groups.md
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/awsmodel/autoscalinggroup.go
  tests/integration/update_cluster/mixed_instances/in-v1alpha2.yaml
  tests/integration/update_cluster/mixed_instances/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7180 Automated cherry pick of #7177: Instance protection
  docs/instance_groups.md
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/awsmodel/autoscalinggroup.go
  tests/integration/update_cluster/mixed_instances/in-v1alpha2.yaml
  tests/integration/update_cluster/mixed_instances/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7196 Automated cherry pick of #7195: update instances list with make update-machine-types
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7197 Automated cherry pick of #7195: update instances list with make update-machine-types
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7198 Automated cherry pick of #7166: update instances list with make update-machine-types
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7199 Automated cherry pick of #7166: update instances list with make update-machine-types
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/M
