Repository kubernetes/kops, pull requests merged in 2019-04, with the labels that each got.

#6708 Addon for Citrix Ingress
  addons/ingress-citrix/README.md
  addons/ingress-citrix/addon.yaml
  addons/ingress-citrix/v1.1.1-aws.yaml
  addons/ingress-citrix/v1.1.1.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#6726 Update information in README
  addons/ingress-citrix/README.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/M

#6719 Allow customizing Resource Request & Limits for CoreDNS
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/components/BUILD.bazel
  pkg/model/components/kubedns.go
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6731 Automated cherry pick of #6719: Add DNS Resource Settings
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/components/BUILD.bazel
  pkg/model/components/kubedns.go
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6724 Update instances types
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cherry-pick, cncf-cla: yes, lgtm, size/L

#6733 Automated cherry pick of #6724: Update instances types
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6723 Update 1.3.0 to 1.3.3
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cherry-pick, cncf-cla: yes, lgtm, size/S

#6734 Automated cherry pick of #6723: Update 1.3.0 to 1.3.3
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6737 Add min-resync-period for Controller Manager
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6713 Update dashboard instructions for accessing the dashboard addon
  docs/addons.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#6730 Allow the AWS IAM Authenticator image name to be overridden
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, area/addon-manager, area/aws, cncf-cla: yes, lgtm, size/S

#6739 Cherry pick of #6272 onto release-1.11
  pkg/validation/validate_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6714 Document kubeAPIServer featureGates
  docs/cluster_spec.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6740 kube-dns-autoscaler: Add node watch to permissions
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6742 Cherry pick of #6740 onto release-1.12
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6741 kube-dns: Update to 1.14.13
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cherry-pick, cncf-cla: yes, lgtm, size/M

#6745 Cherry pick of #6743 onto release-1.12
  nodeup/pkg/model/kube_apiserver.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6744 channels: promote alpha to stable
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6743 Increase apiserver timeout to 45 seconds
  nodeup/pkg/model/kube_apiserver.go
Labels: approved, cherry-pick, cncf-cla: yes, lgtm, size/XS

#6746 Cherry pick of #6732 onto release-1.12
  pkg/model/resources/nodeup.go
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup_test.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6732 Fix issue #6700: User Data for launch templates & other terraform issues
  pkg/model/resources/nodeup.go
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup_test.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#6748 Improved release process docs
  docs/development/release.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6750 Cherry pick of #6741 onto release-1.12
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6753 Use version number as well as name when checking LaunchTemplates
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, cherry-pick, cncf-cla: yes, lgtm, ok-to-test, size/S

#6755 Automated cherry pick of #6753: User version number as well as name when checking
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6762 1.12.0-beta.1 bug - use dynamic s3 prefix in addAmazonVPCCNIPermissions func
  pkg/model/iam/iam_builder.go
Labels: approved, cherry-pick, cncf-cla: yes, lgtm, ok-to-test, size/S

#6357 add the registry-qps kubelet flag
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6759 Update authentication.md
  docs/authentication.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6706 Add ability to specify cpuRequest for API Server
  nodeup/pkg/model/kube_apiserver.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6765 Automated cherry pick of #6762: use dynamic s3 prefix in addAmazonVPCCNIPermissions func
  pkg/model/iam/iam_builder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6772 Release 1.14.0-alpha.1
  Makefile
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
  version.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6781 Put 1.13 and 1.14 into channels
  channels/alpha
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/S

#6780 1.12 release notes: populate list of PRs
  docs/releases/1.12-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#6776 Carry Provisioned IOPS to Terraform and CloudFormation templates
  upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6768 pin nvidia-docker2 version to avoid installation failure
  hooks/nvidia-device-plugin/image/files/02-nvidia-docker.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6769 pkg/model: Fix dropped error
  pkg/model/iam.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6789 Using const() defines constants together (part:1)
  pkg/apis/kops/channel.go
  pkg/apis/kops/labels.go
  pkg/apis/kops/registry/registry.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6791 Using const() defines constants together (part:3)
  pkg/model/bastion.go
  protokube/pkg/gossip/dns/hosts/hosts.go
  protokube/pkg/protokube/vsphere_volume.go
  upup/pkg/fi/cloudup/aliup/ali_cloud.go
  upup/pkg/fi/cloudup/gce/labels.go
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/urls.go
  util/pkg/vfs/vfssync.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6766 Update rules go
  WORKSPACE
Labels: approved, cherry-pick, cncf-cla: yes, lgtm, size/XS

#6774 Update etcd3-migration.md doc
  docs/etcd3-migration.md
  docs/releases/1.12-NOTES.md
Labels: approved, area/documentation, cherry-pick, cncf-cla: yes, lgtm, ok-to-test, size/M

#6794 Automated cherry pick of #6766: Update rules go
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6787 KubeAPIServer HTTP2 Stream Parameter
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6793 Automated cherry pick of #6766: Update rules go
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6420 Refactor names of URLs in assets to clarify their purpose
  pkg/assets/builder.go
  upup/pkg/fi/cloudup/loader.go
  upup/pkg/fi/dryrun_target.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6802 Update docker README.md file, delete `$`
  docker/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#6798 Switch to golang 1.11.5
  .travis.yml
  BUILD.bazel
  Makefile
  WORKSPACE
  cloudmock/aws/mockautoscaling/group.go
  docker/Dockerfile
  hack/verify-gofmt.sh
  images/dns-controller-builder/Dockerfile
  images/protokube-builder/Dockerfile
  node-authorizer/pkg/client/helper.go
  nodeup/pkg/model/kubelet.go
  pkg/model/firewall_test.go
  pkg/pki/certificate_test.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
  upup/pkg/fi/fitasks/keypair.go
  upup/pkg/fi/vfs_castore.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6805 Cherry pick of #6769 onto release-1.13
  pkg/model/iam.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6806 Cherry pick of #6776 onto release-1.13
  upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6807 Cherry pick of #6787 onto release-1.13
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6808 Cherry pick of #6798 onto release-1.13
  .travis.yml
  BUILD.bazel
  Makefile
  WORKSPACE
  cloudmock/aws/mockautoscaling/group.go
  docker/Dockerfile
  hack/verify-gofmt.sh
  images/dns-controller-builder/Dockerfile
  images/protokube-builder/Dockerfile
  node-authorizer/pkg/client/helper.go
  nodeup/pkg/model/kubelet.go
  pkg/model/firewall_test.go
  pkg/pki/certificate_test.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
  upup/pkg/fi/fitasks/keypair.go
  upup/pkg/fi/vfs_castore.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6799 Switch to golang 1.12.1
  .travis.yml
  Makefile
  WORKSPACE
  docker/Dockerfile
  images/dns-controller-builder/Dockerfile
  images/protokube-builder/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#6812 Cherry pick of #6776 onto release-1.14
  upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6809 Using const() defines constants together (part:3)
  cloudmock/aws/mockec2/tags.go
  dns-controller/pkg/watchers/annotations.go
  nodeup/pkg/model/cloudconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6813 Cherry pick of #6769 onto release-1.14
  pkg/model/iam.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6814 Cherry pick of #6787 onto release-1.14
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6815 Cherry pick of #6798 and #6799 onto release-1.14
  .travis.yml
  BUILD.bazel
  Makefile
  WORKSPACE
  cloudmock/aws/mockautoscaling/group.go
  docker/Dockerfile
  hack/verify-gofmt.sh
  images/dns-controller-builder/Dockerfile
  images/protokube-builder/Dockerfile
  node-authorizer/pkg/client/helper.go
  nodeup/pkg/model/kubelet.go
  pkg/model/firewall_test.go
  pkg/pki/certificate_test.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
  upup/pkg/fi/fitasks/keypair.go
  upup/pkg/fi/vfs_castore.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6816 Cherry pick of #6420 onto release-1.13
  pkg/assets/builder.go
  upup/pkg/fi/cloudup/loader.go
  upup/pkg/fi/dryrun_target.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6810 Using const() defines constants together (part:4)
  nodeup/pkg/model/kubelet.go
  pkg/model/alimodel/api_loadbalancer.go
  pkg/model/alimodel/external_access.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6278 [docs] Use env var for state store examples
  docs/tutorial/gce.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6820 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6833 set kubernetes version to 1.12.8 to match current release
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6838 Automated cherry pick of #6837: Add t3a family #6823: Canal manifest updates for k8s v1.12+
  hack/machine_types/vpc_ip_resource_limit.go
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/openstackmodel/firewall.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/awsup/machine_types.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/openstacktasks/lb.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6839 Automated cherry pick of #6837: Add t3a family #6823: Canal manifest updates for k8s v1.12+
  hack/machine_types/vpc_ip_resource_limit.go
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/openstackmodel/firewall.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/awsup/machine_types.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/openstacktasks/lb.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6823 Canal manifest updates for k8s v1.12+
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/openstackmodel/firewall.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/openstacktasks/lb.go
Labels: approved, cherry-pick, cncf-cla: yes, lgtm, size/M

#6836 Update readme chart given alphas and betas
  README.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#6842 Automated cherry pick of #6840: Fix typo in aws-iam-authenticator image field name
  pkg/apis/kops/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6843 Automated cherry pick of #6840: Fix typo in aws-iam-authenticator image field name
  pkg/apis/kops/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6840 Fix typo in aws-iam-authenticator image field name
  pkg/apis/kops/cluster.go
Labels: approved, area/api, cncf-cla: yes, lgtm, size/XS

#6841 Remove verify bazel and expose error
  Makefile
  hack/verify-bazel.sh
Labels: approved, cherry-pick, cncf-cla: yes, lgtm, size/XS

#6837 Add t3a family
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cherry-pick, cncf-cla: yes, lgtm, size/M

#6846 Automated cherry pick of #6841: Remove verify bazel from travis its run in prow
  Makefile
  hack/verify-bazel.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6845 Automated cherry pick of #6841: Remove verify bazel from travis its run in prow
  Makefile
  hack/verify-bazel.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6821 update tolerations to openstack external cloud provider
  upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.11.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/S

#6826 [Unit Tests] Add unit tests for create_kubecfg file
  pkg/kubeconfig/BUILD.bazel
  pkg/kubeconfig/create_kubecfg_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#6859 Protect against nil derefence
  pkg/model/bootstrapscript.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
