Repository kubernetes/kops, pull requests merged in 2019-02, with the labels that each got.

#6423 update openstack documentation
  docs/tutorial/openstack.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#6450 Updated OWNERS file to include link to docs
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6460 [jjo] add docker-ce 18.06.2 for CVE-2019-5736
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6389 Add permission for CreateTag on ENI to amazon-vpc-cni-k8s
  docs/networking.md
  pkg/model/iam/iam_builder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6408 Document etcd3 migration process
  docs/etcd3-migration.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#6410 Normalize etcd cluster provider names
  pkg/commands/set_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6411 Support etcd-manager v3, suitable for backporting
  docs/etcd/manager.md
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/context.go
  nodeup/pkg/model/etcd_manager_tls.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  upup/pkg/fi/nodeup/command.go
Labels: approved, cherry-pick, cncf-cla: yes, lgtm, size/L

#6413 Openstack loadbalancers erronous modification requests
  upup/pkg/fi/cloudup/openstacktasks/lblistener.go
  upup/pkg/fi/cloudup/openstacktasks/lbpool.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/openstack, size/XS

#6416 fix typos for addon doc
  docs/addons.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6422 upgrade calico to 2.6.12 to fix TTA-2018-001
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6424 Use the forward plugin instead of proxy plugin in CoreDNS
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6426 Update bazel workspace
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#6427 Fix machine types and cleanup makefile
  Makefile
  hack/machine_types/vpc_ip_resource_limit.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6461 Add jessie patch
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6468 Allow NodeAuthorizer to speak via HTTP Proxy if configured
  upup/models/cloudup/resources/addons/node-authorizer.addons.k8s.io/k8s-1.10.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6469 Updated Canal manifest to v3.5.0 for k8s v1.12+
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6246 Update document for GPU support
  docs/gpu.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/M

#6210 Fixing kops-4049
  nodeup/pkg/model/kubelet.go
  nodeup/pkg/model/kubelet_test.go
  nodeup/pkg/model/tests/kubelet/featuregates/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6453 kube-apiserver: Add oidc-required-claim flag
  docs/cluster_spec.md
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6367 add OWNERS file to openstack spesific folders
  pkg/model/openstackmodel/OWNERS
  pkg/resources/openstack/OWNERS
  upup/pkg/fi/cloudup/openstack/OWNERS
  upup/pkg/fi/cloudup/openstacktasks/OWNERS
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/S

#6433 Update Loadbalancer Pools
  upup/pkg/fi/cloudup/openstacktasks/lb.go
  upup/pkg/fi/cloudup/openstacktasks/servergroup.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/openstack, size/XS

#6442 fix hostnames in kops openstack
  pkg/model/openstackmodel/servergroup.go
  pkg/resources/openstack/instances.go
  pkg/resources/openstack/ports.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/M

#6418 implement ig deletegroup for openstack
  upup/pkg/fi/cloudup/openstack/cloud.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/M

#6480 Removing openstack credential file support
  docs/tutorial/openstack.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, sig/openstack, size/M

#6431 fix error when updating/creating lb in openstack
  upup/pkg/fi/cloudup/openstacktasks/floatingip.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/S

#6432 recheck floatingip after server is active
  upup/pkg/fi/cloudup/openstacktasks/floatingip.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/S

#6421 Ability to scale down instancegroup in openstack
  pkg/model/openstackmodel/servergroup.go
  upup/pkg/fi/cloudup/openstacktasks/servergroup.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/M

#6415 expose DryRunTarget changes and deletions
  upup/pkg/fi/dryrun_target.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/S

#6438 support both octavia and old lbaasv2 api in openstack
  cmd/kops/create_cluster.go
  docs/tutorial/openstack.md
  pkg/resources/openstack/BUILD.bazel
  pkg/resources/openstack/lb.go
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/loadbalancer.go
  upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel
  upup/pkg/fi/cloudup/openstacktasks/lb.go
  upup/pkg/fi/cloudup/openstacktasks/lbpool.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/L

#6487 Guess SSH usernames for RHEL & Centos in toolbox dump
  pkg/resources/aws/aws.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6488 Choose docker version 18.06.2 for k8s >= 1.12
  pkg/model/components/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6489 Install kubelet config for default centos user
  nodeup/pkg/model/kubectl.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6485 Update the CoreDNS manifest
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6486 docs: improve the queries for finding RHEL/CentOS images
  docs/images.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#6491 Workaround for overlay2 vs rhel-family docker bug
  nodeup/pkg/model/docker.go
Labels: approved, cherry-pick, cncf-cla: yes, lgtm, size/M

#6497 retry l3floatingip list in fresh cluster
  upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel
  upup/pkg/fi/cloudup/openstacktasks/floatingip.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/M

#6397 Update 1.12 addon manifests to use apps/v1, rbac v1
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml
  upup/models/cloudup/resources/addons/authentication.kope.io/k8s-1.12.yaml
  upup/models/cloudup/resources/addons/core.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.flannel/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.kope.io/k8s-1.12.yaml
  upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.romana/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/node-authorizer.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/podsecuritypolicy.addons.k8s.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#6492 Fix package name & version for container-selinux
  nodeup/pkg/model/docker.go
Labels: approved, cherry-pick, cncf-cla: yes, lgtm, size/S

#6508 Adding Comment
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6513 Kube Proxy Metrics Option
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6313 Etcd memory and cpu requests
  cmd/kops/BUILD.bazel
  cmd/kops/create_cluster.go
  docs/cluster_spec.md
  hack/make-apimachinery.sh
  pkg/apis/kops/BUILD.bazel
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/BUILD.bazel
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/BUILD.bazel
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/bootstrapscript.go
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/cluster.yaml
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  protokube/pkg/protokube/etcd_cluster.go
  protokube/pkg/protokube/etcd_manifest.go
  protokube/tests/integration/build_etcd_manifest/main/etcd_env_vars.yaml
  protokube/tests/integration/build_etcd_manifest/main/non_tls.yaml
  protokube/tests/integration/build_etcd_manifest/main/tls.yaml
  tests/integration/conversion/minimal/v1alpha0.yaml
  tests/integration/conversion/minimal/v1alpha1.yaml
  tests/integration/conversion/minimal/v1alpha2.yaml
  tests/integration/create_cluster/complex/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha/expected-v1alpha1.yaml
  tests/integration/create_cluster/ha/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha1.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha1.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal/expected-v1alpha1.yaml
  tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha1.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
  tests/integration/create_cluster/private/expected-v1alpha1.yaml
  tests/integration/create_cluster/private/expected-v1alpha2.yaml
  tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets/expected-v1alpha1.yaml
  tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha1.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_vpc/expected-v1alpha1.yaml
  tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#6523 Map docker 18.06.3
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/docker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6524 Make docker 18.06.3 the default for k8s >= 1.12
  pkg/model/components/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6458 Upgrade base image to alpine 3.8 and GO to 1.10.8
  Makefile
  docker/Dockerfile
Labels: approved, cherry-pick, cncf-cla: yes, ok-to-test, size/XS

#6522 Document strategy for cve_2019_5736
  docs/advisories/cve_2019_5736.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#6506 Try using chattr to mark docker-runc as immutable
  nodeup/pkg/model/docker.go
  upup/pkg/fi/nodeup/nodetasks/BUILD.bazel
  upup/pkg/fi/nodeup/nodetasks/chattr.go
  upup/pkg/fi/nodeup/nodetasks/service.go
Labels: approved, cherry-pick, cncf-cla: yes, lgtm, size/L

#6503 Simple mirror support
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  upup/pkg/fi/assetstore.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/networking.go
  upup/pkg/fi/cloudup/networking_test.go
  upup/pkg/fi/cloudup/urls.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6526 Bump etcd-manager version to 3.0.20190224
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6530 specify dns servers to openstack subnet
  cmd/kops/create_cluster.go
  docs/tutorial/openstack.md
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/openstackmodel/network.go
  upup/pkg/fi/cloudup/openstacktasks/subnet.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/M

#6477 possibility to specify floatingip subnet for resources in openstack
  cmd/kops/create_cluster.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/subnet.go
  upup/pkg/fi/cloudup/openstacktasks/floatingip.go
  upup/pkg/fi/cloudup/openstacktasks/router.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/L

#6525 Add Experimental Cluster Signing Duration flag
  docs/cluster_spec.md
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6540 Cherry pick of #6180 onto release-1.11
  pkg/apis/kops/validation/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6541 Cherry pick of #6202 onto release-1.11
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6542 Cherry pick of #6401 onto release-1.11
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6543 Cherry pick of #6410 onto release-1.11
  pkg/commands/set_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6545 Cherry pick of #6427 onto release-1.11
  Makefile
  hack/machine_types/vpc_ip_resource_limit.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6343 set net.ipv4.ip_local_reserved_ports to the KubeAPIServer ServiceNodePortRange parameter on nodeup
  nodeup/pkg/model/sysctls.go
Labels: approved, cherry-pick, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6546 Cherry pick of #6458 onto release-1.11
  Makefile
  docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6544 Cherry pick of #6411 onto release-1.11
  docs/etcd/manager.md
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/context.go
  nodeup/pkg/model/etcd_manager_tls.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6547 Cherry pick of #6488 onto release-1.11
  pkg/model/components/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6548 Cherry pick of #6491 onto release-1.11
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6549 Cherry pick of #6506 onto release-1.11
  nodeup/pkg/model/docker.go
  upup/pkg/fi/nodeup/nodetasks/BUILD.bazel
  upup/pkg/fi/nodeup/nodetasks/chattr.go
  upup/pkg/fi/nodeup/nodetasks/service.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6550 Cherry pick of #6338 onto release-1.11
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6534 spread instances equally to all AZs
  pkg/model/openstackmodel/servergroup.go
  upup/pkg/fi/cloudup/openstacktasks/instance.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/M

#6552 Cherry pick of #6343 onto release-1.11
  nodeup/pkg/model/sysctls.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6553 Cherry pick of #6461 onto release-1.11
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6555 Cherry pick of #6526 onto release-1.11
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6556 Cherry pick of #6524 onto release-1.11
  pkg/model/components/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6557 Cherry pick of #6551 onto release-1.11
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6554 Cherry pick of #6523 onto release-1.11
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/docker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
