Repository kubernetes/kops, pull requests merged in 2019-01, with the labels that each got.

#6270 Release notes for 1.11
  docs/releases/1.11-NOTES.md
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/L

#6281 fixed the sentence mistake
  docs/releases/1.8-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6263 update calico version to version 3.4.0
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6265 Remove duplicate Deployment for prometheus-operator
  addons/prometheus-operator/v0.26.0.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6262 Update aws-china.md
  docs/aws-china.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6293 Change jessie to stretch
  docs/releases/1.8-NOTES.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#6289 Included type in SSL certificate documentation
  docs/cluster_spec.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#6287 Update distroless
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6299 Create prow-postsubmit target for release candidates
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6300 Include windows build in distribution
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6312 Fix kubelet api admin
  upup/models/cloudup/resources/addons/rbac.addons.k8s.io/kubelet-api-admin.yaml
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6295 GCE terraform: map source tags in firewallrule
  tests/integration/update_cluster/ha_gce/kubernetes.tf
  upup/pkg/fi/cloudup/gcetasks/firewallrule.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6296 GCE terraform: support labels
  tests/integration/update_cluster/ha_gce/kubernetes.tf
  upup/pkg/fi/cloudup/gcetasks/disk.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6305 Add extra privilege to prometheus-k8s ClusterRole
  addons/prometheus-operator/v0.19.0.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6317 Kubelet API RBAC Manifest
  upup/models/cloudup/resources/addons/kubelet-api.rbac.addons.k8s.io/k8s-1.9.yaml
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6326 Upgrading coredns version to 1.3.0
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6257 Release 1.12.0-alpha.1
  Makefile
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
  version.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6328 Fix prow-postsubmit by copying prebuilt archive in bazel
  Makefile
  WORKSPACE
  images/utils-builder/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/M

#6338 include docker 18.06.1 missed dependency
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6226 Fix alternative AWS partitions in custom instance profiles
  Gopkg.lock
  pkg/apis/kops/validation/BUILD.bazel
  pkg/apis/kops/validation/instancegroup.go
  pkg/apis/kops/validation/instancegroup_test.go
  vendor/github.com/aws/aws-sdk-go/aws/arn/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/aws/arn/arn.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6297 AWS: Enable ICMP Type 3 Code 4 for API server ELBs
  pkg/model/awsmodel/api_loadbalancer.go
  tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
  tests/integration/update_cluster/complex/kubernetes.tf
  tests/integration/update_cluster/existing_sg/kubernetes.tf
  tests/integration/update_cluster/private-shared-subnet/kubernetes.tf
  tests/integration/update_cluster/privatecalico/kubernetes.tf
  tests/integration/update_cluster/privatecanal/kubernetes.tf
  tests/integration/update_cluster/privatedns1/kubernetes.tf
  tests/integration/update_cluster/privatedns2/kubernetes.tf
  tests/integration/update_cluster/privateflannel/kubernetes.tf
  tests/integration/update_cluster/privatekopeio/kubernetes.tf
  tests/integration/update_cluster/privateweave/kubernetes.tf
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#6066 Additional Storage & Volume Mounting
  docs/instance_groups.md
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/context.go
  nodeup/pkg/model/hooks.go
  nodeup/pkg/model/protokube.go
  nodeup/pkg/model/volumes.go
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/validation/BUILD.bazel
  pkg/apis/kops/validation/instancegroup.go
  pkg/apis/kops/validation/legacy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/awsmodel/BUILD.bazel
  pkg/model/awsmodel/autoscalinggroup.go
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
  upup/pkg/fi/cloudup/awstasks/block_device_mappings.go
  upup/pkg/fi/cloudup/awstasks/ebsvolume.go
  upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
  upup/pkg/fi/nodeup/command.go
  upup/pkg/fi/nodeup/nodetasks/file.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#6396 Update upgrade.md
  docs/upgrade.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6301 minor grammar improvements to kops terraform docs
  docs/terraform.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6374 Docs: Drop last DrainAndValidateRollingUpdate note
  docs/changing_configuration.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6375 Allow users to set kubelet cpu-cfs-quota and cpu-cfs-quota-period flags
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6381 implement etcd status for openstack
  pkg/commands/status_discovery.go
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/status.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/L

#6382 remove using deviceowner when filtering existing routerinterfaces
  upup/pkg/fi/cloudup/openstacktasks/routerinterface.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/XS

#6383 ignore openstack managed volume tags
  upup/pkg/fi/cloudup/openstacktasks/volume.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/XS

#6232 kops version: Add --short flag, use it to get version in scripts
  cmd/kops/root.go
  cmd/kops/version.go
  docs/cli/kops_version.md
  docs/development/adding_a_feature.md
  docs/development/testing.md
  hack/dev-build.sh
  pkg/commands/BUILD.bazel
  pkg/commands/version.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6384 find sshkey resource when updating cluster
  pkg/resources/openstack/compute.go
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/keypair.go
  upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel
  upup/pkg/fi/cloudup/openstacktasks/sshkey.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/S

#6386 implement GetCloudGroups for openstack
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/server_group.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/openstack, size/M

#6387 minor fixes to openstack
  upup/pkg/fi/cloudup/openstacktasks/lbpool.go
  upup/pkg/fi/cloudup/openstacktasks/servergroup.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/S

#6388 fix openstack lb pool member logic
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/loadbalancer.go
  upup/pkg/fi/cloudup/openstacktasks/poolassociation.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/M

#6218 Support "egress: External" to avoid configuring networking
  cmd/kops/integration_test.go
  docs/cluster_spec.md
  docs/run_in_existing_vpc.md
  pkg/apis/kops/cluster.go
  pkg/apis/kops/validation/legacy.go
  pkg/model/network.go
  tests/integration/update_cluster/unmanaged/id_rsa.pub
  tests/integration/update_cluster/unmanaged/in-v1alpha2.yaml
  tests/integration/update_cluster/unmanaged/kubernetes.tf
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#6405 Bump alpha channels
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6406 Update bazel rules
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#6385 implement delete cluster for openstack
  pkg/resources/openstack/BUILD.bazel
  pkg/resources/openstack/compute.go
  pkg/resources/openstack/dns.go
  pkg/resources/openstack/instances.go
  pkg/resources/openstack/lb.go
  pkg/resources/openstack/network.go
  pkg/resources/openstack/networking.go
  pkg/resources/openstack/openstack.go
  pkg/resources/openstack/ports.go
  pkg/resources/openstack/securitygroups.go
  pkg/resources/openstack/servergroup.go
  pkg/resources/openstack/sshkey.go
  pkg/resources/openstack/volumes.go
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/instance.go
  upup/pkg/fi/cloudup/openstack/keypair.go
  upup/pkg/fi/cloudup/openstack/loadbalancer.go
  upup/pkg/fi/cloudup/openstack/network.go
  upup/pkg/fi/cloudup/openstack/port.go
  upup/pkg/fi/cloudup/openstack/router.go
  upup/pkg/fi/cloudup/openstack/security_group.go
  upup/pkg/fi/cloudup/openstack/server_group.go
  upup/pkg/fi/cloudup/openstack/subnet.go
  upup/pkg/fi/cloudup/openstack/volume.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/XXL
