Repository kubernetes/kops, pull requests merged in 2019-07, with the labels that each got.

#7191 Automated cherry pick of #6897: Add helpers to set the built-in pod priorities
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_controller_manager.go
  nodeup/pkg/model/kube_proxy.go
  nodeup/pkg/model/kube_scheduler.go
  pkg/kubemanifest/BUILD.bazel
  pkg/kubemanifest/priority.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  protokube/pkg/protokube/etcd_manifest.go
  protokube/tests/integration/build_etcd_manifest/main/etcd_env_vars.yaml
  protokube/tests/integration/build_etcd_manifest/main/non_tls.yaml
  protokube/tests/integration/build_etcd_manifest/main/tls.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#7192 Automated cherry pick of #6897: Add helpers to set the built-in pod priorities
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_controller_manager.go
  nodeup/pkg/model/kube_proxy.go
  nodeup/pkg/model/kube_scheduler.go
  pkg/kubemanifest/BUILD.bazel
  pkg/kubemanifest/priority.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  protokube/pkg/protokube/etcd_manifest.go
  protokube/tests/integration/build_etcd_manifest/main/etcd_env_vars.yaml
  protokube/tests/integration/build_etcd_manifest/main/non_tls.yaml
  protokube/tests/integration/build_etcd_manifest/main/tls.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#7207 Cherry pick of #7153 onto release 1.13
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/flagbuilder/buildflags_test.go
  upup/pkg/fi/cloudup/openstack/server_group.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7208 Cherry pick of #7153 onto release-1.14
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/flagbuilder/buildflags_test.go
  upup/pkg/fi/cloudup/openstack/server_group.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7224 Remove kube-proxy resource-container flag
  nodeup/pkg/model/kube_proxy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7217 Drop missing sources when building utils image
  images/utils-builder/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7218 goimports update
  Makefile
  hack/verify-goimports
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_controller_manager.go
  nodeup/pkg/model/kube_proxy_test.go
  nodeup/pkg/model/kube_scheduler.go
  nodeup/pkg/model/protokube.go
  pkg/model/components/etcdmanager/model.go
  util/pkg/proxy/proxy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7202 Add more debug info for when cluster path doesnt match
  pkg/client/simple/vfsclientset/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7206 Canal v3.7.4
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7051 Upgrade Calico to 3.7.2
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, area/networking, cncf-cla: yes, lgtm, ok-to-test, size/L

#7183 Spotinst: Ocean's Strategy object is optional
  upup/pkg/fi/cloudup/spotinsttasks/ocean.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7195 update instances list with make update-machine-types
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7178 Possibility to use OpenStack without lbaas (loadbalancer)
  cmd/kops/create_cluster.go
  docs/tutorial/openstack.md
  pkg/model/openstackmodel/servergroup.go
  pkg/resources/openstack/securitygroups.go
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/floatingip.go
  upup/pkg/fi/cloudup/openstack/instance.go
  upup/pkg/fi/cloudup/openstack/loadbalancer.go
  upup/pkg/fi/cloudup/openstacktasks/floatingip.go
Labels: approved, cncf-cla: yes, lgtm, sig/openstack, size/L

#7226 Automated cherry pick of #7223: Bumping calico for bugfixes.
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7225 Automated cherry pick of #7223: Bumping calico for bugfixes.
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7151 doc: support to debug kops-apiserver
  docs/api-server/README.md
  docs/kops-server/README.md
  docs/kops-server/kops-server.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7188 GCE tutorial markdown formatting
  docs/tutorial/gce.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7219 Make an actual deep-copy of the state
  protokube/pkg/gossip/mesh/state.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6897 Set priority for static pods
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_controller_manager.go
  nodeup/pkg/model/kube_proxy.go
  nodeup/pkg/model/kube_scheduler.go
  pkg/kubemanifest/BUILD.bazel
  pkg/kubemanifest/priority.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  protokube/pkg/protokube/etcd_manifest.go
  protokube/tests/integration/build_etcd_manifest/main/etcd_env_vars.yaml
  protokube/tests/integration/build_etcd_manifest/main/non_tls.yaml
  protokube/tests/integration/build_etcd_manifest/main/tls.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7230 Automated cherry pick of #7219: Make an actual deep-copy of the state
  protokube/pkg/gossip/mesh/state.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7231 Automated cherry pick of #7219: Make an actual deep-copy of the state
  protokube/pkg/gossip/mesh/state.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7232 Automated cherry pick of #7211: Use NodeAuthorizer config options instead of soely
  nodeup/pkg/model/node_authorizer.go
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7234 Automated cherry pick of #7211: Use NodeAuthorizer config options instead of soely
  nodeup/pkg/model/node_authorizer.go
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7233 Automated cherry pick of #7211: Use NodeAuthorizer config options instead of soely
  nodeup/pkg/model/node_authorizer.go
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7235 Automated cherry pick of #7219: Make an actual deep-copy of the state
  protokube/pkg/gossip/mesh/state.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7260 Allow setting Limit & Request for aws-iam-authenticator
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/L

#6811 Delete the function keyword to prevent shellcheck from failing
  hack/make-apimachinery.sh
  hack/make-gendocs.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7279 Cherry pick of #7182 onto release-1.13
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7278 Cherry-pick of #7051: Upgrade Calico to 3.7.2
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7276 Cherry pick of #7051 onto release-1.12
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7280 Cherry pick of #7182 onto release-1.14
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7268 Cherry pick of #7160 onto release-1.14
  pkg/commands/set_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7269 Cherry pick of #7160 onto release-1.13
  pkg/commands/set_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7275 Update canal to 3.6.4, for TTA-2019-002
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7271 Cherry pick of #6803 onto release-1.13
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7264 Cherry pick of #7077 onto release-1.14
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#7265 Cherry pick of #7109 onto release-1.14
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7277 Cherry-pick of #7051: Upgrade Calico to 3.7.2
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7266 Cherry pick of #7084 onto release-1.14
  docs/images.md
  nodeup/pkg/distros/distribution.go
  nodeup/pkg/distros/identify.go
  nodeup/pkg/model/context.go
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/etcd.go
  nodeup/pkg/model/kubelet.go
  nodeup/pkg/model/logrotate.go
  nodeup/pkg/model/update_service.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7267 Cherry pick of #7141 onto release-1.14
  upup/pkg/fi/cloudup/dns.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7270 Cherry pick of #6803 onto release-1.14
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7272 Cherry pick of #7202 onto release-1.14
  pkg/client/simple/vfsclientset/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7281 Cherry pick of #7260 onto release-1.14
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/L

#7249 Bumping calico to 3.7.4.
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7102 Use readinessProbe for weave-net instead of livenessProbe
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7248 Add some permissions to cluster-autoscaler clusterrole
  addons/cluster-autoscaler/v1.10.0.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7251 Spotinst: Rolling update always reports NeedsUpdate
  pkg/resources/spotinst/resources.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7283 Cherry pick of #7249 onto release-1.12
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7284 Cherry pick of #7249 onto release-1.13
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7273 Cherry pick of #7206: Canal v3.7.4
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7274 Cherry-pick of #7206: Canal v3.7.4
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7285 Cherry pick of #7249 onto release-1.14
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7256 Add documentation example for running Kops in a CI environment
  README.md
  docs/README.md
  docs/continuous_integration.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#7282 Calico -> 3.7.4 for older versions
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7221 [Issue-7148] Legacyetcd support for Digital Ocean
  docs/tutorial/digitalocean.md
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/model.go
  upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/dns.go
  upup/pkg/fi/cloudup/do/cloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7288 Stop .gitignoring all files named go-bindata
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7291 Create hack/update-expected.sh to update test output
  hack/update-expected.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#7185 replace behavior for @aws hostnameOverride
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/context.go
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7293 Update DigitalOcean CCM to v0.1.16
  upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7296 Cherry pick of #7185 onto release-1.13
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/context.go
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7297 Cherry pick of #7185 onto release-1.14
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/context.go
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7289 Replace use of cmdutil IsFilenameSliceEmpty
  cmd/kops/create.go
  cmd/kops/delete.go
  cmd/kops/replace.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6229 GCE: support ipalias networking mode, named "gce"
  cmd/kops/create_cluster.go
  nodeup/pkg/model/network.go
  pkg/apis/kops/cluster.go
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/validation/legacy.go
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/components/context.go
  pkg/model/components/kubecontrollermanager.go
  pkg/model/components/networking.go
  pkg/model/gcemodel/autoscalinggroup.go
  pkg/model/gcemodel/context.go
  pkg/model/gcemodel/firewall.go
  pkg/model/gcemodel/network.go
  pkg/resources/gce/gce.go
  upup/pkg/fi/cloudup/defaults.go
  upup/pkg/fi/cloudup/gce/BUILD.bazel
  upup/pkg/fi/cloudup/gce/network.go
  upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
  upup/pkg/fi/cloudup/gcetasks/subnet.go
  upup/pkg/fi/cloudup/networking.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, sig/gcp, size/XL

#7300 Machine types fix
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7133 Improve channel updates
  channels/pkg/api/channel.go
  channels/pkg/channels/addon.go
  channels/pkg/channels/addons_test.go
  channels/pkg/channels/channel_version.go
  docs/addon_manager.md
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
  upup/pkg/fi/utils/BUILD.bazel
  upup/pkg/fi/utils/hash.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7301 Automated cherry pick of #7300: Fix m5a.8xlarge and i3en.metal has been removed
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7302 Automated cherry pick of #7300: Fix m5a.8xlarge and i3en.metal has been removed
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7290 Rationalize golden-output comparison
  cmd/kops/BUILD.bazel
  cmd/kops/create_cluster_integration_test.go
  cmd/kops/integration_test.go
  hack/update-expected.sh
  nodeup/pkg/model/tests/kubelet/featuregates/tasks.yaml
  pkg/model/BUILD.bazel
  pkg/model/bootstrapscript_test.go
  pkg/testutils/modelharness.go
  tests/integration/update_cluster/additional_user-data/cloudformation.json
  tests/integration/update_cluster/mixed_instances/cloudformation.json
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json
  upup/pkg/fi/cloudup/BUILD.bazel
  upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7305 Cherry Pick #7133 to release 1.14
  channels/pkg/api/channel.go
  channels/pkg/channels/addon.go
  channels/pkg/channels/addons_test.go
  channels/pkg/channels/channel_version.go
  docs/addon_manager.md
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
  upup/pkg/fi/utils/BUILD.bazel
  upup/pkg/fi/utils/hash.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7308 Automated cherry pick of #7185: Replace behavior for aws hostnameOverride
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/context.go
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7311 hack/update-expected: regenerate gobindata
  hack/update-expected.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7313 Add me as reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7257 Update Calico to v3.8.0
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7312 Manifest hashing: move trimming out of hash function
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/utils/hash.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7292 Adding documentation to mitigate workload outages on AWS
  docs/etcd3-migration.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6874 Mount FlexVolume directory in kube-controller-manager pod
  nodeup/pkg/model/kube_controller_manager.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7324 remove code: remove kops-server chart
  charts/kops/Chart.yaml
  charts/kops/templates/kops-api-server-deployment.yaml
  charts/kops/templates/kops-etcd-deployment.yaml
  charts/kops/values.yaml
  docs/kops-server/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7329 Cherry pick of #7282 onto release-1.12
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7330 Cherry pick of #7282 onto release-1.13
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7331 Cherry pick of #7282 onto release-1.14
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7332 Cherry pick of #7312 onto release-1.14
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/utils/hash.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7338 Bump alpha channel with latest kubernetes versions
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/S

#7341 Default etcd-version to 3.3.10 for >= 1.14
  pkg/model/components/etcd.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7340 Warn/prevent if the version of etcd is unsupported with etcd-manager
  pkg/featureflag/featureflag.go
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/options.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7335 Update Image version and RBAC for Citrix Ingress Controller
  addons/ingress-citrix/v1.1.1-aws.yaml
  addons/ingress-citrix/v1.1.1.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7337 Promote k8s 1.12.9 from alpha -> stable
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/XS
