Repository kubernetes/kops, pull requests merged in 2019-11, with the labels that each got.

#7857 Remove extraneous document separator causing failures applying addons
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7846 docs(addons): fix broken links
  README-ES.md
  README.md
  addons/README.md
  addons/ingress-citrix/README.md
  cmd/kops/update_cluster.go
  docs/README.md
  docs/examples/kops-test-route53-subdomain.md
  docs/operations/addons.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/M

#7869 Fix extraneous whitespace in warning message
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7847 Revert "Upgrade Amazon VPC CNI plugin to 1.5.4"
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha2/networking.go
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7874 mark weavenet-pod as system-critical
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7881 increase retry count
  upup/pkg/fi/cloudup/openstack/instance.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7868 awsup: fix shadowed var when looking for etcd cluster name
  upup/pkg/fi/cloudup/awsup/status.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7886 Automated cherry pick of #7885: Add back calico metrics options:
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7885 Add back calico metrics options
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7887 Fix kops upgrade cluster link
  docs/operations/cluster_upgrades_and_migrations.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7877 Automated cherry pick of #7857: Remove extraneous document separator causing failures
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7850 Alicloud: remove unnecessary if when evaluateHostnameOverride
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7852 Alicloud: split ProviderID with "."
  pkg/cloudinstances/cloud_instance_group.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7867 Fix behavior of mock DescribeAutoScalingGroups when no names supplied
  cloudmock/aws/mockautoscaling/group.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7884 Update "Guide" links for DigitalOcean & OpenStack
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7697 Add ci postsubmit script for pushing images to staging
  ci/postsubmit/push-to-staging/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7791 remove the unnecessary break
  pkg/model/spotinstmodel/instance_group.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7838 [DO-7442] Add gossip cluster implementation for Digital Ocean cloud provider
  hack/.packages
  nodeup/pkg/model/protokube.go
  pkg/model/domodel/droplets.go
  pkg/resources/digitalocean/resources.go
  protokube/cmd/protokube/main.go
  protokube/pkg/gossip/do/BUILD.bazel
  protokube/pkg/gossip/do/seeds.go
  protokube/pkg/protokube/BUILD.bazel
  protokube/pkg/protokube/do_volume.go
  upup/pkg/fi/cloudup/do/cloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7841 fix-up static-check
  nodeup/pkg/model/cloudconfig.go
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_proxy.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7888 remove myself from OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7863 Cleanup make targets
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#7854 fix golint failures
  channels/pkg/channels/channel_version.go
  cloudmock/aws/mockroute53/records.go
  cmd/kops/create.go
  cmd/kops/upgrade_cluster.go
  cmd/kops/validate_cluster.go
  pkg/acls/s3/storage.go
  pkg/apis/kops/channel.go
  pkg/cloudinstances/cloud_instance_group.go
  pkg/instancegroups/instancegroups.go
  pkg/model/alimodel/scalinggroup.go
  pkg/pki/certificate.go
  pkg/resources/ali/ali.go
  pkg/util/stringorslice/stringorslice.go
  protokube/pkg/gossip/mesh/peer.go
  protokube/pkg/protokube/aws_volume.go
  protokube/pkg/protokube/volume_mounter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7892 Recommend kops 1.11.1
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7839 fix-up staticcheck problems
  node-authorizer/cmd/node-authorizer/server.go
  node-authorizer/pkg/authorizers/aws/verifier.go
  node-authorizer/pkg/server/admission.go
  upup/pkg/fi/cloudup/alitasks/vpc.go
  upup/pkg/fi/cloudup/aliup/ali_cloud.go
  upup/pkg/fi/cloudup/awstasks/helper.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7735 Add hint how to determine mount path of etcd data
  docs/single-to-multi-master.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7893 stable channel: promote default AMIs from alpha -> stable
  channels/stable
  tests/integration/create_cluster/minimal/expected-v1alpha1.yaml
  tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_vpc/expected-v1alpha1.yaml
  tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7895 Release notes for 1.14.1
  docs/development/release.md
  docs/releases/1.14-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7896 Add release notes for 1.16.0-alpha.1
  docs/releases/1.16-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#7891 stable channel: promote kubernetes 1.13.12, 1.14.8 etc
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/S

#7872 Don't update first node in instancegroup if cluster fails validation
  cmd/kops/rollingupdatecluster.go
  cmd/kops/validate_cluster.go
  pkg/instancegroups/BUILD.bazel
  pkg/instancegroups/instancegroups.go
  pkg/instancegroups/rollingupdate.go
  pkg/instancegroups/rollingupdate_test.go
  pkg/validation/validate_cluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7842 add missing priorityClassName to flannel DaemonSet
  upup/models/cloudup/resources/addons/networking.flannel/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7901 fix broken links
  docs/README.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/S

#7913 Automated cherry pick of #7842: Add missing priorityClassName to flannel DaemonSet
  upup/models/cloudup/resources/addons/networking.flannel/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7916 Fix rendering of the Node Authorizer template
  upup/models/cloudup/resources/addons/node-authorizer.addons.k8s.io/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/S

#7935 Fix fork bomb in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7936 Unhide docs make logging
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#7938 Upgrade AWS VPC CNI to 1.5.5
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha2/networking.go
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7922 Correct spelling mistakes
  upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
  upup/pkg/fi/cloudup/awstasks/subnet.go
  upup/pkg/fi/context.go
  upup/pkg/fi/nodeup/nodetasks/file.go
  upup/pkg/fi/nodeup/nodetasks/file_test.go
  upup/pkg/fi/utils/yaml.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7924 Fix flannel CNI version to use 0.2.0
  upup/models/cloudup/resources/addons/networking.flannel/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7937 Update vendoring documentation for go modules
  docs/development/vendoring.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#7939 Remove duplication and update release details
  docs/index.md
  docs/welcome/releases.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7439 Updated documentation on how to move from single to multi master
  docs/single-to-multi-master.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/M

#7860 Add support for newer Docker versions
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/docker_test.go
  pkg/model/components/docker.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#7942 Cherry pick of #7856 onto release-1.15
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7947 Machine types updates
  hack/machine_types/machine_types.go
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#7948 Automated cherry pick of #7947: Update for NA storage
  hack/machine_types/machine_types.go
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#7943 fix 404 urls in docs
  addons/kube-ingress-aws-controller/README.md
  docs/development/testing.md
  docs/networking.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#7949 Fix generation of documentation /sitemap.xml file
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7951 Cherry pick of #7860 onto release-1.15
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/docker_test.go
  pkg/model/components/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7950 Kops site link
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#7953 Fix netlify mixed content
  docs/apireference/build/node_modules/jquery.scrollto/README.md
  docs/apireference/build/node_modules/optimist/readme.markdown
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#7955 Fix goimports errors
  cmd/kops/rollingupdatecluster.go
  pkg/instancegroups/rollingupdate.go
  pkg/instancegroups/rollingupdate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7402 Upate Lyft CNI to v0.5.1
  docs/networking.md
  pkg/model/iam/iam_builder.go
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7962 Add relnotes for 1.16.0-alpha.2
  docs/releases/1.16-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7963 Bump version of alpha
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/S

#7964 Add relnotes for 1.15.0
  docs/releases/1.15-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7969 Update feature flag documentation
  docs/advanced/experimental.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#7941 Fix panic when ssh key not exists on digitalocean
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7973 Upgrade go to 1.13
  .travis.yml
  Makefile
  WORKSPACE
  docker/Dockerfile
  go.mod
  images/dns-controller-builder/Dockerfile
  images/protokube-builder/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#7899 Use correct values for CALICO_IPV4POOL_IPIP in Calico v3
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7982 Put kubernetes 1.17.0-beta.2 into channels
  channels/alpha
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/S

#7984 Update compatability matrix
  README.md
  docs/welcome/releases.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7983 Promote peter & ryan & zetaab to approvers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7910 upgrade the time api
  node-authorizer/cmd/node-authorizer/server.go
  upup/pkg/fi/executor.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7923 sysctls.go: Fix some comments
  nodeup/pkg/model/sysctls.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7987 Ignore devcontainer for vscode remote-containers
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7988 Dont run travis with Go 1.11
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7907 Change doc cross-references from absolute to relative links
  docs/authentication.md
  docs/cluster_spec.md
  docs/development/adding_a_feature.md
  docs/examples/coreos-kops-tests-multimaster.md
  docs/examples/kops-tests-private-net-bastion-host.md
  docs/labels.md
  docs/operations/images.md
  docs/releases/1.12-NOTES.md
  docs/single-to-multi-master.md
  docs/vsphere-dev.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/S

#7954 Correct link error:404
  upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7906 Update apiVersion in docs and tests
  docs/instance_groups.md
  nodeup/pkg/model/tests/dockerbuilder/skipinstall/cluster.yaml
  tests/integration/update_cluster/additional_cidr/in-v1alpha3.yaml
  tests/integration/update_cluster/api_elb_cross_zone/in-v1alpha2.yaml
  tests/integration/update_cluster/unmanaged/in-v1alpha2.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7926 [aws-iam-authenticator] Docs - Steps to disable DaemonSet Temporarily
  docs/authentication.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7979 Add indent template function and use it to fix KubeDNS.ExternalCoreFile rendering
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/BUILD.bazel
  upup/pkg/fi/cloudup/template_functions.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7995 Automated cherry pick of #7979: cloudup: Map sprig indent template function
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/BUILD.bazel
  upup/pkg/fi/cloudup/template_functions.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7894 fix golint failures
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/managed_zones_delete_call.go
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/managed_zones_get_call.go
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/managed_zones_list_call.go
  upup/pkg/fi/assettasks/copyfile.go
  upup/pkg/fi/clientset_castore.go
  upup/pkg/fi/files.go
  upup/pkg/fi/printers.go
  upup/pkg/fi/secrets/clientset_secretstore.go
  upup/pkg/fi/task.go
  upup/pkg/fi/vfs_castore.go
  upup/pkg/kutil/convert_kubeup_cluster.go
  util/pkg/vfs/s3context.go
  util/pkg/vfs/s3fs.go
  util/pkg/vfs/sshfs.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7961 [Issue-7870] kops controller support for digital ocean
  cmd/kops-controller/BUILD.bazel
  cmd/kops-controller/main.go
  hack/.packages
  pkg/model/domodel/droplets.go
  pkg/nodeidentity/do/BUILD.bazel
  pkg/nodeidentity/do/identify.go
  upup/pkg/fi/cloudup/do/cloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7997 cleanup whitespace in root.go
  cmd/kops/root.go
  docs/cli/kops.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7998 Run goimports from locked version in go.mod
  go.mod
  go.sum
  hack/update-goimports
  hack/verify-goimports
Labels: approved, cncf-cla: yes, lgtm, size/S

#8000 Remove note about 1.15 not being released
  docs/releases/1.15-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8004 fix(openstack): fix additional security groups on instance groups
  upup/pkg/fi/cloudup/openstacktasks/port.go
  upup/pkg/fi/cloudup/openstacktasks/port_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8005 DOCS: fix simple typo in readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7985 Release 1.17.0-alpha.1
  Makefile
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
  version.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8006 Release notes for 1.17.0-alpha.1
  docs/releases/1.17-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7424 Implementing audit dynamic configuration (#7392)
  docs/cluster_spec.md
  k8s/crds/kops.k8s.io_clusters.yaml
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_apiserver_test.go
  nodeup/pkg/model/tests/apiServer/auditDynamicConfiguration/cluster.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8008 Automated cherry pick of #8004 origin release 1.15: fix(openstack): fix additional security groups on instance groups
  upup/pkg/fi/cloudup/openstacktasks/port.go
  upup/pkg/fi/cloudup/openstacktasks/port_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#7996 Set bazel version
  .bazelversion
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7952 Add verify-gomod and verify-goimports to Travis job
  Makefile
  go.mod
  hack/verify-goimports
  tools.go
  vendor/golang.org/x/tools/cmd/goimports/BUILD.bazel
  vendor/golang.org/x/tools/cmd/goimports/doc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go
  vendor/golang.org/x/tools/go/analysis/analysis.go
  vendor/golang.org/x/tools/go/analysis/diagnostic.go
  vendor/golang.org/x/tools/go/analysis/diagnostic_experimental.go
  vendor/golang.org/x/tools/go/analysis/doc.go
  vendor/golang.org/x/tools/go/analysis/passes/inspect/inspect.go
  vendor/golang.org/x/tools/go/analysis/validate.go
  vendor/golang.org/x/tools/go/buildutil/overlay.go
  vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go
  vendor/golang.org/x/tools/go/internal/gcimporter/bimport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  vendor/golang.org/x/tools/go/packages/BUILD.bazel
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/go/packages/loadmode_string.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/types/objectpath/objectpath.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/BUILD.bazel
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/golang.org/x/tools/internal/module/BUILD.bazel
  vendor/golang.org/x/tools/internal/module/module.go
  vendor/golang.org/x/tools/internal/span/BUILD.bazel
  vendor/golang.org/x/tools/internal/span/parse.go
  vendor/golang.org/x/tools/internal/span/span.go
  vendor/golang.org/x/tools/internal/span/token.go
  vendor/golang.org/x/tools/internal/span/token111.go
  vendor/golang.org/x/tools/internal/span/token112.go
  vendor/golang.org/x/tools/internal/span/uri.go
  vendor/golang.org/x/tools/internal/span/utf16.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#8011 Alicloud: fix typo for listenerPort
  upup/pkg/fi/cloudup/alitasks/loadbalancerlistener.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8015 Alicloud: only private subnets need SNAT rule
  pkg/model/alimodel/network.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8012 Alicloud: use ID of EIP to compare
  upup/pkg/fi/cloudup/alitasks/eip_natgateway_association.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7904 Improve rolling update test coverage
  pkg/instancegroups/BUILD.bazel
  pkg/instancegroups/rollingupdate_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#7506 Add download link for etcd-manager-ctl, clarify restarting etcd
  docs/operations/etcd_backup_restore_encryption.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/S

#8023 Run goimports in make ci
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#8029 Alicloud: fix comparison failure for scalinggroup
  upup/pkg/fi/cloudup/alitasks/scalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8014 Alicloud: support internal api loadbalancer
  pkg/model/alimodel/api_loadbalancer.go
  pkg/model/alimodel/context.go
  upup/pkg/fi/cloudup/alitasks/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
