Repository kubernetes/kops, pull requests merged in 2019-08, with the labels that each got.

#7348 Update repo-infra and distroless for bazel fixes
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6958 Cross-Zone Load Balancing for API ELB
  cmd/kops/integration_test.go
  cmd/kops/update_cluster.go
  docs/cluster_spec.md
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/awsmodel/api_loadbalancer.go
  tests/integration/update_cluster/api_elb_cross_zone/id_rsa.pub
  tests/integration/update_cluster/api_elb_cross_zone/in-v1alpha2.yaml
  tests/integration/update_cluster/api_elb_cross_zone/kubernetes.tf
  tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
  tests/integration/update_cluster/complex/kubernetes.tf
  tests/integration/update_cluster/existing_sg/kubernetes.tf
  tests/integration/update_cluster/private-shared-subnet/kubernetes.tf
  tests/integration/update_cluster/privatecalico/kubernetes.tf
  tests/integration/update_cluster/privatecanal/kubernetes.tf
  tests/integration/update_cluster/privatedns1/kubernetes.tf
  tests/integration/update_cluster/privatedns2/kubernetes.tf
  tests/integration/update_cluster/privateflannel/kubernetes.tf
  tests/integration/update_cluster/privatekopeio/kubernetes.tf
  tests/integration/update_cluster/privateweave/kubernetes.tf
  tests/integration/update_cluster/unmanaged/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/loadbalancer_attributes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#7350 Cherry pick of #7341 onto release-1.14
  pkg/model/components/etcd.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7353 Cherry pick of #7340 onto release-1.13
  pkg/featureflag/featureflag.go
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/options.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7354 Cherry pick of #7340 onto release-1.14
  pkg/featureflag/featureflag.go
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/options.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7345 stop kubelet to prevent orphan containers
  hooks/nvidia-device-plugin/image/files/02-nvidia-docker.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7358 Cherry pick of #7221 onto release-1.14
  docs/tutorial/digitalocean.md
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/model.go
  upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/dns.go
  upup/pkg/fi/cloudup/do/cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7351 Cherry pick of #7341 onto release-1.13
  pkg/model/components/etcd.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7339 Update default flexvolumepath for COS
  nodeup/pkg/model/kube_controller_manager.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7343 Promote 1.12 image from alpha to stable
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7317 Update kube-router to 0.3.1
  upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7326 Enable scraping of weave metrics
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7349 Bump etcd-manager to 3.0.20190801
  pkg/model/components/etcd.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7344 Add mappings for Webhook authorization mode.
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/flagbuilder/buildflags_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7362 Cherry pick of #6958 onto release-1.14
  cmd/kops/integration_test.go
  cmd/kops/update_cluster.go
  docs/cluster_spec.md
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/awsmodel/api_loadbalancer.go
  tests/integration/update_cluster/api_elb_cross_zone/id_rsa.pub
  tests/integration/update_cluster/api_elb_cross_zone/in-v1alpha2.yaml
  tests/integration/update_cluster/api_elb_cross_zone/kubernetes.tf
  tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
  tests/integration/update_cluster/complex/kubernetes.tf
  tests/integration/update_cluster/existing_sg/kubernetes.tf
  tests/integration/update_cluster/private-shared-subnet/kubernetes.tf
  tests/integration/update_cluster/privatecalico/kubernetes.tf
  tests/integration/update_cluster/privatecanal/kubernetes.tf
  tests/integration/update_cluster/privatedns1/kubernetes.tf
  tests/integration/update_cluster/privatedns2/kubernetes.tf
  tests/integration/update_cluster/privateflannel/kubernetes.tf
  tests/integration/update_cluster/privatekopeio/kubernetes.tf
  tests/integration/update_cluster/privateweave/kubernetes.tf
  tests/integration/update_cluster/unmanaged/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/loadbalancer_attributes.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#7360 Cherry pick of #7292 onto release-1.14
  upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7363 Cherry pick of #7349 onto release-1.12
  pkg/model/components/etcd.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7364 Cherry pick of #7349 onto release-1.13
  pkg/model/components/etcd.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7365 Cherry pick of #7349 onto release-1.14
  pkg/model/components/etcd.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7366 Cherry pick of #7317 onto release-1.14
  upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7352 Cherry pick of #7340 onto release-1.12
  pkg/featureflag/featureflag.go
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/options.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7356 Cherry pick of #7102 onto release-1.14
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7355 Set and mount the correct volume plugin dir based on OS
  cmd/kops/update_cluster.go
  docs/cluster_spec.md
  nodeup/pkg/model/kube_controller_manager.go
  nodeup/pkg/model/kubelet.go
  nodeup/pkg/model/tests/kubelet/featuregates/tasks.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7368 Cherry pick of #7344 onto release-1.14
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/flagbuilder/buildflags_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7369 Cherry pick of #7326 onto release-1.14
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#7370 Don't default adding MIMEBOUNDARY headers when a mixed instances policy is set
  pkg/model/resources/nodeup.go
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7372 Add release notes for 1.13.0 beta.2 -> 1.13.0
  docs/releases/1.13-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7373 Release notes for 1.12.2 -> 1.12.3
  docs/releases/1.12-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7380 correct typo in output message
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7374 Remove extraneous note in 1.13 release notes
  docs/releases/1.13-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7382 protokube/gce_volume.go: error info correction
  protokube/pkg/protokube/gce_volume.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7394 cleanup: client.go error message words correction
  node-authorizer/pkg/client/client.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7412 awstasks: fix misspelled words in logging.
  upup/pkg/fi/cloudup/awstasks/instance_volume_attachment.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7408 Update Compatibility Table in Readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7346 Add maxPersistentVolumes to support the KUBE_MAX_PD_VOLS scheduler setting
  nodeup/pkg/model/kube_scheduler.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7403 add zetaab as reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7416 Cherry pick of #7346 onto release-1.14
  nodeup/pkg/model/kube_scheduler.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7417 Cherry pick of #7377 onto release-1.14
  pkg/bundle/builder.go
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_master-us-west-2a.masters.k8s-iam.us-west-2.td.priv_user_data
  tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_nodes.k8s-iam.us-west-2.td.priv_user_data
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/urls.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7418 Cherry pick of #7370 onto release-1.14
  pkg/model/resources/nodeup.go
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7377 Support mirroring for nodeup also
  pkg/bundle/builder.go
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_master-us-west-2a.masters.k8s-iam.us-west-2.td.priv_user_data
  tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_nodes.k8s-iam.us-west-2.td.priv_user_data
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/urls.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7400 Use Cluster Proportional Autoscaler for CoreDNS 1.12+
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7388 Upgrading k8s-srcdst to v0.2.2
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7395 add OpenStack etcd-manager support
  pkg/model/components/etcd.go
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  pkg/model/openstackmodel/firewall.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7426 Cherry pick of #7103 onto release-1.14
  hack/.packages
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/convenience.go
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_controller_manager.go
  nodeup/pkg/model/kube_scheduler.go
  nodeup/pkg/model/protokube.go
  util/pkg/proxy/BUILD.bazel
  util/pkg/proxy/proxy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7422 Bump k8s versions in alpha channel
  channels/alpha
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/S

#7421 Bump k8s versions in alpha channel
  channels/alpha
Labels: approved, cncf-cla: yes, size/XS

#7420 Update AMIs in alpha channels
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/S

#7428 cherrypick #7103 Egress proxy for etcd manager
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/model.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7387 skip verification when the file already installed
  hooks/nvidia-device-plugin/image/files/01-aws-nvidia-driver.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7425 cleanup: fix error message typos
  kube-discovery/cmd/kube-discovery/main.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#7419 Cherrypick etcd-manager support for openstack
  pkg/model/components/etcd.go
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  pkg/model/openstackmodel/firewall.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7441 fix Typo 'the the' -> 'the'
  cmd/kops/integration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7433 ali.go: cleanup error words in messages
  pkg/resources/ali/ali.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7437 promote k8s versions
  channels/alpha
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/S

#7430 Dont set ExperimentalCriticalPodAnnotation feature gate in k8s 1.16
  pkg/model/components/kubelet.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7440 fix typo "specifiction" -> "specification"
  protokube/tests/integration/build_etcd_manifest/integration_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7443 Add relnotes for 1.14.0-beta.1
  docs/development/release.md
  docs/releases/1.14-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7448 bash script: don't assume nodeup filename
  pkg/model/resources/nodeup.go
  pkg/model/tests/data/bootstrapscript_0.txt
  pkg/model/tests/data/bootstrapscript_1.txt
  pkg/model/tests/data/bootstrapscript_2.txt
  pkg/model/tests/data/bootstrapscript_3.txt
  pkg/model/tests/data/bootstrapscript_4.txt
  pkg/model/tests/data/bootstrapscript_5.txt
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#7434 Add doc for using custom CA
  docs/custom_ca.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7447 nodeup download should try all mirrors
  pkg/model/resources/nodeup.go
  pkg/model/tests/data/bootstrapscript_0.txt
  pkg/model/tests/data/bootstrapscript_1.txt
  pkg/model/tests/data/bootstrapscript_2.txt
  pkg/model/tests/data/bootstrapscript_3.txt
  pkg/model/tests/data/bootstrapscript_4.txt
  pkg/model/tests/data/bootstrapscript_5.txt
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_master-us-west-2a.masters.k8s-iam.us-west-2.td.priv_user_data
  tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_nodes.k8s-iam.us-west-2.td.priv_user_data
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#7449 Add nodeup to shipbot targets for release upload
  .shipbot.yaml
  Makefile
  docs/development/release.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7446 Update channel recommended versions for kops versions
  channels/alpha
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/S

#7451 fix typo "in ingards to" -> "in regard to"
  README.md
  docs/index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7454 Automated cherry pick of #7444: upgrade weave to 2.5.2 to address the issues in
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#7444 Update weave to 2.5.2
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7455 Cherry pick of #7448 onto release-1.14
  pkg/model/resources/nodeup.go
  pkg/model/tests/data/bootstrapscript_0.txt
  pkg/model/tests/data/bootstrapscript_1.txt
  pkg/model/tests/data/bootstrapscript_2.txt
  pkg/model/tests/data/bootstrapscript_3.txt
  pkg/model/tests/data/bootstrapscript_4.txt
  pkg/model/tests/data/bootstrapscript_5.txt
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#7456 Cherry pick of #7447 onto release-1.14
  pkg/model/resources/nodeup.go
  pkg/model/tests/data/bootstrapscript_0.txt
  pkg/model/tests/data/bootstrapscript_1.txt
  pkg/model/tests/data/bootstrapscript_2.txt
  pkg/model/tests/data/bootstrapscript_3.txt
  pkg/model/tests/data/bootstrapscript_4.txt
  pkg/model/tests/data/bootstrapscript_5.txt
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_master-us-west-2a.masters.k8s-iam.us-west-2.td.priv_user_data
  tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_nodes.k8s-iam.us-west-2.td.priv_user_data
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#7457 Cherry pick of #7449 onto release-1.14
  .shipbot.yaml
  Makefile
  docs/development/release.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7450 cloudformation tests: use standard file comparison
  cmd/kops/BUILD.bazel
  cmd/kops/integration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7461 Relnotes for 1.14.0-beta.2
  docs/releases/1.14-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7468 Look for sha256 and sha1 files for artifacts
  pkg/assets/BUILD.bazel
  pkg/assets/builder.go
  upup/pkg/fi/assettasks/copyfile.go
  upup/pkg/fi/cloudup/networking.go
  util/pkg/vfs/context.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7467 [Digital Ocean] DO-7442 upgrade godo client to latest version
  Gopkg.lock
  Gopkg.toml
  pkg/resources/digitalocean/dns/BUILD.bazel
  pkg/resources/digitalocean/dns/dns.go
  pkg/resources/digitalocean/dns/dns_test.go
  upup/pkg/fi/cloudup/dotasks/BUILD.bazel
  upup/pkg/fi/cloudup/dotasks/volume_test.go
  vendor/github.com/digitalocean/godo/.travis.yml
  vendor/github.com/digitalocean/godo/BUILD.bazel
  vendor/github.com/digitalocean/godo/CHANGELOG.md
  vendor/github.com/digitalocean/godo/CONTRIBUTING.md
  vendor/github.com/digitalocean/godo/README.md
  vendor/github.com/digitalocean/godo/account.go
  vendor/github.com/digitalocean/godo/action.go
  vendor/github.com/digitalocean/godo/cdn.go
  vendor/github.com/digitalocean/godo/certificates.go
  vendor/github.com/digitalocean/godo/context/BUILD.bazel
  vendor/github.com/digitalocean/godo/context/context.go
  vendor/github.com/digitalocean/godo/context/context_go17.go
  vendor/github.com/digitalocean/godo/context/context_pre_go17.go
  vendor/github.com/digitalocean/godo/databases.go
  vendor/github.com/digitalocean/godo/doc.go
  vendor/github.com/digitalocean/godo/domains.go
  vendor/github.com/digitalocean/godo/droplet_actions.go
  vendor/github.com/digitalocean/godo/droplets.go
  vendor/github.com/digitalocean/godo/firewalls.go
  vendor/github.com/digitalocean/godo/floating_ips.go
  vendor/github.com/digitalocean/godo/floating_ips_actions.go
  vendor/github.com/digitalocean/godo/go.mod
  vendor/github.com/digitalocean/godo/go.sum
  vendor/github.com/digitalocean/godo/godo.go
  vendor/github.com/digitalocean/godo/image_actions.go
  vendor/github.com/digitalocean/godo/images.go
  vendor/github.com/digitalocean/godo/keys.go
  vendor/github.com/digitalocean/godo/kubernetes.go
  vendor/github.com/digitalocean/godo/links.go
  vendor/github.com/digitalocean/godo/load_balancers.go
  vendor/github.com/digitalocean/godo/projects.go
  vendor/github.com/digitalocean/godo/regions.go
  vendor/github.com/digitalocean/godo/sizes.go
  vendor/github.com/digitalocean/godo/snapshots.go
  vendor/github.com/digitalocean/godo/storage.go
  vendor/github.com/digitalocean/godo/storage_actions.go
  vendor/github.com/digitalocean/godo/strings.go
  vendor/github.com/digitalocean/godo/tags.go
  vendor/github.com/digitalocean/godo/vpcs.go
  vendor/github.com/docker/spdystream/connection.go
  vendor/github.com/docker/spdystream/handlers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#7464 Fix Flatcar distro
  upup/pkg/fi/nodeup/nodetasks/service.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#7462 fix typo "new" -> "newer"
  README.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7465 print all failure messages
  pkg/instancegroups/instancegroups.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7435 [DO-7148] Digital Ocean support for etcd-manager
  docs/tutorial/digitalocean.md
  pkg/model/components/etcdmanager/model.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7483 util/pkg/vfs: Fix swallowed errors
  util/pkg/vfs/sshfs.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7485 Set GOPROXY in travis builds
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7481 Allow configure ip to ip mode in calico
  go.sum
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/S

#7460 Add exec-opts options to dockerconfig
  pkg/apis/kops/dockerconfig.go
  pkg/apis/kops/v1alpha1/dockerconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/dockerconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7488 move OpenStack from alpha to beta
  README.md
  cmd/kops/create_cluster.go
  docs/cli/kops_create_cluster.md
  docs/tutorial/openstack.md
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7429 Add support for netExtraArgs
  docs/networking.md
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7491 Cleanup versions, deprecate kops 1.10, remove k8s 1.8
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm

#7498 Create verify-gomod script
  Makefile
  go.mod
  hack/verify-gomod
Labels: approved, cncf-cla: yes, lgtm, size/M

#7499 Update to golang 1.12.9
  WORKSPACE
  tools/bazel.rc
Labels: approved, cncf-cla: yes, lgtm, size/S

#7495 Corrected spelling of 'we' in the documentation
  docs/examples/kops-tests-private-net-bastion-host.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
