Repository kubernetes/kops, pull requests merged in 2019-10, with the labels that each got.

#7714 Update DigitalOcean CCM to v0.1.20
  upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7695 Automated cherry pick of #7474: Change Cilium templates to standalone version
  docs/networking.md
  k8s/crds/kops_v1alpha2_cluster.yaml
  k8s/crds/kops_v1alpha2_instancegroup.yaml
  nodeup/pkg/model/network.go
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/validation/legacy.go
  pkg/model/firewall.go
  pkg/model/iam/iam_builder.go
  pkg/model/openstackmodel/firewall.go
  pkg/model/pki.go
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#7716 Automated cherry pick of #7714: Update DigitalOcean CCM to v0.1.20
  upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7718 Automated cherry pick of #7646: Fix Cilium addon version
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7719 Automated cherry pick of #7694: Add calico 3.9.1
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7720 Automated cherry pick of #7663: Fix some staticcheck warnings
  nodeup/pkg/model/context.go
  pkg/apis/kops/validation/gce.go
  protokube/cmd/protokube/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7721 Automated cherry pick of #7020: Add arg min-port=1024 to dnsmasq container in kube-dns
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7560 ineffectual assignment to
  util/pkg/ui/user.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7715 remove duplicated entry in notes
  docs/releases/1.14-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7709 docs: fix spelling mistakes
  docs/apireference/build/documents/_generated_cluster_v1alpha2_kops_concept.md
  docs/apireference/build/documents/_generated_clustersubnetspec_v1alpha2_kops_definition.md
  docs/apireference/build/documents/_generated_instancegroup_v1alpha2_kops_concept.md
  docs/apireference/build/scroll.js
  docs/continuous_integration.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7722 Automated cherry pick of #7378: Add artifacts.k8s.io to mirror list
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
  upup/pkg/fi/cloudup/urls.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7717 Docs: Adding a doc on how to propose a cherry-pick
  docs/development/proposing-a-cherry-pick.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7725 relnotes for 1.14.0
  docs/releases/1.14-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7724 bazel: fix hashes rule to generate outputs
  Makefile
  tools/hashes.bzl
Labels: approved, cncf-cla: yes, lgtm, size/S

#7729 remove the repeat word in docs/authentication.md b/docs/authentication.md
  docs/authentication.md
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7734 Rollback alpha channels 1.14.7
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7652 Openstack block device mapping support
  docs/instance_groups.md
  pkg/model/openstackmodel/servergroup.go
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/image.go
  upup/pkg/fi/cloudup/openstack/instance.go
  upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel
  upup/pkg/fi/cloudup/openstacktasks/instance.go
  vendor/github.com/gophercloud/gophercloud/internal/BUILD.bazel
  vendor/github.com/gophercloud/gophercloud/internal/pkg.go
  vendor/github.com/gophercloud/gophercloud/internal/util.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/BUILD.bazel
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/BUILD.bazel
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/types.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/urls.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#7746 Cherry pick of #7477 onto release-1.13
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7727 Upgrade bazel's rules_go and rules_docker
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#7745 simplfy code
  dnsprovider/pkg/dnsprovider/providers/openstack/designate/rrchangeset.go
  pkg/resources/aws/aws.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
  upup/pkg/fi/cloudup/awsup/status.go
  upup/pkg/fi/executor.go
  upup/pkg/fi/nodeup/nodetasks/archive.go
  upup/pkg/fi/nodeup/nodetasks/bindmount.go
  upup/pkg/fi/nodeup/nodetasks/file.go
  upup/pkg/fi/nodeup/nodetasks/mount_disk.go
  util/pkg/reflectutils/print.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7747 Cherry pick of #7477 onto release-1.14
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7744 fix-up some staticcheck error
  dnsprovider/pkg/dnsprovider/providers/openstack/designate/designate.go
  nodeup/pkg/model/context.go
  pkg/model/openstackmodel/servergroup.go
  upup/pkg/fi/cloudup/alitasks/loadbalancerwhitelist.go
  upup/pkg/fi/cloudup/alitasks/securitygrouprule.go
  util/pkg/maps/maps.go
  util/pkg/reflectutils/walk.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7751 nodeup download: try to use compression
  pkg/model/resources/nodeup.go
  pkg/model/tests/data/bootstrapscript_0.txt
  pkg/model/tests/data/bootstrapscript_1.txt
  pkg/model/tests/data/bootstrapscript_2.txt
  pkg/model/tests/data/bootstrapscript_3.txt
  pkg/model/tests/data/bootstrapscript_4.txt
  pkg/model/tests/data/bootstrapscript_5.txt
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#7756 Add optional RBE support for kops
  WORKSPACE
  images/BUILD.bazel
  tools/bazel.rc
Labels: approved, cncf-cla: yes, lgtm, size/M

#7757 Update readme for 1.14
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7758 Add a BAZEL_CONFIG Makefile arg to bazel commands
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#7771 bazel: comment out shallow_since as fails to build with bazel 1.0
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7692 Kops controller support for OpenStack
  Makefile
  cmd/kops-controller/BUILD.bazel
  cmd/kops-controller/main.go
  hack/.packages
  pkg/nodeidentity/openstack/BUILD.bazel
  pkg/nodeidentity/openstack/identify.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7398 Upgrade Amazon VPC CNI plugin to 1.5.4
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha2/networking.go
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7728 Add documentation for updating CRDs when making API changes
  docs/development/api_updates.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7539 Kubelet configuration: Maximum pods flag is miscalculated when using Amazon VPC CNI
  nodeup/pkg/model/kubelet.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7487 Add event ttl flag
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/flagbuilder/buildflags_test.go
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, ok-to-test, size/M

#7750 docs: document state store configuration
  docs/state.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/L

#7378 Add artifacts.k8s.io to mirror list
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
  upup/pkg/fi/cloudup/urls.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7754 fix-up gosimple check error
  cloudmock/aws/mockec2/securitygroups.go
  dnsprovider/pkg/dnsprovider/providers/aws/route53/stubs/route53api.go
  hack/machine_types/machine_types.go
  nodeup/pkg/model/kubelet.go
  pkg/model/awsmodel/autoscalinggroup.go
  pkg/resources/ali/ali.go
  pkg/resources/aws/aws.go
  pkg/resources/ops/delete.go
  protokube/pkg/protokube/gossipdns.go
  upup/pkg/fi/cloudup/gcetasks/instance.go
  upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7755 fix-up staticcheck error
  dnsprovider/pkg/dnsprovider/providers/openstack/designate/rrchangeset.go
  nodeup/pkg/model/context.go
  pkg/kubemanifest/visitor.go
  pkg/model/components/kubelet.go
  pkg/model/context.go
  pkg/resources/aws/aws.go
  protokube/pkg/protokube/etcd_manifest.go
  upup/pkg/fi/cloudup/gce/op.go
  upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go
  upup/pkg/fi/cloudup/terraform/hcl_printer.go
  upup/pkg/fi/utils/sanitize.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7760 remove the unnecessary newline and unused vars
  channels/pkg/channels/addon.go
  dnsprovider/pkg/dnsprovider/dns_test.go
  pkg/apis/kops/util/versions_test.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/external_access.go
  protokube/pkg/gossip/mesh/gossip.go
  protokube/pkg/protokube/do_volume.go
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7777 Upload dns-controller archive, use in KOPS_BASE_URL
  Makefile
  dns-controller/cmd/dns-controller/BUILD.bazel
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7774 Move kops-controller to use a yaml configuration file
  cmd/kops-controller/BUILD.bazel
  cmd/kops-controller/main.go
  cmd/kops-controller/pkg/config/BUILD.bazel
  cmd/kops-controller/pkg/config/options.go
  go.mod
  hack/.packages
  upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/BUILD.bazel
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/template_functions.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#7784 Automated cherry pick of #7398: Upgrade Amazon VPC CNI plugin to 1.5.4
  k8s/crds/kops_v1alpha2_cluster.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha2/networking.go
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7786 Automated cherry pick of #7487: Add Event TTL flag
  k8s/crds/kops_v1alpha2_cluster.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/flagbuilder/buildflags_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7785 Automated cherry pick of #7539: fix(nodeup): miscalculated `max-pods` when using
  nodeup/pkg/model/kubelet.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7781 fix(apiserver): allow multiple service-account-key-file
  nodeup/pkg/model/kube_apiserver_test.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7787 Automated cherry pick of #7781: fix(apiserver): allow multiple service-account-key-file
  nodeup/pkg/model/kube_apiserver_test.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7783 Move kops-controller to daemonset
  cmd/kops-controller/main.go
  upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#7778 Change default port for memberlist from 3997
  dns-controller/cmd/dns-controller/BUILD.bazel
  dns-controller/cmd/dns-controller/main.go
  docs/development/ports.md
  hack/.packages
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/model.go
  pkg/model/openstackmodel/BUILD.bazel
  pkg/model/openstackmodel/firewall.go
  pkg/wellknownports/BUILD.bazel
  pkg/wellknownports/wellknownports.go
  protokube/cmd/protokube/BUILD.bazel
  protokube/cmd/protokube/main.go
  upup/pkg/fi/cloudup/BUILD.bazel
  upup/pkg/fi/cloudup/template_functions.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7788 Automated cherry pick of #7649 origin release 1.15
  pkg/model/openstackmodel/servergroup.go
  pkg/model/openstackmodel/servergroup_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7779 bazel: remove deprecated stamp attribute from container building
  images/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7795 Promote alpha to stable, bump alpha
  channels/alpha
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/S

#7811 Upgrade go version to 1.12.11
  Makefile
  WORKSPACE
  docker/Dockerfile
  images/dns-controller-builder/Dockerfile
  images/protokube-builder/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#7809 Cherry-pick #7807 to release-1.15
  upup/pkg/fi/cloudup/openstacktasks/port.go
  upup/pkg/fi/cloudup/openstacktasks/port_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#7798 Rename upload command variable in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7793 fix-up bug in nodeup/pkg/model
  nodeup/pkg/model/protokube.go
  upup/pkg/fi/cloudup/awstasks/elastic_ip.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7801 fix string trim func in main
  hack/machine_types/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7802 Alicloud: add OSS as upload dest
  Makefile
  hack/upload
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7804 Alicloud: fix status discovery
  pkg/commands/status_discovery.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7803 Alicloud: add hostname override
  pkg/model/components/kubelet.go
  pkg/model/components/kubeproxy.go
  upup/pkg/fi/nodeup/command.go
  util/pkg/vfs/context.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7814 Alicloud: fix error msg when check hostname
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7818 dnsprovider,nodeup: fix static check
  dnsprovider/pkg/dnsprovider/providers/aws/route53/route53_test.go
  dnsprovider/pkg/dnsprovider/providers/coredns/coredns_test.go
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/clouddns.go
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/file_assets.go
  nodeup/pkg/model/hooks.go
  nodeup/pkg/model/network.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7819 pkg: fix static check
  pkg/apis/kops/validation/instancegroup.go
  pkg/dns/gossip.go
  pkg/drain/cordon.go
  pkg/model/bootstrapscript.go
  pkg/model/gcemodel/autoscalinggroup.go
  pkg/model/spotinstmodel/instance_group.go
  pkg/resources/digitalocean/cloud.go
  pkg/resources/digitalocean/dns/dns.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7797 Add relnotes for 1.15.0-beta.1
  docs/releases/1.15-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7794 Allow for override of CoreDNS version
  docs/cluster_spec.md
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7823 Add netlify config
  Makefile
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7822 Update etcd-manager to 3.0.20191025
  pkg/model/components/etcd.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7826 Document eventTTL
  docs/cluster_spec.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/S

#7699 use existing network and subnet in OpenStack
  cmd/kops/BUILD.bazel
  cmd/kops/create_cluster.go
  docs/cli/kops_create_cluster.md
  docs/getting_started/openstack.md
  pkg/model/openstackmodel/context.go
  pkg/model/openstackmodel/network.go
  pkg/model/openstackmodel/servergroup.go
  pkg/model/openstackmodel/servergroup_test.go
  pkg/resources/openstack/lb.go
  pkg/resources/openstack/network.go
  pkg/resources/openstack/ports.go
  protokube/pkg/gossip/openstack/seeds.go
  protokube/pkg/protokube/openstack_volume.go
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/floatingip.go
  upup/pkg/fi/cloudup/openstack/network.go
  upup/pkg/fi/cloudup/openstack/subnet.go
  upup/pkg/fi/cloudup/openstacktasks/network.go
  upup/pkg/fi/cloudup/openstacktasks/port.go
  upup/pkg/fi/cloudup/openstacktasks/port_test.go
  upup/pkg/fi/cloudup/openstacktasks/subnet.go
  upup/pkg/fi/cloudup/utils.go
  upup/pkg/fi/values.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/BUILD.bazel
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/urls.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#7831 fix static check
  protokube/pkg/protokube/etcd_manifest.go
  upup/pkg/fi/nodeup/cloudinit/cloud_init_target.go
  util/pkg/reflectutils/walk.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7829 fix firewalls for OpenStack
  pkg/model/openstackmodel/firewall.go
  pkg/wellknownports/wellknownports.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#7773 Set default image for OpenStack CCM
  docs/getting_started/openstack.md
  upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.13.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/template_functions.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7835 allow protocol rules in master
  pkg/model/openstackmodel/firewall.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7834 Add protocol rules to master as well
  pkg/model/openstackmodel/firewall.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7836 Fix permalink
  permalinks/upgrade_k8s.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#7848 Automated cherry pick of #7847: Revert "Upgrade Amazon VPC CNI plugin to 1.5.4"
  k8s/crds/kops_v1alpha2_cluster.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha2/networking.go
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S
