Repository kubernetes/kops, pull requests merged in 2020-01, with the labels that each got.

#8254 Run Travis verifications in a separate parallel job
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8213 Automated cherry pick of #7832: cilium: don't try to mount sys/fs/bpf if already mounted
  nodeup/pkg/model/network.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8214 Automated cherry pick of #7832: cilium: don't try to mount sys/fs/bpf if already mounted
  nodeup/pkg/model/network.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8216 Adding ability to configure resources for weave (#8113)
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/parse_test.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/cluster.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8217 containerd: Fix tiny nits
  nodeup/pkg/model/containerd_test.go
  nodeup/pkg/model/docker_test.go
  nodeup/pkg/model/kubelet.go
  nodeup/pkg/model/node_authorizer.go
  nodeup/pkg/model/protokube.go
  nodeup/pkg/model/tests/kubelet/featuregates/cluster.yaml
  nodeup/pkg/model/tests/protokube/containerd/tasks.yaml
  upup/pkg/fi/nodeup/nodetasks/load_image.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7730 Custom sysctl Parameters
  docs/cluster_spec.md
  docs/instance_groups.md
  k8s/crds/kops.k8s.io_clusters.yaml
  k8s/crds/kops.k8s.io_instancegroups.yaml
  nodeup/pkg/model/sysctls.go
  pkg/apis/kops/cluster.go
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8258 Update mock kops version in integration tests
  cmd/kops/integration_test.go
  cmd/kops/lifecycle_integration_test.go
  pkg/resources/aws/vpc_test.go
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_master-us-west-2a.masters.k8s-iam.us-west-2.td.priv_user_data
  tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_nodes.k8s-iam.us-west-2.td.priv_user_data
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8263 Fix protokube osx build
  Makefile
  tools/gzip.bzl
  tools/sha1
  tools/sha256
Labels: approved, cncf-cla: yes, lgtm, size/S

#8243 Fix aws-china.md to download SHA-256 checksums for kops assets
  docs/aws-china.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, retest-not-required-docs-only, size/XS

#8266 Fix broken link
  docs/development/rolling_update.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8262 Exclude one Travis osx job
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8021 Support tainting all nodes needing update during rolling update
  pkg/instancegroups/BUILD.bazel
  pkg/instancegroups/instancegroups.go
  pkg/instancegroups/rollingupdate_test.go
Labels: approved, area/rolling-update, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#8261 Fix RollingUpdate behaviour when using LaunchTemplates for both kops & terraform spec updates
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8268 Refactor rolling update tests
  pkg/instancegroups/BUILD.bazel
  pkg/instancegroups/rollingupdate_test.go
Labels: approved, area/rolling-update, cncf-cla: yes, lgtm, ok-to-test, size/L

#8239 Simplify code for rolling updates of nodes
  pkg/instancegroups/instancegroups.go
  pkg/instancegroups/rollingupdate.go
Labels: approved, area/rolling-update, cncf-cla: yes, lgtm, ok-to-test, size/M

#8212 Move nodeup to /opt/kops/bin
  nodeup/pkg/model/firewall.go
  pkg/model/resources/nodeup.go
  pkg/model/tests/data/bootstrapscript_0.txt
  pkg/model/tests/data/bootstrapscript_1.txt
  pkg/model/tests/data/bootstrapscript_2.txt
  pkg/model/tests/data/bootstrapscript_3.txt
  pkg/model/tests/data/bootstrapscript_4.txt
  pkg/model/tests/data/bootstrapscript_5.txt
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#8196 For dev, don't preload docker images on nodes
  nodeup/pkg/model/protokube.go
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/nodeup/command.go
  upup/pkg/fi/nodeup/nodetasks/load_image.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7772 fixed yum proxy configuration
  pkg/model/bootstrapscript.go
  pkg/model/tests/data/bootstrapscript_0.txt
  pkg/model/tests/data/bootstrapscript_1.txt
  pkg/model/tests/data/bootstrapscript_2.txt
  pkg/model/tests/data/bootstrapscript_3.txt
  pkg/model/tests/data/bootstrapscript_4.txt
  pkg/model/tests/data/bootstrapscript_5.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7900 Use non-experimental version of encryption provider config flag in 1.13+
  k8s/crds/kops.k8s.io_clusters.yaml
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_apiserver_test.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7909 Remove DrainAndValidateRollingUpdate feature flag
  cmd/kops/rollingupdatecluster.go
  pkg/featureflag/featureflag.go
  pkg/instancegroups/BUILD.bazel
  pkg/instancegroups/instancegroups.go
  pkg/instancegroups/rollingupdate.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8253 staticcheck:modify the import package alias
  upup/pkg/fi/clientset_castore.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7914 Remove forcing disabled cgos Darwin
  cmd/kops/validate_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8269 Make /opt/kops writeable on COS
  nodeup/pkg/model/directories.go
  pkg/model/resources/nodeup.go
  pkg/model/tests/data/bootstrapscript_0.txt
  pkg/model/tests/data/bootstrapscript_1.txt
  pkg/model/tests/data/bootstrapscript_2.txt
  pkg/model/tests/data/bootstrapscript_3.txt
  pkg/model/tests/data/bootstrapscript_4.txt
  pkg/model/tests/data/bootstrapscript_5.txt
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
  upup/pkg/fi/nodeup/nodetasks/bindmount.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8277 Remove duplicated words
  docs/operations/addons.md
  pkg/drain/drain.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8270 nodeup: Add some dependencies for Service
  upup/pkg/fi/nodeup/nodetasks/service.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8278 Automated cherry pick of #8263: Replace binary "which" with build in "command"
  Makefile
  tools/gzip.bzl
  tools/sha1
  tools/sha256
Labels: approved, cncf-cla: yes, lgtm, size/S

#8279 Automated cherry pick of #8263: Replace binary "which" with build in "command"
  Makefile
  tools/gzip.bzl
  tools/sha1
  tools/sha256
Labels: approved, cncf-cla: yes, lgtm, size/S

#8283 containerd: Set a default version even with Kubernetes 1.17
  pkg/model/components/containerd.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8285 small documentation typo fixes
  docs/http_proxy.md
  docs/networking.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8288 Automated cherry pick of #7916: Fix rendering of the Node Authorizer template
  upup/models/cloudup/resources/addons/node-authorizer.addons.k8s.io/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/S

#8204 Enable host logging for kops-controller
  nodeup/pkg/model/logrotate.go
  upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/template_functions.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8303 Fix unit name for memory request for weave
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#8286 Add wget and nfs-utils deps needed for e2e tests
  nodeup/pkg/model/miscutils.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8302 Some Calico doc updates
  docs/calico-v3.md
  docs/networking.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/M

#8307 Remove "pigz" containerd dependency for RHEL/CentOS 7
  nodeup/pkg/model/containerd.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8247 Stabilize sequence of "export xx=xxx" statements
  pkg/model/bootstrapscript.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8193 upup/pkg/fi-fix staticcheck
  hack/.staticcheck_failures
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/awstasks/sshkey.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/loader.go
  upup/pkg/fi/cloudup/populate_cluster_spec.go
  upup/pkg/fi/executor.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8315 Build dns-controller using bazel
  Makefile
  images/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/M

#8317 Don't output empty sections in the manifests
  cmd/kops/BUILD.bazel
  cmd/kops/create_cluster_integration_test.go
  cmd/kops/integration_test.go
  hack/.packages
  pkg/assets/BUILD.bazel
  pkg/assets/builder.go
  pkg/assets/builder_test.go
  pkg/assets/testdata/emptysection.expected.yaml
  pkg/assets/testdata/emptysection.input.yaml
  pkg/kubemanifest/manifest.go
  pkg/model/BUILD.bazel
  pkg/model/bootstrapscript_test.go
  pkg/testutils/BUILD.bazel
  pkg/testutils/golden/BUILD.bazel
  pkg/testutils/golden/compare.go
  pkg/testutils/modelharness.go
  upup/pkg/fi/cloudup/BUILD.bazel
  upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8206 Automated cherry pick of #8176 and #8209: Add deprecation warning for older k8s versions
  permalinks/upgrade_k8s.md
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8208 Remove support for Kubernetes 1.8 and earlier
  permalinks/upgrade_k8s.md
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8284 Improve CIDR validation
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
  tests/integration/update_cluster/restrict_access/in-v1alpha2.yaml
  tests/integration/update_cluster/restrict_access/kubernetes.tf
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8273 Remove kops-controller deployment
  upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8319 Automated cherry pick of #8273: Remove kops-controller deployment
  upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8207 Automated cherry pick of #8176 and #8209: Add deprecation warning for older k8s versions
  permalinks/upgrade_k8s.md
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8321 Add release notes for deleting the kops-controller deployment
  docs/architecture/kops-controller.md
  docs/releases/1.16-NOTES.md
  docs/releases/1.17-NOTES.md
  docs/releases/1.18-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#8320 Automated cherry pick of #8273: Remove kops-controller deployment
  upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8324 Automated cherry pick of #8317: Don't output empty sections in the manifests
  cmd/kops/BUILD.bazel
  cmd/kops/create_cluster_integration_test.go
  cmd/kops/integration_test.go
  hack/.packages
  pkg/assets/BUILD.bazel
  pkg/assets/builder.go
  pkg/assets/builder_test.go
  pkg/assets/testdata/emptysection.expected.yaml
  pkg/assets/testdata/emptysection.input.yaml
  pkg/kubemanifest/manifest.go
  pkg/model/BUILD.bazel
  pkg/model/bootstrapscript_test.go
  pkg/testutils/BUILD.bazel
  pkg/testutils/golden/BUILD.bazel
  pkg/testutils/golden/compare.go
  pkg/testutils/modelharness.go
  upup/pkg/fi/cloudup/BUILD.bazel
  upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#7833 Use /opt/cni/bin on all distros (including COS)
  nodeup/pkg/model/context.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8245 Add unit test for func RenderInstanceGroupSubnets in instancegroup.go
  pkg/formatter/instancegroup_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8235 upup/pkg/fi/cloudup/awstasks/ staticcheck
  hack/.staticcheck_failures
  upup/pkg/kutil/import_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8334 Allow CoreDNS to be specified by create cluster overrides
  pkg/commands/set_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8331 Allow removed of additionalUserData on bastion
  cmd/kops/integration_test.go
  pkg/model/bootstrapscript.go
  tests/integration/update_cluster/private-shared-subnet/kubernetes.tf
  tests/integration/update_cluster/privatecalico/cloudformation.json
  tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/privatecalico/kubernetes.tf
  tests/integration/update_cluster/privatecanal/kubernetes.tf
  tests/integration/update_cluster/privatedns1/kubernetes.tf
  tests/integration/update_cluster/privatedns2/kubernetes.tf
  tests/integration/update_cluster/privateflannel/kubernetes.tf
  tests/integration/update_cluster/privatekopeio/kubernetes.tf
  tests/integration/update_cluster/privateweave/kubernetes.tf
  tests/integration/update_cluster/unmanaged/kubernetes.tf
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8337 docs(docs/operations) Adding more steps to etcd-manager restore operation to work properly
  docs/operations/etcd_backup_restore_encryption.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/M

#7096 Configuration to specify no SSH key
  cmd/kops/integration_test.go
  docs/cluster_spec.md
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/awsmodel/autoscalinggroup.go
  pkg/model/context.go
  pkg/model/names.go
  pkg/model/sshkey.go
  protokube/pkg/gossip/mesh/mesh.pb.go
  tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json
  tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/nosshkey-cloudformation/in-v1alpha2.yaml
  tests/integration/update_cluster/nosshkey/in-v1alpha2.yaml
  tests/integration/update_cluster/nosshkey/kubernetes.tf
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/awstasks/BUILD.bazel
  upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
  upup/pkg/fi/cloudup/awstasks/sshkey.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#8090 Cherry pick #7874 onto 1.15
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8327 Remove code for unsupported Kubernetes versions
  nodeup/pkg/model/context.go
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_controller_manager.go
  nodeup/pkg/model/kube_proxy.go
  nodeup/pkg/model/kubelet.go
  nodeup/pkg/model/kubelet_test.go
  nodeup/pkg/model/logrotate.go
  nodeup/pkg/model/network.go
  nodeup/pkg/model/protokube.go
  nodeup/pkg/model/secrets.go
  nodeup/pkg/model/tests/kubelet/featuregates/cluster.yaml
  nodeup/pkg/model/tests/kubelet/featuregates/tasks.yaml
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/validation/instancegroup.go
  pkg/apis/kops/validation/instancegroup_test.go
  pkg/apis/kops/validation/legacy.go
  pkg/model/components/apiserver.go
  pkg/model/components/docker.go
  pkg/model/components/kubecontrollermanager.go
  pkg/model/components/kubecontrollermanager_test.go
  pkg/model/components/kubelet.go
  pkg/model/components/kubelet_test.go
  pkg/model/components/kubescheduler.go
  pkg/model/components/kubescheduler_test.go
  pkg/model/components/networking.go
  pkg/model/context.go
  pkg/model/network.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
  upup/pkg/fi/cloudup/networking.go
  upup/pkg/fi/cloudup/networking_test.go
  upup/pkg/fi/cloudup/populatecluster_test.go
  upup/pkg/fi/cloudup/tagbuilder.go
  upup/pkg/fi/cloudup/tagbuilder_test.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/cluster.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/cluster.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#8339 Automated cherry pick of #7096: Add ability to specify no ssh key by setting sshKeyName to
  cmd/kops/integration_test.go
  docs/cluster_spec.md
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/awsmodel/autoscalinggroup.go
  pkg/model/context.go
  pkg/model/names.go
  pkg/model/sshkey.go
  protokube/pkg/gossip/mesh/mesh.pb.go
  tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json
  tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/nosshkey-cloudformation/in-v1alpha2.yaml
  tests/integration/update_cluster/nosshkey/in-v1alpha2.yaml
  tests/integration/update_cluster/nosshkey/kubernetes.tf
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/awstasks/BUILD.bazel
  upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
  upup/pkg/fi/cloudup/awstasks/sshkey.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#8341 Automated cherry pick of #8139: tests: increase timeout in rolling update tests
  pkg/instancegroups/rollingupdate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8345 Securing http link to https link
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8205 fix author nickName
  docs/releases/1.12-NOTES.md
  docs/releases/1.13-NOTES.md
  docs/releases/1.14-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8343 Fix crossbuild-nodeup-in-docker
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#8351 Automated cherry pick of #8343: Fix crossbuild-nodeup-in-docker
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8350 Update CentOS 7 AMI
  docs/operations/images.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#8353 Fix DNS loop on Ubuntu 18.04 (Bionic)
  nodeup/pkg/model/kubelet.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8265 Add support for weave.npcExtraArgs
  docs/networking.md
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/cluster.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8354 Make /opt/cni/bin writeable on COS
  nodeup/pkg/model/directories.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8342 Automated cherry pick of #7983: Promote peter & ryan & zetaab to approvers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8328 Add shellcheck verification
  Makefile
  hack/.shellcheck_failures
  hack/verify-shellcheck.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#7957 Update Terraform resource names to be 0.12 compatible.
  tests/integration/update_cluster/additional_cidr/kubernetes.tf
  tests/integration/update_cluster/api_elb_cross_zone/kubernetes.tf
  tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
  tests/integration/update_cluster/complex/kubernetes.tf
  tests/integration/update_cluster/existing_iam/kubernetes.tf
  tests/integration/update_cluster/existing_iam_cloudformation/kubernetes.tf
  tests/integration/update_cluster/existing_sg/kubernetes.tf
  tests/integration/update_cluster/externallb/kubernetes.tf
  tests/integration/update_cluster/ha/kubernetes.tf
  tests/integration/update_cluster/lifecycle_phases/network-kubernetes.tf
  tests/integration/update_cluster/minimal-141/kubernetes.tf
  tests/integration/update_cluster/minimal/kubernetes.tf
  tests/integration/update_cluster/mixed_instances/kubernetes.tf
  tests/integration/update_cluster/mixed_instances_spot/kubernetes.tf
  tests/integration/update_cluster/nosshkey/kubernetes.tf
  tests/integration/update_cluster/privatecalico/kubernetes.tf
  tests/integration/update_cluster/privatecanal/kubernetes.tf
  tests/integration/update_cluster/privatedns1/kubernetes.tf
  tests/integration/update_cluster/privatedns2/kubernetes.tf
  tests/integration/update_cluster/privateflannel/kubernetes.tf
  tests/integration/update_cluster/privatekopeio/kubernetes.tf
  tests/integration/update_cluster/privateweave/kubernetes.tf
  tests/integration/update_cluster/restrict_access/kubernetes.tf
  tests/integration/update_cluster/shared_vpc/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/route.go
  upup/pkg/fi/cloudup/awstasks/vpccidrblock.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8349 Add unit test for pkg/edit/edit.go
  pkg/edit/BUILD.bazel
  pkg/edit/edit_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8363 Automated cherry pick of #7957: Update terraform resource names to be 0.12 compatible.
  tests/integration/update_cluster/additional_cidr/kubernetes.tf
  tests/integration/update_cluster/api_elb_cross_zone/kubernetes.tf
  tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
  tests/integration/update_cluster/complex/kubernetes.tf
  tests/integration/update_cluster/existing_iam/kubernetes.tf
  tests/integration/update_cluster/existing_iam_cloudformation/kubernetes.tf
  tests/integration/update_cluster/existing_sg/kubernetes.tf
  tests/integration/update_cluster/externallb/kubernetes.tf
  tests/integration/update_cluster/ha/kubernetes.tf
  tests/integration/update_cluster/lifecycle_phases/network-kubernetes.tf
  tests/integration/update_cluster/minimal-141/kubernetes.tf
  tests/integration/update_cluster/minimal/kubernetes.tf
  tests/integration/update_cluster/mixed_instances/kubernetes.tf
  tests/integration/update_cluster/mixed_instances_spot/kubernetes.tf
  tests/integration/update_cluster/nosshkey/kubernetes.tf
  tests/integration/update_cluster/privatecalico/kubernetes.tf
  tests/integration/update_cluster/privatecanal/kubernetes.tf
  tests/integration/update_cluster/privatedns1/kubernetes.tf
  tests/integration/update_cluster/privatedns2/kubernetes.tf
  tests/integration/update_cluster/privateflannel/kubernetes.tf
  tests/integration/update_cluster/privatekopeio/kubernetes.tf
  tests/integration/update_cluster/privateweave/kubernetes.tf
  tests/integration/update_cluster/restrict_access/kubernetes.tf
  tests/integration/update_cluster/shared_vpc/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/route.go
  upup/pkg/fi/cloudup/awstasks/vpccidrblock.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8352 Automated cherry pick of #8343: Fix crossbuild-nodeup-in-docker
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8360 Test package versions as well as hashes
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/containerd_test.go
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/docker_test.go
  upup/pkg/fi/nodeup/nodetasks/package.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8361 Publish update AMIs into the alpha channel
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/S

#6465 Allow local filesystem state stores (to aid CI pull-request workflows)
  docs/state.md
  util/pkg/vfs/vfs.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8323 Automated cherry pick of #8321: Add release notes for deleting the kops-controller deployment
  docs/architecture/kops-controller.md
  docs/releases/1.16-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8364 Add release notes for terraform resource renaming
  docs/releases/1.17-NOTES.md
  docs/releases/1.18-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#8340 Automated cherry pick of #7096: Add ability to specify no ssh key by setting sshKeyName to
  cmd/kops/integration_test.go
  docs/cluster_spec.md
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/awsmodel/autoscalinggroup.go
  pkg/model/context.go
  pkg/model/names.go
  pkg/model/sshkey.go
  protokube/pkg/gossip/mesh/mesh.pb.go
  tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json
  tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/nosshkey-cloudformation/in-v1alpha2.yaml
  tests/integration/update_cluster/nosshkey/in-v1alpha2.yaml
  tests/integration/update_cluster/nosshkey/kubernetes.tf
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/awstasks/BUILD.bazel
  upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
  upup/pkg/fi/cloudup/awstasks/sshkey.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#8368 Add a warning when using file:// state store
  cmd/kops/util/factory.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8325 Automated cherry pick of #8317: Don't output empty sections in the manifests
  cmd/kops/BUILD.bazel
  cmd/kops/create_cluster_integration_test.go
  cmd/kops/integration_test.go
  hack/.packages
  pkg/assets/BUILD.bazel
  pkg/assets/builder.go
  pkg/assets/builder_test.go
  pkg/assets/testdata/emptysection.expected.yaml
  pkg/assets/testdata/emptysection.input.yaml
  pkg/kubemanifest/manifest.go
  pkg/model/BUILD.bazel
  pkg/model/bootstrapscript_test.go
  pkg/testutils/BUILD.bazel
  pkg/testutils/golden/BUILD.bazel
  pkg/testutils/golden/compare.go
  pkg/testutils/modelharness.go
  upup/pkg/fi/cloudup/BUILD.bazel
  upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8369 Automated cherry pick of #6465: Allow local filesystem state stores #8368: Add a warning when using file:// state store
  cmd/kops/util/factory.go
  docs/state.md
  util/pkg/vfs/vfs.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8282 Update default instance types for AWS
  docs/releases/1.18-NOTES.md
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8358 update docs: updating kops
  docs/operations/updates_and_upgrades.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8367 Update lyft CNI to v0.5.3
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8248 Fix issues with older versions of k8s for basic clusters
  docs/releases/1.18-NOTES.md
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8375 Automated cherry pick of #8248: Fix issues with older versions of k8s for basic clusters
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8376 Automated cherry pick of #8248: Fix issues with older versions of k8s for basic clusters
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8378 Backport the k8s 1.9 required action release note
  docs/releases/1.15-NOTES.md
  docs/releases/1.16-NOTES.md
  docs/releases/1.17-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8384 Automated cherry pick of #8378: Backport the k8s 1.9 required action release note
  docs/releases/1.15-NOTES.md
  docs/releases/1.16-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8385 Automated cherry pick of #8378: Backport the k8s 1.9 required action release note
  docs/releases/1.15-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8380 Change the deleted user to ghost
  docs/releases/1.13-NOTES.md
  docs/releases/1.14-NOTES.md
  docs/releases/1.15-NOTES.md
  docs/releases/1.9-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8379 Add Cilium.EnablePolicy back into templates
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#8366 Use IAMPrefix() for hostedzone
  pkg/model/iam/iam_builder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8386 Fix scheduler policy configmap args
  nodeup/pkg/model/kube_scheduler.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8395 Automated cherry pick of #8386: Fix scheduler policy configmap args
  nodeup/pkg/model/kube_scheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8389 Automated cherry pick of #8366: use IAMPrefix() for hostedzone
  pkg/model/iam/iam_builder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8394 Automated cherry pick of #8386: Fix scheduler policy configmap args
  nodeup/pkg/model/kube_scheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8326 Automated cherry pick of #8317: Don't output empty sections in the manifests
  cmd/kops/BUILD.bazel
  cmd/kops/create_cluster_integration_test.go
  cmd/kops/integration_test.go
  hack/.packages
  pkg/assets/BUILD.bazel
  pkg/assets/builder.go
  pkg/assets/builder_test.go
  pkg/assets/testdata/emptysection.expected.yaml
  pkg/assets/testdata/emptysection.input.yaml
  pkg/kubemanifest/manifest.go
  pkg/model/BUILD.bazel
  pkg/model/bootstrapscript_test.go
  pkg/testutils/BUILD.bazel
  pkg/testutils/golden/BUILD.bazel
  pkg/testutils/golden/compare.go
  pkg/testutils/modelharness.go
  upup/pkg/fi/cloudup/BUILD.bazel
  upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8392 Bump k8s versions in alpha and stable channels
  channels/alpha
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8390 Automated cherry pick of #8366: use IAMPrefix() for hostedzone
  pkg/model/iam/iam_builder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8387 Automated cherry pick of #8379: Add Cilium.EnablePolicy back into templates
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#8388 Automated cherry pick of #8379: Add Cilium.EnablePolicy back into templates
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#8145 Enabling JSON output for Terraform instead of writing the HCL syntax …
  cmd/kops/integration_test.go
  docs/advanced/experimental.md
  docs/terraform.md
  pkg/featureflag/featureflag.go
  tests/integration/update_cluster/minimal-json/id_rsa.pub
  tests/integration/update_cluster/minimal-json/in-v1alpha0.yaml
  tests/integration/update_cluster/minimal-json/kubernetes.tf.json
  upup/pkg/fi/cloudup/terraform/target.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#8410 Cherry pick of #8399 onto release-1.17
  pkg/model/components/etcd.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/options.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#8199 containerd: Add support for tar.gz package
  Makefile
  nodeup/pkg/distros/identify.go
  nodeup/pkg/model/containerd.go
  nodeup/pkg/model/convenience.go
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/miscutils.go
  nodeup/pkg/model/packages.go
  nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml
  upup/pkg/fi/nodeup/nodetasks/archive.go
  upup/pkg/fi/nodeup/nodetasks/package.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8333 CoreDNS default image bump to 1.6.6 to resolve CVE
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8399 Bump etcd-manager to 3.0.20200116 (#8310)
  pkg/model/components/etcd.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/options.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
  pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8318 Remove addons only applicable to unsupported versions of Kubernetes
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/pre-k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/pre-k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.flannel/pre-k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.kope.io/pre-k8s-1.6.yaml
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.8.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/pre-k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/pre-k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.8.0.yaml.template
  upup/models/cloudup/resources/addons/storage-aws.addons.k8s.io/v1.6.0.yaml
  upup/models/cloudup/resources/addons/storage-gce.addons.k8s.io/v1.6.0.yaml
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#8338 Don't load nonexistent calico-client cert when CNI is Cilium
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#8374 Edit author name
  docs/releases/1.9-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8411 Automated cherry pick of #8333: CoreDNS default image bump to 1.6.6
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8412 Automated cherry pick of #8333: CoreDNS default image bump to 1.6.6
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8415 Automated cherry pick of #8333: CoreDNS default image bump to 1.6.6
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8373 Kops releases - prefix git tags with v
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8407 Support additional kube-scheduler config parameters via config file
  hack/.packages
  k8s/crds/kops.k8s.io_clusters.yaml
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/kube_scheduler.go
  nodeup/pkg/model/kube_scheduler_test.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/configbuilder/BUILD.bazel
  pkg/configbuilder/buildconfigfile.go
  pkg/configbuilder/buildconfigfile_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8419 Automated cherry pick of #8338: Don't load nonexistent calico-client cert when CNI is Cilium
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8417 Automated cherry pick of #8338: Don't load nonexistent calico-client cert when CNI is Cilium
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8418 Automated cherry pick of #8338: Don't load nonexistent calico-client cert when CNI is Cilium
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8271 Option to increase concurrency of rolling update within instancegroup
  k8s/crds/kops.k8s.io_clusters.yaml
  k8s/crds/kops.k8s.io_instancegroups.yaml
  pkg/apis/kops/BUILD.bazel
  pkg/apis/kops/cluster.go
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha1/BUILD.bazel
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/BUILD.bazel
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/validation/BUILD.bazel
  pkg/apis/kops/validation/instancegroup.go
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/instancegroups/BUILD.bazel
  pkg/instancegroups/instancegroups.go
  pkg/instancegroups/rollingupdate_test.go
  pkg/instancegroups/settings.go
  pkg/instancegroups/settings_test.go
Labels: approved, area/rolling-update, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XXL

#8421 Automated cherry pick of #8373: Prefix git tags with `v`
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8420 Automated cherry pick of #8373: Prefix git tags with `v`
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8422 Automated cherry pick of #8373: Prefix git tags with `v`
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8427 Automated cherry pick of #7865: feat(api): DeleteOnTermination fields for volumes
  k8s/crds/kops.k8s.io_instancegroups.yaml
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/awsmodel/autoscalinggroup.go
  tests/integration/update_cluster/complex/cloudformation.json
  tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
  tests/integration/update_cluster/complex/in-v1alpha2.yaml
  tests/integration/update_cluster/complex/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7319 Fix template clusterName behavior
  cmd/kops/toolbox_template.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8426 Automated cherry pick of #7865: feat(api): DeleteOnTermination fields for volumes
  k8s/crds/kops.k8s.io_instancegroups.yaml
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/awsmodel/autoscalinggroup.go
  tests/integration/update_cluster/complex/cloudformation.json
  tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
  tests/integration/update_cluster/complex/in-v1alpha2.yaml
  tests/integration/update_cluster/complex/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8425 Update support for Amazon Linux 2
  nodeup/pkg/distros/distribution.go
  nodeup/pkg/distros/identify.go
  nodeup/pkg/model/containerd.go
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/packages.go
  pkg/model/components/containerd.go
  pkg/resources/aws/aws.go
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8064 Announce impending removal of v1alpha1 API
  docs/releases/1.16-NOTES.md
  docs/releases/1.17-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8016 Alicloud: etcd-manager support
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/model.go
  pkg/model/master_volumes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8429 Automated cherry pick of #8064: Announce removal of kops/v1alpha1 in kops 1.18
  docs/releases/1.16-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8430 Fixes regression in e2e tests
  nodeup/pkg/model/kube_scheduler.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8436 Automated cherry pick of #8016: Alicloud: etcd-manager support
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/model.go
  pkg/model/master_volumes.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8438 Release notes for 1.17.0-alpha.2
  docs/releases/1.17-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8200 Add missing priorityClassName for critical pods
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/authentication.kope.io/k8s-1.12.yaml
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.kope.io/k8s-1.12.yaml
  upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/node-authorizer.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.13.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
  upup/pkg/fi/cloudup/tests/manifests/k8s-1.13.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#8439 Cherry pick of #8200: Add missing priorityClassName for critical pods
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/authentication.kope.io/k8s-1.12.yaml
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.kope.io/k8s-1.12.yaml
  upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/node-authorizer.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.13.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
  upup/pkg/fi/cloudup/tests/manifests/k8s-1.13.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8440 Cherry pick of #8200: Add missing priorityClassName for critical pods
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/authentication.kope.io/k8s-1.12.yaml
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.kope.io/k8s-1.12.yaml
  upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/node-authorizer.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.13.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
  upup/pkg/fi/cloudup/tests/manifests/k8s-1.13.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8441 Release notes for 1.16.0-beta.1
  docs/releases/1.16-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8442 Release notes for 1.15.1
  docs/releases/1.15-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8444 Fix typo in comment
  hack/verify-shellcheck.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8455 Add an EnvVar type to the API
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8452 Update coredns to 1.6.7
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8448 Automated cherry pick of #8025: Alicloud: allow use RAM role for OSS client
  util/pkg/vfs/BUILD.bazel
  util/pkg/vfs/osscontext.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
