Repository kubernetes/kops, pull requests merged in 2020-04, with the labels that each got.

#8802 Add support for Spot block in launch template
  k8s/crds/kops.k8s.io_instancegroups.yaml
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/validation/aws.go
  pkg/apis/kops/validation/aws_test.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/awsmodel/autoscalinggroup.go
  tests/integration/update_cluster/launch_templates/cloudformation.json
  tests/integration/update_cluster/launch_templates/in-v1alpha2.yaml
  tests/integration/update_cluster/launch_templates/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/launchtemplate.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation_test.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
Labels: approved, area/api, area/provider/aws, cncf-cla: yes, lgtm, ok-to-test, size/L

#8832 Cleanup InstanceGroup MixedInstancePolicy docs
  docs/instance_groups.md
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Labels: approved, area/api, area/documentation, area/provider/aws, cncf-cla: yes, lgtm, size/M

#8835 Enable stamping on bazel image builds
  cmd/kops-controller/BUILD.bazel
  dns-controller/cmd/dns-controller/BUILD.bazel
  images/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8840 Automated cherry pick of #8835: Enable stamping on bazel image builds
  cmd/kops-controller/BUILD.bazel
  dns-controller/cmd/dns-controller/BUILD.bazel
  images/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8841 Automated cherry pick of #8835: Enable stamping on bazel image builds
  cmd/kops-controller/BUILD.bazel
  dns-controller/cmd/dns-controller/BUILD.bazel
  images/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8844 Remove unused ECU and Burstable fields from AWSMachineTypeInfo
  hack/machine_types/machine_types.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, area/provider/aws, cncf-cla: yes, lgtm, size/L

#8848 Use CNI 0.8.5 for Kubernetes 1.18+
  upup/pkg/fi/cloudup/networking.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8849 Update GCB jobs to use bazel 2.2.0
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8845 Add support for Docker 19.03.8 in Kops 1.17
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/docker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8700 Balk at using Kubernetes versions too new to be supported
  pkg/apis/kops/util/versions.go
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8851 Automated cherry pick of #8757: Update lyft CNI to 0.6.0
  docs/networking.md
  pkg/model/iam/iam_builder.go
  upup/pkg/fi/cloudup/apply_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8783 Remove basic authentication support for k8s 1.19+
  docs/cluster_spec.md
  docs/releases/1.18-NOTES.md
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/secrets.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, area/api, area/documentation, area/nodeup, cncf-cla: yes, lgtm, size/M

#8833 Make kubelet topology-manager-policy configurable
  k8s/crds/kops.k8s.io_clusters.yaml
  k8s/crds/kops.k8s.io_instancegroups.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/validation/legacy.go
Labels: approved, area/api, cncf-cla: yes, lgtm, size/L

#8852 Switch to the k/k implementation of drain.Helper
  hack/.packages
  pkg/drain/README.md
  pkg/instancegroups/BUILD.bazel
  pkg/instancegroups/instancegroups.go
  vendor/github.com/bazelbuild/bazel-gazelle/cmd/gazelle/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/config/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/flag/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/internal/version/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/internal/wspace/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/label/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/language/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/language/go/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/language/proto/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/merger/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/pathtools/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/repo/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/resolve/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/rule/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/walk/BUILD.bazel
  vendor/github.com/bazelbuild/buildtools/build/BUILD.bazel
  vendor/k8s.io/kubectl/pkg/drain/BUILD.bazel
  vendor/k8s.io/kubectl/pkg/drain/cordon.go
  vendor/k8s.io/kubectl/pkg/drain/default.go
  vendor/k8s.io/kubectl/pkg/drain/drain.go
  vendor/k8s.io/kubectl/pkg/drain/filters.go
  vendor/modules.txt
Labels: approved, area/rolling-update, cncf-cla: yes, lgtm, size/L

#8853 Update build instructions for dns controller
  docs/development/testing.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#8847 Switch to using ec2.DescribeInstanceTypes for building the MachineTypes list
  hack/machine_types/BUILD.bazel
  hack/machine_types/machine_types.go
  hack/machine_types/vpc_ip_resource_limit.go
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, area/provider/aws, cncf-cla: yes, lgtm, size/XL

#8855 Remove support for Docker 1.11, 1.12 and 1.13
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
Labels: approved, area/api, cncf-cla: yes, lgtm, size/M

#8846 Cleanup after #8855
  docs/releases/1.16-NOTES.md
  docs/releases/1.17-NOTES.md
  docs/releases/1.18-NOTES.md
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/docker_test.go
  nodeup/pkg/model/tests/dockerbuilder/docker_18.06.3/cluster.yaml
  nodeup/pkg/model/tests/dockerbuilder/docker_18.06.3/tasks.yaml
  nodeup/pkg/model/tests/dockerbuilder/healthcheck/cluster.yaml
  nodeup/pkg/model/tests/dockerbuilder/healthcheck/tasks.yaml
  nodeup/pkg/model/tests/dockerbuilder/logflags/cluster.yaml
  nodeup/pkg/model/tests/dockerbuilder/logflags/tasks.yaml
  nodeup/pkg/model/tests/dockerbuilder/simple/cluster.yaml
  nodeup/pkg/model/tests/dockerbuilder/simple/tasks.yaml
  pkg/model/components/containerd.go
Labels: approved, area/api, area/documentation, area/nodeup, cncf-cla: yes, lgtm, size/L

#8862 fixes auth problem in case of openstack kops-controller
  pkg/nodeidentity/openstack/identify.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8842 Update metrics-server deployment apiVersion to apps/v1
  addons/metrics-server/README.md
  addons/metrics-server/addon.yaml
  addons/metrics-server/v1.16.x.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8865 Update Calico and Canal to v3.13.2
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8860 Automated cherry pick of #8855: Remove support for Docker 1.11, 1.12 and 1.13
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8859 Automated cherry pick of #8855: Remove support for Docker 1.11, 1.12 and 1.13
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8863 Automated cherry pick of #8697 #8735 #8742 #8751: Update kube-router to v0.4.0
  upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8864 Automated cherry pick of #8697 #8735 #8742 #8751: Update kube-router to v0.4.0
  upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8250 GCE: Delete cluster will also delete the DNS entries created by kubernetes
  pkg/resources/gce/BUILD.bazel
  pkg/resources/gce/gce.go
  upup/pkg/fi/cloudup/gce/BUILD.bazel
  upup/pkg/fi/cloudup/gce/gce_cloud.go
  upup/pkg/fi/cloudup/gce/mock_gce_cloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8584 Don't compress bindata & allow Kops to be imported as a package.
  .gitignore
  Makefile
  upup/models/BUILD.bazel
  upup/models/bindata.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#8868 Validate cluster N times in rolling-update
  cmd/kops/rollingupdatecluster.go
  docs/cli/kops_rolling-update_cluster.md
  pkg/instancegroups/instancegroups.go
  pkg/instancegroups/rollingupdate.go
  pkg/instancegroups/rollingupdate_test.go
Labels: approved, area/documentation, area/rolling-update, cncf-cla: yes, lgtm, size/M

#8872 pkg: add some unit tests
  pkg/pretty/BUILD.bazel
  pkg/pretty/help_test.go
  pkg/systemd/BUILD.bazel
  pkg/systemd/escaping_test.go
  pkg/urls/BUILD.bazel
  pkg/urls/join_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8876 add verify-bindata.sh & separate bindata check and update make commands.
  Makefile
  hack/verify-bindata.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#8877 Don't delete bindata on "make clean"
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8878 Fix Terraform 0.12 support for GCE
  hack/verify-terraform.sh
  tests/integration/update_cluster/ha_gce/kubernetes.tf
  tests/integration/update_cluster/minimal_gce/kubernetes.tf
  upup/pkg/fi/cloudup/gcetasks/instance.go
  upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
  upup/pkg/fi/cloudup/terraform/BUILD.bazel
  upup/pkg/fi/cloudup/terraform/hcl2.go
  upup/pkg/fi/cloudup/terraform/hcl2_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8880 Makefile: simplify running go-bindata
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#8884 update gophercloud dependencies
  go.mod
  go.sum
  vendor/github.com/bazelbuild/bazel-gazelle/cmd/gazelle/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/config/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/flag/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/internal/version/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/internal/wspace/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/label/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/language/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/language/go/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/language/proto/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/merger/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/pathtools/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/repo/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/resolve/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/rule/BUILD.bazel
  vendor/github.com/bazelbuild/bazel-gazelle/walk/BUILD.bazel
  vendor/github.com/bazelbuild/buildtools/build/BUILD.bazel
  vendor/github.com/gophercloud/gophercloud/.zuul.yaml
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/go.mod
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/volumes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/BUILD.bazel
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/microversions.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/BUILD.bazel
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/microversions.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/BUILD.bazel
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/requests.go
  vendor/github.com/gophercloud/gophercloud/params.go
  vendor/github.com/weaveworks/mesh/BUILD.bazel
  vendor/github.com/weaveworks/mesh/peer_name_hash.go
  vendor/github.com/weaveworks/mesh/peer_name_mac.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XL

#8882 Update to golang 1.13.9 to match 1.18.1
  WORKSPACE
  docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8883 Use kubescheduler.config.k8s.io/v1alpha2 for Kubernetes 1.18+
  nodeup/pkg/model/kube_scheduler.go
  nodeup/pkg/model/kube_scheduler_test.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/S

#8857 Fix addon/ing/nginx v1.6.0 deployment apiVersion and selector
  addons/ingress-nginx/v1.6.0.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8886 Update go to 1.13.9 (continued)
  Makefile
  images/dns-controller-builder/Dockerfile
  images/protokube-builder/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8889 Fix tests for obsolete Docker versions in 1.17
  pkg/model/components/docker.go
  upup/pkg/fi/cloudup/populatecluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8890 Fix tests for obsolete Docker versions in 1.16
  pkg/model/components/docker.go
  upup/pkg/fi/cloudup/populatecluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8885 Replace deprecated x/net/context with context
  dnsprovider/pkg/dnsprovider/providers/coredns/BUILD.bazel
  dnsprovider/pkg/dnsprovider/providers/coredns/rrchangeset.go
  dnsprovider/pkg/dnsprovider/providers/coredns/rrsets.go
  dnsprovider/pkg/dnsprovider/providers/coredns/stubs/BUILD.bazel
  dnsprovider/pkg/dnsprovider/providers/coredns/stubs/corednsapi.go
  protokube/pkg/protokube/BUILD.bazel
  protokube/pkg/protokube/gce_volume.go
  upup/pkg/fi/assettasks/BUILD.bazel
  upup/pkg/fi/assettasks/docker_api.go
  upup/pkg/fi/cloudup/gce/BUILD.bazel
  upup/pkg/fi/cloudup/gce/gce_cloud.go
  upup/pkg/fi/cloudup/gce/instancegroups.go
  upup/pkg/fi/cloudup/gce/network.go
  upup/pkg/fi/cloudup/gce/wrappers.go
  util/pkg/vfs/BUILD.bazel
  util/pkg/vfs/context.go
  util/pkg/vfs/gsfs.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8893 Add go 1.14 to travis testing
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8892 Update 1.18 release notes now that Terraform 0.12 is supported
  docs/releases/1.18-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#8894 Add Docker version and new distros to release notes
  docs/releases/1.17-NOTES.md
  docs/releases/1.18-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#8780 NodeLocal DNSCache
  docs/cluster_spec.md
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/validation/legacy.go
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/components/kubedns.go
  upup/models/bindata.go
  upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/template_functions.go
Labels: approved, area/api, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XL

#8895 Remove duplicated docs
  README.md
  docs/index.md
  docs/welcome/releases.md
  mkdocs.yml
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/L

#8900 Adds docsite hidden note on index.md
  docs/README.md
  docs/extra.css
  docs/index.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#8901 Clean up the kubectl docs
  docs/getting_started/commands.md
  docs/getting_started/kubectl.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#8903 Add CloudLabels tags to additional AWS resources
  pkg/model/context.go
  tests/integration/update_cluster/api_elb_cross_zone/kubernetes.tf
  tests/integration/update_cluster/complex/cloudformation.json
  tests/integration/update_cluster/complex/kubernetes.tf
  tests/integration/update_cluster/externalpolicies/kubernetes.tf
  tests/integration/update_cluster/nosshkey/kubernetes.tf
  tests/integration/update_cluster/privatedns1/in-v1alpha2.yaml
  tests/integration/update_cluster/privatedns1/kubernetes.tf
Labels: approved, cncf-cla: yes, lgtm, size/L

#8904 Automated cherry pick of #8903: Add CloudLabels tags to additional AWS resources
  pkg/model/context.go
  tests/integration/update_cluster/api_elb_cross_zone/kubernetes.tf
  tests/integration/update_cluster/complex/cloudformation.json
  tests/integration/update_cluster/complex/kubernetes.tf
  tests/integration/update_cluster/nosshkey/kubernetes.tf
  tests/integration/update_cluster/privatedns1/in-v1alpha2.yaml
  tests/integration/update_cluster/privatedns1/kubernetes.tf
Labels: approved, cncf-cla: yes, lgtm, size/L

#8905 Add unit test for func IsGTE
  pkg/k8sversion/version_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8902 Clean up the spec docs
  docs/cluster_spec.md
  docs/instance_groups.md
  docs/tutorial/working-with-instancegroups.md
  mkdocs.yml
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XXL

#8907 Etcd docs cleanup
  docs/etcd/manager.md
  docs/etcd/roadmap.md
  docs/etcd3-migration.md
  docs/operations/etcd_administration.md
  docs/operations/etcd_backup_restore_encryption.md
  mkdocs.yml
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/L

#8918 Exclude GO 1.14 for OSX
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8912 Update security_groups.md
  docs/security_groups.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8924 Automated cherry pick of #8727: Add support for Ubuntu 20.04 (Focal)
  nodeup/pkg/distros/distribution.go
  nodeup/pkg/distros/identify.go
  nodeup/pkg/model/kubelet.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8750 Use etcd-manager for the cilium etcd cluster
  cmd/kops/integration_test.go
  docs/networking.md
  docs/releases/1.18-NOTES.md
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/cilium.go
  nodeup/pkg/model/network.go
  pkg/apis/kops/validation/validation.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/firewall.go
  pkg/model/iam/iam_builder.go
  pkg/wellknownports/wellknownports.go
  tests/integration/update_cluster/privatecilium/cloudformation.json
  tests/integration/update_cluster/privatecilium/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/privatecilium/data/aws_iam_role_bastions.privatecilium.example.com_policy
  tests/integration/update_cluster/privatecilium/data/aws_iam_role_masters.privatecilium.example.com_policy
  tests/integration/update_cluster/privatecilium/data/aws_iam_role_nodes.privatecilium.example.com_policy
  tests/integration/update_cluster/privatecilium/data/aws_iam_role_policy_bastions.privatecilium.example.com_policy
  tests/integration/update_cluster/privatecilium/data/aws_iam_role_policy_masters.privatecilium.example.com_policy
  tests/integration/update_cluster/privatecilium/data/aws_iam_role_policy_nodes.privatecilium.example.com_policy
  tests/integration/update_cluster/privatecilium/data/aws_key_pair_kubernetes.privatecilium.example.com-c4a6ed9aa889b9e2c39cd663eb9c7157_public_key
  tests/integration/update_cluster/privatecilium/data/aws_launch_configuration_master-us-test-1a.masters.privatecilium.example.com_user_data
  tests/integration/update_cluster/privatecilium/data/aws_launch_configuration_nodes.privatecilium.example.com_user_data
  tests/integration/update_cluster/privatecilium/id_rsa.pub
  tests/integration/update_cluster/privatecilium/in-v1alpha2.yaml
  tests/integration/update_cluster/privatecilium/kubernetes.tf
  tests/integration/update_cluster/privateciliumadvanced/cloudformation.json
  tests/integration/update_cluster/privateciliumadvanced/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/privateciliumadvanced/data/aws_iam_role_bastions.privateciliumadvanced.example.com_policy
  tests/integration/update_cluster/privateciliumadvanced/data/aws_iam_role_masters.privateciliumadvanced.example.com_policy
  tests/integration/update_cluster/privateciliumadvanced/data/aws_iam_role_nodes.privateciliumadvanced.example.com_policy
  tests/integration/update_cluster/privateciliumadvanced/data/aws_iam_role_policy_bastions.privateciliumadvanced.example.com_policy
  tests/integration/update_cluster/privateciliumadvanced/data/aws_iam_role_policy_masters.privateciliumadvanced.example.com_policy
  tests/integration/update_cluster/privateciliumadvanced/data/aws_iam_role_policy_nodes.privateciliumadvanced.example.com_policy
  tests/integration/update_cluster/privateciliumadvanced/data/aws_key_pair_kubernetes.privateciliumadvanced.example.com-c4a6ed9aa889b9e2c39cd663eb9c7157_public_key
  tests/integration/update_cluster/privateciliumadvanced/data/aws_launch_configuration_master-us-test-1a.masters.privateciliumadvanced.example.com_user_data
  tests/integration/update_cluster/privateciliumadvanced/data/aws_launch_configuration_nodes.privateciliumadvanced.example.com_user_data
  tests/integration/update_cluster/privateciliumadvanced/id_rsa.pub
  tests/integration/update_cluster/privateciliumadvanced/in-v1alpha2.yaml
  tests/integration/update_cluster/privateciliumadvanced/kubernetes.tf
  upup/models/bindata.go
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/nodeup/command.go
Labels: approved, area/api, area/documentation, area/nodeup, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#8921 Bastion additionnal s gs
  docs/bastion.md
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/bastion.go
  pkg/apis/kops/v1alpha2/bastion.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/bastion.go
  tests/integration/update_cluster/bastionadditional_user-data/in-v1alpha2.yaml
  tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
Labels: approved, area/api, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/L

#8930 Change NodeLocalDNS Enabled to *bool
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/validation/legacy.go
  pkg/apis/kops/validation/validation_test.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/components/kubedns.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, area/api, cncf-cla: yes, lgtm, size/M

#8931 Rolling-update validation harmonization
  cmd/kops/rollingupdatecluster.go
  pkg/instancegroups/instancegroups.go
  pkg/instancegroups/rollingupdate.go
  pkg/instancegroups/rollingupdate_test.go
Labels: approved, area/rolling-update, cncf-cla: yes, lgtm, size/L

#8482 Upgrade CUDA from 9.1 to 10.0
  hooks/nvidia-device-plugin/Makefile
  hooks/nvidia-device-plugin/README.md
  hooks/nvidia-device-plugin/image/files/01-aws-nvidia-driver.sh
  hooks/nvidia-device-plugin/image/files/02-nvidia-docker.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8933 Import package aliases modified
  cmd/kops/create_ig.go
  cmd/kops/delete_cluster.go
  cmd/kops/export_kubecfg.go
  cmd/kops/get_cluster.go
  cmd/kops/rollingupdatecluster.go
  cmd/kops/upgrade_cluster.go
  cmd/kops/validate_cluster.go
  pkg/model/components/containerd_test.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
  upup/pkg/fi/cloudup/deepvalidate_test.go
  upup/pkg/fi/cloudup/loader.go
  upup/pkg/fi/cloudup/networking.go
  upup/pkg/fi/cloudup/populate_cluster_spec.go
  upup/pkg/fi/cloudup/populatecluster_test.go
  upup/pkg/fi/cloudup/populateinstancegroup_test.go
  upup/pkg/fi/cloudup/spec_builder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8935 Automated cherry pick of #8051: Fix CloudFormation template tags for NatGateway
  upup/pkg/fi/cloudup/awstasks/natgateway.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8934 Update the testing page
  docs/development/adding_a_feature.md
  docs/development/testing.md
  mkdocs.yml
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/L

#8937 Automated cherry pick of #8936: Remove irrelevant TODO comment from userdata
  pkg/model/resources/nodeup.go
  pkg/model/tests/data/bootstrapscript_0.txt
  pkg/model/tests/data/bootstrapscript_1.txt
  pkg/model/tests/data/bootstrapscript_2.txt
  pkg/model/tests/data/bootstrapscript_3.txt
  pkg/model/tests/data/bootstrapscript_4.txt
  pkg/model/tests/data/bootstrapscript_5.txt
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_master-us-west-2a.masters.k8s-iam.us-west-2.td.priv_user_data
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json.extracted.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8294 Spotinst: Support for Headroom, Taints and Subnets in Ocean Launch Spec and User Data fixes
  pkg/model/spotinstmodel/BUILD.bazel
  pkg/model/spotinstmodel/instance_group.go
  upup/pkg/fi/cloudup/spotinsttasks/BUILD.bazel
  upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go
  upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go
  upup/pkg/fi/cloudup/spotinsttasks/ocean.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#8939 Partially implement MountSensitive
  protokube/pkg/hostmount/nsenter_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8940 Use latest patch version for GO in tests
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8941 Add support for containerd v1.3.4
  nodeup/pkg/model/containerd.go
  pkg/model/components/containerd.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/S

#8947 Add unit test for func rewriteAPIGroup
  pkg/kopscodecs/codecs_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8945 Load the correct certificate before deleting
  upup/pkg/fi/BUILD.bazel
  upup/pkg/fi/vfs_castore.go
  upup/pkg/fi/vfs_castore_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#8951 Automated cherry pick of #8945: Load the correct certificate before deleting
  upup/pkg/fi/BUILD.bazel
  upup/pkg/fi/vfs_castore.go
  upup/pkg/fi/vfs_castore_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8952 Automated cherry pick of #8945: Load the correct certificate before deleting
  upup/pkg/fi/BUILD.bazel
  upup/pkg/fi/vfs_castore.go
  upup/pkg/fi/vfs_castore_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8955 Add unit test for func JoinSuffixes
  pkg/model/firewall_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8948 Update rotating secrets docs
  docs/rotate-secrets.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#8381 Fix net.bridge setting for Flannel on CentOS 7
  nodeup/pkg/model/sysctls.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8958 Turn on flannel sysctl fixes on rhel7 as well
  nodeup/pkg/model/sysctls.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/XS

#8926 Automated cherry pick of #8145: Enabling JSON output for Terraform instead of writing the HCL
  cmd/kops/integration_test.go
  docs/advanced/experimental.md
  docs/terraform.md
  pkg/featureflag/featureflag.go
  tests/integration/update_cluster/minimal-json/id_rsa.pub
  tests/integration/update_cluster/minimal-json/in-v1alpha0.yaml
  tests/integration/update_cluster/minimal-json/kubernetes.tf.json
  upup/pkg/fi/cloudup/terraform/target.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XL

#8962 Automated cherry pick of #7900: Add encryptionProviderConfig field
  k8s/crds/kops.k8s.io_clusters.yaml
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_apiserver_test.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8963 Automated cherry pick of #7900: Add encryptionProviderConfig field
  k8s/crds/kops.k8s.io_clusters.yaml
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_apiserver_test.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8906 Add unit test case for pkg/systemd/escaping_test.go
  pkg/systemd/escaping_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8966 Add release notes for 1.16.1
  docs/releases/1.16-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#8970 Modify the wrong name for unit test case
  pkg/k8sversion/version_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8972 Migrates GCE sdk from v0.beta to v1
  docs/releases/1.18-NOTES.md
  pkg/nodeidentity/gce/BUILD.bazel
  pkg/nodeidentity/gce/identify.go
  pkg/resources/gce/BUILD.bazel
  pkg/resources/gce/dump.go
  pkg/resources/gce/gce.go
  protokube/pkg/gossip/gce/BUILD.bazel
  protokube/pkg/gossip/gce/seeds.go
  protokube/pkg/protokube/BUILD.bazel
  protokube/pkg/protokube/gce_volume.go
  upup/pkg/fi/cloudup/gce/BUILD.bazel
  upup/pkg/fi/cloudup/gce/gce_cloud.go
  upup/pkg/fi/cloudup/gce/instancegroups.go
  upup/pkg/fi/cloudup/gce/mock_gce_cloud.go
  upup/pkg/fi/cloudup/gce/network.go
  upup/pkg/fi/cloudup/gce/op.go
  upup/pkg/fi/cloudup/gce/status.go
  upup/pkg/fi/cloudup/gce/wrappers.go
  upup/pkg/fi/cloudup/gcetasks/BUILD.bazel
  upup/pkg/fi/cloudup/gcetasks/address.go
  upup/pkg/fi/cloudup/gcetasks/disk.go
  upup/pkg/fi/cloudup/gcetasks/firewallrule.go
  upup/pkg/fi/cloudup/gcetasks/forwardingrule.go
  upup/pkg/fi/cloudup/gcetasks/instance.go
  upup/pkg/fi/cloudup/gcetasks/instancegroupmanager.go
  upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
  upup/pkg/fi/cloudup/gcetasks/network.go
  upup/pkg/fi/cloudup/gcetasks/subnet.go
  upup/pkg/fi/cloudup/gcetasks/targetpool.go
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#8961 Update Calico and Canal to latest patch versions
  upup/models/bindata.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8925 Automated cherry pick of #8727: Add support for Ubuntu 20.04 (Focal)
  nodeup/pkg/distros/distribution.go
  nodeup/pkg/distros/identify.go
  nodeup/pkg/model/kubelet.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8974 Update alpha and stable channels with April updates
  channels/alpha
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8986 Make addons directory link absolute to avoid 404
  docs/operations/addons.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8987 Make CPU Requests for Calico configurable instead of hard-coded
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  upup/models/bindata.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, area/api, cncf-cla: yes, lgtm, ok-to-test, size/M

#8994 Ignore already-deleted nodes during rolling update
  pkg/instancegroups/instancegroups.go
Labels: approved, area/rolling-update, cncf-cla: yes, lgtm, size/XS

#8990 Add initial github actions workflow
  .github/workflows/main.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8999 feat(openstack): propagate cloud labels to machines
  pkg/model/openstackmodel/servergroup.go
  pkg/model/openstackmodel/servergroup_test.go
Labels: approved, area/provider/openstack, cncf-cla: yes, lgtm, ok-to-test, size/XL

#8967 Profiling and protect kernel defaults flags
  docs/cluster_spec.md
  k8s/crds/kops.k8s.io_clusters.yaml
  k8s/crds/kops.k8s.io_instancegroups.yaml
  nodeup/pkg/model/kube_apiserver_test.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, area/api, area/documentation, area/nodeup, cncf-cla: yes, lgtm, ok-to-test, size/L

#9001 Automated cherry pick of #8999: feat(openstack): propagate cloud labels to machines
  pkg/model/openstackmodel/servergroup.go
  pkg/model/openstackmodel/servergroup_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#8979 cherry pick of #8967 upstream release 1.17
  docs/cluster_spec.md
  k8s/crds/kops.k8s.io_clusters.yaml
  k8s/crds/kops.k8s.io_instancegroups.yaml
  nodeup/pkg/model/kube_apiserver_test.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8980 Allow single to multi-master cluster
  docs/single-to-multi-master.md
  pkg/apis/kops/validation/BUILD.bazel
  pkg/apis/kops/validation/cluster.go
  pkg/apis/kops/validation/cluster_test.go
Labels: approved, area/api, area/documentation, cncf-cla: yes, lgtm, size/L

#8982 Bump cilium to 1.7.2
  upup/models/bindata.go
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#8975 Automated cherry pick of #8961: Update Calico and Canal to v3.13.3 for k8s 1.16+
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#9004 GCE: needs to use v1 network resources, not beta
  upup/pkg/fi/cloudup/gcetasks/network.go
  upup/pkg/fi/cloudup/gcetasks/subnet.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8977 Default to Debian 9 (Stretch) for Kubernetes 1.8, 1.9 and 1.10
  channels/alpha
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, size/S

#8965 Fix missing changes in Weave manifest
  upup/models/bindata.go
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#9018 Spotinst: Support for Grace Period in Ocean Cluster
  go.mod
  go.sum
  pkg/model/spotinstmodel/instance_group.go
  upup/pkg/fi/cloudup/spotinsttasks/ocean.go
  vendor/github.com/spotinst/spotinst-sdk-go/NOTICE.md
  vendor/github.com/spotinst/spotinst-sdk-go/service/elastigroup/providers/gcp/gcp.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/ocean.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/right_sizing.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/gcp/ocean.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/version.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#9020 Upgrade amazon vpc cni to 1.6.1
  upup/models/bindata.go
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#9021 Add af-south-1 and eu-south-1 regions (AWS)
  go.mod
  go.sum
  upup/pkg/fi/cloud.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/endpointcreds/provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/web_identity_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/token_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/session/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/session/shared_config.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/build.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/service/cloudformation/api.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/ec2iface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/iam/api.go
  vendor/github.com/aws/aws-sdk-go/service/kms/api.go
  vendor/github.com/aws/aws-sdk-go/service/route53/api.go
  vendor/github.com/aws/aws-sdk-go/service/route53/errors.go
  vendor/github.com/aws/aws-sdk-go/service/route53/route53iface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/s3/statusok_error.go
  vendor/github.com/aws/aws-sdk-go/service/s3/unmarshal_error.go
  vendor/github.com/jmespath/go-jmespath/.travis.yml
  vendor/github.com/jmespath/go-jmespath/README.md
  vendor/github.com/jmespath/go-jmespath/api.go
  vendor/github.com/jmespath/go-jmespath/go.mod
  vendor/github.com/jmespath/go-jmespath/go.sum
  vendor/github.com/jmespath/go-jmespath/parser.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#9016 Update to etcd-manager 3.0.20200429
  pkg/model/components/etcd.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/options.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
  pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
  pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#8988 Use KOPS_RSA_PRIVATE_KEY_SIZE for more keys
  hack/.packages
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/cilium.go
  nodeup/pkg/model/etcd_manager_tls.go
  pkg/pki/BUILD.bazel
  pkg/pki/certificate.go
  pkg/pki/certificate_test.go
  pkg/pki/csr.go
  pkg/pki/privatekey.go
  pkg/pkiutil/BUILD.bazel
  pkg/pkiutil/pki_helpers.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/L

#8998 Don't force bazel to use python2
  tools/bazel.rc
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9002 Automated cherry pick of #8982: Bump cilium to 1.7.2
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#8869 GCE DNS Cleanup: Print record name
  pkg/resources/gce/gce.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9013 Automated cherry pick of #8999: feat(openstack): propagate cloud labels to machines
  pkg/model/openstackmodel/servergroup.go
  pkg/model/openstackmodel/servergroup_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#9026 Bump cilium to 1.7.3
  upup/models/bindata.go
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
