Repository kubernetes/kops, pull requests merged in 2020-02, with the labels that each got.

#8458 Automated cherry pick of #8452: Update coredns to 1.6.7
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8459 Automated cherry pick of #8452: Update coredns to 1.6.7
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8460 Update godoc.org references to use pkg.go.dev
  README-ES.md
  README.md
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/clouddns.go
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/clouddns.go
  docs/README.md
  docs/cluster_spec.md
  docs/index.md
  docs/manifests_and_customizing_via_api.md
  docs/state.md
  mkdocs.yml
  nodeup/pkg/model/kube_proxy_test.go
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#8450 docs: trivial fix some typos
  docs/node_authorization.md
  docs/operations/images.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8462 Tag EBS volumes when using launch templates with AWS API target
  pkg/model/awsmodel/autoscalinggroup.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8237 [DigitalOcean] Add load balancer support for master HA
  pkg/commands/BUILD.bazel
  pkg/commands/status_discovery.go
  pkg/model/domodel/BUILD.bazel
  pkg/model/domodel/api_loadbalancer.go
  pkg/resources/digitalocean/cloud.go
  pkg/resources/digitalocean/resources.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/dotasks/BUILD.bazel
  upup/pkg/fi/cloudup/dotasks/loadbalancer.go
  upup/pkg/fi/cloudup/dotasks/loadbalancer_fitask.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8445 Cilium - Add missing Identity Allocation Mode to Operator Template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8467 Stop logging to /var/log/kops-controller.log
  cmd/kops-controller/BUILD.bazel
  dns-controller/cmd/dns-controller/BUILD.bazel
  hack/.packages
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/logrotate.go
  pkg/wellknownusers/BUILD.bazel
  pkg/wellknownusers/wellknownusers.go
  upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/template_functions.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8474 Fix typos in cluster_spec.md
  docs/cluster_spec.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8468 Fix Github download url for nodeup
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
  upup/pkg/fi/cloudup/urls.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8477 Cherry pick of #8468 onto release-1.17
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json.extracted.yaml
  upup/pkg/fi/cloudup/urls.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8480 Release notes for 1.18.0-alpha.2
  docs/releases/1.18-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#8479 Cherry pick of #8468 onto release-1.15
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
  upup/pkg/fi/cloudup/urls.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8478 Cherry pick of #8468 onto release-1.16
  tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json.extracted.yaml
  upup/pkg/fi/cloudup/urls.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8484 Update cilium to 1.6.6
  pkg/apis/kops/networking.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8485 Release notes for 1.17.0-alpha.3
  docs/releases/1.17-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8433 Make it possible to enable Prometheus metrics for Cilium
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#8493 GCS: Don't try to set ACLs if bucket-policy only is set
  pkg/acls/gce/BUILD.bazel
  pkg/acls/gce/storage.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8492 Automated cherry pick of #8445: Cilium - Add missing Identity Allocation Mode to Operator
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8501 Revert "Merge pull request #8458 from gjtempleton/automated-cherry-pi…
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8502 Revert "Merge pull request #8459 from gjtempleton/automated-cherry-pi…
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8503 Revert "Merge pull request #8452 from maruina/coredns-1.6.7"
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8500 Cherry pick of #8493 onto release-1.15
  pkg/acls/gce/BUILD.bazel
  pkg/acls/gce/storage.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8495 GCS: Fix bug where around retry on GCS
  util/pkg/vfs/gsfs.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8498 Cherry pick of #8493 onto release-1.17
  pkg/acls/gce/BUILD.bazel
  pkg/acls/gce/storage.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8506 Fix Netlify deps for tests
  images/mkdocs/requirements.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8496 GCS: Log ACLs if we're writing them
  util/pkg/vfs/gsfs.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8499 Cherry pick of #8493 onto release-1.16
  pkg/acls/gce/BUILD.bazel
  pkg/acls/gce/storage.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8491 Automated cherry pick of #8445: Cilium - Add missing Identity Allocation Mode to Operator
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8447 Automated cherry pick of #8025: Alicloud: allow use RAM role for OSS client
  util/pkg/vfs/BUILD.bazel
  util/pkg/vfs/osscontext.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8490 Automated cherry pick of #8445: Cilium - Add missing Identity Allocation Mode to Operator
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8505 Move cloudbuild.yaml to repo root
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8504 Add support for containerd v1.3.3
  nodeup/pkg/model/containerd.go
  pkg/model/components/containerd.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8461 Use BindMount task for /home/kubernetes/bin
  nodeup/pkg/model/directories.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8509 Automated cherry pick of #8433: Make it possible to enable Prometheus metrics for Cilium
  k8s/crds/kops_v1alpha2_cluster.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8510 Automated cherry pick of #8433: Make it possible to enable Prometheus metrics for Cilium
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8511 Automated cherry pick of #8433: Make it possible to enable Prometheus metrics for Cilium
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8487 Automated cherry pick of #8484: Update cilium to 1.6.6
  pkg/apis/kops/networking.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8513 Release notes for 1.15.2
  docs/releases/1.15-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8486 Automated cherry pick of #8484: Update cilium to 1.6.6
  pkg/apis/kops/networking.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8514 Image Pushing - Remove .git dependency from get_workspace_status.sh
  tools/get_workspace_status.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#8518 cloudbuild: Try uploading our binaries to the staging bucket also
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#8449 Return more errors at once during API validation
  cmd/kops/create_ig.go
  cmd/kops/edit_instancegroup.go
  pkg/apis/kops/validation/cluster.go
  pkg/apis/kops/validation/instancegroup.go
  pkg/apis/kops/validation/instancegroup_test.go
  pkg/apis/kops/validation/legacy.go
  pkg/client/simple/vfsclientset/cluster.go
  pkg/client/simple/vfsclientset/instancegroup.go
  upup/pkg/fi/cloudup/populate_cluster_spec.go
  upup/pkg/fi/cloudup/populate_instancegroup_spec.go
  upup/pkg/fi/cloudup/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#8519 Release notes for 1.16.0-beta.2
  docs/releases/1.16-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8489 Bump alphas to stable
  channels/stable
  tests/integration/create_cluster/complex/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha/expected-v1alpha1.yaml
  tests/integration/create_cluster/ha/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha1.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha1.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal/expected-v1alpha1.yaml
  tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha1.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
  tests/integration/create_cluster/private/expected-v1alpha1.yaml
  tests/integration/create_cluster/private/expected-v1alpha2.yaml
  tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets/expected-v1alpha1.yaml
  tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha1.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_vpc/expected-v1alpha1.yaml
  tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8520 Use larger machine type for cloudbuild jobs
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8497 Mark dns-controller and kops-controller as non-root
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#8246 Alicloud: support modification of LaunchConfiguration
  pkg/model/alimodel/scalinggroup.go
  upup/pkg/fi/cloudup/alitasks/BUILD.bazel
  upup/pkg/fi/cloudup/alitasks/launchconfiguration.go
  upup/pkg/fi/cloudup/aliup/ali_cloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8522 Fix Machine types vcpus
  upup/pkg/fi/cloudup/awsup/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8423 Update AWS IAM Authenticator to 0.5.0
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8524 Release notes for 1.17.0-alpha.4
  docs/releases/1.17-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8475 Add unit test for pkg/jsonutils/streamwriter.go
  pkg/jsonutils/BUILD.bazel
  pkg/jsonutils/streamwriter_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8527 Automated cherry pick of #8247 release-1.17
  pkg/model/bootstrapscript.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8532 channels: bump k8s versions after feb. patch releases
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/S

#8535 Add events RBAC permissions to kops-controller
  upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8536 Automated cherry pick of #8535: Add events RBAC permissions to kops-controller
  upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8537 Automated cherry pick of #8535: Add events RBAC permissions to kops-controller
  upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8538 Update amazon-vpc-cni-k8s to v1.6.0
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha2/networking.go
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8542 Automated cherry pick of #8353: Fix DNS loop on Ubuntu 18.04 (Bionic)
  nodeup/pkg/model/kubelet.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8545 Automated cherry pick of #8423: Update AWS IAM Authenticator to 0.5.0
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8544 Automated cherry pick of #8423: Update AWS IAM Authenticator to 0.5.0
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8220 Cilium nodeport
  pkg/apis/kops/validation/legacy.go
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8548 Update IAM permissions for amazon-vpc-cni-k8s 1.6.0
  pkg/model/iam/iam_builder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8540 Automated cherry pick of #8538: Update amazon-vpc-cni-k8s to v1.6.0
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha2/networking.go
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8547 Only create git tags with the v prefix
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8553 Automated cherry pick of #8548: Update IAM permissions for amazon-vpc-cni-k8s 1.6.0
  pkg/model/iam/iam_builder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8552 Automated cherry pick of #8548: Update IAM permissions for amazon-vpc-cni-k8s 1.6.0
  pkg/model/iam/iam_builder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8541 Automated cherry pick of #8538: Update amazon-vpc-cni-k8s to v1.6.0
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha2/networking.go
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8555 Switch AWS IAM Authenticator to use non-scratch image
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
Labels: approved, blocks-next, cncf-cla: yes, lgtm, size/XS

#8557 Automated cherry pick of #8555: Switch AWS IAM Authenticator to use non-scratch image
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8556 Automated cherry pick of #8555: Switch AWS IAM Authenticator to use non-scratch image
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8443 Add Kubernetes deprecation/removal release notes
  docs/releases/1.16-NOTES.md
  docs/releases/1.17-NOTES.md
  docs/releases/1.18-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8565 go-bindata: don't store file metadata
  Makefile
  upup/models/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8561 Replace unmaintained go-bindata
  Makefile
  go.mod
  go.sum
  tools.go
  upup/models/BUILD.bazel
  vendor/github.com/go-bindata/go-bindata/.gitignore
  vendor/github.com/go-bindata/go-bindata/BUILD.bazel
  vendor/github.com/go-bindata/go-bindata/CONTRIBUTING.md
  vendor/github.com/go-bindata/go-bindata/LICENSE
  vendor/github.com/go-bindata/go-bindata/Makefile
  vendor/github.com/go-bindata/go-bindata/README.md
  vendor/github.com/go-bindata/go-bindata/_config.yml
  vendor/github.com/go-bindata/go-bindata/asset.go
  vendor/github.com/go-bindata/go-bindata/bytewriter.go
  vendor/github.com/go-bindata/go-bindata/config.go
  vendor/github.com/go-bindata/go-bindata/convert.go
  vendor/github.com/go-bindata/go-bindata/debug.go
  vendor/github.com/go-bindata/go-bindata/doc.go
  vendor/github.com/go-bindata/go-bindata/file.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/.gitignore
  vendor/github.com/go-bindata/go-bindata/go-bindata/AppendSliceValue.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/BUILD.bazel
  vendor/github.com/go-bindata/go-bindata/go-bindata/main.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/version.go
  vendor/github.com/go-bindata/go-bindata/release.go
  vendor/github.com/go-bindata/go-bindata/restore.go
  vendor/github.com/go-bindata/go-bindata/stringwriter.go
  vendor/github.com/go-bindata/go-bindata/toc.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#8566 gzip: use --no-name to avoid saving timestamp
  Makefile
  tools/gzip.bzl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8543 Automated cherry pick of #8353: Fix DNS loop on Ubuntu 18.04 (Bionic)
  nodeup/pkg/model/kubelet.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8570 Update makefile to reduce dependency on GOPATH
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#8569 Fix field names in api validation
  channels/pkg/channels/addon.go
  cmd/kops/create_cluster.go
  cmd/kops/root.go
  pkg/apis/kops/registry/registry.go
  pkg/apis/kops/validation/cluster.go
  pkg/apis/kops/validation/gce.go
  pkg/apis/kops/validation/instancegroup.go
  pkg/apis/kops/validation/instancegroup_test.go
  pkg/apis/kops/validation/legacy.go
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
  pkg/client/simple/vfsclientset/cluster.go
  pkg/commands/set_cluster.go
  upup/pkg/fi/cloudup/populatecluster_test.go
  upup/pkg/fi/cloudup/populateinstancegroup_test.go
  upup/pkg/fi/cloudup/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8574 Update golang to 1.13.8
  Makefile
  WORKSPACE
  docker/Dockerfile
  images/dns-controller-builder/Dockerfile
  images/protokube-builder/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#8572 Hack directory cleanup
  hack/.shellcheck_failures
  hack/boilerplate/boilerplate.py
  hack/common.sh
  hack/dep.py
  hack/dev-build.sh
  hack/publish-docs.sh
  hack/update-bazel.sh
  hack/update-expected.sh
  hack/update-header.sh
  hack/verify-apimachinery.sh
  hack/verify-bazel.sh
  hack/verify-boilerplate.sh
  hack/verify-generate.sh
  hack/verify-gofmt.sh
  hack/verify-gomod
  hack/verify-packages.sh
  hack/verify-shellcheck.sh
  hack/verify-spelling.sh
  hack/verify-staticcheck.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#8316 Cilium eni
  k8s/crds/kops.k8s.io_clusters.yaml
  nodeup/pkg/model/context.go
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/validation/legacy.go
  pkg/model/iam/iam_builder.go
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8576 EnsureFileOwner: cleanup logic
  upup/pkg/fi/files_owner.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8575 Use UTC when calculating copyright year
  hack/update-header.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8568 makefile: use more hash helpers when building images
  Makefile
  cmd/kops-controller/BUILD.bazel
  dns-controller/cmd/dns-controller/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/M

#7837 Add External Policies (AWS managed policy attachments)
  cloudmock/aws/mockiam/api.go
  cloudmock/aws/mockiam/iamrole.go
  cmd/kops/integration_test.go
  docs/iam_roles.md
  hack/make-apimachinery.sh
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/iam.go
  pkg/resources/aws/aws.go
  tests/integration/update_cluster/externalpolicies/id_rsa.pub
  tests/integration/update_cluster/externalpolicies/in-v1alpha2.yaml
  tests/integration/update_cluster/externalpolicies/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/iamrolepolicy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#8578 Fix inappropriate use of field.Invalid()
  pkg/apis/kops/cluster.go
  pkg/apis/kops/topology.go
  pkg/apis/kops/validation/aws.go
  pkg/apis/kops/validation/gce.go
  pkg/apis/kops/validation/instancegroup.go
  pkg/apis/kops/validation/legacy.go
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
  upup/pkg/fi/cloudup/awstasks/subnet_test.go
  upup/pkg/fi/cloudup/deepvalidate_test.go
  upup/pkg/fi/errors.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8571 Use cluster name as default subnet tag for Lyft CNI
  docs/networking.md
  docs/releases/1.18-NOTES.md
  upup/models/nodeup/resources/_lyft_vpc_cni/files/etc/cni/net.d/10-cni-ipvlan-vpc-k8s.conflist.template
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8583 Revert update of AWS IAM Authenticator to 0.5.0 for 1.16
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8585 Staging build: don't use _GIT_TAG
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8586 prow-postsubmit: Upload to a consistently named directory
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8533 Spotinst: Add OWNERS file to Spotinst specific packages
  pkg/model/spotinstmodel/OWNERS
  pkg/resources/spotinst/OWNERS
  upup/pkg/fi/cloudup/spotinsttasks/OWNERS
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8589 Bump Cilium to 1.7 for k8s 1.12+
  pkg/apis/kops/cluster.go
  pkg/apis/kops/networking.go
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8593 cherrypick #8592 (add s3 region)
  util/pkg/env/standard.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8592 add s3 region
  util/pkg/env/standard.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8594 cherrypick #8592 (add s3 region)
  util/pkg/env/standard.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8539 Add unit test for pkg/nodelabels/builder.go
  pkg/nodelabels/BUILD.bazel
  pkg/nodelabels/builder_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8591 Fix typo in the cilium default version
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8595 Add unit test for pkg/apis/kops/util/labels.go
  pkg/apis/kops/util/BUILD.bazel
  pkg/apis/kops/util/labels_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8600 Fail cluster validation if a master missing kube-controller-manager
  pkg/validation/validate_cluster.go
  pkg/validation/validate_cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8466 Update tags support for LaunchTemplates
  pkg/model/context.go
  pkg/model/spotinstmodel/BUILD.bazel
  pkg/model/spotinstmodel/instance_group.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8604 Fix a bug in UT apis/kops/util/labels_test.go
  pkg/apis/kops/util/labels_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8601 [Digital Ocean] Update documentation for multi-master HA setup
  docs/getting_started/digitalocean.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8603 Add release notes and docs for containerd
  docs/cluster_spec.md
  docs/releases/1.18-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8602 Update coredns to 1.6.7
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8609 Automated cherry pick of #8602: Update coredns to 1.6.7
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8608 Automated cherry pick of #8602: Update coredns to 1.6.7
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8610 Use supported kubernetes versions in tests
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_apiserver_test.go
  nodeup/pkg/model/tests/apiServer/auditDynamicConfiguration/cluster.yaml
  nodeup/pkg/model/tests/dockerbuilder/docker_1.12.1/cluster.yaml
  nodeup/pkg/model/tests/dockerbuilder/docker_1.12.1/tasks.yaml
  nodeup/pkg/model/tests/dockerbuilder/logflags/cluster.yaml
  nodeup/pkg/model/tests/dockerbuilder/logflags/tasks.yaml
  nodeup/pkg/model/tests/dockerbuilder/simple/cluster.yaml
  nodeup/pkg/model/tests/dockerbuilder/simple/tasks.yaml
  nodeup/pkg/model/tests/dockerbuilder/skipinstall/cluster.yaml
  pkg/kubeconfig/create_kubecfg_test.go
  pkg/model/awsmodel/autoscalinggroup_test.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/cluster.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8581 kubelet: map rotate-certificates options
  k8s/crds/kops.k8s.io_clusters.yaml
  k8s/crds/kops.k8s.io_instancegroups.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8579 Resolve TODO in /pkg/model/component/context.go
  pkg/model/components/context.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8590 Fix typo in comment for struct LyftVPCNetworkingSpec
  pkg/apis/kops/networking.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8599 Cilium fix bpffs check
  go.mod
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/network.go
Labels: approved, blocks-next, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#8611 Automated cherry pick of #8599: Properly detect that bpffs has been mounted
  go.mod
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/network.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8613 Automated cherry pick of #8599: Properly detect that bpffs has been mounted
  go.mod
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/network.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8612 Automated cherry pick of #8599: Properly detect that bpffs has been mounted
  go.mod
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/network.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8549 Spotinst: Add support for blacklisting or whitelisting instance types in Ocean
  pkg/model/spotinstmodel/instance_group.go
  upup/pkg/fi/cloudup/spotinsttasks/ocean.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#8573 Don't try to configure a bastion DNS name in gossip mode
  cmd/kops/create_cluster.go
  docs/bastion.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8563 use v0.29 in prometheus operator
  addons/prometheus-operator/addon.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8473 Update Calico CNI Networking Documentation Links
  docs/networking.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8616 Spotinst: Support for Tags (Cloud Labels) in Ocean Launch Spec
  go.mod
  go.sum
  pkg/model/spotinstmodel/instance_group.go
  upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go
  upup/pkg/fi/cloudup/spotinsttasks/ocean.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/elastigroup/providers/aws/aws.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/elastigroup/providers/aws/service.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/BUILD.bazel
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/launch_spec.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/launch_spec_ecs.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/ocean.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/ocean_ecs.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/right_sizing.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/service.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/gcp/ocean.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/BUILD.bazel
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/config.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/util/useragent/BUILD.bazel
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/util/useragent/useragent.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/version.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XL

#8622 Automated cherry pick of #8160: Add Docker 19.03.4 and 18.09.9 for Ubuntu Xenial
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8625 Automated cherry pick of #8589: Bump Cilium to 1.7 for k8s 1.12+ #8591: Fix typo in the cilium default version
  pkg/apis/kops/cluster.go
  pkg/apis/kops/networking.go
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#8606 Automated cherry pick of #7925: Extract the list of instance groups earlier in validation #8039: Vendor github.com/stretchr/testify/require #8159: Determine node role from instancegroup spec #8600: Fail cluster validation if a master missing
  cmd/kops/rollingupdatecluster.go
  cmd/kops/validate_cluster.go
  pkg/validation/BUILD.bazel
  pkg/validation/validate_cluster.go
  pkg/validation/validate_cluster_test.go
  vendor/github.com/stretchr/testify/require/BUILD.bazel
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#8628 Automated cherry pick of #7730: Add SysctlParameters to ClusterSpec and InstanceGroupSpec
  docs/cluster_spec.md
  docs/instance_groups.md
  k8s/crds/kops.k8s.io_clusters.yaml
  k8s/crds/kops.k8s.io_instancegroups.yaml
  nodeup/pkg/model/sysctls.go
  pkg/apis/kops/cluster.go
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/instancegroup.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8623 Automated cherry pick of #8160: Add Docker 19.03.4 and 18.09.9 for Ubuntu Xenial
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8408 Refuse to read channels with addons with unparseable versions
  channels/pkg/api/BUILD.bazel
  channels/pkg/api/channel.go
  channels/pkg/api/channel_test.go
  channels/pkg/channels/BUILD.bazel
  channels/pkg/channels/addons.go
  channels/pkg/channels/addons_test.go
  channels/pkg/cmd/apply_channel.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8630 Automated cherry pick of #8020: Automatically install dependencies with local packages
  nodeup/pkg/model/docker.go
  upup/pkg/fi/nodeup/nodetasks/package.go
  upup/pkg/fi/nodeup/tags/tags.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8631 Adding Unit Test for pkg/dns/gossip.go
  pkg/dns/BUILD.bazel
  pkg/dns/gossip_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8617 Validate at most one networking option chosen
  pkg/apis/kops/validation/legacy.go
  pkg/apis/kops/validation/validation.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8276 Add support for custom env vars in amazon-vpc-cni
  docs/networking.md
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/cluster.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.12.yaml
Labels: approved, area/api, cncf-cla: yes, lgtm, size/L

#8633 Automated cherry pick of #8276 and #8455: Add env API field to amazonvpc
  docs/networking.md
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/cluster.go
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/cluster.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.12.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8632 Promote alphas to stable
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8637 Release notes for 1.16.0
  docs/releases/1.16-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8618 Update Calico and Canal to v3.12.0
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/validation/validation.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8641 Release notes for 1.17.0 beta.1
  docs/releases/1.17-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8453 Update release process
  docs/development/release.md
  hack/set-version
Labels: approved, cncf-cla: yes, lgtm, size/M

#8643 Automated cherry pick of #7979: cloudup: Map sprig indent template function
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/BUILD.bazel
  upup/pkg/fi/cloudup/template_functions.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8649 Fix node-authorizer/pkg/server staticcheck failure
  hack/.staticcheck_failures
  node-authorizer/pkg/server/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8645 Cherry pick of #8618: Update Calico and Canal to v3.12.0
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha2/networking.go
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8646 Bump Calico and Canal version tags for older k8s
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8651 Add the aws iam authenticator known issue to the 1.17 release notes
  docs/releases/1.17-NOTES.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8635 Install packages updates during bootstrap
  docs/getting_started/arguments.md
  upup/pkg/fi/nodeup/nodetasks/package.go
  upup/pkg/fi/nodeup/tags/tags.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8653 Revert AWS IAM Authenticator Update in release-1.17
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8567 Treat nil of LaunchTemplateSpecification.Version as $Default [0]
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8654 Cleanup release documentation
  docs/development/release.md
  docs/releases.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/L

#8656 Automated cherry pick of #8282: Set the default instance type to t3.medium for AWS
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8657 Fix condition for innstall packages updates during bootstrap
  upup/pkg/fi/nodeup/nodetasks/package.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8639 Delete launch templates when using EnableLaunchTemplates
  pkg/resources/aws/aws.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8638 Automated cherry pick of #8589: Bump Cilium to 1.7 for k8s 1.12+ #8591: Fix typo in the cilium default version
  pkg/apis/kops/cluster.go
  pkg/apis/kops/networking.go
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
