Repository kubernetes/kops, pull requests merged in 2020-05, with the labels that each got.

#9029 Update docs on supported distros and images
  docs/README.md
  docs/operations/images.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/L

#9033 Rename tests to make it easier to search for failing tests
  dnsprovider/pkg/dnsprovider/providers/aws/route53/route53_test.go
  dnsprovider/pkg/dnsprovider/providers/coredns/coredns_test.go
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/clouddns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9032 Use raw tarfile for AmazonLinux2 + Containerd 1.2.10
  nodeup/pkg/model/containerd.go
  nodeup/pkg/model/docker.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/M

#7733 Correct expression typos on docs/aws.md
  docs/getting_started/aws.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, lifecycle/stale, ok-to-test, size/M

#9019 Update the cross-account example with working policy
  docs/state.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#9017 Allow changing AZ of masters
  cmd/kops/create_ig.go
  cmd/kops/edit_instancegroup.go
  pkg/apis/kops/validation/cluster.go
  pkg/apis/kops/validation/cluster_test.go
  pkg/apis/kops/validation/instancegroup.go
  pkg/apis/kops/validation/instancegroup_test.go
  pkg/apis/kops/validation/legacy.go
  tests/integration/update_cluster/existing_iam/data/aws_launch_configuration_master-us-test-1a.masters.existing-iam.example.com_user_data
  tests/integration/update_cluster/existing_iam/data/aws_launch_configuration_master-us-test-1b.masters.existing-iam.example.com_user_data
  tests/integration/update_cluster/existing_iam/data/aws_launch_configuration_master-us-test-1c.masters.existing-iam.example.com_user_data
  tests/integration/update_cluster/existing_iam/in-v1alpha2.yaml
  tests/integration/update_cluster/existing_iam/kubernetes.tf
  upup/pkg/fi/cloudup/deepvalidate_test.go
  upup/pkg/fi/cloudup/populateinstancegroup_test.go
  upup/pkg/fi/cloudup/validation_test.go
Labels: approved, area/api, cncf-cla: yes, lgtm, size/L

#9036 Back-port well known owner aliases and SSH users to 1.16
  pkg/resources/aws/aws.go
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#9035 Back-port well known owner aliases and SSH users to 1.17
  pkg/resources/aws/aws.go
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#9046 Use Ubuntu 18.04 Docker packages for Ubuntu 20.04 setups
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9047 Use Ubuntu 18.04 Docker packages for Ubuntu 20.04 setups
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9045 Automated cherry pick of #8794: Make cilium operator health check go against localhost IP
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9034 Update docs on supported distros and release notes
  docs/operations/images.md
  docs/releases/1.17-NOTES.md
  docs/releases/1.18-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/L

#9038 Updating stable channel to use latest k8s versions
  channels/stable
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8787 Support S3 Virtual Hosted Style
  util/pkg/vfs/s3context.go
  util/pkg/vfs/s3context_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#9022 Feature spotinst controller v1.0.58
  upup/models/bindata.go
  upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
  upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.9.0.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#9044 Ubuntu focal: Use generic docker & container packages
  nodeup/pkg/model/containerd.go
  nodeup/pkg/model/docker.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/S

#9055 Move GCEServiceAccount into CloudConfig
  cmd/kops/create_cluster.go
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/cluster.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/model/gcemodel/autoscalinggroup.go
  tests/integration/create_cluster/gce_byo_sa/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
  tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-a-ha-gce-example-com_metadata_startup-script
  tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-b-ha-gce-example-com_metadata_startup-script
  tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-c-ha-gce-example-com_metadata_startup-script
  tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_nodes-ha-gce-example-com_metadata_startup-script
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
Labels: approved, area/api, cncf-cla: yes, lgtm, size/M

#9043 Automated cherry pick of #9016: Update to etcd-manager 3.0.20200428
  pkg/model/components/etcd.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#9042 Automated cherry pick of #9016: Update to etcd-manager 3.0.20200428
  pkg/model/components/etcd.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/options.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#9041 Automated cherry pick of #9016: Update to etcd-manager 3.0.20200428
  pkg/model/components/etcd.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/options.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#9028 Automated cherry pick of #9026: Bump cilium to 1.7.3
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#9057 Automated cherry pick of #8216 #8303: Adding ability to configure resources for weave
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/parse_test.go
  pkg/apis/kops/v1alpha1/networking.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/cluster.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#9054 Don't restrict GitHub Actions to master
  .github/workflows/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9050 Update service_account_token_volumes.md
  docs/operations/service_account_token_volumes.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8978 Don't install static utils for Flatcar
  nodeup/pkg/model/kubelet.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/M

#9049 Validate more static pods on masters
  pkg/validation/validate_cluster.go
  pkg/validation/validate_cluster_test.go
Labels: approved, area/rolling-update, cncf-cla: yes, lgtm, size/L

#9058 Automated cherry pick of #7898 8691 8764 8965: Update Weave Net to version 2.6.2
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8997 util/pkg/vfs/fs.go: Add Unit Test for WriteTo
  util/pkg/vfs/fs_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#9064 Add more ca-central-1 AZs, add ap-northeast-3 AZs
  upup/pkg/fi/cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9059 Update docs on supported distros and release notes
  docs/operations/images.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#9070 Release notes for 1.15.3
  docs/releases/1.15-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#9071 Release notes for 1.16.2
  docs/releases/1.16-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#9030 Add etcd-manager certificate expiration advisory
  docs/advisories/README.md
  docs/advisories/etcd-manager-certificate-expiration.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#9052 Treat NatGatewaysNotFound error as already-deleted
  pkg/resources/aws/aws.go
Labels: approved, area/provider/aws, cncf-cla: yes, lgtm, size/S

#9053 Allow cluster maintenance when channel is unavailable
  cmd/kops/create_ig.go
  cmd/kops/edit_instancegroup.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/populate_instancegroup_spec.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#9075 Release notes for 1.18.0-alpha.3
  docs/development/release.md
  docs/releases/1.18-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/L

#9073 Release notes for 1.17.0-beta.2
  docs/releases/1.17-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#9076 Automated cherry pick of #9053: Allow cluster maintenance when channel is unavailable
  cmd/kops/create_ig.go
  cmd/kops/edit_instancegroup.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/populate_instancegroup_spec.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#9074 Disable TX checksum offload for Flannel VXLAN
  nodeup/pkg/model/network.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/M

#9068 Added support for configuring disable-attach-detach-reconcile-sync in…
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, area/api, cncf-cla: yes, lgtm, ok-to-test, size/S

#9079 Automated cherry pick of #9068: Added support for configuring disable-attach-detach-reconcile-sync
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha1/componentconfig.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#9083 Add advisory notice to readme and docs homepage
  README.md
  docs/advisories/README.md
  docs/index.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#9087 Revert "feat(openstack): propagate cloud labels to machines"
  pkg/model/openstackmodel/servergroup.go
  pkg/model/openstackmodel/servergroup_test.go
Labels: approved, area/provider/openstack, cncf-cla: yes, lgtm, size/XL

#9089 Revert "Automated cherry pick of #8999: feat(openstack): propagate cloud labels to machines"
  pkg/model/openstackmodel/servergroup.go
  pkg/model/openstackmodel/servergroup_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#9088 Revert "Automated cherry pick of #8999: feat(openstack): propagate cloud labels to machines"
  pkg/model/openstackmodel/servergroup.go
  pkg/model/openstackmodel/servergroup_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#9069 kube-apiserver: healthcheck via sidecar container
  Makefile
  cmd/kube-apiserver-healthcheck/BUILD.bazel
  cmd/kube-apiserver-healthcheck/README.md
  cmd/kube-apiserver-healthcheck/main.go
  cmd/kube-apiserver-healthcheck/proxy_test.go
  hack/.packages
  hack/set-version
  hack/update-expected.sh
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/context.go
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_apiserver_healthcheck.go
  pkg/apis/nodeup/config.go
  pkg/assets/builder.go
  pkg/model/BUILD.bazel
  pkg/model/components/apiserver.go
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/kubeapiserver/BUILD.bazel
  pkg/model/components/kubeapiserver/model.go
  pkg/model/components/kubeapiserver/model_test.go
  pkg/model/components/kubeapiserver/tests/minimal/cluster.yaml
  pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
  pkg/model/manifests.go
  pkg/wellknownusers/wellknownusers.go
  tools/get_workspace_status.sh
  upup/pkg/fi/cloudup/BUILD.bazel
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/nodeup/command.go
Labels: approved, area/api, area/documentation, area/nodeup, area/provider/aws, cncf-cla: yes, lgtm, size/XXL

#9090 manual cherry-pick #8994 into 1.17.
  pkg/instancegroups/instancegroups.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#9078 Automated cherry pick of #9074: Disable TX checksum offload for Flannel VXLAN
  nodeup/pkg/model/network.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#9085 Use Ubuntu 18.04 Docker 19.03.8 packages for Ubuntu 20.04
  nodeup/pkg/model/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9008 Include secondary protocol flag always
  nodeup/pkg/model/protokube.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, ok-to-test, size/XS

#9092 Cherry pick of #9069 onto release-1.17
  Makefile
  cmd/kube-apiserver-healthcheck/BUILD.bazel
  cmd/kube-apiserver-healthcheck/README.md
  cmd/kube-apiserver-healthcheck/main.go
  cmd/kube-apiserver-healthcheck/proxy_test.go
  hack/.packages
  hack/update-expected.sh
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/context.go
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_apiserver_healthcheck.go
  pkg/apis/nodeup/config.go
  pkg/assets/builder.go
  pkg/model/BUILD.bazel
  pkg/model/components/apiserver.go
  pkg/model/components/etcdmanager/BUILD.bazel
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/kubeapiserver/BUILD.bazel
  pkg/model/components/kubeapiserver/model.go
  pkg/model/components/kubeapiserver/model_test.go
  pkg/model/components/kubeapiserver/tests/minimal/cluster.yaml
  pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
  pkg/model/context.go
  pkg/model/manifests.go
  pkg/wellknownusers/BUILD.bazel
  pkg/wellknownusers/wellknownusers.go
  tools/get_workspace_status.sh
  upup/pkg/fi/cloudup/BUILD.bazel
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/nodeup/command.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#9081 Reduce the number of TravisCI jobs for release branch
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9080 Reduce the number of TravisCI jobs for release branch
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9096 Cherry pick of #8576 onto release-1.17
  upup/pkg/fi/files_owner.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#9097 Fix port conflict on etcd-cilium vs dns-controller memberlist
  pkg/wellknownports/wellknownports.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9095 kube-apiserver-healthcheck: actually enable on 1.17
  pkg/model/components/apiserver.go
  pkg/model/components/kubeapiserver/model.go
  pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#9098 kube-apiserver-healthcheck: actually enable on 1.17
  pkg/model/components/apiserver.go
  pkg/model/components/kubeapiserver/model.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9072 Update instance_groups.md
  docs/instance_groups.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/M

#9101 Fix containerd image side-loading
  nodeup/pkg/model/protokube.go
  nodeup/pkg/model/tests/protokube/containerd/tasks.yaml
  upup/pkg/fi/nodeup/nodetasks/load_image.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/S

#9084 Dont use terraform's file() for singleline strings in GCE metadata
  cmd/kops/integration_test.go
  tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-a-ha-gce-example-com_metadata_cluster-name
  tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-a-ha-gce-example-com_metadata_kops-k8s-io-instance-group-name
  tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-b-ha-gce-example-com_metadata_cluster-name
  tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-b-ha-gce-example-com_metadata_kops-k8s-io-instance-group-name
  tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-c-ha-gce-example-com_metadata_cluster-name
  tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-c-ha-gce-example-com_metadata_kops-k8s-io-instance-group-name
  tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_nodes-ha-gce-example-com_metadata_cluster-name
  tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_nodes-ha-gce-example-com_metadata_kops-k8s-io-instance-group-name
  tests/integration/update_cluster/ha_gce/kubernetes.tf
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_cluster-name
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_kops-k8s-io-instance-group-name
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_cluster-name
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_kops-k8s-io-instance-group-name
  tests/integration/update_cluster/minimal_gce/kubernetes.tf
  upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
  upup/pkg/fi/cloudup/terraform/hcl2.go
  upup/pkg/fi/cloudup/terraform/literal.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#9111 Add documentation on gossip
  docs/bastion.md
  docs/getting_started/aws.md
  docs/gossip.md
  mkdocs.yml
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#9113 upgrade to use cinder v3 api
  cmd/kops/create_cluster.go
  pkg/resources/openstack/BUILD.bazel
  pkg/resources/openstack/volumes.go
  protokube/pkg/protokube/BUILD.bazel
  protokube/pkg/protokube/openstack_volume.go
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/status.go
  upup/pkg/fi/cloudup/openstack/volume.go
  upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel
  upup/pkg/fi/cloudup/openstacktasks/volume.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/volumes/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/BUILD.bazel
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/util.go
  vendor/modules.txt
Labels: approved, area/provider/openstack, cncf-cla: yes, lgtm, size/M

#9108 Fix zsh completion
  cmd/kops/completion.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#9120 Automated cherry pick of #9108: Fix zsh completion
  cmd/kops/completion.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#9119 Automated cherry pick of #9108: Fix zsh completion
  cmd/kops/completion.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#9114 Add unit test for util/pkg/hashing/hash.go
  util/pkg/hashing/BUILD.bazel
  util/pkg/hashing/hash_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#9091 Spotinst: Allow users to disable the controller add-on
  pkg/featureflag/featureflag.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9077 Automated cherry pick of #9053: Allow cluster maintenance when channel is unavailable
  cmd/kops/create_ig.go
  cmd/kops/edit_instancegroup.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/populate_instancegroup_spec.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#9126 Fail cluster validation if too few nodes for ig's target size
  cmd/kops/rollingupdatecluster.go
  pkg/cloudinstances/cloud_instance_group.go
  pkg/resources/spotinst/resources.go
  pkg/validation/validate_cluster.go
  pkg/validation/validate_cluster_test.go
  upup/pkg/fi/cloudup/aliup/status.go
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
  upup/pkg/fi/cloudup/gce/instancegroups.go
  upup/pkg/fi/cloudup/openstack/server_group.go
Labels: approved, area/provider/aws, area/provider/openstack, cncf-cla: yes, lgtm, size/M

#9125 Adding most recent version of kube-state-metrics - 1.9.5
  addons/kube-state-metrics/addon.yaml
  addons/kube-state-metrics/v1.9.5.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#9106 PKI code cleanup
  hack/.packages
  nodeup/pkg/model/kube_apiserver_test.go
  upup/pkg/fi/ca.go
  upup/pkg/fi/clientset_castore.go
  upup/pkg/fi/k8sapi/BUILD.bazel
  upup/pkg/fi/k8sapi/cert_secret.go
  upup/pkg/fi/k8sapi/k8s_keystore.go
  upup/pkg/fi/vfs_castore.go
  upup/pkg/kutil/convert_kubeup_cluster.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/L

#9118 Return cluster validation failure if ASG missing
  pkg/validation/validate_cluster.go
  pkg/validation/validate_cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#9121 Add EC2 Instance LifeCycle label
  cmd/kops-controller/controllers/node_controller.go
  pkg/nodeidentity/aws/identify.go
  pkg/nodeidentity/interfaces.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8960 add some unit tests
  pkg/model/defaults/BUILD.bazel
  pkg/model/defaults/volumes_test.go
  upup/pkg/fi/utils/BUILD.bazel
  upup/pkg/fi/utils/equals_test.go
  upup/pkg/fi/utils/hash_test.go
  upup/pkg/fi/utils/sanitize_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#9134 Remove code for unsupported Kubernetes version
  nodeup/pkg/model/cloudconfig.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/M

#9136 http download: set a timeout to avoid hangs
  upup/pkg/fi/http.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9107 Move CNI docs to their own files
  docs/calico-v3.md
  docs/networking.md
  docs/networking/aws-vpc.md
  docs/networking/calico.md
  docs/networking/canal.md
  docs/networking/cilium.md
  docs/networking/flannel.md
  docs/networking/kube-router.md
  docs/networking/lyft-vpc.md
  docs/networking/romana.md
  docs/networking/weave.md
  docs/upgrade_from_kops_1.6_to_1.7_calico_cidr_migration.md
  mkdocs.yml
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XXL

#9024 Added Launch Template support for instance interruption behavior
  k8s/crds/kops.k8s.io_instancegroups.yaml
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/validation/aws.go
  pkg/apis/kops/validation/aws_test.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/awsmodel/autoscalinggroup.go
  tests/integration/update_cluster/launch_templates/cloudformation.json
  tests/integration/update_cluster/launch_templates/in-v1alpha2.yaml
  tests/integration/update_cluster/launch_templates/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/launchtemplate.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation_test.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
Labels: approved, area/api, area/provider/aws, cncf-cla: yes, lgtm, ok-to-test, size/L

#8464 DNS: Don't try to apply empty changesets
  dns-controller/pkg/dns/dnscontroller.go
  dnsprovider/pkg/dnsprovider/dns.go
  dnsprovider/pkg/dnsprovider/providers/aws/route53/route53_test.go
  dnsprovider/pkg/dnsprovider/providers/aws/route53/rrchangeset.go
  dnsprovider/pkg/dnsprovider/providers/coredns/coredns_test.go
  dnsprovider/pkg/dnsprovider/providers/coredns/rrchangeset.go
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/clouddns_test.go
  dnsprovider/pkg/dnsprovider/providers/google/clouddns/rrchangeset.go
  dnsprovider/pkg/dnsprovider/providers/openstack/designate/BUILD.bazel
  dnsprovider/pkg/dnsprovider/providers/openstack/designate/designate_test.go
  dnsprovider/pkg/dnsprovider/providers/openstack/designate/rrchangeset.go
  dnsprovider/pkg/dnsprovider/tests/BUILD.bazel
  dnsprovider/pkg/dnsprovider/tests/commontests.go
  dnsprovider/pkg/dnsprovider/tests/contract.go
  pkg/resources/digitalocean/dns/dns.go
  pkg/resources/digitalocean/dns/dns_test.go
  protokube/pkg/gossip/dns/provider/changeset.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/dns.go
Labels: approved, area/gce, area/provider/digitalocean, cncf-cla: yes, lgtm, size/L

#9144 Remove redundant menu item in the docs site
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9142 Remove Classic networking from docs
  docs/networking.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#9147 doc: Typo in docs/state.md
  docs/state.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#9139 Spotinst: Documentation
  docs/advanced/experimental.md
  docs/getting_started/spot-ocean.md
  mkdocs.yml
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/L

#9133 Map kube-apiserver service-account-jwks-uri flag
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: approved, area/api, cncf-cla: yes, lgtm, size/S

#9124 Don't put bastions in the utility subnets
  pkg/model/openstackmodel/servergroup.go
  tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/private/expected-v1alpha2.yaml
  upup/pkg/fi/cloudup/populate_instancegroup_spec.go
Labels: approved, area/provider/openstack, cncf-cla: yes, lgtm, size/S

#8950 Create golden image test for nodeup kube-apiserver
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/containerd_test.go
  nodeup/pkg/model/docker_test.go
  nodeup/pkg/model/kube_apiserver_test.go
  nodeup/pkg/model/kubelet_test.go
  nodeup/pkg/model/protokube_test.go
  nodeup/pkg/model/tests/golden/minimal/cluster.yaml
  nodeup/pkg/model/tests/golden/minimal/tasks-kube-apiserver.yaml
  pkg/model/components/etcdmanager/model_test.go
  pkg/model/components/kubeapiserver/model_test.go
  pkg/testutils/modelharness.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/L

#8989 Add unit test for func matchesElbTags
  pkg/resources/aws/BUILD.bazel
  pkg/resources/aws/aws_test.go
Labels: approved, area/provider/aws, cncf-cla: yes, lgtm, ok-to-test, size/M

#9152 Automated cherry pick of #9121: Add EC2 instance lifecycle label to nodes
  cmd/kops-controller/controllers/node_controller.go
  pkg/nodeidentity/aws/identify.go
  pkg/nodeidentity/interfaces.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#9131 Remove support for reading legacy-format keypairs
  cmd/kops/util/factory.go
  examples/kops-api-example/apply.go
  examples/kops-api-example/up.go
  hack/.packages
  nodeup/pkg/model/kube_apiserver_test.go
  nodeup/pkg/model/kubelet_test.go
  pkg/client/simple/vfsclientset/clientset.go
  pkg/kubeconfig/create_kubecfg_test.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
  pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
  pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
  pkg/model/pki.go
  tests/BUILD.bazel
  tests/keypair_test.go
  upup/pkg/fi/ca.go
  upup/pkg/fi/clientset_castore.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
  upup/pkg/fi/cloudup/populatecluster_test.go
  upup/pkg/fi/fitasks/keypair.go
  upup/pkg/fi/nodeup/command.go
  upup/pkg/fi/vfs_castore.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/XL

#9153 Automated cherry pick of #9020: Upgrade amazon vpc cni to 1.6.1
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9155 Update alpha channels with May updates
  channels/alpha
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9150 Automated cherry pick of #9020: Upgrade amazon vpc cni to 1.6.1
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9104 Add support for Kubenet with containerd
  nodeup/pkg/model/BUILD.bazel
  nodeup/pkg/model/containerd.go
  nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml
  pkg/model/components/containerd.go
  tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/L

#9116 [Digital Ocean] Handle logic for kops edit/update cluster
  pkg/commands/status_discovery.go
  pkg/resources/digitalocean/BUILD.bazel
  pkg/resources/digitalocean/cloud.go
  upup/pkg/fi/cloudup/dotasks/loadbalancer.go
Labels: approved, area/provider/digitalocean, cncf-cla: yes, lgtm, ok-to-test, size/L

#9093 Move OS deprecations to deprecations section of relnotes
  docs/releases/1.17-NOTES.md
  docs/releases/1.18-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#9112 Add unit test case for pkg/k8sversion/version_test.go
  pkg/k8sversion/version_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#9105 Update OWNERS file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#9160 Minor doc fix. __address__ is not valid to use, will cuase etcd faili…
  docs/cluster_spec.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#9161 Cherrypick 8402 release 1.17
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha1/cluster.go
  pkg/apis/kops/v1alpha1/zz_generated.conversion.go
  pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/components/etcdmanager/model.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#9162 Revert "Add EC2 instance lifecycle label to nodes"
  cmd/kops-controller/controllers/node_controller.go
  pkg/nodeidentity/aws/identify.go
  pkg/nodeidentity/interfaces.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#9135 GCE: don't rely on hostname being correct
  Makefile
  pkg/model/components/kubelet.go
  tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-a-ha-gce-example-com_metadata_startup-script
  tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-b-ha-gce-example-com_metadata_startup-script
  tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-c-ha-gce-example-com_metadata_startup-script
  tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_nodes-ha-gce-example-com_metadata_startup-script
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
  upup/pkg/fi/nodeup/command.go
  util/pkg/vfs/context.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/M

#9164 Reduce test flakiness
  pkg/instancegroups/rollingupdate_test.go
Labels: approved, area/rolling-update, cncf-cla: yes, lgtm, size/XS

#9156 Add unit test case for pkg/apis/kops/util/versions_test.go
  pkg/apis/kops/util/BUILD.bazel
  pkg/apis/kops/util/versions_test.go
Labels: approved, area/api, cncf-cla: yes, lgtm, ok-to-test, size/M

#7252 Spotinst: New hybrid integration mode
  pkg/featureflag/featureflag.go
  pkg/model/awsmodel/BUILD.bazel
  pkg/model/awsmodel/autoscalinggroup.go
  pkg/model/spotinstmodel/BUILD.bazel
  pkg/model/spotinstmodel/instance_group.go
  pkg/resources/aws/aws.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: approved, area/provider/aws, cncf-cla: yes, lgtm, ok-to-test, size/L

#9167 Automated cherry pick of #8002: Minor fix to have proper indexing for digital ocean
  cmd/kops/create_cluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#9169 Fix nodetask.File dependency on owner
  upup/pkg/fi/nodeup/nodetasks/file.go
  upup/pkg/fi/nodeup/nodetasks/file_test.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/M

#9157 Networking cleanup
  cmd/kops/create_cluster.go
  cmd/kops/upgrade_cluster.go
  docs/cli/kops_create_cluster.md
  k8s/crds/kops.k8s.io_clusters.yaml
  nodeup/pkg/model/containerd.go
  nodeup/pkg/model/context.go
  nodeup/pkg/model/kubelet.go
  pkg/apis/kops/cluster.go
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/model/components/containerd.go
  pkg/model/components/containerd_test.go
  pkg/model/components/context.go
  pkg/model/components/docker.go
  pkg/model/components/kubecontrollermanager.go
  pkg/model/components/kubelet.go
  pkg/model/components/kubelet_test.go
  pkg/model/components/networking.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/networking.go
  upup/pkg/fi/cloudup/validation_test.go
Labels: approved, area/api, area/documentation, area/nodeup, cncf-cla: yes, lgtm, size/L

#9168 Automated cherry pick of #8237: Initial changes for load balancer task
  pkg/commands/BUILD.bazel
  pkg/commands/status_discovery.go
  pkg/model/domodel/BUILD.bazel
  pkg/model/domodel/api_loadbalancer.go
  pkg/resources/digitalocean/cloud.go
  pkg/resources/digitalocean/resources.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/dotasks/BUILD.bazel
  upup/pkg/fi/cloudup/dotasks/loadbalancer.go
  upup/pkg/fi/cloudup/dotasks/loadbalancer_fitask.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#9179 Update DigitalOcean cloud-controller-manager to v0.1.24
  upup/models/bindata.go
  upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#9184 Update etcd-manager to 3.0.20200527
  pkg/model/components/etcd.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
  pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
  pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#9181 Use debian as default image for DO images
  docs/getting_started/digitalocean.md
  upup/pkg/fi/cloudup/populate_instancegroup_spec.go
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#9182 Use systemd-timesyncd for Ubuntu 20.04
  nodeup/pkg/model/ntp.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9171 Remove all versions of a file form the S3 bucket
  upup/models/vfs.go
  util/pkg/vfs/fs.go
  util/pkg/vfs/gsfs.go
  util/pkg/vfs/k8sfs.go
  util/pkg/vfs/memfs.go
  util/pkg/vfs/ossfs.go
  util/pkg/vfs/s3fs.go
  util/pkg/vfs/sshfs.go
  util/pkg/vfs/swiftfs.go
  util/pkg/vfs/vfs.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#9174 Remove unused VFSScan
  util/pkg/vfs/BUILD.bazel
  util/pkg/vfs/vfssync.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#9170 Remove loader support for nodeup tasks not used in models
  upup/pkg/fi/nodeup/loader.go
  upup/pkg/fi/nodeup/nodetasks/BUILD.bazel
  upup/pkg/fi/nodeup/nodetasks/archive_test.go
  upup/pkg/fi/nodeup/nodetasks/bindmount_test.go
  upup/pkg/fi/nodeup/nodetasks/file.go
  upup/pkg/fi/nodeup/nodetasks/mount_disk.go
  upup/pkg/fi/nodeup/nodetasks/service.go
  upup/pkg/fi/nodeup/nodetasks/user.go
Labels: approved, area/nodeup, cncf-cla: yes, kind/cleanup, lgtm, size/L

#9187 Document etcd-manager backups retention settings
  docs/cluster_spec.md
  docs/operations/etcd_backup_restore_encryption.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#9183 Add gjtempleton as reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9185 Automated cherry pick of #9184: Update etcd-manager to 3.0.20200527
  pkg/model/components/etcd.go
  pkg/model/components/etcdmanager/model.go
  pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
  pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#9188 Fix nits for removal of S3 file versions
  pkg/model/iam/iam_builder.go
  upup/models/vfs.go
  util/pkg/vfs/fs.go
  util/pkg/vfs/gsfs.go
  util/pkg/vfs/k8sfs.go
  util/pkg/vfs/memfs.go
  util/pkg/vfs/ossfs.go
  util/pkg/vfs/s3fs.go
  util/pkg/vfs/sshfs.go
  util/pkg/vfs/swiftfs.go
  util/pkg/vfs/vfs.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#9065 Remove support for CoreOS and Jessie
  cmd/kops/update_cluster.go
  docs/cluster_spec.md
  docs/releases/1.18-NOTES.md
  docs/security.md
  images/utils-builder/README.md
  nodeup/pkg/distros/distribution.go
  nodeup/pkg/distros/identify.go
  nodeup/pkg/model/containerd.go
  nodeup/pkg/model/context.go
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/etcd.go
  nodeup/pkg/model/kube_controller_manager.go
  nodeup/pkg/model/kubectl.go
  nodeup/pkg/model/kubelet.go
  nodeup/pkg/model/logrotate.go
  nodeup/pkg/model/miscutils.go
  nodeup/pkg/model/ntp.go
  nodeup/pkg/model/update_service.go
  pkg/apis/kops/validation/BUILD.bazel
  pkg/apis/kops/validation/aws.go
  pkg/apis/kops/validation/aws_test.go
  pkg/model/bootstrapscript.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/nodeup/nodetasks/package.go
  upup/pkg/fi/nodeup/nodetasks/service.go
  upup/pkg/fi/nodeup/tags/tags.go
Labels: approved, area/api, area/documentation, area/nodeup, area/provider/aws, cncf-cla: yes, lgtm, size/L

#9191 Automated cherry pick of #9179: Update DigitalOcean cloud-controller-manager to v0.1.24
  upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#9186 Automated cherry pick of #9182: Use systemd-timesyncd for Ubuntu 20.04
  nodeup/pkg/model/ntp.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9196 Update Bazel rules for Docker to v0.14.2
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#9192 Automated cherry pick of #9181: Use debian as default image for DO images
  docs/getting_started/digitalocean.md
  upup/pkg/fi/cloudup/populate_instancegroup_spec.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#8826 Remove support for the legacy etcd provider as of k8s 1.18
  docs/releases/1.18-NOTES.md
  pkg/apis/kops/validation/legacy.go
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
Labels: approved, area/api, area/documentation, cncf-cla: yes, lgtm, size/L

#9193 Automated cherry pick of #8180: Refactor: Add Region() method to fi.Cloud #9116: Changes for handling kops update
  pkg/commands/status_discovery.go
  pkg/resources/digitalocean/BUILD.bazel
  pkg/resources/digitalocean/cloud.go
  pkg/resources/digitalocean/resources.go
  upup/pkg/fi/cloud.go
  upup/pkg/fi/cloudup/aliup/ali_cloud.go
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
  upup/pkg/fi/cloudup/baremetal/cloud.go
  upup/pkg/fi/cloudup/dotasks/loadbalancer.go
  upup/pkg/fi/cloudup/dotasks/volume.go
  upup/pkg/fi/cloudup/dotasks/volume_test.go
  upup/pkg/fi/cloudup/gce/gce_cloud.go
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/vsphere/vsphere_cloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#9201 Add deprecation notice for legacy etcd provider to 1.17 relnotes
  docs/releases/1.17-NOTES.md
  docs/releases/1.18-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#9194 Automated cherry pick of #9171: Remove all versions of a file form the S3 bucket #9188: Fix nits for removal of S3 file versions
  pkg/model/iam/iam_builder.go
  upup/models/vfs.go
  util/pkg/vfs/fs.go
  util/pkg/vfs/gsfs.go
  util/pkg/vfs/k8sfs.go
  util/pkg/vfs/memfs.go
  util/pkg/vfs/ossfs.go
  util/pkg/vfs/s3fs.go
  util/pkg/vfs/sshfs.go
  util/pkg/vfs/swiftfs.go
  util/pkg/vfs/vfs.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#9202 Add comment in OWNERS linking to test-infra OWNERS files
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9195 Automated cherry pick of #9171: Remove all versions of a file form the S3 bucket #9188: Fix nits for removal of S3 file versions
  pkg/model/iam/iam_builder.go
  upup/models/vfs.go
  util/pkg/vfs/fs.go
  util/pkg/vfs/gsfs.go
  util/pkg/vfs/k8sfs.go
  util/pkg/vfs/memfs.go
  util/pkg/vfs/ossfs.go
  util/pkg/vfs/s3fs.go
  util/pkg/vfs/sshfs.go
  util/pkg/vfs/swiftfs.go
  util/pkg/vfs/vfs.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#9203 Fix repo packages not being installed
  upup/pkg/fi/nodeup/nodetasks/package.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/S

#9205 Allow listing versions for objects in the S3 bucket
  pkg/model/iam/iam_builder.go
  pkg/model/iam/tests/iam_builder_master_legacy.json
  pkg/model/iam/tests/iam_builder_master_strict.json
  pkg/model/iam/tests/iam_builder_master_strict_ecr.json
  pkg/model/iam/tests/iam_builder_node_legacy.json
  pkg/model/iam/tests/iam_builder_node_strict.json
  pkg/model/iam/tests/iam_builder_node_strict_ecr.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#9165 Try validating multiple times before updating instancegroup
  pkg/instancegroups/instancegroups.go
Labels: approved, area/rolling-update, cncf-cla: yes, lgtm, size/M

#9206 Automated cherry pick of #9205: Allow listing versions for objects in the S3 bucket
  pkg/model/iam/iam_builder.go
  pkg/model/iam/tests/iam_builder_master_legacy.json
  pkg/model/iam/tests/iam_builder_master_strict.json
  pkg/model/iam/tests/iam_builder_master_strict_ecr.json
  pkg/model/iam/tests/iam_builder_node_legacy.json
  pkg/model/iam/tests/iam_builder_node_strict.json
  pkg/model/iam/tests/iam_builder_node_strict_ecr.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#9207 Automated cherry pick of #9205: Allow listing versions for objects in the S3 bucket
  pkg/model/iam/iam_builder.go
  pkg/model/iam/tests/iam_builder_master_legacy.json
  pkg/model/iam/tests/iam_builder_master_strict.json
  pkg/model/iam/tests/iam_builder_master_strict_ecr.json
  pkg/model/iam/tests/iam_builder_node_legacy.json
  pkg/model/iam/tests/iam_builder_node_strict.json
  pkg/model/iam/tests/iam_builder_node_strict_ecr.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#9204 Use kubescheduler.config.k8s.io/v1beta1 for Kubernetes 1.19
  nodeup/pkg/model/kube_scheduler.go
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/XS

#9208 Update adding_a_feature.md with more modern example
  docs/development/adding_a_feature.md
  nodeup/pkg/model/context.go
  pkg/apis/kops/validation/validation_test.go
Labels: approved, area/api, area/documentation, area/nodeup, cncf-cla: yes, lgtm, size/L

#9198 Add example for delete secret
  cmd/kops/delete_secret.go
  docs/cli/kops_delete_secret.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, ok-to-test, size/XS

#9215 Upgrade docker/containerd/containeros hashes to SHA256
  nodeup/pkg/model/containerd.go
  nodeup/pkg/model/docker.go
  nodeup/pkg/model/docker_test.go
  nodeup/pkg/model/kubelet.go
  nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml
  nodeup/pkg/model/tests/dockerbuilder/docker_18.06.3/tasks.yaml
  nodeup/pkg/model/tests/dockerbuilder/healthcheck/tasks.yaml
  nodeup/pkg/model/tests/dockerbuilder/logflags/tasks.yaml
  nodeup/pkg/model/tests/dockerbuilder/simple/tasks.yaml
Labels: approved, area/nodeup, cncf-cla: yes, lgtm, size/L

#9219 Release notes for 1.16.3
  docs/releases/1.16-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#9220 Remove extraneous markdown files in pkg/apis
  pkg/apis/kops/v1alpha2/CHANGES.md
  pkg/apis/kops/v1alpha2/upgrade.md
Labels: approved, area/api, cncf-cla: yes, lgtm, size/M

#9222 Release notes for 1.17.0
  docs/releases/1.17-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/M

#9218 Remove unused file
  cmd/kops/BUILD.bazel
  cmd/kops/create_secret_tls.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#9224 Update set-version script to bump tag in Makefile
  docs/development/release.md
  hack/set-version
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/XS

#9223 Start release notes for kops 1.19
  docs/releases/1.19-NOTES.md
Labels: approved, area/documentation, cncf-cla: yes, lgtm, size/S

#9227 Use AWS SDK to fetch metadata
  util/pkg/vfs/context.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#9228 S3 DeleteAllVersions: use pagination
  util/pkg/vfs/s3fs.go
Labels: approved, cncf-cla: yes, lgtm, size/M
