Repository kubernetes/kops, pull requests merged in 2021-10, with the labels that each got.

#12442 Add support for YAML/JSON output to 'kops get instances'
  cmd/kops/get_instances.go
Labels: cncf-cla: yes, lgtm, approved, size/M, ok-to-test

#12454 Update stable k8s versions
  channels/stable
Labels: cncf-cla: yes, lgtm, approved, size/S, area/channels

#12455 Bump aws-cni version to 1.9.1
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Labels: cncf-cla: yes, lgtm, approved, size/M, area/addons

#12452 Skip load balancer test in IPv6 clusters
  tests/e2e/pkg/tester/skip_regex.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#12456 Automated cherry pick of #12442: Add support for YAML/JSON output to 'kops get instances'
  cmd/kops/get_instances.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#12461 Remove unnecessary sysctl "net.ipv6.conf.all.accept_ra=2"
  nodeup/pkg/model/sysctls.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/XS

#12462 Automated cherry pick of #12461: Remove unnecessary sysctl "net.ipv6.conf.all.accept_ra=2"
  nodeup/pkg/model/sysctls.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/XS

#12464 Don't ignore channel value in toolbox template
  cmd/kops/toolbox_template.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#12463 Bump Cluster Autoscaler images
  pkg/model/components/clusterautoscaler.go
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
Labels: cncf-cla: yes, lgtm, approved, size/S

#12465 Automated cherry pick of #12464: Don't ignore channel value in toolbox template
  cmd/kops/toolbox_template.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#12466 v1alpha3 API fixup
  pkg/apis/kops/v1alpha3/BUILD.bazel
  pkg/apis/kops/v1alpha3/CHANGES.md
  pkg/apis/kops/v1alpha3/bastion.go
  pkg/apis/kops/v1alpha3/cluster.go
  pkg/apis/kops/v1alpha3/networking.go
  pkg/apis/kops/v1alpha3/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, area/api, approved, size/M

#12468 Release notes for 1.22.0-beta.2
  docs/releases/1.22-NOTES.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/M

#12469 Fail if an apimachinery conversion is missing
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/XS

#12473 kube-controller-manager also doesn't mount /srv/kubernetes
  docs/releases/1.22-NOTES.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS

#12472 Cleanup ClusterSpec code
  k8s/crds/kops.k8s.io_clusters.yaml
  nodeup/pkg/model/context.go
  pkg/apis/kops/cluster.go
  pkg/apis/kops/v1alpha2/cluster.go
  pkg/apis/kops/v1alpha3/cluster.go
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
  pkg/model/alimodel/policy_builder.go
  pkg/model/components/apiserver.go
  pkg/model/components/etcd.go
  pkg/model/context.go
  pkg/model/iam/iam_builder.go
  pkg/testutils/cluster.go
  tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/bastionadditional_user-data/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/complex/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/compress/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/digit/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/existing_iam/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/existing_sg/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/external_dns/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/external_dns_irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/externallb/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/externalpolicies/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/ha/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/ha_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/ipv6-cloudipam/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-gp3/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal_gce_private/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal_gossip/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/mixed_instances/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/mixed_instances_spot/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/nvidia/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/private-shared-ip/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/private-shared-subnet/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatedns1/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatedns2/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/privateflannel/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatekopeio/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/privateweave/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/public-jwks-apiserver/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/shared_subnet/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/shared_vpc/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/unmanaged/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/vfs-said/data/aws_s3_bucket_object_cluster-completed.spec_content
  upup/pkg/fi/cloudup/template_functions.go
Labels: cncf-cla: yes, lgtm, area/nodeup, area/api, approved, size/L, kind/cleanup, area/provider/alicloud

#12474 Automated cherry pick of #12463: Bump CAS images
  pkg/model/components/clusterautoscaler.go
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
Labels: cncf-cla: yes, lgtm, approved, size/S

#12471 Remove Docker overlayfs upgrade code
  cmd/kops/upgrade_cluster.go
  pkg/apis/kops/channel.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, area/api, approved, size/M

#12478 Update k8s dependencies to v1.22.2 for kOps 1.22
  go.mod
  go.sum
  protokube/pkg/hostmount/nsenter_linux.go
  protokube/pkg/hostmount/nsenter_unsupported.go
  tests/e2e/go.mod
  tests/e2e/go.sum
  vendor/k8s.io/apimachinery/third_party/forked/golang/LICENSE
  vendor/k8s.io/apimachinery/third_party/forked/golang/PATENTS
  vendor/k8s.io/client-go/third_party/forked/golang/LICENSE
  vendor/k8s.io/client-go/third_party/forked/golang/PATENTS
  vendor/k8s.io/client-go/util/jsonpath/jsonpath.go
  vendor/k8s.io/cloud-provider/go.mod
  vendor/k8s.io/cloud-provider/go.sum
  vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go
  vendor/k8s.io/legacy-cloud-providers/aws/BUILD.bazel
  vendor/k8s.io/legacy-cloud-providers/aws/aws.go
  vendor/k8s.io/mount-utils/fake_mounter.go
  vendor/k8s.io/mount-utils/go.mod
  vendor/k8s.io/mount-utils/go.sum
  vendor/k8s.io/mount-utils/mount.go
  vendor/k8s.io/mount-utils/mount_linux.go
  vendor/k8s.io/mount-utils/mount_unsupported.go
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, size/L

#12476 Spotinst: Update `spotinst/ocean-controller` to v1.0.78
  upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/M, area/addons

#12483 Update k8s dependencies to v1.22.2
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
  protokube/pkg/hostmount/nsenter_linux.go
  protokube/pkg/hostmount/nsenter_unsupported.go
  tests/e2e/go.mod
  tests/e2e/go.sum
  vendor/k8s.io/apimachinery/third_party/forked/golang/LICENSE
  vendor/k8s.io/apimachinery/third_party/forked/golang/PATENTS
  vendor/k8s.io/client-go/third_party/forked/golang/LICENSE
  vendor/k8s.io/client-go/third_party/forked/golang/PATENTS
  vendor/k8s.io/client-go/util/jsonpath/jsonpath.go
  vendor/k8s.io/cloud-provider/go.mod
  vendor/k8s.io/cloud-provider/go.sum
  vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go
  vendor/k8s.io/legacy-cloud-providers/aws/BUILD.bazel
  vendor/k8s.io/legacy-cloud-providers/aws/aws.go
  vendor/k8s.io/mount-utils/fake_mounter.go
  vendor/k8s.io/mount-utils/go.mod
  vendor/k8s.io/mount-utils/go.sum
  vendor/k8s.io/mount-utils/mount.go
  vendor/k8s.io/mount-utils/mount_linux.go
  vendor/k8s.io/mount-utils/mount_unsupported.go
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, size/L

#12414 Add Cilium agent pod annotations support to improve personalization
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha3/networking.go
  pkg/apis/kops/v1alpha3/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
  upup/pkg/fi/cloudup/template_functions.go
Labels: cncf-cla: yes, lgtm, area/api, approved, size/S, ok-to-test, area/addons

#12485 [DigitalOcean] Incorporate existing vpc support for kops
  pkg/model/domodel/droplets.go
  upup/pkg/fi/cloudup/dotasks/droplet.go
Labels: cncf-cla: yes, lgtm, approved, size/S, area/provider/digitalocean

#12486 Add kubescheduler.config.k8s.io/v1beta2 for k8s 1.22+
  nodeup/pkg/model/kube_scheduler.go
Labels: cncf-cla: yes, lgtm, area/nodeup, blocks-next, approved, size/XS

#12487 Automated cherry pick of #12486: Add kubescheduler.config.k8s.io/v1beta2 for k8s 1.22+
  nodeup/pkg/model/kube_scheduler.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/XS

#12484 Update remaining k8s dependencies to v1.22.2 for kOps 1.22
  hack/go.mod
  hack/go.sum
  tests/e2e/go.mod
  tests/e2e/go.sum
Labels: cncf-cla: yes, lgtm, approved, size/L

#12488 Automated cherry pick of #12424: protokube: don't try to connect to apiserver if not
  protokube/pkg/protokube/kube_boot.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#12490 Update controller-runtime to v0.10.2
  go.mod
  go.sum
  tests/e2e/go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/FAQ.md
  vendor/sigs.k8s.io/controller-runtime/OWNERS_ALIASES
  vendor/sigs.k8s.io/controller-runtime/README.md
  vendor/sigs.k8s.io/controller-runtime/TMP-LOGGING.md
  vendor/sigs.k8s.io/controller-runtime/doc.go
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/deleg_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/disabledeepcopy.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/metadata_infomer_wrapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/namespaced_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/recorder/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/recorder/recorder.go
  vendor/sigs.k8s.io/controller-runtime/pkg/leaderelection/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/leaderelection/leader_election.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/client_go_adapter.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/defaulter_custom.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator_custom.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/alias.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/conversion.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#12491 Update Calico to v3.20.2
  tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.16_content
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/S, area/addons

#12639 Log `kops toolbox dump` output to artifacts dir rather than stdout
  tests/e2e/kubetest2-kops/deployer/dumplogs.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#12637 Integration test cleanup
  cmd/kops/integration_test.go
  tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-anonymous-issuer-discovery.addons.k8s.io-k8s-1.16_content
  tests/integration/update_cluster/complex/data/aws_key_pair_kubernetes.complex.example.com-c4a6ed9aa889b9e2c39cd663eb9c7157_public_key
  tests/integration/update_cluster/external_dns/cloudformation.json
  tests/integration/update_cluster/external_dns/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/external_dns/data/aws_s3_bucket_object_minimal.example.com-addons-dns-controller.addons.k8s.io-k8s-1.12_content
  tests/integration/update_cluster/external_dns_irsa/data/aws_s3_bucket_object_minimal.example.com-addons-dns-controller.addons.k8s.io-k8s-1.12_content
  tests/integration/update_cluster/irsa/data/aws_iam_role_dns-controller.kube-system.sa.minimal.example.com_policy
  tests/integration/update_cluster/irsa/data/aws_iam_role_policy_dns-controller.kube-system.sa.minimal.example.com_policy
  tests/integration/update_cluster/nvidia/cloudformation.json
  tests/integration/update_cluster/nvidia/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/vfs-said/data/aws_iam_role_dns-controller.kube-system.sa.minimal.example.com_policy
  tests/integration/update_cluster/vfs-said/data/aws_iam_role_policy_dns-controller.kube-system.sa.minimal.example.com_policy
Labels: cncf-cla: yes, lgtm, approved, size/XL

#12641 Allow kops-controller to describe network interfaces
  pkg/model/iam/iam_builder.go
  tests/integration/update_cluster/minimal-ipv6-calico/cloudformation.json
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_iam_role_policy_masters.minimal-ipv6.example.com_policy
  tests/integration/update_cluster/minimal-ipv6-cilium/cloudformation.json
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_iam_role_policy_masters.minimal-ipv6.example.com_policy
  tests/integration/update_cluster/minimal-ipv6/cloudformation.json
  tests/integration/update_cluster/minimal-ipv6/data/aws_iam_role_policy_masters.minimal-ipv6.example.com_policy
Labels: cncf-cla: yes, lgtm, approved, size/S

#12635 Check for hardcoded partitions in integration tests
  hack/verify-terraform.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#12642 Enable Router Advertisements for Debian 11
  nodeup/pkg/model/sysctls.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/XS

#12643 Use prefixes for IPv6 with Calico
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
  pkg/model/components/calico.go
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.16_content
  tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.16_content
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
Labels: cncf-cla: yes, lgtm, area/nodeup, area/api, approved, size/L, area/addons

#12645 doc: Number subsections that are procedural steps
  docs/operations/rotate-secrets.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/S

#12646 Revert "Make dns-controller delete placeholder addresses for IPv6 cluster"
  dns-controller/pkg/dns/dnscontroller.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#12647 Prohibit masquerading in IPv6 clusters
  Makefile
  nodeup/pkg/model/cloudconfig_test.go
  pkg/apis/kops/validation/legacy.go
Labels: cncf-cla: yes, lgtm, area/nodeup, area/api, approved, size/M

#12650 Validate CNI can support IPv6
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
  upup/pkg/fi/cloudup/populate_cluster_spec_test.go
Labels: cncf-cla: yes, lgtm, area/api, approved, size/M

#12610 Remove unused Cilium fields from v1alpha3 API
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/networking.go
  pkg/apis/kops/v1alpha3/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, area/api, approved, size/XL

#12648 Remove obsolete documents
  docs/advanced/experimental.md
  docs/kops-server/README.md
  docs/node_authorization.md
  mkdocs.yml
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/M

#12652 Enable Router Advertisements for Debian 11 on ens* interfaces
  nodeup/pkg/model/sysctls.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/S

#12651 IPv6 requires external CCM
  cmd/kops/integration_test.go
  pkg/apis/kops/validation/validation.go
  tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
  tests/integration/update_cluster/minimal-ipv6-calico/cloudformation.json
  tests/integration/update_cluster/minimal-ipv6-calico/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_iam_role_policy_masters.minimal-ipv6.example.com_policy
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_launch_template_master-us-test-1a.masters.minimal-ipv6.example.com_user_data
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_launch_template_nodes.minimal-ipv6.example.com_user_data
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-storage-aws.addons.k8s.io-v1.15.0_content
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-ipv6-calico/in-v1alpha2.yaml
  tests/integration/update_cluster/minimal-ipv6-calico/kubernetes.tf
  tests/integration/update_cluster/minimal-ipv6-cilium/cloudformation.json
  tests/integration/update_cluster/minimal-ipv6-cilium/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_iam_role_policy_masters.minimal-ipv6.example.com_policy
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_launch_template_master-us-test-1a.masters.minimal-ipv6.example.com_user_data
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_launch_template_nodes.minimal-ipv6.example.com_user_data
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-storage-aws.addons.k8s.io-v1.15.0_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-ipv6-cilium/in-v1alpha2.yaml
  tests/integration/update_cluster/minimal-ipv6-cilium/kubernetes.tf
  tests/integration/update_cluster/minimal-ipv6/cloudformation.json
  tests/integration/update_cluster/minimal-ipv6/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-ipv6/data/aws_iam_role_policy_masters.minimal-ipv6.example.com_policy
  tests/integration/update_cluster/minimal-ipv6/data/aws_launch_template_master-us-test-1a.masters.minimal-ipv6.example.com_user_data
  tests/integration/update_cluster/minimal-ipv6/data/aws_launch_template_nodes.minimal-ipv6.example.com_user_data
  tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
  tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
  tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-storage-aws.addons.k8s.io-v1.15.0_content
  tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-ipv6/in-v1alpha2.yaml
  tests/integration/update_cluster/minimal-ipv6/kubernetes.tf
  upup/pkg/fi/cloudup/new_cluster.go
  upup/pkg/fi/cloudup/populate_cluster_spec_test.go
Labels: cncf-cla: yes, lgtm, area/api, approved, size/XXL

#12655 Release notes for 1.23.0-alpha.2
  docs/releases/1.23-NOTES.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/L
