Repository kubernetes/kops, pull requests merged in 2022-01, with the labels that each got.

#13066 Use latest GCP CCM for k8s 1.24
  pkg/model/components/gcpcloudcontrollermanager.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#12805 Add action for automatically tagging releases
  .github/workflows/tag-release.yml
  hack/tag-release.sh
Labels: cncf-cla: yes, lgtm, approved, size/M

#13067 Bump external-snapshotted to v5.0.0
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
  upup/models/cloudup/resources/addons/snapshot-controller.addons.k8s.io/k8s-1.20.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/XXL, area/addons

#13070 Release notes for 1.24.0-alpha.2
  docs/releases/1.24-NOTES.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/L

#13075 Update release process for automatic tagging
  docs/contributing/release-process.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/M

#13072 Automated cherry pick of #12805: Add action for automatically tagging releases #13071: Remove temporary restrictions on automatically tagging
  .github/workflows/tag-release.yml
  hack/tag-release.sh
Labels: cncf-cla: yes, lgtm, approved, size/M

#13073 Automated cherry pick of #12805: Add action for automatically tagging releases #13071: Remove temporary restrictions on automatically tagging
  .github/workflows/tag-release.yml
  hack/tag-release.sh
Labels: cncf-cla: yes, lgtm, approved, size/M

#13074 Automated cherry pick of #12805: Add action for automatically tagging releases #13071: Remove temporary restrictions on automatically tagging
  .github/workflows/tag-release.yml
  hack/tag-release.sh
Labels: cncf-cla: yes, lgtm, approved, size/M

#13071 Remove temporary restrictions on automatically tagging releases
  .github/workflows/tag-release.yml
  hack/tag-release.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13061 add flatcar note related to additionalUserData
  docs/instance_groups.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS, ok-to-test

#13076 Automated cherry pick of #13067: Bump external-snapshotted to v5.0.0
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
  upup/models/cloudup/resources/addons/snapshot-controller.addons.k8s.io/k8s-1.20.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/XXL, area/addons

#12983 Drain OpenStack loadbalancers
  cloudmock/gce/mock_gce_cloud.go
  pkg/instancegroups/instancegroups.go
  pkg/kubeconfig/create_kubecfg_test.go
  pkg/model/openstackmodel/servergroup.go
  pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer.yaml
  upup/pkg/fi/cloud.go
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
  upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
  upup/pkg/fi/cloudup/azure/azure_cloud.go
  upup/pkg/fi/cloudup/azuretasks/testing.go
  upup/pkg/fi/cloudup/do/cloud.go
  upup/pkg/fi/cloudup/do/mock_do_cloud.go
  upup/pkg/fi/cloudup/gce/instancegroups.go
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/instance.go
  upup/pkg/fi/cloudup/openstack/loadbalancer.go
  upup/pkg/fi/cloudup/openstack/mock_cloud.go
  upup/pkg/fi/cloudup/openstacktasks/poolassociation.go
Labels: cncf-cla: yes, lgtm, area/rolling-update, approved, size/L, area/provider/aws, area/provider/azure, area/provider/gcp, area/provider/openstack, area/provider/digitalocean

#13028 Extend terraform support for IPv6
  tests/integration/update_cluster/apiservernodes/kubernetes.tf
  tests/integration/update_cluster/aws-lb-controller/kubernetes.tf
  tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
  tests/integration/update_cluster/complex/kubernetes.tf
  tests/integration/update_cluster/compress/kubernetes.tf
  tests/integration/update_cluster/digit/kubernetes.tf
  tests/integration/update_cluster/existing_iam/kubernetes.tf
  tests/integration/update_cluster/existing_sg/kubernetes.tf
  tests/integration/update_cluster/external_dns/kubernetes.tf
  tests/integration/update_cluster/external_dns_irsa/kubernetes.tf
  tests/integration/update_cluster/externallb/kubernetes.tf
  tests/integration/update_cluster/externalpolicies/kubernetes.tf
  tests/integration/update_cluster/ha/kubernetes.tf
  tests/integration/update_cluster/irsa/kubernetes.tf
  tests/integration/update_cluster/karpenter/kubernetes.tf
  tests/integration/update_cluster/lifecycle_phases/network-kubernetes.tf
  tests/integration/update_cluster/many-addons-ccm-irsa/kubernetes.tf
  tests/integration/update_cluster/many-addons-ccm/kubernetes.tf
  tests/integration/update_cluster/many-addons/kubernetes.tf
  tests/integration/update_cluster/minimal-1.23/kubernetes.tf
  tests/integration/update_cluster/minimal-1.24/kubernetes.tf
  tests/integration/update_cluster/minimal-gp3/kubernetes.tf
  tests/integration/update_cluster/minimal-ipv6-calico/kubernetes.tf
  tests/integration/update_cluster/minimal-ipv6-cilium/kubernetes.tf
  tests/integration/update_cluster/minimal-ipv6-private/kubernetes.tf
  tests/integration/update_cluster/minimal-ipv6/kubernetes.tf
  tests/integration/update_cluster/minimal-warmpool/kubernetes.tf
  tests/integration/update_cluster/minimal/kubernetes.tf
  tests/integration/update_cluster/minimal_gossip/kubernetes.tf
  tests/integration/update_cluster/mixed_instances/kubernetes.tf
  tests/integration/update_cluster/mixed_instances_spot/kubernetes.tf
  tests/integration/update_cluster/nth_sqs_resources/kubernetes.tf
  tests/integration/update_cluster/nvidia/kubernetes.tf
  tests/integration/update_cluster/private-shared-ip/kubernetes.tf
  tests/integration/update_cluster/private-shared-subnet/kubernetes.tf
  tests/integration/update_cluster/privatecalico/kubernetes.tf
  tests/integration/update_cluster/privatecanal/kubernetes.tf
  tests/integration/update_cluster/privatecilium/kubernetes.tf
  tests/integration/update_cluster/privatecilium2/kubernetes.tf
  tests/integration/update_cluster/privateciliumadvanced/kubernetes.tf
  tests/integration/update_cluster/privatedns1/kubernetes.tf
  tests/integration/update_cluster/privatedns2/kubernetes.tf
  tests/integration/update_cluster/privateflannel/kubernetes.tf
  tests/integration/update_cluster/privatekopeio/kubernetes.tf
  tests/integration/update_cluster/privateweave/kubernetes.tf
  tests/integration/update_cluster/public-jwks-apiserver/kubernetes.tf
  tests/integration/update_cluster/shared_subnet/kubernetes.tf
  tests/integration/update_cluster/shared_vpc/kubernetes.tf
  tests/integration/update_cluster/unmanaged/kubernetes.tf
  tests/integration/update_cluster/vfs-said/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup_test.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
  upup/pkg/fi/cloudup/awstasks/subnet.go
  upup/pkg/fi/cloudup/terraform/target_hcl2.go
Labels: cncf-cla: yes, lgtm, approved, size/L, area/provider/aws

#13084 Update containerd to v1.6.0-beta.5
  pkg/model/components/containerd.go
  tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_master-us-test-1a.masters.minimal-ipv6.example.com_user_data
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_nodes.minimal-ipv6.example.com_user_data
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
  upup/pkg/fi/cloudup/containerd.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#13085 Release notes for 1.22.3
  docs/releases/1.22-NOTES.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/S

#13086 Spotinst: Update `spotinst/ocean-controller` to v1.0.81
  upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/XS, area/addons

#13081 Support price and priority cluster-autoscaler expanders
  docs/addons.md
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha3/componentconfig.go
  pkg/apis/kops/validation/validation.go
Labels: area/documentation, cncf-cla: yes, lgtm, area/api, approved, size/S, ok-to-test

#13091 Automated cherry pick of #13081: Support price and priority cluster-autoscaler expanders.
  docs/addons.md
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha3/componentconfig.go
  pkg/apis/kops/validation/validation.go
Labels: area/documentation, cncf-cla: yes, lgtm, area/api, approved, size/S

#13098 Update containerd to v1.6.0-rc.0
  pkg/model/components/containerd.go
  tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_master-us-test-1a.masters.minimal-ipv6.example.com_user_data
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_nodes.minimal-ipv6.example.com_user_data
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
  upup/pkg/fi/cloudup/containerd.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#13099 Automated cherry pick of #13084: Update containerd to v1.6.0-beta.5 #13098: Update containerd to v1.6.0-rc.0
  pkg/model/components/containerd.go
  tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
  upup/pkg/fi/cloudup/containerd.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#13097 decrease the openstack monitoring default timeout
  upup/pkg/fi/cloudup/new_cluster.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13106 Don't try to add node name to instances without node object
  cmd/kops/get_instances.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/bug

#13108 Automated cherry pick of #13106: Don't try to add node name to instances without node object
  cmd/kops/get_instances.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13107 Automated cherry pick of #13106: Don't try to add node name to instances without node object
  cmd/kops/get_instances.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13093 fix ipv4+ipv6 sec groups/listeners in OpenStack
  pkg/model/openstackmodel/BUILD.bazel
  pkg/model/openstackmodel/firewall.go
  pkg/model/openstackmodel/servergroup.go
  upup/pkg/fi/cloudup/openstacktasks/lblistener.go
Labels: cncf-cla: yes, lgtm, approved, size/L, kind/bug, area/provider/openstack

#13110 Do not create an IAM role for dns-controller on gossip clusters
  cmd/kops/integration_test.go
  pkg/model/iam/iam_builder.go
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_iam_role_masters.minimal.k8s.local_policy
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_iam_role_nodes.minimal.k8s.local_policy
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_iam_role_policy_masters.minimal.k8s.local_policy
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_iam_role_policy_nodes.minimal.k8s.local_policy
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_key_pair_kubernetes.minimal.k8s.local-c4a6ed9aa889b9e2c39cd663eb9c7157_public_key
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_launch_template_master-us-test-1a.masters.minimal.k8s.local_user_data
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_launch_template_nodes.minimal.k8s.local_user_data
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_discovery.json_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_etcd-cluster-spec-events_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_etcd-cluster-spec-main_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_keys.json_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_kops-version.txt_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_manifests-etcdmanager-events_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_manifests-etcdmanager-main_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_manifests-static-kube-apiserver-healthcheck_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_minimal.k8s.local-addons-bootstrap_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_minimal.k8s.local-addons-core.addons.k8s.io_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_minimal.k8s.local-addons-coredns.addons.k8s.io-k8s-1.12_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_minimal.k8s.local-addons-dns-controller.addons.k8s.io-k8s-1.12_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_minimal.k8s.local-addons-kops-controller.addons.k8s.io-k8s-1.16_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_minimal.k8s.local-addons-kubelet-api.rbac.addons.k8s.io-k8s-1.9_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_minimal.k8s.local-addons-limit-range.addons.k8s.io_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_minimal.k8s.local-addons-storage-aws.addons.k8s.io-v1.15.0_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal_gossip_irsa/id_rsa.pub
  tests/integration/update_cluster/minimal_gossip_irsa/in-v1alpha2.yaml
  tests/integration/update_cluster/minimal_gossip_irsa/kubernetes.tf
  upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#13112 Automated cherry pick of #13110: Do not create an IAM role for dns-controller on gossip
  cmd/kops/integration_test.go
  pkg/model/iam/iam_builder.go
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_iam_role_masters.minimal.k8s.local_policy
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_iam_role_nodes.minimal.k8s.local_policy
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_iam_role_policy_masters.minimal.k8s.local_policy
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_iam_role_policy_nodes.minimal.k8s.local_policy
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_key_pair_kubernetes.minimal.k8s.local-c4a6ed9aa889b9e2c39cd663eb9c7157_public_key
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_launch_template_master-us-test-1a.masters.minimal.k8s.local_user_data
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_launch_template_nodes.minimal.k8s.local_user_data
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_discovery.json_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_etcd-cluster-spec-events_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_etcd-cluster-spec-main_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_keys.json_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_kops-version.txt_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_manifests-etcdmanager-events_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_manifests-etcdmanager-main_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_manifests-static-kube-apiserver-healthcheck_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_minimal.k8s.local-addons-bootstrap_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_minimal.k8s.local-addons-core.addons.k8s.io_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_minimal.k8s.local-addons-coredns.addons.k8s.io-k8s-1.12_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_minimal.k8s.local-addons-dns-controller.addons.k8s.io-k8s-1.12_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_minimal.k8s.local-addons-kops-controller.addons.k8s.io-k8s-1.16_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_minimal.k8s.local-addons-kubelet-api.rbac.addons.k8s.io-k8s-1.9_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_minimal.k8s.local-addons-limit-range.addons.k8s.io_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_minimal.k8s.local-addons-storage-aws.addons.k8s.io-v1.15.0_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal_gossip_irsa/id_rsa.pub
  tests/integration/update_cluster/minimal_gossip_irsa/in-v1alpha2.yaml
  tests/integration/update_cluster/minimal_gossip_irsa/kubernetes.tf
  upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#13094 Automated cherry pick of #13093: fix ipv4+ipv6 sec groups/listeners in OpenStack
  pkg/model/openstackmodel/BUILD.bazel
  pkg/model/openstackmodel/firewall.go
  pkg/model/openstackmodel/servergroup.go
  upup/pkg/fi/cloudup/openstacktasks/lblistener.go
Labels: cncf-cla: yes, lgtm, approved, size/L, kind/bug, area/provider/openstack

#13088 Add ipv6 to relnotes
  docs/releases/1.23-NOTES.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS

#13030 Use IPv6-only subnets for worker nodes in private IPv6 topology
  docs/networking/ipv6.md
  pkg/apis/kops/cluster.go
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
  pkg/model/awsmodel/api_loadbalancer.go
  pkg/model/awsmodel/autoscalinggroup.go
  pkg/model/awsmodel/bastion.go
  pkg/model/awsmodel/network.go
  pkg/model/awsmodel/spotinst.go
  pkg/model/azuremodel/api_loadbalancer.go
  pkg/model/azuremodel/vmscaleset.go
  pkg/model/gcemodel/network.go
  pkg/model/openstackmodel/servergroup.go
  pkg/testutils/cluster.go
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-ipv6-private/in-v1alpha2.yaml
  tests/integration/update_cluster/minimal-ipv6-private/kubernetes.tf
  upup/pkg/fi/cloudup/deepvalidate_test.go
  upup/pkg/fi/cloudup/new_cluster.go
  upup/pkg/fi/cloudup/populate_cluster_spec_test.go
  upup/pkg/fi/cloudup/populate_instancegroup_spec.go
  upup/pkg/fi/cloudup/subnets.go
  upup/pkg/fi/cloudup/subnets_test.go
Labels: area/documentation, cncf-cla: yes, lgtm, area/api, approved, size/L, area/provider/aws, area/provider/azure, area/provider/gcp, area/provider/openstack, kind/office-hours

#13120 Remove networking flags as of k8s 1.24
  pkg/model/components/kubelet.go
  pkg/model/components/networking.go
  tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content
Labels: cncf-cla: yes, lgtm, approved, size/S

#12788 Remove featureflag for creating IPv6 clusters
  cmd/kops/create_cluster.go
  cmd/kops/integration_test.go
  docs/cli/kops_create_cluster.md
  pkg/featureflag/featureflag.go
Labels: area/documentation, cncf-cla: yes, lgtm, blocks-next, approved, size/S

#13049 Preload channel versions from namespaces
  channels/pkg/channels/addon.go
  channels/pkg/channels/addons_test.go
  channels/pkg/channels/channel_version.go
  channels/pkg/cmd/BUILD.bazel
  channels/pkg/cmd/apply_channel.go
  channels/pkg/cmd/apply_channel_test.go
  channels/pkg/cmd/get_addons.go
Labels: cncf-cla: yes, lgtm, approved, size/L, area/channels

#13111 Don't set unsupported configs by default
  pkg/apis/kops/v1alpha2/defaults.go
  pkg/apis/kops/v1alpha3/defaults.go
  tests/integration/update_cluster/minimal/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal/in-v1alpha2.yaml
Labels: cncf-cla: yes, lgtm, area/api, approved, size/M

#13128 Clean up kubelet networking flags for dockershim
  nodeup/pkg/model/kubelet.go
  nodeup/pkg/model/tests/kubelet/featuregates/cluster.yaml
  nodeup/pkg/model/tests/kubelet/featuregates/tasks.yaml
  nodeup/pkg/model/tests/kubelet/warmpool/cluster.yaml
  nodeup/pkg/model/tests/kubelet/warmpool/tasks.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha3/componentconfig.go
  pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/kops/validation/legacy.go
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/components/kubelet.go
  pkg/model/components/networking.go
  upup/pkg/fi/cloudup/populate_cluster_spec_test.go
Labels: cncf-cla: yes, lgtm, area/nodeup, area/api, approved, size/L

#13130 January bump of channels
  channels/alpha
  channels/stable
Labels: cncf-cla: yes, lgtm, approved, size/M, area/channels

#13134 Fix recommended kops versions in channels
  channels/alpha
  channels/stable
Labels: cncf-cla: yes, lgtm, approved, size/S, area/channels

#13135 Bump metrics-server to 0.6.0 and enable HA mode
  pkg/model/components/apiserver.go
  upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
Labels: cncf-cla: yes, lgtm, approved, size/M, area/addons

#13138 Automated cherry pick of #13131: expose external ccm metrics for OpenStack
  pkg/model/openstackmodel/firewall.go
Labels: cncf-cla: yes, lgtm, approved, size/S, area/provider/openstack

#13096 OpenStack - Add loadbalancer pool monitor to API LB
  pkg/model/openstackmodel/servergroup.go
  pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer.yaml
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/loadbalancer.go
  upup/pkg/fi/cloudup/openstack/mock_cloud.go
  upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel
  upup/pkg/fi/cloudup/openstacktasks/poolmonitor.go
  upup/pkg/fi/cloudup/openstacktasks/poolmonitor_fitask.go
Labels: cncf-cla: yes, lgtm, approved, size/L, area/provider/openstack

#13143 Bump CCM images
  pkg/model/components/awscloudcontrollermanager.go
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
Labels: cncf-cla: yes, lgtm, approved, size/S

#13142 Automated cherry pick of #13096: OpenStack - Add loadbalancer pool monitor to API LB
  pkg/model/openstackmodel/servergroup.go
  pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer.yaml
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/loadbalancer.go
  upup/pkg/fi/cloudup/openstack/mock_cloud.go
  upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel
  upup/pkg/fi/cloudup/openstacktasks/poolmonitor.go
  upup/pkg/fi/cloudup/openstacktasks/poolmonitor_fitask.go
Labels: cncf-cla: yes, lgtm, approved, size/L, area/provider/openstack

#13145 Automated cherry pick of #13143: Bump CCM images
  pkg/model/components/awscloudcontrollermanager.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13144 Automated cherry pick of #13143: Bump CCM images
  pkg/model/components/awscloudcontrollermanager.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13147 Automated cherry pick of #13111: No need to set kubelet in tests
  pkg/apis/kops/v1alpha2/defaults.go
  pkg/apis/kops/v1alpha3/defaults.go
  tests/integration/update_cluster/minimal/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal/in-v1alpha2.yaml
Labels: cncf-cla: yes, lgtm, area/api, approved, size/M

#13151 Bump karpenter to 0.5.6
  tests/integration/update_cluster/karpenter/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/karpenter/data/aws_s3_bucket_object_minimal.example.com-addons-karpenter.sh-k8s-1.19_content
  upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/S, area/addons

#13152 Promote alpha AMIs to stable
  channels/stable
  tests/integration/create_cluster/complex/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
  tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.18/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.19/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.21/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.22/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.23/expected-v1alpha2.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
  tests/integration/create_cluster/private/expected-v1alpha2.yaml
  tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
Labels: cncf-cla: yes, lgtm, approved, size/L, ok-to-test, area/channels

#13153 Bump 1.23 version in alpha channel
  channels/alpha
Labels: cncf-cla: yes, lgtm, approved, size/XS, area/channels

#13155 Add missing v prefix to default upgrade test version
  tests/e2e/scenarios/lib/common.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13154 Bump cert-manager and related godep to 1.6.2
  go.mod
  go.sum
  tests/e2e/go.sum
  tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
  upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, size/XL, area/addons

#13103 add node-drain-timeout flag to rolling-update
  cmd/kops/rolling-update_cluster.go
  docs/cli/kops_rolling-update_cluster.md
  docs/releases/1.23-NOTES.md
  pkg/instancegroups/instancegroups.go
  pkg/instancegroups/rollingupdate.go
Labels: area/documentation, cncf-cla: yes, lgtm, area/rolling-update, approved, size/S, ok-to-test

#13162 Replace deprecated aws.BackgroundContext with context.Background
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, area/provider/aws

#13167 Fix nil pointer when IAM not populated
  upup/pkg/fi/cloudup/template_functions.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13168 Automated cherry pick of #13166: JWKS / IRSA: Expose public ACLs to terraform
  tests/integration/update_cluster/aws-lb-controller/kubernetes.tf
  tests/integration/update_cluster/digit/kubernetes.tf
  tests/integration/update_cluster/external_dns_irsa/kubernetes.tf
  tests/integration/update_cluster/irsa/kubernetes.tf
  tests/integration/update_cluster/many-addons-ccm-irsa/kubernetes.tf
  tests/integration/update_cluster/minimal_gossip_irsa/kubernetes.tf
  tests/integration/update_cluster/public-jwks-apiserver/kubernetes.tf
  tests/integration/update_cluster/vfs-said/kubernetes.tf
  upup/pkg/fi/fitasks/managedfile.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#13166 JWKS / IRSA: Expose public ACLs to terraform
  tests/integration/update_cluster/aws-lb-controller/kubernetes.tf
  tests/integration/update_cluster/digit/kubernetes.tf
  tests/integration/update_cluster/external_dns_irsa/kubernetes.tf
  tests/integration/update_cluster/irsa/kubernetes.tf
  tests/integration/update_cluster/karpenter/kubernetes.tf
  tests/integration/update_cluster/many-addons-ccm-irsa/kubernetes.tf
  tests/integration/update_cluster/many-addons-ccm-irsa23/kubernetes.tf
  tests/integration/update_cluster/minimal_gossip_irsa/kubernetes.tf
  tests/integration/update_cluster/public-jwks-apiserver/kubernetes.tf
  tests/integration/update_cluster/vfs-said/kubernetes.tf
  upup/pkg/fi/fitasks/managedfile.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#13169 Automated cherry pick of #13166: JWKS / IRSA: Expose public ACLs to terraform
  tests/integration/update_cluster/aws-lb-controller/kubernetes.tf
  tests/integration/update_cluster/digit/kubernetes.tf
  tests/integration/update_cluster/external_dns_irsa/kubernetes.tf
  tests/integration/update_cluster/irsa/kubernetes.tf
  tests/integration/update_cluster/many-addons-ccm-irsa/kubernetes.tf
  tests/integration/update_cluster/public-jwks-apiserver/kubernetes.tf
  tests/integration/update_cluster/vfs-said/kubernetes.tf
  upup/pkg/fi/fitasks/managedfile.go
Labels: cncf-cla: yes, lgtm, approved, size/M
