Repository kubernetes/kops, pull requests merged in 2022-03, with the labels that each got.

#13312 Automated cherry pick of #13311: use own function to define CSI image version
  upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/template_functions.go
Labels: cncf-cla: yes, lgtm, approved, size/S, area/addons

#13314 Update kubetest2 deps
  tests/e2e/go.mod
  tests/e2e/go.sum
  tests/e2e/kubetest2-kops/deployer/common.go
  tests/e2e/kubetest2-kops/deployer/down.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#13311 use own function to define CSI image version
  upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/template_functions.go
Labels: cncf-cla: yes, lgtm, approved, size/S, kind/bug, area/addons

#13304 Add support for ed25519 keys in AWS
  pkg/pki/sshkey.go
  pkg/pki/sshkey_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M, ok-to-test

#13308 Append policy config map arguments only if UsePolicyConfigmap is true
  nodeup/pkg/model/kube_scheduler.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/XS, tide/merge-method-squash, ok-to-test

#13317 Automated cherry pick of #13304: add support for ed25519 keys
  pkg/pki/sshkey.go
  pkg/pki/sshkey_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#13306 Cluster config update after kOps update
  docs/operations/updates_and_upgrades.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS, tide/merge-method-squash, ok-to-test

#13325 Update containerd to v1.6.1
  pkg/model/components/containerd.go
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_master-us-test-1a.masters.minimal-ipv6.example.com_user_data
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_nodes.minimal-ipv6.example.com_user_data
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
  upup/pkg/fi/cloudup/containerd.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#13327 Automated cherry pick of #13325: Update containerd to v1.6.1
  pkg/model/components/containerd.go
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
  tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
  upup/pkg/fi/cloudup/containerd.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#13310 Fix GCE service account creation
  cloudmock/gce/mockiam/serviceaccounts.go
  pkg/model/gcemodel/service_accounts.go
  tests/integration/update_cluster/ha_gce/kubernetes.tf
  tests/integration/update_cluster/minimal_gce/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
  upup/pkg/fi/cloudup/gcetasks/serviceaccount.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/provider/gcp

#13329 Automated cherry pick of #13328: Use proper image and add health check
  tests/integration/update_cluster/irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/irsa/data/aws_s3_bucket_object_minimal.example.com-addons-eks-pod-identity-webhook.addons.k8s.io-k8s-1.16_content
  upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/S, area/addons

#13328 Use proper image and add health check
  tests/integration/update_cluster/irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/irsa/data/aws_s3_bucket_object_minimal.example.com-addons-eks-pod-identity-webhook.addons.k8s.io-k8s-1.16_content
  upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/S, area/addons

#13316 Automated cherry pick of #13308: check if UsePolicyConfigMap flag is true
  nodeup/pkg/model/kube_scheduler.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/XS

#13332 Automated cherry pick of #13304: add support for ed25519 keys
  pkg/pki/sshkey.go
  pkg/pki/sshkey_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#13333 Automated cherry pick of #13304: add support for ed25519 keys
  pkg/pki/sshkey.go
  pkg/pki/sshkey_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#13319 release 1.21.5
  Makefile
  pkg/model/components/kubeapiserver/model.go
  pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
  upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
  upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/jwks/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/service-account-iam/dns-controller.addons.k8s.io-k8s-1.12.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/service-account-iam/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/service-account-iam/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
  upup/pkg/fi/cloudup/urls_test.go
  version.go
Labels: area/documentation, cncf-cla: yes, lgtm, area/nodeup, area/api, area/rolling-update, approved, size/L, area/provider/aws, area/provider/gcp, area/provider/openstack, tide/merge-method-squash, area/addons

#13334 Update stable and alpha channels
  channels/alpha
  channels/stable
Labels: cncf-cla: yes, lgtm, approved, size/XS, area/channels

#13336 Release notes for 1.21.5
  docs/releases/1.21-NOTES.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/S

#13335 Add e2e for pod identity webhook
  tests/e2e/scenarios/lib/common.sh
  tests/e2e/scenarios/podidentitywebhook/cluster.yaml.tmpl
  tests/e2e/scenarios/podidentitywebhook/pod.yaml
  tests/e2e/scenarios/podidentitywebhook/run-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/L

#13338 Add webhook notes + some docs changes
  docs/addons.md
  docs/cluster_spec.md
  docs/releases/1.23-NOTES.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/M

#13289 Only delete node object on GCE
  pkg/instancegroups/instancegroups.go
  pkg/instancegroups/rollingupdate_test.go
Labels: cncf-cla: yes, lgtm, area/rolling-update, approved, size/S

#13340 Release notes for 1.23.0
  docs/releases/1.23-NOTES.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/S

#13342 Bump AWS CCM to 1.22.0-alpha.2
  pkg/model/components/awscloudcontrollermanager.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13357 Bump CCM 1.22 image. Use the 1.23 image for 1.24 due to latest being broken
  pkg/model/components/awscloudcontrollermanager.go
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
  tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
Labels: cncf-cla: yes, lgtm, approved, size/S

#13356 Update channels
  channels/alpha
  channels/stable
  tests/integration/create_cluster/complex/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
  tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.18/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.19/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.21/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.22/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.23/expected-v1alpha2.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
  tests/integration/create_cluster/private/expected-v1alpha2.yaml
  tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
Labels: cncf-cla: yes, lgtm, approved, size/L, area/channels

#12976 Recommend enabling IRSA for new clusters
  docs/getting_started/aws.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/S

#13359 Post 1.23.0 release doc updates
  README-ES.md
  docs/releases/1.23-NOTES.md
  docs/welcome/releases.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/S

#13362 [Digital Ocean] e2e tests - Fix seeding for generating random zones
  tests/e2e/kubetest2-kops/do/zones.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13363 wait for all targetGroups to drain
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/provider/aws, kind/bug

#13330 Support GPU in OpenStack
  docs/gpu.md
  k8s/crds/kops.k8s.io_instancegroups.yaml
  pkg/apis/kops/containerdconfig.go
  pkg/apis/kops/instancegroup.go
  pkg/apis/kops/v1alpha2/instancegroup.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha3/instancegroup.go
  pkg/apis/kops/v1alpha3/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/kops/validation/instancegroup.go
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/components/containerd.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
  upup/pkg/fi/cloudup/populate_instancegroup_spec.go
  upup/pkg/fi/nodeup/command.go
Labels: area/documentation, cncf-cla: yes, lgtm, area/nodeup, area/api, approved, size/L, area/provider/openstack

#13371 Automated cherry pick of #13369: Add missing permissions to aws lbc for IP targeting
  pkg/model/iam/iam_builder.go
  tests/integration/update_cluster/aws-lb-controller/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
  tests/integration/update_cluster/many-addons-ccm/data/aws_iam_role_policy_masters.minimal.example.com_policy
  tests/integration/update_cluster/many-addons/data/aws_iam_role_policy_masters.minimal.example.com_policy
Labels: cncf-cla: yes, lgtm, approved, size/S

#13373 If kubetest2 fails cluster validation, we run down before exiting
  tests/e2e/kubetest2-kops/deployer/up.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13374 If image is empty, have kops upgrade fill it in
  cmd/kops/upgrade_cluster.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13379 Update channels
  channels/alpha
  channels/stable
Labels: cncf-cla: yes, lgtm, approved, size/S, area/channels

#13367 Update HPA docs
  docs/horizontal_pod_autoscaling.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/S, ok-to-test

#13370 Clean up nodeup targets
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/S

#13381 Upgrade aws-iam-authenticator to v0.5.5
  upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/authentication.aws-k8s-1.12.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/authentication.aws-k8s-1.12.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/manifest.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S, ok-to-test, area/addons

#13383 Add protocol explicitly to services
  tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
  tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/irsa/data/aws_s3_bucket_object_minimal.example.com-addons-eks-pod-identity-webhook.addons.k8s.io-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.19.yaml.template
  upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/S, area/addons

#13366 Allow duplicate taint keys
  pkg/apis/kops/validation/instancegroup.go
  pkg/apis/kops/validation/instancegroup_test.go
Labels: cncf-cla: yes, lgtm, area/api, approved, size/S, area/provider/aws

#13382 [Digital Ocean] Remove sfo2 region from the list of supported DO regions
  docs/getting_started/digitalocean.md
  pkg/zones/wellknown.go
  tests/e2e/kubetest2-kops/do/zones.go
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/S

#13364 Fix long role names
  cloudmock/aws/mockiam/iamrole.go
  cmd/kops/BUILD.bazel
  cmd/kops/integration_test.go
  pkg/model/BUILD.bazel
  pkg/model/names.go
  tests/integration/update_cluster/minimal-longclustername/cloudformation.json
  tests/integration/update_cluster/minimal-longclustername/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-longclustername/data/aws_iam_role_masters.this.is.truly.a.really.really.long.cluster-name.m-kaamp9_policy
  tests/integration/update_cluster/minimal-longclustername/data/aws_iam_role_nodes.this.is.truly.a.really.really.long.cluster-name.min-h1jir9_policy
  tests/integration/update_cluster/minimal-longclustername/data/aws_iam_role_policy_masters.this.is.truly.a.really.really.long.cluster-name.m-kaamp9_policy
  tests/integration/update_cluster/minimal-longclustername/data/aws_iam_role_policy_nodes.this.is.truly.a.really.really.long.cluster-name.min-h1jir9_policy
  tests/integration/update_cluster/minimal-longclustername/data/aws_key_pair_kubernetes.this.is.truly.a.really.really.long.cluster-name.minimal.example.com-c4a6ed9aa889b9e2c39cd663eb9c7157_public_key
  tests/integration/update_cluster/minimal-longclustername/data/aws_launch_template_master-us-test-1a.masters.this.is.truly.a.really.really.long.cluster-name.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-longclustername/data/aws_launch_template_nodes.this.is.truly.a.really.really.long.cluster-name.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_etcd-cluster-spec-events_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_etcd-cluster-spec-main_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_kops-version.txt_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_manifests-etcdmanager-events_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_manifests-etcdmanager-main_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_manifests-static-kube-apiserver-healthcheck_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-core.addons.k8s.io_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-coredns.addons.k8s.io-k8s-1.12_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-dns-controller.addons.k8s.io-k8s-1.12_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-kops-controller.addons.k8s.io-k8s-1.16_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-kubelet-api.rbac.addons.k8s.io-k8s-1.9_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-limit-range.addons.k8s.io_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-storage-aws.addons.k8s.io-v1.15.0_content
  tests/integration/update_cluster/minimal-longclustername/id_rsa.pub
  tests/integration/update_cluster/minimal-longclustername/in-v1alpha2.yaml
  tests/integration/update_cluster/minimal-longclustername/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/iamrole.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL, area/provider/aws

#13385 Automated cherry pick of #13383: Add protocol explicitly to services
  tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
  tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/irsa/data/aws_s3_bucket_object_minimal.example.com-addons-eks-pod-identity-webhook.addons.k8s.io-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.19.yaml.template
  upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/S, area/addons

#13388 Automated cherry pick of #13373: If kubetest2 fails cluster validation, we run down before
  tests/e2e/kubetest2-kops/deployer/up.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13387 Automated cherry pick of #13373: If kubetest2 fails cluster validation, we run down before
  tests/e2e/kubetest2-kops/deployer/up.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13384 Automated cherry pick of #13366: Allow taints with unique key,value,effect
  pkg/apis/kops/validation/instancegroup.go
  pkg/apis/kops/validation/instancegroup_test.go
Labels: cncf-cla: yes, lgtm, area/api, approved, size/S

#13389 Remove oss-upload target since aliyun support has been removed
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13161 dev: create scripts to make it easier to run e2e tests
  hack/run-e2e-from-source.sh
  hack/run-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/M

#13391 Automated cherry pick of #13364: Add integration test for really long cluster names
  cloudmock/aws/mockiam/iamrole.go
  cmd/kops/BUILD.bazel
  cmd/kops/integration_test.go
  pkg/model/names.go
  tests/integration/update_cluster/minimal-longclustername/cloudformation.json
  tests/integration/update_cluster/minimal-longclustername/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-longclustername/data/aws_iam_role_masters.this.is.truly.a.really.really.long.cluster-name.m-kaamp9_policy
  tests/integration/update_cluster/minimal-longclustername/data/aws_iam_role_nodes.this.is.truly.a.really.really.long.cluster-name.min-h1jir9_policy
  tests/integration/update_cluster/minimal-longclustername/data/aws_iam_role_policy_masters.this.is.truly.a.really.really.long.cluster-name.m-kaamp9_policy
  tests/integration/update_cluster/minimal-longclustername/data/aws_iam_role_policy_nodes.this.is.truly.a.really.really.long.cluster-name.min-h1jir9_policy
  tests/integration/update_cluster/minimal-longclustername/data/aws_key_pair_kubernetes.this.is.truly.a.really.really.long.cluster-name.minimal.example.com-c4a6ed9aa889b9e2c39cd663eb9c7157_public_key
  tests/integration/update_cluster/minimal-longclustername/data/aws_launch_template_master-us-test-1a.masters.this.is.truly.a.really.really.long.cluster-name.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-longclustername/data/aws_launch_template_nodes.this.is.truly.a.really.really.long.cluster-name.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_etcd-cluster-spec-events_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_etcd-cluster-spec-main_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_kops-version.txt_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_manifests-etcdmanager-events_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_manifests-etcdmanager-main_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_manifests-static-kube-apiserver-healthcheck_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-core.addons.k8s.io_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-coredns.addons.k8s.io-k8s-1.12_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-dns-controller.addons.k8s.io-k8s-1.12_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-kops-controller.addons.k8s.io-k8s-1.16_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-kubelet-api.rbac.addons.k8s.io-k8s-1.9_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-limit-range.addons.k8s.io_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-storage-aws.addons.k8s.io-v1.15.0_content
  tests/integration/update_cluster/minimal-longclustername/id_rsa.pub
  tests/integration/update_cluster/minimal-longclustername/in-v1alpha2.yaml
  tests/integration/update_cluster/minimal-longclustername/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/iamrole.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL, area/provider/aws

#13386 Automated cherry pick of #13364: Add integration test for really long cluster names
  cloudmock/aws/mockiam/iamrole.go
  cmd/kops/BUILD.bazel
  cmd/kops/integration_test.go
  pkg/model/names.go
  tests/integration/update_cluster/minimal-longclustername/cloudformation.json
  tests/integration/update_cluster/minimal-longclustername/cloudformation.json.extracted.yaml
  tests/integration/update_cluster/minimal-longclustername/data/aws_iam_role_masters.this.is.truly.a.really.really.long.cluster-name.m-kaamp9_policy
  tests/integration/update_cluster/minimal-longclustername/data/aws_iam_role_nodes.this.is.truly.a.really.really.long.cluster-name.min-h1jir9_policy
  tests/integration/update_cluster/minimal-longclustername/data/aws_iam_role_policy_masters.this.is.truly.a.really.really.long.cluster-name.m-kaamp9_policy
  tests/integration/update_cluster/minimal-longclustername/data/aws_iam_role_policy_nodes.this.is.truly.a.really.really.long.cluster-name.min-h1jir9_policy
  tests/integration/update_cluster/minimal-longclustername/data/aws_key_pair_kubernetes.this.is.truly.a.really.really.long.cluster-name.minimal.example.com-c4a6ed9aa889b9e2c39cd663eb9c7157_public_key
  tests/integration/update_cluster/minimal-longclustername/data/aws_launch_template_master-us-test-1a.masters.this.is.truly.a.really.really.long.cluster-name.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-longclustername/data/aws_launch_template_nodes.this.is.truly.a.really.really.long.cluster-name.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_etcd-cluster-spec-events_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_etcd-cluster-spec-main_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_kops-version.txt_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_manifests-etcdmanager-events_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_manifests-etcdmanager-main_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_manifests-static-kube-apiserver-healthcheck_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-core.addons.k8s.io_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-coredns.addons.k8s.io-k8s-1.12_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-dns-controller.addons.k8s.io-k8s-1.12_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-kops-controller.addons.k8s.io-k8s-1.16_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-kubelet-api.rbac.addons.k8s.io-k8s-1.9_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-limit-range.addons.k8s.io_content
  tests/integration/update_cluster/minimal-longclustername/data/aws_s3_bucket_object_this.is.truly.a.really.really.long.cluster-name.minimal.example.com-addons-storage-aws.addons.k8s.io-v1.15.0_content
  tests/integration/update_cluster/minimal-longclustername/id_rsa.pub
  tests/integration/update_cluster/minimal-longclustername/in-v1alpha2.yaml
  tests/integration/update_cluster/minimal-longclustername/kubernetes.tf
  upup/pkg/fi/cloudup/awstasks/iamrole.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL, area/provider/aws

#13392 Remove pr target
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13375 Release notes for 1.24.0-alpha.3
  docs/releases/1.24-NOTES.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/L

#13394 [Digital Ocean] Use available regions as per the latest DO documentation
  pkg/zones/wellknown.go
  tests/e2e/kubetest2-kops/do/zones.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13341 Build kops images with ko
  Makefile
  hack/install-ko.sh
Labels: cncf-cla: yes, lgtm, approved, size/M, area/kops-controller, area/addons

#13390 Clean up kops build targets
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/M

#13397 update k8s dependencies
  go.mod
  go.sum
  tests/e2e/go.mod
  tests/e2e/go.sum
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.conversion.go
  vendor/k8s.io/client-go/tools/pager/pager.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
  vendor/k8s.io/kubectl/pkg/drain/default.go
  vendor/k8s.io/legacy-cloud-providers/aws/aws.go
  vendor/k8s.io/legacy-cloud-providers/gce/gce_annotations.go
  vendor/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer_external.go
  vendor/k8s.io/mount-utils/mount_helper_common.go
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/k8s.io/mount-utils/mount_helper_windows.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/merge.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#13398 Automated cherry pick of #13397: update k8s dependencies
  go.mod
  go.sum
  tests/e2e/go.mod
  tests/e2e/go.sum
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.conversion.go
  vendor/k8s.io/client-go/tools/pager/pager.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
  vendor/k8s.io/kubectl/pkg/drain/default.go
  vendor/k8s.io/legacy-cloud-providers/aws/aws.go
  vendor/k8s.io/legacy-cloud-providers/gce/gce_annotations.go
  vendor/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer_external.go
  vendor/k8s.io/mount-utils/mount_helper_common.go
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/k8s.io/mount-utils/mount_helper_windows.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/merge.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#13403 Update golangci-lint to v1.45.0
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
  tests/e2e/go.sum
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/mod/semver/semver.go
  vendor/golang.org/x/tools/go/ast/astutil/enclosing.go
  vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gocommand/vendor.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/golang.org/x/tools/internal/typeparams/BUILD.bazel
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/normalize.go
  vendor/golang.org/x/tools/internal/typeparams/termlist.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/golang.org/x/tools/internal/typeparams/typeterm.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, size/L

#13402 Use k8s.gcr.io for k8s side-loaded images
  nodeup/pkg/model/kube_apiserver.go
  nodeup/pkg/model/kube_controller_manager.go
  nodeup/pkg/model/kube_proxy.go
  nodeup/pkg/model/kube_scheduler.go
  nodeup/pkg/model/tests/golden/side-loading/tasks-kube-apiserver-amd64.yaml
  nodeup/pkg/model/tests/golden/side-loading/tasks-kube-apiserver-arm64.yaml
  nodeup/pkg/model/tests/golden/side-loading/tasks-kube-controller-manager-amd64.yaml
  nodeup/pkg/model/tests/golden/side-loading/tasks-kube-controller-manager-arm64.yaml
  nodeup/pkg/model/tests/golden/side-loading/tasks-kube-proxy-amd64.yaml
  nodeup/pkg/model/tests/golden/side-loading/tasks-kube-proxy-arm64.yaml
  nodeup/pkg/model/tests/golden/side-loading/tasks-kube-scheduler-amd64.yaml
  nodeup/pkg/model/tests/golden/side-loading/tasks-kube-scheduler-arm64.yaml
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/M

#13401 Use ko-builds for dev-upload
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/S

#13407 Don't use bazel for dev-upload
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/M

#13408 Clean up the rest of the dev-upload targets
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/L

#13405 AWS-NODE-TERMINATION: Add possibility to set a tune image version
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha3/componentconfig.go
  pkg/apis/kops/v1alpha3/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/components/nodeterminationhandler.go
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
  tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_cluster-completed.spec_content
  tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_nthsqsresources.longclustername.example.com-addons-bootstrap_content
  tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_nthsqsresources.longclustername.example.com-addons-node-termination-handler.aws-k8s-1.11_content
  upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template
Labels: cncf-cla: yes, lgtm, area/api, approved, size/M, ok-to-test, area/addons

#13412 Update netflify deps
  images/mkdocs/Dockerfile
  images/mkdocs/requirements.txt
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13415 Promote alpha to stable
  channels/stable
Labels: cncf-cla: yes, lgtm, approved, size/S, area/channels

#13410 Correctly detect GovCloud regions
  util/pkg/vfs/s3context.go
  util/pkg/vfs/s3context_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#13417 Automated cherry pick of #13410: Correctly detect GovCloud regions
  util/pkg/vfs/s3context.go
  util/pkg/vfs/s3context_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#13418 Automated cherry pick of #13403: Update golangci-lint to v1.45.0
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
  tests/e2e/go.sum
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/mod/semver/semver.go
  vendor/golang.org/x/tools/go/ast/astutil/enclosing.go
  vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gocommand/vendor.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/golang.org/x/tools/internal/typeparams/BUILD.bazel
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/normalize.go
  vendor/golang.org/x/tools/internal/typeparams/termlist.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/golang.org/x/tools/internal/typeparams/typeterm.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, size/M

#13419 dev-upload from upload directory, not bazelupload
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13416 Automated cherry pick of #13410: Correctly detect GovCloud regions
  util/pkg/vfs/s3context.go
  util/pkg/vfs/s3context_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#13414 fix member update when draining
  upup/pkg/fi/cloudup/openstack/BUILD.bazel
  upup/pkg/fi/cloudup/openstack/instance.go
  upup/pkg/fi/cloudup/openstack/loadbalancer.go
Labels: cncf-cla: yes, lgtm, approved, size/S, kind/bug, area/provider/openstack

#13421 Update the security docs
  docs/security.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/M

#13420 Remove id var, which is never used beyond that if test
  protokube/cmd/protokube/main.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13395 Pin actions to a full length commit SHA
  .github/workflows/main.yml
  .github/workflows/tag-release.yml
Labels: cncf-cla: yes, lgtm, approved, size/S, ok-to-test

#13378 Do not return a '-1' exit if no keys found and json/yaml output
  cmd/kops/get_sshpublickeys.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, ok-to-test

#13409 Use non-bazel builds in kubetest2
  Makefile
  hack/install-ko.sh
Labels: cncf-cla: yes, lgtm, approved, size/M, kind/office-hours

#13426 Run CSI controller in masters
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_minimal-gce.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_minimal-gce.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
  upup/models/cloudup/resources/addons/gcp-pd-csi-driver.addons.k8s.io/k8s-1.23.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/S, area/addons

#13428 Push ko-built images to staging
  Makefile
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, approved, size/M

#13424 Automated cherry pick of #13378: Do not return a '-1' exit if no keys found and json/yaml
  cmd/kops/get_sshpublickeys.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13423 Included githubactions in dependabot config
  .github/dependabot.yml
Labels: cncf-cla: yes, lgtm, approved, size/XS, ok-to-test

#13430 Use golang 1.18 for building
  .github/workflows/main.yml
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S

#13432 Use golang 1.18.0 explicitly
  .github/workflows/main.yml
  Makefile
  cloudbuild.yaml
  hack/install-gsutil.sh
Labels: cncf-cla: yes, lgtm, approved, size/M

#13434 Install gcloud instead of gsutil
  hack/install-gsutil.sh
Labels: cncf-cla: yes, lgtm, approved, size/S

#13435 Use the correct upload folder for the latest.txt file
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13437 Fix upload dir in cloudbuild-artifacts target
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/XS

#13438 Skip upstream e2e log dump
  tests/e2e/pkg/tester/tester.go
Labels: cncf-cla: yes, lgtm, approved, size/XS
