Repository kubernetes/kops, pull requests merged in 2023-04, with the labels that each got.

#15272 Automated cherry pick of #15270: Update kube-router to v1.5.3
  upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/XS, area/addons

#15290 Corrected multiple broken link in calico.md
  docs/networking/calico.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/S, kind/documentation

#15293 Pin github.com/docker/* to v20.10.21+incompatible
  go.mod
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, size/XS

#15294 Update bastion.md
  docs/bastion.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS, ok-to-test

#15295 broken link removed as not available
  docs/architecture/kops-controller.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS, kind/documentation

#15303 Create simple test that runs with boskos
  tests/e2e/scenarios/aws-boskos/README.md
  tests/e2e/scenarios/aws-boskos/run-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/L

#15181 [DigitalOcean] support terraform provider for DO
  pkg/featureflag/featureflag.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/dotasks/droplet.go
  upup/pkg/fi/cloudup/dotasks/sshkey.go
  upup/pkg/fi/cloudup/dotasks/volume.go
  upup/pkg/fi/cloudup/terraform/target_hcl2.go
  util/pkg/vfs/s3fs.go
Labels: cncf-cla: yes, lgtm, approved, size/L, area/provider/digitalocean

#15291 Allow Cluster Autoscaler to ignore daemon pods
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha3/componentconfig.go
  pkg/apis/kops/v1alpha3/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/components/clusterautoscaler.go
  tests/integration/update_cluster/cluster-autoscaler-priority-expander-custom/data/aws_s3_object_cas-priority-expander-custom.example.com-addons-bootstrap_content
  tests/integration/update_cluster/cluster-autoscaler-priority-expander-custom/data/aws_s3_object_cas-priority-expander-custom.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
  tests/integration/update_cluster/cluster-autoscaler-priority-expander-custom/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/cluster-autoscaler-priority-expander/data/aws_s3_object_cas-priority-expander.example.com-addons-bootstrap_content
  tests/integration/update_cluster/cluster-autoscaler-priority-expander/data/aws_s3_object_cas-priority-expander.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
  tests/integration/update_cluster/cluster-autoscaler-priority-expander/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
  tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
  tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
  tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
  tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
  tests/integration/update_cluster/many-addons/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
  upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
Labels: cncf-cla: yes, lgtm, area/api, approved, size/L, area/addons

#15266 OpenStack: Add network-cidr config for etcd-manager
  pkg/model/components/etcdmanager/model.go
Labels: cncf-cla: yes, lgtm, area/api, approved, size/XS, ok-to-test

#15311 Increase max_map_count in sysctls.go
  nodeup/pkg/model/sysctls.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/XS, ok-to-test

#15313 Automated cherry pick of #15311: Increase max_map_count in sysctls.go
  nodeup/pkg/model/sysctls.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/XS

#15283 gce: Avoid spurious changes for ForwardingRule
  upup/pkg/fi/cloudup/gcetasks/forwardingrule.go
Labels: cncf-cla: yes, lgtm, approved, size/S, area/provider/gcp

#15320 Bump golang to 1.20
  .github/workflows/main.yml
  .github/workflows/update-deps.yml
  .golangci.yaml
  cloudbuild.yaml
  go.mod
  hack/go.mod
  tests/e2e/go.mod
Labels: cncf-cla: yes, lgtm, approved, size/S

#15334 scaleway: small fixes in loadbalancer tasks
  upup/pkg/fi/cloudup/scaleway/cloud.go
  upup/pkg/fi/cloudup/scalewaytasks/lb_backend.go
  upup/pkg/fi/cloudup/scalewaytasks/lb_frontend.go
  upup/pkg/fi/cloudup/scalewaytasks/loadbalancer.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, approved, size/S, area/provider/scaleway

#15323 docs(release): fix typo in 1.22 Notes
  docs/releases/1.22-NOTES.md
Labels: area/documentation, cncf-cla: yes, lgtm, needs-ok-to-test, approved, size/S

#15326 docs(release): fix broken CLI link in 1.19 notes
  docs/releases/1.19-NOTES.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS, ok-to-test

#15331 gce: set ip address family on all FirewallRule tasks
  pkg/model/gcemodel/api_loadbalancer.go
  pkg/model/gcemodel/external_access.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, area/provider/gcp

#15338 Spot: Update Spot Ocean controller to the latest version (1.0.90)
  upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/XS, ok-to-test, area/addons

#15341 add csi cinder metrics
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha3/componentconfig.go
  pkg/apis/kops/v1alpha3/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/openstackmodel/firewall.go
  upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template
Labels: cncf-cla: yes, lgtm, area/api, approved, size/M, area/provider/openstack, area/addons

#15333 scaleway: downgrade CCM + refactoring tags
  cmd/kops/integration_test.go
  pkg/model/scalewaymodel/instances.go
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_manifests-etcdmanager-events-control-plane-fr-par-1_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_manifests-etcdmanager-main-control-plane-fr-par-1_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-scaleway-cloud-controller.addons.k8s.io-k8s-1.24_content
  tests/integration/update_cluster/minimal_scaleway/data/scaleway_instance_server_control-plane-fr-par-1_user_data
  tests/integration/update_cluster/minimal_scaleway/data/scaleway_instance_server_nodes-fr-par-1_user_data
  tests/integration/update_cluster/minimal_scaleway/kubernetes.tf
  upup/models/cloudup/resources/addons/scaleway-cloud-controller.addons.k8s.io/k8s-1.24.yaml.template
  upup/pkg/fi/cloudup/scaleway/cloud.go
  upup/pkg/fi/cloudup/scalewaytasks/instance.go
Labels: cncf-cla: yes, lgtm, approved, size/M, ok-to-test, area/addons, area/provider/scaleway

#15348 makefile: use go run to execute ko
  Makefile
  hack/install-ko.sh
Labels: cncf-cla: yes, lgtm, approved, size/M

#15347 gce: fix icmpv6 in firewalls
  pkg/model/gcemodel/firewall.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, area/provider/gcp

#15350 scaleway: doc: temporary env var to pull protokube
  docs/getting_started/scaleway.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS, ok-to-test

#15351 Block bootstrap when the node already exists
  cmd/kops-controller/main.go
  cmd/kops-controller/pkg/server/server.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/kops-controller
