Repository kubernetes/kops, pull requests merged in 2023-11, with the labels that each got.

#16076 Fix vet errors
  nodeup/pkg/model/kubectl.go
  nodeup/pkg/model/protokube.go
  nodeup/pkg/model/update_service.go
  pkg/kubemanifest/visitor.go
  pkg/nodeidentity/openstack/identify.go
  pkg/nodeidentity/scaleway/identify.go
  protokube/cmd/protokube/main.go
  upup/pkg/fi/cloudup/awstasks/iamrole.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/S, area/provider/aws, area/provider/scaleway

#16073 toolbox dump: include AWS route table objects
  pkg/resources/aws/routetable.go
Labels: cncf-cla: yes, lgtm, approved, size/S, area/provider/aws

#16083 Document incompatability with Amazon VPC CNI and 22.04
  docs/networking/aws-vpc.md
  docs/operations/images.md
  docs/releases/1.27-NOTES.md
  docs/releases/1.28-NOTES.md
  docs/releases/1.29-NOTES.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/S

#16081 fix: concurrent map write panic
  upup/pkg/fi/cloudup/gce/gce_cloud.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, area/provider/gcp, ok-to-test

#16087 Automated cherry pick of #16085: Update Go to v1.21.4
  .github/workflows/main.yml
  .github/workflows/update-deps.yml
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S

#16085 Update Go to v1.21.4
  .github/workflows/main.yml
  .github/workflows/update-deps.yml
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S

#16086 Automated cherry pick of #16085: Update Go to v1.21.4
  .github/workflows/main.yml
  .github/workflows/update-deps.yml
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S

#16037 Thread context through some slower AWS tasks
  cloudmock/aws/mockautoscaling/group.go
  cloudmock/aws/mockautoscaling/tags.go
  cloudmock/aws/mockautoscaling/warmpool.go
  cloudmock/aws/mockec2/launch_templates.go
  pkg/instancegroups/rollingupdate_test.go
  pkg/resources/aws/aws.go
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
  upup/pkg/fi/cloudup/awstasks/autoscalinglifecyclehook.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
  upup/pkg/fi/cloudup/awstasks/warmpool.go
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
  upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
  upup/pkg/fi/nodeup/command.go
Labels: cncf-cla: yes, lgtm, area/nodeup, area/rolling-update, approved, size/L, area/provider/aws

#16091 Fix Designate naming typo
  docs/getting_started/openstack.md
Labels: area/documentation, cncf-cla: yes, lgtm, needs-ok-to-test, approved, size/XS

#16102 Don't get cluster --full when attempting leak cleanup
  tests/e2e/kubetest2-kops/deployer/down.go
  tests/e2e/pkg/kops/state.go
  tests/e2e/pkg/tester/tester.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#16107 Update Calico to v3.26.4
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.25_content
  tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.25_content
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.25.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/XL, area/addons

#16112 Check cluster information when filtering instances
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/server_group.go
Labels: cncf-cla: yes, lgtm, approved, size/M, kind/bug, area/provider/openstack

#16114 Automated cherry pick of #16112: check kops cluster name when filtering instances in
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/server_group.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/provider/openstack

#16110 Update kube-router to 1.6
  docs/networking/kube-router.md
  docs/releases/1.27-NOTES.md
  docs/releases/1.28-NOTES.md
  pkg/apis/kops/validation/validation.go
  upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
Labels: area/documentation, cncf-cla: yes, lgtm, area/api, approved, size/S, ok-to-test, area/addons

#16115 allow local file VFS in asset copy
  pkg/assets/copyfile.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16116 Automated cherry pick of #16110: Update kube-router to v1.6.0
  docs/networking/kube-router.md
  docs/releases/1.27-NOTES.md
  docs/releases/1.28-NOTES.md
  pkg/apis/kops/validation/validation.go
  upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
Labels: area/documentation, cncf-cla: yes, lgtm, area/api, approved, size/S, area/addons

#16118 Automated cherry pick of #16113: Replace * in IAM tags when IRSA namespace has wildcard
  pkg/model/context.go
  tests/integration/update_cluster/irsa/kubernetes.tf
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16120 bump k8s and ubuntu ami versions in alpha
  channels/alpha
Labels: cncf-cla: yes, lgtm, approved, size/S, area/channels

#16123 Fix parsing of newer kubernetes version URLs
  pkg/apis/kops/util/versions.go
  pkg/apis/kops/util/versions_test.go
Labels: cncf-cla: yes, lgtm, area/api, approved, size/M

#16099 Spotinst: Feature/add multi arch in VNG and resource tag specification
  docs/getting_started/spot-ocean.md
  go.mod
  go.sum
  pkg/model/awsmodel/spotinst.go
  upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go
  upup/pkg/fi/cloudup/spotinsttasks/ocean.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/elastigroup/providers/aws/aws.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/elastigroup/providers/azure/v3/azure.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/elastigroup/providers/gcp/gcp.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/ocean.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/cluster.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/cluster_ecs.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/launchspec.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/azure_np/cluster_np.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/azure_np/common.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/azure_np/nodegroup_np.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/azure_np/service.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/gcp/cluster.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/gcp/launchspec.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/spark/cluster.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/spark/spark.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/version.go
  vendor/modules.txt
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/L, area/provider/aws, ok-to-test, area/provider/spotinst

#16109 Improve kops edit command
  cmd/kops/edit_cluster.go
  docs/cli/kops_edit_cluster.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS, ok-to-test

#16128 kops: Support quotes in --set flags
  cmd/kops/create_cluster.go
  cmd/kops/edit_cluster.go
  cmd/kops/edit_instancegroup.go
  cmd/kops/flags_stringslice_lazyquotes.go
  docs/cli/kops_create_cluster.md
  docs/cli/kops_edit_cluster.md
  docs/cli/kops_edit_instancegroup.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/L

#16117 skip file remapping if same host
  pkg/assets/builder.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#16131 Promote alpha to stable
  channels/stable
  tests/integration/create_cluster/cilium-eni/expected-v1alpha2.yaml
  tests/integration/create_cluster/complex-private/expected-v1alpha2.yaml
  tests/integration/create_cluster/complex/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
  tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.24/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.25/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.26-arm64/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.26-irsa/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.26/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.27/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.28/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.29/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal_feature-gates/expected-v1alpha2.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
  tests/integration/create_cluster/private/expected-v1alpha2.yaml
  tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
Labels: cncf-cla: yes, lgtm, approved, size/L, area/channels

#16136 limit jobname value to 80
  tests/e2e/kubetest2-kops/deployer/common.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16138 build: add script for rapid development of kops-controller
  hack/dev-push-kops-controller.sh
Labels: cncf-cla: yes, lgtm, approved, size/M

#16140 feat: Support multiple token verifiers in kops-controller
  cmd/kops-controller/main.go
  pkg/bootstrap/authenticate.go
  pkg/bootstrap/chain.go
  upup/pkg/fi/cloudup/awsup/aws_verifier.go
  upup/pkg/fi/cloudup/azure/verifier.go
  upup/pkg/fi/cloudup/do/verifier.go
  upup/pkg/fi/cloudup/gce/tpm/gcetpmverifier/tpmverifier.go
  upup/pkg/fi/cloudup/hetzner/verifier.go
  upup/pkg/fi/cloudup/openstack/verifier.go
  upup/pkg/fi/cloudup/scaleway/verifier.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/L, area/provider/aws, area/provider/azure, area/provider/gcp, area/provider/openstack, area/provider/digitalocean, area/kops-controller, area/provider/hetzner, area/provider/scaleway
