Repository kubernetes/kops, pull requests merged in 2024-01, with the labels that each got.

#16198 Include pod logs in toolbox dump
  cmd/kops/toolbox_dump.go
  pkg/dump/podlogs.go
  pkg/dump/resourcedumper.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#16202 test: Print the `create cluster` command
  tests/e2e/kubetest2-kops/deployer/up.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16200 Dump previous and current container logs separately
  pkg/dump/podlogs.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#16207 aws: Add option for setting QPS and Burst for EBS CSI Driver
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha3/componentconfig.go
  pkg/apis/kops/v1alpha3/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
Labels: cncf-cla: yes, lgtm, area/api, approved, size/M, area/addons

#16208 Spotinst: Bump controller version to 1.0.97
  upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/XS, ok-to-test, area/addons

#16209 feat: add us-west zone for hetzner
  pkg/zones/wellknown.go
  upup/pkg/fi/cloudup/hetzner/utils.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, ok-to-test, area/provider/hetzner

#16205 Check if kubeconfig exists before dumping resources
  cmd/kops/toolbox_dump.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#16210 Promote alpha to stable
  channels/stable
  tests/integration/create_cluster/cilium-eni/expected-v1alpha2.yaml
  tests/integration/create_cluster/complex-private/expected-v1alpha2.yaml
  tests/integration/create_cluster/complex/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
  tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.24/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.25/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.26-arm64/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.26-irsa/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.26/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.27/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.28/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.29/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal_feature-gates/expected-v1alpha2.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
  tests/integration/create_cluster/private/expected-v1alpha2.yaml
  tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
Labels: cncf-cla: yes, lgtm, approved, size/L, area/channels

#16213 aws: Use instance metadata to get warm pool state
  pkg/model/iam/iam_builder.go
  upup/pkg/fi/nodeup/command.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/M

#16211 Dump and redact secrets
  pkg/dump/resourcedumper.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#16214 Update to Cilium 1.14.5
  pkg/model/components/cilium.go
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
Labels: cncf-cla: yes, lgtm, approved, size/L

#16215 Update Cilium to v1.13.10
  pkg/model/components/cilium.go
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
Labels: cncf-cla: yes, lgtm, approved, size/L

#16216 aws: Retrieve instance info only when max pods is not set
  nodeup/pkg/model/kubelet.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/M

#16221 Remove kube-system cert-manager webhook exclusion
  tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
  tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
  tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
  tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-certmanager.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-certmanager.io-k8s-1.16_content
  upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
Labels: cncf-cla: yes, lgtm, approved, size/M, area/addons

#16220 Jaeger tracing visualizer improvements
  docs/img/jaeger-query.png
  docs/opentelemetry.md
  tools/otel/traceserver/main.go
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/M

#16223 aws: Set provider ID when starting kubelet
  nodeup/pkg/model/kubelet.go
  nodeup/pkg/model/kubelet_test.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/S

#16225 scale-test: Reduce validation count and interval
  tests/e2e/scenarios/scalability/run-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16228 Add option for setting CCM ConcurrentNodeSyncs
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha3/componentconfig.go
  pkg/apis/kops/v1alpha3/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  tests/integration/update_cluster/complex/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
  tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-bootstrap_content
  tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
  tests/integration/update_cluster/complex/in-v1alpha2.yaml
Labels: cncf-cla: yes, lgtm, area/api, approved, size/S

#16229 aws: Skip deleting ASG instances without volumes
  pkg/resources/aws/aws.go
Labels: cncf-cla: yes, lgtm, approved, size/S, area/provider/aws

#16231 Make cluster deletion configurable
  cmd/kops/delete_cluster.go
  docs/cli/kops_delete_cluster.md
  pkg/resources/ops/delete.go
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/S

#16204 scale-test: Use single nodes instance group for AWS
  tests/e2e/kubetest2-kops/deployer/down.go
  tests/e2e/scenarios/scalability/run-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/S

#16234 Bump kubetest2
  tests/e2e/go.mod
  tests/e2e/go.sum
Labels: cncf-cla: yes, lgtm, approved, size/S

#16236 test: Improve cluster deletion defaults
  cmd/kops/delete_cluster.go
  docs/cli/kops_delete_cluster.md
  tests/e2e/kubetest2-kops/deployer/down.go
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/S

#16238 Replace `k8s.io/utils/strings/slices` with `golang.org/x/exp/slices`
  pkg/model/gcemodel/api_loadbalancer.go
  tests/e2e/go.mod
  tests/e2e/kubetest2-kops/deployer/up.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, area/provider/gcp

#16242 Bump GCP terraform provider to latest
  tests/integration/update_cluster/ha_gce/kubernetes.tf
  tests/integration/update_cluster/many-addons-gce/kubernetes.tf
  tests/integration/update_cluster/minimal_gce/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_longclustername/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
  upup/pkg/fi/cloudup/terraform/target_hcl2.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#16243 docs: fix broken example command
  docs/security.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS, ok-to-test

#16246 Revert "aws: Skip deleting ASG instances without volumes"
  pkg/resources/aws/aws.go
Labels: cncf-cla: yes, lgtm, approved, area/provider/aws, kind/office-hours

#16247 Automated cherry pick of #16245: Update Go to v1.21.6
  .github/workflows/main.yml
  .github/workflows/update-deps.yml
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S

#16245 Update Go to v1.21.6
  .github/workflows/main.yml
  .github/workflows/update-deps.yml
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S

#16248 Prefer external endpoints when building kubeconfig
  pkg/kubeconfig/create_kubecfg.go
  upup/pkg/fi/cloud.go
  upup/pkg/fi/cloudup/gce/gce_cloud.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/provider/gcp

#16251 aws: Terminate ASG instances in batches of 100 instances
  pkg/resources/aws/aws.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/provider/aws

#16252 aws: Ignore InvalidRouteTableID.NotFound errors during cluster deletion
  pkg/resources/aws/aws.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/provider/aws

#16253 aws: fix maxPods when cilium ipam=eni is used
  nodeup/pkg/model/kubelet.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/XS, ok-to-test

#16257 Update containerd to v1.7.12
  pkg/model/components/containerd.go
  tests/integration/update_cluster/additionalobjects/data/aws_launch_template_master-us-test-1a.masters.additionalobjects.example.com_user_data
  tests/integration/update_cluster/additionalobjects/data/aws_launch_template_nodes.additionalobjects.example.com_user_data
  tests/integration/update_cluster/additionalobjects/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/additionalobjects/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/additionalobjects/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-1.27/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.27/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-1.28/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.28/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.28/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.28/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.28/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-1.29/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.29/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.29/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.29/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.29/data/aws_s3_object_nodeupconfig-nodes_content
  upup/pkg/fi/cloudup/runc.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#16258 Switch to GCS url for upgrades tests
  tests/e2e/scenarios/upgrade-ab/run-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16262 Use dns=none for newly created clusters including for AWS and GCE
  tests/integration/create_cluster/cilium-eni/expected-v1alpha2.yaml
  tests/integration/create_cluster/complex-private/expected-v1alpha2.yaml
  tests/integration/create_cluster/complex/expected-v1alpha2.yaml
  tests/integration/create_cluster/gce_byo_sa/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
  tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.24/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.25/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.26-arm64/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.26-gce/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.26-irsa/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.26/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.27/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.28/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.29-gce/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.29/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal_feature-gates/expected-v1alpha2.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
  tests/integration/create_cluster/private/expected-v1alpha2.yaml
  tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
  tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
  upup/pkg/fi/cloudup/new_cluster.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#16263 Update aws-sdk-go to v1.49.24
  go.mod
  go.sum
  tests/e2e/go.mod
  tests/e2e/go.sum
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, size/S

#16260 Automated cherry pick of #16216: aws: Retrieve instance info only when max pods is not set #16253: aws: fix maxPods when cilium ipam is used
  nodeup/pkg/model/kubelet.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/M

#16176 test: Set num-nodes flag
  tests/e2e/pkg/tester/skip_regex.go
  tests/e2e/pkg/tester/tester.go
Labels: cncf-cla: yes, lgtm, approved, size/S, tide/merge-method-squash

#15829 Refactor: Replace ForAPIServer with WellKnownServices
  pkg/commands/toolbox_enroll.go
  pkg/model/awsmodel/api_loadbalancer.go
  pkg/model/bootstrapscript.go
  pkg/model/bootstrapscript_test.go
  pkg/model/domodel/api_loadbalancer.go
  pkg/model/gcemodel/api_loadbalancer.go
  pkg/model/hetznermodel/loadbalancer.go
  pkg/model/openstackmodel/servergroup.go
  pkg/model/openstackmodel/servergroup_test.go
  pkg/model/openstackmodel/tests/servergroup/adds-additional-security-groups.yaml
  pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-ClusterSpec.yaml
  pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-InstanceGroupSpec.yaml
  pkg/model/openstackmodel/tests/servergroup/configures-allowed-address-pairs-with-annotations.yaml
  pkg/model/openstackmodel/tests/servergroup/configures-server-group-affinity-with-annotations.yaml
  pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-auto-zone-distribution.yaml
  pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer-dns-none.yaml
  pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer.yaml
  pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion.yaml
  pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-external-router.yaml
  pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion-2.yaml
  pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion.yaml
  pkg/model/openstackmodel/tests/servergroup/one-master-one-node-without-bastion-no-public-ip-association.yaml
  pkg/model/openstackmodel/tests/servergroup/one-master-one-node.yaml
  pkg/model/openstackmodel/tests/servergroup/single-zone-setup-3-masters-1-node-without-bastion-with-API-loadbalancer-dns-none.yaml
  pkg/model/openstackmodel/tests/servergroup/truncate-cluster-names-to-42-characters.yaml
  pkg/model/openstackmodel/tests/servergroup/uses-instance-group-subnet-as-availability-zones-fallback.yaml
  pkg/model/openstackmodel/tests/servergroup/uses-instance-group-zones-as-availability-zones.yaml
  pkg/model/scalewaymodel/api_loadbalancer.go
  pkg/wellknownservices/wellknownservices.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/awstasks/classic_load_balancer.go
  upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
  upup/pkg/fi/cloudup/azuretasks/loadbalancer.go
  upup/pkg/fi/cloudup/dotasks/loadbalancer.go
  upup/pkg/fi/cloudup/gcetasks/address.go
  upup/pkg/fi/cloudup/hetznertasks/loadbalancer.go
  upup/pkg/fi/cloudup/openstacktasks/floatingip.go
  upup/pkg/fi/cloudup/openstacktasks/instance.go
  upup/pkg/fi/cloudup/openstacktasks/port.go
  upup/pkg/fi/cloudup/scalewaytasks/loadbalancer.go
  upup/pkg/fi/has_address.go
Labels: cncf-cla: yes, lgtm, approved, size/XL, area/provider/aws, area/provider/azure, area/provider/gcp, area/provider/openstack, area/provider/digitalocean, area/provider/hetzner, area/provider/scaleway

#16265 gce: fix nlb firewall rules, operations and alias network subnets
  pkg/model/gcemodel/firewall.go
  tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
  upup/pkg/fi/cloudup/gce/network.go
  upup/pkg/fi/cloudup/gce/op.go
Labels: cncf-cla: yes, lgtm, approved, size/S, area/provider/gcp

#16271 openstack: Include kube-apiserver controlplane ports in dns=none
  pkg/model/openstackmodel/servergroup.go
  pkg/model/openstackmodel/tests/servergroup/adds-additional-security-groups.yaml
  pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-ClusterSpec.yaml
  pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-InstanceGroupSpec.yaml
  pkg/model/openstackmodel/tests/servergroup/configures-allowed-address-pairs-with-annotations.yaml
  pkg/model/openstackmodel/tests/servergroup/configures-server-group-affinity-with-annotations.yaml
  pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-auto-zone-distribution.yaml
  pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer-dns-none.yaml
  pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer.yaml
  pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion.yaml
  pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-external-router.yaml
  pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion-2.yaml
  pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion.yaml
  pkg/model/openstackmodel/tests/servergroup/one-master-one-node-without-bastion-no-public-ip-association.yaml
  pkg/model/openstackmodel/tests/servergroup/one-master-one-node.yaml
  pkg/model/openstackmodel/tests/servergroup/single-zone-setup-3-masters-1-node-without-bastion-with-API-loadbalancer-dns-none.yaml
  pkg/model/openstackmodel/tests/servergroup/truncate-cluster-names-to-42-characters.yaml
  pkg/model/openstackmodel/tests/servergroup/uses-instance-group-subnet-as-availability-zones-fallback.yaml
  pkg/model/openstackmodel/tests/servergroup/uses-instance-group-zones-as-availability-zones.yaml
  upup/pkg/fi/cloudup/openstacktasks/port.go
Labels: cncf-cla: yes, lgtm, approved, size/L, area/provider/openstack

#16256 Increase CCM workers to speed up node bootstrap process
  tests/e2e/scenarios/scalability/run-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16275 Add 1.28 release notes to docs menu
  mkdocs.yml
Labels: cncf-cla: yes, lgtm, approved, size/XS, ok-to-test

#16277 Add support to configure HPA Controller concurrent syncs flag in HPA/KCM Controller
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha3/componentconfig.go
  pkg/apis/kops/v1alpha3/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  tests/integration/update_cluster/complex/data/aws_launch_template_master-us-test-1a.masters.complex.example.com_user_data
  tests/integration/update_cluster/complex/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/complex/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
  tests/integration/update_cluster/complex/in-v1alpha2.yaml
Labels: cncf-cla: yes, lgtm, area/api, approved, size/S

#16280 Add support to configure Job Controller concurrent syncs flag in Job…
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha3/componentconfig.go
  pkg/apis/kops/v1alpha3/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  tests/integration/update_cluster/complex/data/aws_launch_template_master-us-test-1a.masters.complex.example.com_user_data
  tests/integration/update_cluster/complex/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/complex/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
  tests/integration/update_cluster/complex/in-v1alpha2.yaml
Labels: cncf-cla: yes, lgtm, area/api, approved, size/S

#16281 Refactor: Plumb context through GCE firewallRule methods
  cloudmock/gce/mockcompute/forwarding_rule.go
  pkg/resources/gce/gce.go
  upup/pkg/fi/cloudup/gce/compute.go
  upup/pkg/fi/cloudup/gcetasks/forwardingrule.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/provider/gcp

#16266 Fix dumping logs for GCE scale tests
  cmd/kops/toolbox_dump.go
  pkg/dump/dumper.go
  pkg/resources/gce/dump.go
  tests/e2e/kubetest2-kops/deployer/common.go
  tests/e2e/kubetest2-kops/deployer/deployer.go
  tests/e2e/kubetest2-kops/deployer/dumplogs.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/provider/gcp

#16268 Add `boskos-resource-type` flag to use different GCE projects for scale/gpu testing
  tests/e2e/kubetest2-kops/deployer/common.go
  tests/e2e/kubetest2-kops/deployer/deployer.go
  tests/e2e/kubetest2-kops/deployer/up.go
  tests/e2e/scenarios/build/run-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/M

#16283 OpenStack: update CSI images
  upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/S, area/addons

#16285 toolbox dump: output correct type for target groups
  pkg/resources/aws/aws.go
Labels: cncf-cla: yes, lgtm, approved, size/S, area/provider/aws

#16284 chore(channels): bump k8s and ubuntu ami versions in alpha channel
  channels/alpha
Labels: cncf-cla: yes, lgtm, approved, size/S, area/channels

#16290 Fix: support comparison of int types in dry-run
  upup/pkg/fi/dryrun_target.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16288 refactor: NetworkLoadBalancer Name should match Name tag
  pkg/model/awsmodel/api_loadbalancer.go
  pkg/model/awsmodel/bastion.go
  pkg/model/names.go
  upup/pkg/fi/cloudup/awstasks/dnsname.go
  upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
Labels: cncf-cla: yes, lgtm, approved, size/S, area/provider/aws

#16289 Tweak: Set Scheme on NLB tasks for public load balancers
  pkg/model/awsmodel/api_loadbalancer.go
  pkg/model/awsmodel/bastion.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, area/provider/aws

#16292 refactor: Introduce runTests helper method into aws tests
  upup/pkg/fi/cloudup/awstasks/egressonlyinternetgateway_test.go
  upup/pkg/fi/cloudup/awstasks/elastic_ip_test.go
  upup/pkg/fi/cloudup/awstasks/internetgateway_test.go
  upup/pkg/fi/cloudup/awstasks/securitygroup_test.go
  upup/pkg/fi/cloudup/awstasks/subnet_test.go
  upup/pkg/fi/cloudup/awstasks/vpc_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L, area/provider/aws

#16295 Refactor: Move NLB listing function into awsup
  cloudmock/aws/mockelbv2/loadbalancers.go
  pkg/resources/aws/aws.go
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
  upup/pkg/fi/cloudup/awsup/elbv2_loadbalancers.go
Labels: cncf-cla: yes, lgtm, approved, size/L, area/provider/aws

#16297 chore(networking): bump aws cni to 1.16.2
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XXL, area/addons
