Repository kubernetes/kops, pull requests merged in 2024-02, with the labels that each got.

#16303 cherry pick of #16302: Update runc & containerd
  pkg/model/components/containerd.go
  tests/integration/update_cluster/minimal-1.27/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.27/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_nodeupconfig-nodes_content
  upup/pkg/fi/cloudup/runc.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#16302 Update runc & containerd
  pkg/model/components/containerd.go
  tests/integration/update_cluster/additionalobjects/data/aws_launch_template_master-us-test-1a.masters.additionalobjects.example.com_user_data
  tests/integration/update_cluster/additionalobjects/data/aws_launch_template_nodes.additionalobjects.example.com_user_data
  tests/integration/update_cluster/additionalobjects/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/additionalobjects/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/additionalobjects/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-1.27/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.27/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-1.28/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.28/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.28/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.28/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.28/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-1.29/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.29/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.29/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.29/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.29/data/aws_s3_object_nodeupconfig-nodes_content
  upup/pkg/fi/cloudup/runc.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#16305 cherrypick: update containerd & runc versions
  pkg/model/components/containerd.go
  tests/integration/update_cluster/minimal-1.27/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.27/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_nodeupconfig-nodes_content
  upup/pkg/fi/cloudup/containerd.go
  upup/pkg/fi/cloudup/runc.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#16306 chore(channels): promote alpha to stable
  channels/stable
  tests/integration/create_cluster/cilium-eni/expected-v1alpha2.yaml
  tests/integration/create_cluster/complex-private/expected-v1alpha2.yaml
  tests/integration/create_cluster/complex/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
  tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.24/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.25/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.26-arm64/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.26-irsa/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.26/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.27/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.28/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.29/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal_feature-gates/expected-v1alpha2.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
  tests/integration/create_cluster/private/expected-v1alpha2.yaml
  tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
Labels: cncf-cla: yes, lgtm, approved, size/L, area/channels

#16294 refactor: wait for load balancer readiness using a private field
  pkg/model/awsmodel/api_loadbalancer.go
  upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/provider/aws

#16181 Add GCE scale testing on kops
  tests/e2e/scenarios/scalability/run-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/L, area/provider/gcp, area/addons

#16313 fix(nodeup): set `MACAddressPolicy=none` when using AWS VPC CNI
  nodeup/pkg/model/networking/amazon-vpc-routed-eni.go
  upup/pkg/fi/nodeup/command.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/M

#16316 Upgrade AWS Load Balancer Controller to v2.7.0
  tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
  tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
  tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
  tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
  tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
  tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
  upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.19.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/M, ok-to-test, area/addons

#16319 Automated cherry pick of #16313: fix(nodeup): set `MACAddressPolicy` to `none` when using AWS
  nodeup/pkg/model/networking/amazon-vpc-routed-eni.go
  upup/pkg/fi/nodeup/command.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/M

#16315 Update to cilium 1.15
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
  pkg/model/components/cilium.go
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/minimal-ipv6-cilium/kubernetes.tf
  tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-warmpool/kubernetes.tf
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/minimal_scaleway/kubernetes.tf
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium-eni/kubernetes.tf
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium/kubernetes.tf
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium2/kubernetes.tf
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privateciliumadvanced/kubernetes.tf
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.15.yaml.template
  upup/pkg/fi/cloudup/bootstrapchannelbuilder/cilium.go
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
Labels: cncf-cla: yes, lgtm, area/api, approved, size/L, ok-to-test, area/addons

#16320 Automated cherry pick of #16318: added image minimum and maximum gc age
  k8s/crds/kops.k8s.io_clusters.yaml
  k8s/crds/kops.k8s.io_instancegroups.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha3/componentconfig.go
  pkg/apis/kops/v1alpha3/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, area/api, approved, size/M

#16318 feat: added image minimum and maximum gc age
  k8s/crds/kops.k8s.io_clusters.yaml
  k8s/crds/kops.k8s.io_instancegroups.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha3/componentconfig.go
  pkg/apis/kops/v1alpha3/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, area/api, approved, size/M, ok-to-test

#16299 Refactor: Split out NLB Listener into its own task
  cloudmock/aws/mockelbv2/listeners.go
  pkg/model/awsmodel/api_loadbalancer.go
  pkg/model/awsmodel/bastion.go
  pkg/model/names.go
  upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
  upup/pkg/fi/cloudup/awstasks/networkloadbalancerlistener.go
  upup/pkg/fi/cloudup/awstasks/networkloadbalancerlistener_fitask.go
Labels: cncf-cla: yes, lgtm, approved, size/XL, area/provider/aws

#16324 refactor: Drop TargetGroups from NetworkLoadBalancer task
  pkg/model/awsmodel/api_loadbalancer.go
  pkg/model/awsmodel/bastion.go
  upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/provider/aws

#16325 Dont set -num-nodes on karpenter-managed clusters
  tests/e2e/pkg/tester/tester.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16326 docs: Remove warning about Amazon VPC CNI not being compatible with Ubuntu 22.04
  docs/networking/aws-vpc.md
  docs/operations/images.md
  docs/releases/1.29-NOTES.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/S

#16329 Set LimitNOFILE to 1048576 instead of `infinity`
  nodeup/pkg/model/containerd.go
  nodeup/pkg/model/tests/containerdbuilder/complex/tasks.yaml
  nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/XS

#16334 Set KUBECONFIG for LBC's ginkgo tests
  tests/e2e/scenarios/aws-lb-controller/run-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16337 Docs: fix typos in office hours page
  docs/welcome/office_hours.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS

#16338 clockmock: Add more methods that take a context
  cloudmock/aws/mockautoscaling/tags.go
  cloudmock/aws/mockelbv2/tags.go
  cloudmock/aws/mockelbv2/targetgroups.go
  cloudmock/aws/mockroute53/records.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#16342 Move DNS topology setup earlier in cluster creation
  tests/integration/create_cluster/complex-private/expected-v1alpha2.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/private/expected-v1alpha2.yaml
  tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
  upup/pkg/fi/cloudup/new_cluster.go
  upup/pkg/fi/cloudup/new_cluster_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#16341 deletion: tolerate concurrent SQS queue deletion
  cloudmock/aws/mocksqs/api.go
  pkg/resources/aws/sqs.go
Labels: cncf-cla: yes, lgtm, approved, size/S, area/provider/aws

#16343 Cleanup import of the same package in tests
  pkg/apis/kops/validation/aws_test.go
Labels: cncf-cla: yes, lgtm, area/api, approved, size/XS

#16344 validation: Allow overlap of pod/node CIDR and service CIDR
  pkg/apis/kops/validation/validation.go
  pkg/apis/kops/validation/validation_test.go
Labels: cncf-cla: yes, lgtm, area/api, approved, size/L

#16347 Include /etc/hosts coredns mounts for dns=none clusters
  tests/integration/update_cluster/minimal-dns-none/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-dns-none/data/aws_s3_object_minimal.example.com-addons-coredns.addons.k8s.io-k8s-1.12_content
  tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-coredns.addons.k8s.io-k8s-1.12_content
  tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.example.com-addons-coredns.addons.k8s.io-k8s-1.12_content
  upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
  upup/pkg/fi/cloudup/template_functions.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/addons

#16348 azure: Replace lb.ForAPIServer with lb.WellKnownServices
  pkg/model/azuremodel/api_loadbalancer.go
  upup/pkg/fi/cloudup/azuretasks/loadbalancer.go
  upup/pkg/fi/cloudup/azuretasks/loadbalancer_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L, area/provider/azure

#16350 Add support for AL2023 AMI to use Amazon VPC CNI
  nodeup/pkg/model/networking/amazon-vpc-routed-eni.go
  nodeup/pkg/model/packages.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/M, do-not-merge/hold

#16009 If specified, posts event data to URL upon instance interruption action.
  docs/addons.md
  docs/releases/1.29-NOTES.md
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kops/v1alpha3/componentconfig.go
  pkg/apis/kops/v1alpha3/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template
Labels: area/documentation, cncf-cla: yes, lgtm, area/api, approved, size/S, ok-to-test, area/addons

#16308 create command: remove example docs say is not implemented yet.
  cmd/kops/create.go
  docs/cli/kops_create.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS, ok-to-test

#16293 refactor: Introduce DeletionProcessingMode
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/awstasks/egressonlyinternetgateway_test.go
  upup/pkg/fi/cloudup/awstasks/elastic_ip_test.go
  upup/pkg/fi/cloudup/awsup/aws_apitarget.go
  upup/pkg/fi/cloudup/azure/azure_apitarget.go
  upup/pkg/fi/cloudup/do/api_target.go
  upup/pkg/fi/cloudup/gce/gce_apitarget.go
  upup/pkg/fi/cloudup/gcetasks/serviceaccount_test.go
  upup/pkg/fi/cloudup/hetzner/api_target.go
  upup/pkg/fi/cloudup/openstack/apitarget.go
  upup/pkg/fi/cloudup/scaleway/api_target.go
  upup/pkg/fi/cloudup/terraform/target.go
  upup/pkg/fi/context.go
  upup/pkg/fi/default_methods.go
  upup/pkg/fi/deletions.go
  upup/pkg/fi/dryrun_target.go
  upup/pkg/fi/nodeup/install/install_target.go
  upup/pkg/fi/nodeup/local/local_target.go
  upup/pkg/fi/target.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/L, area/provider/aws, area/provider/azure, area/provider/gcp, area/provider/openstack, area/provider/digitalocean, area/provider/hetzner, area/provider/scaleway

#16346 Update Go to v1.22.0
  .github/workflows/main.yml
  .github/workflows/update-deps.yml
  cloudbuild.yaml
  go.mod
  hack/go.mod
  tests/e2e/go.mod
  tools/otel/traceserver/go.mod
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_key.pem
  vendor/github.com/google/s2a-go/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/testdata/client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_root_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_key.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_cert.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_key.pem
  vendor/github.com/google/s2a-go/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/testdata/server_key.pem
Labels: cncf-cla: yes, lgtm, approved, size/S, kind/office-hours

#16358 azure: Avoid spurious changes in VirtualNetwork
  upup/pkg/fi/cloudup/azuretasks/virtualnetwork.go
  upup/pkg/fi/cloudup/new_cluster.go
Labels: cncf-cla: yes, lgtm, approved, size/S, area/provider/azure

#16356 Generate revisions of NLB objects, and introduce cleanup phase
  cloudmock/aws/mockautoscaling/attach.go
  cmd/kops/update_cluster.go
  docs/cli/kops_update_cluster.md
  pkg/instancegroups/instancegroups.go
  pkg/model/awsmodel/api_loadbalancer.go
  pkg/model/awsmodel/autoscalinggroup.go
  pkg/model/awsmodel/bastion.go
  pkg/model/awsmodel/spotinst.go
  pkg/resources/aws/aws.go
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
  upup/pkg/fi/cloudup/awstasks/dnsname.go
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
  upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
  upup/pkg/fi/cloudup/awstasks/networkloadbalancer_attributes.go
  upup/pkg/fi/cloudup/awstasks/networkloadbalancerlistener.go
  upup/pkg/fi/cloudup/awstasks/securitygroup.go
  upup/pkg/fi/cloudup/awstasks/subnet.go
  upup/pkg/fi/cloudup/awstasks/targetgroup.go
  upup/pkg/fi/cloudup/awstasks/vpc.go
  upup/pkg/fi/cloudup/awsup/aws_cloud.go
  upup/pkg/fi/cloudup/awsup/aws_utils.go
  upup/pkg/fi/cloudup/awsup/elbv2_targetgroups.go
  upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
  upup/pkg/fi/cloudup/awsup/tags.go
  upup/pkg/fi/cloudup/openstacktasks/securitygroup.go
  upup/pkg/fi/default_methods.go
  upup/pkg/fi/deletions.go
  upup/pkg/fi/dryrun_target.go
  upup/pkg/fi/topological_sort.go
Labels: area/documentation, cncf-cla: yes, lgtm, area/rolling-update, approved, size/XL, area/provider/aws, area/provider/openstack

#16355 gce: Update GCE storage service scope to DevstorageFullControlScope to resolve permission error.
  util/pkg/vfs/context.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, ok-to-test, kind/office-hours

#16186 add support for devcontainer
  .devcontainer/devcontainer.json
  .devcontainer/setup.sh
  .devcontainer/welcome-message.txt
  .gitignore
Labels: cncf-cla: yes, lgtm, approved, size/M

#16359 azure: Mark a few tasks as implementing HasAddress
  upup/pkg/fi/cloudup/azuretasks/loadbalancer.go
  upup/pkg/fi/cloudup/openstacktasks/port.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, area/provider/azure, area/provider/openstack

#16360 Set --dns=none on upgrade tests from older kops versions
  tests/e2e/scenarios/upgrade-ab/run-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16362 Update Cilium to v1.15.1
  pkg/model/components/cilium.go
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
Labels: cncf-cla: yes, lgtm, approved, size/L, area/addons

#16364 Fix bash conditional pattern matching in upgrade script
  tests/e2e/scenarios/upgrade-ab/run-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16365 devcontainer: update go version, use features
  .devcontainer/devcontainer.json
  .devcontainer/setup.sh
Labels: cncf-cla: yes, lgtm, approved, size/S

#16368 Skip known-failing test on most e2e jobs
  tests/e2e/pkg/tester/skip_regex.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#16370 doc/aws: Add space before the k8s slack url
  docs/getting_started/aws.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS, ok-to-test

#16373 Skip hostname test for all aws jobs by default
  tests/e2e/pkg/tester/skip_regex.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16374 Migrate many-addons e2e template to dns=none
  tests/e2e/templates/many-addons.yaml.tmpl
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16380 gce: match IP addresses including subnet where relevant
  upup/pkg/fi/cloudup/gcetasks/address.go
  upup/pkg/fi/cloudup/gcetasks/forwardingrule.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/provider/gcp

#16372 chore: update dependencies in submodules
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16379 GCE: Use internal load balancer for node to control-plane traffic
  pkg/model/gcemodel/api_loadbalancer.go
  tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/gcetasks/forwardingrule.go
Labels: cncf-cla: yes, lgtm, approved, size/L, area/provider/gcp

#16381 Skip hostname e2e test on digitalocean
  tests/e2e/pkg/tester/skip_regex.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16385 gce: Limit health check names to 63 chars
  pkg/model/gcemodel/context.go
  tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
Labels: cncf-cla: yes, lgtm, approved, size/XS, area/provider/gcp

#16386 gce: Limit backend names to 63 chars
  pkg/model/gcemodel/context.go
  tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
Labels: cncf-cla: yes, lgtm, approved, size/XS, area/provider/gcp

#16387 Update NVIDIA Container Toolkit URL
  nodeup/pkg/model/nvidia.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/XS

#16389 Continue attemps to dump artifacts in `toolbox dump`
  cmd/kops/toolbox_dump.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16390 chore: update boilerplate.py to recognize new build tags
  hack/boilerplate/boilerplate.py
Labels: cncf-cla: yes, lgtm, approved, size/S

#16391 Add validation to help users move from usePolicyConfigMap
  k8s/crds/kops.k8s.io_clusters.yaml
  nodeup/pkg/model/kube_scheduler.go
  pkg/apis/kops/componentconfig.go
  pkg/apis/kops/v1alpha2/componentconfig.go
  pkg/apis/kops/v1alpha3/componentconfig.go
  pkg/apis/kops/validation/validation.go
  pkg/model/components/kubescheduler_test.go
  upup/models/cloudup/resources/addons/scheduler.addons.k8s.io/v1.7.0.yaml
  upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Labels: cncf-cla: yes, lgtm, area/nodeup, area/api, approved, size/L, area/addons
