Repository kubernetes/kops, pull requests merged in 2025-01, with the labels that each got.

#17164 Automated cherry pick of #17163: chore(networking): bump aws-vpc-cni version to 1.19.2
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Labels: cncf-cla: yes, lgtm, approved, size/L, area/addons

#17163 chore(networking): bump aws-vpc-cni version to 1.19.2
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
  tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
  upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Labels: cncf-cla: yes, lgtm, approved, size/L, area/addons

#17161 Only configure STS region for Route 53 when we obtain it using IDMS
  dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go
Labels: cncf-cla: yes, lgtm, approved, size/M, ok-to-test

#17165 Automated cherry pick of #17161: Only configure STS region for Route 53 when we obtain it using IDMS
  dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#17166 Automated cherry pick of #17161: Only configure STS region for Route 53 when we obtain it using IDMS
  dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#17170 Update Cilium to v1.16.5
  pkg/model/components/cilium.go
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
Labels: cncf-cla: yes, lgtm, approved, size/L

#17172 Skip test `Services should implement NodePort and HealthCheckNodePort…
  tests/e2e/pkg/tester/skip_regex.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#17173 Automated cherry pick of #17170: Update Cilium to v1.16.5
  pkg/model/components/cilium.go
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
  tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
  upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
Labels: cncf-cla: yes, lgtm, approved, size/L

#17171 Adding VolumeType for Azure for etcdMembers
  pkg/model/master_volumes.go
  upup/pkg/fi/cloudup/azuretasks/disk.go
  upup/pkg/fi/cloudup/azuretasks/disk_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S, area/provider/azure, ok-to-test

#17175 Automated cherry pick of #17171: Adding VolumeType for Azure for etcdMembers
  pkg/model/master_volumes.go
  upup/pkg/fi/cloudup/azuretasks/disk.go
  upup/pkg/fi/cloudup/azuretasks/disk_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S, area/provider/azure

#16739 Propagate IG NodeLabels to k8s nodes in Hetzner
  pkg/model/context.go
  pkg/model/hetznermodel/servers.go
  pkg/nodeidentity/hetzner/identify.go
  tests/integration/update_cluster/minimal_hetzner/kubernetes.tf
  upup/pkg/fi/cloudup/hetzner/cloud.go
Labels: cncf-cla: yes, lgtm, approved, size/M, lifecycle/stale, area/provider/hetzner

#17176 Automated cherry pick of #16739: Propagate IG NodeLabels to k8s nodes in Hetzner
  pkg/model/context.go
  pkg/model/hetznermodel/servers.go
  pkg/nodeidentity/hetzner/identify.go
  tests/integration/update_cluster/minimal_hetzner/kubernetes.tf
  upup/pkg/fi/cloudup/hetzner/cloud.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/provider/hetzner

#17184 Update Go to v1.23.4
  cloudbuild.yaml
  go.mod
  hack/go.mod
  tests/e2e/go.mod
  tools/otel/traceserver/go.mod
Labels: cncf-cla: yes, lgtm, approved, size/S

#17185 Automated cherry pick of #17184: Update Go to v1.23.4
  cloudbuild.yaml
  go.mod
  hack/go.mod
  tests/e2e/go.mod
  tools/otel/traceserver/go.mod
Labels: cncf-cla: yes, lgtm, approved, size/S

#17188 Automated cherry pick of #17180: fix the random order of block_device_mappings render Include
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/provider/aws

#17189 Automated cherry pick of #17180: fix the random order of block_device_mappings render Include
  upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/provider/aws

#17183 Use SDK's built-in resolver for S3Path.GetHTTPsUrl
  util/pkg/vfs/s3fs.go
  util/pkg/vfs/s3fs_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#17196 Fix aws cli command for discovering 24.04 AMIs
  docs/operations/images.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS

#17195 Automated cherry pick of #17183: Use SDK's built-in resolver for S3Path.GetHTTPsUrl
  util/pkg/vfs/s3fs.go
  util/pkg/vfs/s3fs_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#17177 Use the same port for hubble-metrics that is used by cilium
  docs/contributing/ports.md
  pkg/wellknownports/wellknownports.go
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.15.yaml.template
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/S, ok-to-test, area/addons

#17187 Refactor validation logic around checking for multiple options
  pkg/apis/kops/networking.go
  pkg/apis/kops/v1alpha2/networking.go
  pkg/apis/kops/validation/validation.go
  util/pkg/reflectutils/access.go
  util/pkg/reflectutils/set_fields.go
  util/pkg/reflectutils/tests/access_test.go
Labels: cncf-cla: yes, lgtm, area/api, approved, size/L

#17198 Automated cherry pick of #17177: Use the same port for hubble-metrics that is used by
  docs/contributing/ports.md
  pkg/wellknownports/wellknownports.go
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
  upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.15.yaml.template
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/S, area/addons

#17201 Automated cherry pick of #17183: Use SDK's built-in resolver for S3Path.GetHTTPsUrl
  util/pkg/vfs/s3fs.go
  util/pkg/vfs/s3fs_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#17202 Automated cherry pick of #17178: Update containerd to v1.7.24 #17200: Update containerd to v1.7.25
  hack/generate-asset-hashes.sh
  pkg/assets/assetdata/cni-1.2.yaml
  pkg/assets/assetdata/cni-1.3.yaml
  pkg/assets/assetdata/cni-1.4.yaml
  pkg/assets/assetdata/cni-1.5.yaml
  pkg/assets/assetdata/cni-1.6.yaml
  pkg/assets/assetdata/containerd-1.7.yaml
  pkg/assets/assetdata/containerd-2.0.yaml
  pkg/assets/assetdata/runc-1.2.yaml
  pkg/model/components/containerd.go
  tests/integration/update_cluster/additionalobjects/data/aws_launch_template_master-us-test-1a.masters.additionalobjects.example.com_user_data
  tests/integration/update_cluster/additionalobjects/data/aws_launch_template_nodes.additionalobjects.example.com_user_data
  tests/integration/update_cluster/additionalobjects/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/additionalobjects/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/additionalobjects/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/complex/data/aws_launch_template_master-us-test-1a.masters.complex.example.com_user_data
  tests/integration/update_cluster/complex/data/aws_launch_template_nodes.complex.example.com_user_data
  tests/integration/update_cluster/complex/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/complex/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/complex/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-1.27/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.27/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-1.28/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.28/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.28/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.28/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.28/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-1.29/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.29/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.29/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.29/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.29/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/minimal-1.30/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.30/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/minimal-1.30/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-1.30/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/minimal-1.30/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/privatecilium2/data/aws_launch_template_master-us-test-1a.masters.privatecilium.example.com_user_data
  tests/integration/update_cluster/privatecilium2/data/aws_launch_template_nodes.privatecilium.example.com_user_data
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/privatecilium2/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/public-jwks-apiserver/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
  tests/integration/update_cluster/public-jwks-apiserver/data/aws_launch_template_nodes.minimal.example.com_user_data
  tests/integration/update_cluster/public-jwks-apiserver/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/public-jwks-apiserver/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/public-jwks-apiserver/data/aws_s3_object_nodeupconfig-nodes_content
Labels: cncf-cla: yes, lgtm, approved, size/XL

#17203 Use Ubuntu 24.04 (Noble) as the default distro for K8s 1.32+
  channels/alpha
  channels/stable
  tests/integration/create_cluster/cilium-eni/expected-v1alpha2.yaml
  tests/integration/create_cluster/complex-private/expected-v1alpha2.yaml
  tests/integration/create_cluster/complex/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_hetzner/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.32/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-arm64/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-gce-dns-none/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-gce/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-irsa/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal_feature-gates/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal_hetzner/expected-v1alpha2.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
  tests/integration/create_cluster/private/expected-v1alpha2.yaml
  tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
  tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
  upup/pkg/fi/cloudup/new_cluster.go
  upup/pkg/fi/cloudup/new_cluster_test.go
  upup/pkg/fi/cloudup/populate_instancegroup_spec.go
Labels: cncf-cla: yes, lgtm, approved, size/L, area/channels

#17204 kindnet: use commands instead of args for the container image
  tests/integration/update_cluster/minimal-ipv6-kindnet/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-ipv6-kindnet/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.kindnet-k8s-1.32_content
  tests/integration/update_cluster/privatekindnet/data/aws_s3_object_privatekindnet.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatekindnet/data/aws_s3_object_privatekindnet.example.com-addons-networking.kindnet-k8s-1.32_content
  upup/models/cloudup/resources/addons/networking.kindnet/k8s-1.32.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/S, area/addons

#17211 delete cluster: avoid logspam on GCE "resource in use" error
  pkg/resources/gce/errors.go
  pkg/resources/ops/delete.go
  upup/pkg/fi/cloudup/gce/wrappers.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/provider/gcp

#17212 toolbox dump: include full instance details on GCE
  pkg/model/components/kubecontrollermanager.go
  pkg/resources/gce/dump.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, area/provider/gcp

#17208 reconcile: wait for apiserver to response before trying rolling-update
  cmd/kops/delete_instance.go
  cmd/kops/reconcile_cluster.go
  cmd/kops/rolling-update_cluster.go
  cmd/kops/validate_cluster.go
  pkg/instancegroups/instancegroups.go
  pkg/instancegroups/rollingupdate_test.go
  pkg/instancegroups/rollingupdate_warmpool_test.go
  pkg/validation/validate_cluster.go
  pkg/validation/validate_cluster_test.go
Labels: cncf-cla: yes, lgtm, area/rolling-update, approved, size/L

#17210 bump kindnet default version to 1.8.2
  pkg/model/components/kindnet.go
  tests/integration/update_cluster/minimal-ipv6-kindnet/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/minimal-ipv6-kindnet/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-ipv6-kindnet/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.kindnet-k8s-1.32_content
  tests/integration/update_cluster/privatekindnet/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatekindnet/data/aws_s3_object_privatekindnet.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatekindnet/data/aws_s3_object_privatekindnet.example.com-addons-networking.kindnet-k8s-1.32_content
Labels: cncf-cla: yes, lgtm, approved, size/S

#17214 reconcile: if --yes is not provided, print the same output as `update cluster` does
  cmd/kops/reconcile_cluster.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#17213 fix kindnet permissions
  tests/integration/update_cluster/minimal-ipv6-kindnet/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-ipv6-kindnet/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.kindnet-k8s-1.32_content
  tests/integration/update_cluster/privatekindnet/data/aws_s3_object_privatekindnet.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatekindnet/data/aws_s3_object_privatekindnet.example.com-addons-networking.kindnet-k8s-1.32_content
  upup/models/cloudup/resources/addons/networking.kindnet/k8s-1.32.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/S, area/addons

#17209 gce: Update scale test scenario
  tests/e2e/scenarios/scalability/run-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#17215 Kindnet requires cluster to provide ipam via the node.spec.podcidr
  pkg/model/components/kubecontrollermanager.go
  tests/integration/update_cluster/privatekindnet/data/aws_launch_template_master-us-test-1a.masters.privatekindnet.example.com_user_data
  tests/integration/update_cluster/privatekindnet/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/privatekindnet/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
Labels: cncf-cla: yes, lgtm, approved, size/XS

#17216 chore(channels): update alpha k8s and ubuntu ami versions
  channels/alpha
Labels: cncf-cla: yes, lgtm, approved, size/S, area/channels

#16978 Support strong-typing for --target values
  cmd/kops/create_cluster.go
  cmd/kops/update_cluster.go
  docs/cli/kops_create_cluster.md
  docs/cli/kops_update_cluster.md
  upup/pkg/fi/cloudup/apply_cluster.go
  upup/pkg/fi/cloudup/target.go
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/M

#17152 tests: use reconcile command for kOps 1.31+
  tests/e2e/scenarios/upgrade-ab/run-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/M, kind/office-hours

#17217 Update Go to v1.23.5
  cloudbuild.yaml
  go.mod
  hack/go.mod
  tests/e2e/go.mod
  tools/otel/traceserver/go.mod
Labels: cncf-cla: yes, lgtm, approved, size/S

#17218 Automated cherry pick of #17217: Update Go to v1.23.5
  cloudbuild.yaml
  go.mod
  hack/go.mod
  tests/e2e/go.mod
  tools/otel/traceserver/go.mod
Labels: cncf-cla: yes, lgtm, approved, size/S

#17219 Automated cherry pick of #17217: Update Go to v1.23.5
  cloudbuild.yaml
  go.mod
  hack/go.mod
  tests/e2e/go.mod
  tools/otel/traceserver/go.mod
Labels: cncf-cla: yes, lgtm, approved, size/S

#16943 e2e: add `kops validate` step to metal test
  tests/e2e/scenarios/bare-metal/run-test
  upup/pkg/fi/cloudup/metal/cloud.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#17222 Automated cherry pick of #17153: chore: add context to rolling update functions
  cmd/kops/delete_instance.go
  cmd/kops/rolling-update_cluster.go
  pkg/instancegroups/instancegroups.go
  pkg/instancegroups/instancegroups_test.go
  pkg/instancegroups/rollingupdate.go
  pkg/instancegroups/rollingupdate_os_test.go
  pkg/instancegroups/rollingupdate_test.go
  pkg/instancegroups/rollingupdate_warmpool_test.go
Labels: cncf-cla: yes, lgtm, area/rolling-update, approved, size/L

#17220 Remove reconcile flag from `kops update`
  cmd/kops/update_cluster.go
  docs/cli/kops_update_cluster.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS

#17221 Automated cherry pick of #17151: s3 vfs: fix delete all versions to handle errors
  util/pkg/vfs/s3fs.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#17223 Automated cherry pick of #17214: reconcile: if --yes is not provided, print the same output as `update cluster` does
  cmd/kops/reconcile_cluster.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#17225 Automated cherry pick of #17154: chore: refactor factory to accept a cluster
  channels/cmd/channels/main.go
  channels/pkg/cmd/apply.go
  channels/pkg/cmd/apply_channel.go
  channels/pkg/cmd/factory.go
  channels/pkg/cmd/get.go
  channels/pkg/cmd/get_addons.go
  channels/pkg/cmd/root.go
  cmd/kops/delete_instance.go
  cmd/kops/get_instances.go
  cmd/kops/rolling-update_cluster.go
  cmd/kops/toolbox_addons.go
  cmd/kops/toolbox_dump.go
  cmd/kops/util/factory.go
  cmd/kops/validate_cluster.go
  pkg/commands/commandutils/factory.go
  pkg/commands/toolbox_enroll.go
  pkg/instancegroups/rollingupdate.go
  pkg/validation/validate_cluster.go
  pkg/validation/validate_cluster_test.go
Labels: cncf-cla: yes, lgtm, area/rolling-update, approved, size/XL, area/channels

#17226 Automated cherry pick of #17220: Remove reconcile flag from `kops update`
  cmd/kops/update_cluster.go
  docs/cli/kops_update_cluster.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS

#17228 Automated cherry pick of #17152: tests: use reconcile command for kOps 1.31+
  tests/e2e/scenarios/upgrade-ab/run-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/M

#17227 Automated cherry pick of #17155: chore: generate kubeconfig on the fly
  cmd/kops/util/factory.go
  cmd/kops/validate_cluster.go
  pkg/kubeconfig/create_kubecfg.go
  pkg/kubeconfig/kubecfg_builder.go
Labels: cncf-cla: yes, lgtm, area/rolling-update, approved, size/L, area/channels

#17232 chore(channels): promote alpha to stable
  channels/stable
  tests/integration/create_cluster/cilium-eni/expected-v1alpha2.yaml
  tests/integration/create_cluster/complex-private/expected-v1alpha2.yaml
  tests/integration/create_cluster/complex/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
  tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.27/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.28/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.29/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.30/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.31/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.32/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-arm64/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-irsa/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal_feature-gates/expected-v1alpha2.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
  tests/integration/create_cluster/private/expected-v1alpha2.yaml
  tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
Labels: cncf-cla: yes, lgtm, approved, size/L, area/channels

#17191 Add docs for the new kops reconcile cluster command
  docs/operations/updates_and_upgrades.md
  docs/releases/1.31-NOTES.md
  docs/tutorial/upgrading-kubernetes.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/M

#17192 Promote Ubuntu 24.04 to stable in Kops 1.31
  docs/operations/images.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS, kind/office-hours

#17233 Add more IOPS to help raft latencies
  tests/e2e/scenarios/scalability/run-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/S

#17245 chore: avoid replacing client-go version in tests/e2e
  tests/e2e/go.mod
  tests/e2e/go.sum
Labels: cncf-cla: yes, lgtm, approved, size/XS

#17244 chore: create script to update dependencies
  Makefile
  dev/codebots/update-dependencies
Labels: cncf-cla: yes, lgtm, approved, size/M
