Repository kubernetes/kops, pull requests merged in 2025-06, with the labels that each got.

#17410 [docs] fixed cilium cni exclusive topic placement
  docs/networking/cilium.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/S, ok-to-test

#17428 Automated cherry pick of #17427: Upgrade calico to 3.29.4
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.25_content
  tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.25_content
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.25.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/L, area/addons

#17427 Upgrade calico to 3.29.4
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
  tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.25_content
  tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
  tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.25_content
  upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.25.yaml.template
Labels: cncf-cla: yes, lgtm, approved, size/L, area/addons

#17426 Fix minor version upgrade recommendations
  cmd/kops/upgrade_cluster.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#17430 Re-enable additionalSecurityGroups for bastion LB
  k8s/crds/kops.k8s.io_clusters.yaml
  pkg/apis/kops/bastion.go
  pkg/apis/kops/v1alpha2/bastion.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/bastion.go
  pkg/apis/kops/v1alpha3/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/kops/zz_generated.deepcopy.go
  pkg/model/awsmodel/bastion.go
  tests/integration/update_cluster/bastionadditional_user-data/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
Labels: cncf-cla: yes, lgtm, area/api, approved, size/S, area/provider/aws, ok-to-test

#17431 Add documentation on max node lifetime
  docs/getting_started/production.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/XS

#17441 GCE: do not reset MIG target size on cluster updates
  tests/integration/update_cluster/ha_gce/kubernetes.tf
  tests/integration/update_cluster/many-addons-gce/kubernetes.tf
  tests/integration/update_cluster/minimal_gce/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_longclustername/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
  upup/pkg/fi/cloudup/gcetasks/instancegroupmanager.go
Labels: cncf-cla: yes, lgtm, approved, size/L, area/provider/gcp, ok-to-test

#17442 Makefile: correct .PHONY casing
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/XS, ok-to-test

#17444 chore: Bump node images
  channels/alpha
  channels/stable
  pkg/apis/kops/channel.go
  tests/integration/create_cluster/cilium-eni/expected-v1alpha2.yaml
  tests/integration/create_cluster/complex-private/expected-v1alpha2.yaml
  tests/integration/create_cluster/complex/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
  tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
  tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.27/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.28/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.29/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.30/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.31/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-1.32/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-arm64/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-gce-dns-none/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-gce/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal-irsa/expected-v1alpha2.yaml
  tests/integration/create_cluster/minimal_feature-gates/expected-v1alpha2.yaml
  tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
  tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
  tests/integration/create_cluster/private/expected-v1alpha2.yaml
  tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
  tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
  tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
Labels: cncf-cla: yes, lgtm, area/api, approved, size/L, area/channels

#17445 Automated cherry pick of #17438: add systemd network config for Cilium and Amazon VPC CNI on Ubuntu 22.04+ and AL2023 to prevent route removal
  nodeup/pkg/model/networking/amazon-vpc-routed-eni.go
  nodeup/pkg/model/networking/cilium.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/S

#17448 Automated cherry pick of #17441: GCE: do not reset MIG target size on cluster updates
  tests/integration/update_cluster/ha_gce/kubernetes.tf
  tests/integration/update_cluster/many-addons-gce/kubernetes.tf
  tests/integration/update_cluster/minimal_gce/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_longclustername/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
  tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
  upup/pkg/fi/cloudup/gcetasks/instancegroupmanager.go
Labels: cncf-cla: yes, lgtm, approved, size/L, area/provider/gcp

#17446 Automated cherry pick of #17438: add systemd network config for Cilium and Amazon VPC CNI on Ubuntu 22.04+ and AL2023 to prevent route removal
  nodeup/pkg/model/networking/amazon-vpc-routed-eni.go
  nodeup/pkg/model/networking/cilium.go
Labels: cncf-cla: yes, lgtm, area/nodeup, approved, size/S

#17429 Fix toolbox addons apply command
  cmd/kops/toolbox_addons.go
  docs/cli/kops_toolbox_addons_apply.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/S, ok-to-test

#17391 Skip tests-e2e-scenarios-bare-metal when `version.go` changes
  .github/workflows/e2e.yml
Labels: cncf-cla: yes, lgtm, approved, size/S

#17406 Extend openstack mock by misc. resources
  cloudmock/openstack/mockcompute/api.go
  cloudmock/openstack/mockcompute/instanceactions.go
  cloudmock/openstack/mockcompute/servers.go
  cloudmock/openstack/mocknetworking/floatingips.go
  go.mod
  go.sum
  tests/e2e/go.mod
  tests/e2e/go.sum
  vendor/github.com/gophercloud/gophercloud/v2/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/v2/endpoint_search.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/client.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/compute/v2/instanceactions/doc.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/compute/v2/instanceactions/request.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/compute/v2/instanceactions/results.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/compute/v2/instanceactions/urls.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/endpoint_location.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/layer3/floatingips/requests.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/layer3/floatingips/results.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/layer3/routers/requests.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/layer3/routers/results.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/security/groups/requests.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/security/groups/results.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/security/rules/requests.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/security/rules/results.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/networking/v2/networks/requests.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/networking/v2/ports/requests.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/networking/v2/subnets/requests.go
  vendor/github.com/gophercloud/gophercloud/v2/openstack/networking/v2/subnets/results.go
  vendor/github.com/gophercloud/gophercloud/v2/provider_client.go
  vendor/github.com/gophercloud/gophercloud/v2/service_client.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, size/L, ok-to-test

#17454 Automated cherry pick of #17391: Skip tests-e2e-scenarios-bare-metal when `version.go` changes
  .github/workflows/e2e.yml
Labels: cncf-cla: yes, lgtm, approved, size/S

#17455 Automated cherry pick of #17391: Skip tests-e2e-scenarios-bare-metal when `version.go` changes
  .github/workflows/e2e.yml
Labels: cncf-cla: yes, lgtm, approved, size/S

#17453 hetzner: Add support for Object Storage
  pkg/clouds/supported.go
  util/pkg/vfs/context.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#17457 Automated cherry pick of #17456: Update golang to 1.23.10
  cloudbuild.yaml
  go.mod
  hack/go.mod
  tests/e2e/go.mod
  tools/otel/traceserver/go.mod
Labels: cncf-cla: yes, lgtm, approved, size/S

#17459 Create flag api-server which allows for custom DNS setups
  cmd/kops/delete_instance.go
  cmd/kops/export_kubeconfig.go
  cmd/kops/get_instances.go
  cmd/kops/rolling-update_cluster.go
  cmd/kops/toolbox_enroll.go
  cmd/kops/update_cluster.go
  cmd/kops/util/factory.go
  cmd/kops/validate_cluster.go
  docs/cli/kops_delete_instance.md
  docs/cli/kops_export_kubeconfig.md
  docs/cli/kops_get_instances.md
  docs/cli/kops_rolling-update_cluster.md
  docs/cli/kops_toolbox_enroll.md
  docs/cli/kops_update_cluster.md
  docs/cli/kops_validate_cluster.md
  pkg/commands/commandutils/factory.go
  pkg/commands/toolbox_enroll.go
  pkg/kubeconfig/create_kubecfg.go
  pkg/kubeconfig/create_kubecfg_test.go
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/L

#17466 Automated cherry pick of #17459: Create flag api-server which allows for custom DNS setups
  cmd/kops/delete_instance.go
  cmd/kops/export_kubeconfig.go
  cmd/kops/get_instances.go
  cmd/kops/rolling-update_cluster.go
  cmd/kops/toolbox_enroll.go
  cmd/kops/update_cluster.go
  cmd/kops/util/factory.go
  cmd/kops/validate_cluster.go
  docs/cli/kops_delete_instance.md
  docs/cli/kops_export_kubeconfig.md
  docs/cli/kops_get_instances.md
  docs/cli/kops_rolling-update_cluster.md
  docs/cli/kops_toolbox_enroll.md
  docs/cli/kops_update_cluster.md
  docs/cli/kops_validate_cluster.md
  pkg/commands/commandutils/factory.go
  pkg/commands/toolbox_enroll.go
  pkg/kubeconfig/create_kubecfg.go
  pkg/kubeconfig/create_kubecfg_test.go
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/L
