Repository kubernetes/kops, pull requests merged in 2025-07, with the labels that each got.

#17434 GCE: set node labels and taints as autoscaler env vars
  pkg/model/gcemodel/autoscalinggroup.go
  tests/integration/update_cluster/ha_gce/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_nodes-ha-gce-example-com_metadata_user-data
  tests/integration/update_cluster/ha_gce/in-v1alpha2.yaml
  tests/integration/update_cluster/ha_gce/kubernetes.tf
Labels: cncf-cla: yes, lgtm, approved, size/M, area/provider/gcp, ok-to-test

#15324 docs: Add note to 1.22 about the CA CN rename
  docs/releases/1.22-NOTES.md
Labels: area/documentation, cncf-cla: yes, lgtm, size/XS, tide/merge-method-squash, ok-to-test, do-not-merge/invalid-commit-message

#16961 fix(openstack): determine ports to delete based on tags
  cloudmock/openstack/mocknetworking/ports.go
  upup/pkg/fi/cloudup/openstack/cloud.go
  upup/pkg/fi/cloudup/openstack/cloud_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L, area/provider/openstack, ok-to-test

#17474 Add an example script to setup RAID-10 for instances with multiple NVMe disks
  docs/tutorial/working-with-instancegroups.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/M, ok-to-test

#17491 Update ecr-credential-provider checksums
  pkg/assets/assetdata/ecr.yaml
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, approved, size/XS

#17488 Automated cherry pick of #17482: Fix cloud-provider flag for K8s 1.31+
  pkg/model/components/apiserver.go
  pkg/model/components/kubelet.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#17493 azure: Track resources by ID during deletion
  pkg/resources/azure/azure.go
  pkg/resources/azure/azure_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L, area/provider/azure

#17495 tests: don't override etcd-manager image in bare-metal test
  tests/e2e/scenarios/bare-metal/run-test
Labels: cncf-cla: yes, lgtm, approved, size/XS

#17498 Reduce verbosity of k8s version warning
  cmd/kops/update_cluster.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#17501 Automated cherry pick of #17500: Fix invalid filters for describing security group rules
  upup/pkg/fi/cloudup/awstasks/securitygroup.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, area/provider/aws

#17505 chore: Use constants for default network CIDRs
  upup/pkg/fi/cloudup/defaults.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#17508 Automated cherry pick of #17500: Fix invalid filters for describing security group rules
  upup/pkg/fi/cloudup/awstasks/securitygroup.go
Labels: cncf-cla: yes, lgtm, approved, size/S, area/provider/aws

#17509 protokube: Initialize CloudProvider only with Gossip
  protokube/cmd/protokube/main.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#17512 Wait for GCE disk creation operation
  upup/pkg/fi/cloudup/gcetasks/disk.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, area/provider/gcp, ok-to-test

#17514 Automated cherry pick of #17512: Wait for the GCE disk creation operation to finish
  upup/pkg/fi/cloudup/gcetasks/disk.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, area/provider/gcp

#17516 Prefer using `id_ed25519.pub` instead of `id_rsa.pub`
  cmd/kops/create_cluster.go
  docs/releases/1.34-NOTES.md
Labels: area/documentation, cncf-cla: yes, lgtm, approved, size/M

#17517 azure: Fix periodic tests
  cmd/kops/create_cluster.go
  tests/e2e/kubetest2-kops/deployer/common.go
  upup/pkg/fi/cloudup/azure/verifier.go
  upup/pkg/fi/cloudup/azuretasks/vmscaleset.go
  upup/pkg/fi/cloudup/azuretasks/vmscaleset_test.go
  upup/pkg/fi/cloudup/new_cluster.go
Labels: cncf-cla: yes, lgtm, approved, size/M, area/provider/azure

#17523 testing: Fix e2e test job name
  tests/e2e/kubetest2-kops/deployer/common.go
  tests/e2e/pkg/tester/skip_regex.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#16593 aws: Add support for using ECR as pull-through image cache
  docs/iam_roles.md
  k8s/crds/kops.k8s.io_clusters.yaml
  k8s/crds/kops.k8s.io_instancegroups.yaml
  nodeup/pkg/model/kubelet.go
  pkg/apis/kops/containerdconfig.go
  pkg/apis/kops/v1alpha2/containerdconfig.go
  pkg/apis/kops/v1alpha2/zz_generated.conversion.go
  pkg/apis/kops/v1alpha3/containerdconfig.go
  pkg/apis/kops/v1alpha3/zz_generated.conversion.go
  pkg/model/iam/iam_builder.go
  tests/integration/update_cluster/containerd-custom/data/aws_iam_role_policy_masters.containerd.example.com_policy
  tests/integration/update_cluster/containerd-custom/data/aws_iam_role_policy_nodes.containerd.example.com_policy
  tests/integration/update_cluster/containerd-custom/data/aws_launch_template_master-us-test-1a.masters.containerd.example.com_user_data
  tests/integration/update_cluster/containerd-custom/data/aws_launch_template_nodes.containerd.example.com_user_data
  tests/integration/update_cluster/containerd-custom/data/aws_s3_object_cluster-completed.spec_content
  tests/integration/update_cluster/containerd-custom/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
  tests/integration/update_cluster/containerd-custom/data/aws_s3_object_nodeupconfig-nodes_content
  tests/integration/update_cluster/containerd-custom/in-v1alpha2.yaml
  vendor/k8s.io/kubelet/config/v1/doc.go
  vendor/k8s.io/kubelet/config/v1/register.go
  vendor/k8s.io/kubelet/config/v1/types.go
  vendor/k8s.io/kubelet/config/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: area/documentation, cncf-cla: yes, lgtm, area/nodeup, area/api, area/rolling-update, approved, size/L, ok-to-test, area/channels, area/kops-controller, area/addons

#17524 Add more context to terraform fatal log
  upup/pkg/fi/cloudup/terraformWriter/writer.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#17525 Use ssm parameter for AMI ID in LBC scenario
  tests/e2e/scenarios/aws-lb-controller/run-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS
